### ISSUE TITLE
Catching run-away queries

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1005]
In email conversation with @h4yn0nnym0u5e, one somewhat frustrating thing that can crop up when using DB4S (manually, in the "Execute SQL" tab) is getting a join wrong, and the result set tries to return a huge number of rows.  eg 1.6 mill rows

@MKleusberg @innermous @prutz1311 Any idea if there is some way we could catch that kind of thing - without needing a large amount of code change - and not let it go out of control?

**Comment by chrisjlocke** [comment]
Just a thought, but might be worth throwing that out to the sqlite users mailing group, as they might suggest some hook you could use .... you're not going to know how many rows you're going to get back until sqlite has done its biz (and consumed 97 GB of memory...) but you might be able to abort it after ... say, 20 seconds?

**Comment by justinclift** [comment]
Ahhh, good thinking Chris.  You're already on that mailing list aren't you?

If so, would you be ok to ask? :smile:

**Comment by chrisjlocke** [comment]
Surely can.  ✍️

**Comment by MKleusberg** [comment]
No need to ask them :wink: [This](https://sqlite.org/c3ref/interrupt.html) does what we need. I'd suggest to not do anything automatically because some queries just take their time. See #409 for example. But what we can do is add a cancel button which just allows the user to stop the query at any time.

**Comment by justinclift** [comment]
Awesome. 😀

**Comment by chrisjlocke** [comment]
Yup, Dr. Richard Hipp just replied back with the same suggestion:

> Can you get the application to use the sqlite3_interrupt() (https://www.sqlite.org/c3ref/interrupt.html) interface to stop the long-running query?

**Comment by justinclift** [comment]
Excellent, thanks Chris & Dr. Richard Hipp. :smile:

**Comment by justinclift** [comment]
For reference:

&nbsp; &nbsp; https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg103468.html

**Comment by mglatz** [comment]
Cancel button is probably best, other possible approach I can think of is have a setting for query timeout and once that expires, ask user if he wants the query to run some more or cancel.

**Comment by mgrojo** [comment]
What's the state of this issue?

**Comment by tilusnet** [comment]
I think a cancel button is badly needed. Would it be difficult to add?

**Comment by MKleusberg** [comment]
@h4yn0nnym0u5e @tilusnet Sorry for the long delay here. Are you still interested in this issue? I'm asking because we are currently preparing some changes which add, besides making some other changes, a cancel button to the Execute SQL area. Because it's changing a lot of our code we want to test this as good as we can. Are you interested in giving it a try? You can find the Windows and OSX build here:

* https://nightlies.sqlitebrowser.org/win32-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher-issue1575v2-win32.msi
* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher-issue1575v2-win64.msi
* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite_issue-1575v1.dmg
* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher_issue-1575v1.dmg

**Comment by tilusnet** [comment]
Hi @MKleusberg Personally, my focus shifted away from SQLiteBrowser in the near past, moreover I am exclusively on Linux currently which makes testing impossible. Sorry I can't help.

**Comment by justinclift** [comment]
>  I am exclusively on Linux currently

As a data point, we definitely compile and run ok on Linux too.  My main desktop these days is CentOS 7, and that runs DB4S without issue. :smile:

**Comment by chrisjlocke** [comment]
> and that runs DB4S without issue.

No it doesn't.  There's 281 of them.  😉

**Comment by justinclift** [comment]
:stuck_out_tongue:

**Comment by MKleusberg** [comment]
Let's close this issue. I'm pretty sure the cancel button is working as expected and we have other open issues for this too :smile: 


>> and that runs DB4S without issue.
>
> No it doesn't. There's 281 of them. :wink:

I wish this was still the case :wink:
