### ISSUE TITLE
Nightly windows installer executable don't launch

### ISSUE THREAD

**Issue by allender** [sqlitebrowser/sqlitebrowser#1029]
### Details for the issue

I tried downloading the nightly windows installer (64 and 32 bit) so that I could get json support that is not currently available in the release version.  When I double click the executable in windows explorer (or choose open from the context menu), nothing happens.  If I run the executable from the command line, the installer runs and the nightly build is correctly installed.   I'm not entirely sure why the executable will not launch.  I do not get any kind of indication that the process started, nor do I see anything in process explorer that indicates that the installer started.  

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [X] Other: _Nightly__

#### I have also:

- [X] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
@chrisjlocke @karim Any ideas? :smile:

**Comment by karim** [comment]
I just tried installing the latest nightly version and everything is working fine. I'm on windows 7 though.

The only difference I see between the official version and the nightly builds is that the nightly builds are not digitally signed. Also, since they are *downloaded from the internet* they might be flagged as unsafe. Could it be Windows 10 blocking the installer somehow?

@allender Does the official version (v3.9.1) work without a problem? Did you try right-clicking the installer and *Run as administrator*?

@justinclift Can you sign one of the latest nightly versions and send to him to test?

**Comment by chrisjlocke** [comment]
I run this quite happily on Windows 10, although it does come up with the 'Hey, this is a new program, are you sure you want to run this?' 

What anti-virus have you got?  Anything in the event viewer?

**Comment by justinclift** [comment]
@karim Ahhh yeah, good idea.  I can manually sign one of the nightlies to see if that's the problem.

If that does turn out to be the case, then all is not lost.  I have some notes from one of the StartCom (!) staff on how to potentially script the signing.  It may work out doable.

**Comment by allender** [comment]
I "unblocked" the app in the properties pane and it's working.  I didn't even think about digital signatures.  Sorry about that.  I so appreciate the help.

**Comment by justinclift** [comment]
You're welcome @allender, glad the problem didn't turn out to be something more serious. :smile:
