### ISSUE TITLE
CSV import fails on OSX when EOL char is `0D`

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1033]
### Details for the issue

When attempting to import either of the .csv files from GitHubs' recent ["Open Source Survey 2017" data release](http://opensourcesurvey.org/2017/), they both fail with an error message for the first line:
![screen shot 2017-06-04 at 00 21 53](https://cloud.githubusercontent.com/assets/406299/26757683/67512250-48bc-11e7-83c8-93830fa18390.png)
* http://github-images.s3.amazonaws.com/open-source-survey/data_for_public_release.zip ← 2 .csv's in here

That error message is from `negative_incidents.csv`, but `survey_data.csv` (much larger file) exhibits the same problem.  Looking through the data, there's no obvious line of double the correct length.  The error message itself says there's double the number of fields, which indicates some kind of problem with the line ending not being recognised.

The data itself doesn't seem to have a problem though.  The EOL character is `0D` (carriage return):
![screen shot 2017-06-04 at 00 34 33](https://cloud.githubusercontent.com/assets/406299/26757704/ba114afa-48bd-11e7-8325-a577f572431c.png)

Haven't yet looked at the code, but I'm guessing we're assuming Windows style newlines.  If that's the case, we should probably update the import dialog to accept platform-dependent newlines.  Either automatically, or ask like we do in the export dialog.  Kind of thinking we should be able to auto-detect them though. :smile:

#### I'm opening this issue because:

- [x] DB4S has a bug

#### I'm using DB4S on:

- [x] Mac OS: (10.11.6)

#### I'm using DB4S version:

- [x] 3.9.1
- [x] Other: Nightly build from a few days ago (2017-05-2*)

#### I have also:

- [x] Tried out a recent nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
Wow, what an issue 😆 I'm wondering what the chances of this happening are. And what a hell to debug.

So it turns out this is not caused by the ```0D```. We actually support this already. You can tell by the fact that the preview in the Import CSV dialog is working correctly. Instead the issue is caused by the fact that we're not reading the CSV file entirely at once but in smaller chunks. We then loop through each chunk byte by byte and parse it. Now, if we hit a \r character we do a lookahead check if the next byte is a \n character. The problem arises when the \r character is right at the end of the current buffer, that means the following character isn't available yet. Essentially this would put the parser in a wrong state. This is by the way also the reason that smaller portions of the file (what I tried first) won't trigger the error. Anyway, the issue is now fixed by checking for this exact case and loading an extra byte into the buffer when needed :smile:

@justinclift Can you double check it's working for you, too? 😄

**Comment by justinclift** [comment]
Yep, will do shortly. :smile:

**Comment by justinclift** [comment]
Just tested on Fedora 25, and the imports worked.  I'll test it on the OSX Desktop in a few minutes too just to make sure, as that's what the problem originally showed up on.

**Comment by justinclift** [comment]
Awesome, yep this is definitely fixed now @MKleusberg.  Tested it now on the OSX desktop... import went flawlessly. Thanks heaps. :smile:
