### ISSUE TITLE
Feature request: Option to keep sql tabs on open database

### ISSUE THREAD

**Issue by palmiche** [sqlitebrowser/sqlitebrowser#1035]
### Details for the issue

When working with copies of the same database is anoying to reopen every sql tab you had because DB4S closes them very time you open a another DB.

Right now I'm working on android and using adb to retrieve the db from the device. That means for every change I make to the data via app I have to open the new copy and reopen every query I was using at the time.

Please add a simple option preventing DB4S crearing the whole workspace. Or a dialog asking if you want to preserve your stuff when opening a new database.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ x ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ x ] Windows: ( _version: 8.1 Pro )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ x ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ x ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ x ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Sounds like a good idea.  I kind of think someone may have already asked about this previously, but I'm not finding it when looking through our issues either.

@MKleusberg As a related thought, how feasible do you reckon it would be to save the contents of the Execute SQL pane (just the SQL, not the results) in our project files?  So that when a person loads a recent project (eg via Ctrl+1 keypress or equivalent), their desired SQL automatically comes along with it.

**Comment by palmiche** [comment]
@justinclift Just in case I do not reopen databases very ofter and when I do is usually for a different issue and using different queries. What I usually work with is numbered or timestamped db names like:
- bd-834.db
- bd-836_release.db
- bd-20170605-101348-000539_error_cliente.db
And all with a single DB4S instance.

**Comment by justinclift** [comment]
@palmiche Ahhh ok.  Yeah, the "saving Execute SQL in project files" wouldn't help at all in that scenario.

**Comment by MKleusberg** [comment]
@justinclift That's already in there, I believe since the first version of the project files even :smile:

@palmiche Good news, I've just changed the SQL tab handling a bit :wink: There is no extra option (yet) but the new default behaviour should be pretty much what you need. When closing a database a new one we'll keep all SQL tabs opened. When opening a new database only 'empty' SQL tabs are closed. This way you won't have a load of empty tabs after a while but you can still keep your actual tabs opened. Like the other thing with the read only files this will be in the next nightly build. So while you're at it, can you have a look at the tab closing, too, and check if it's now working better for you? :smile:

**Comment by palmiche** [comment]
@MKleusberg is there some afternoonly build? Night seems a long way off. 😄

**Comment by justinclift** [comment]
Hmmm, I'll kick off the nightly build script again now, which will overwrite the existing from from this morning.  It takes about 1/2 hour to run, so check the date/time stamp before you download just to make sure it's looks like an afternoon/evening run made it. :smile:

**Comment by MKleusberg** [comment]
@palmiche Haha 😆 Well, you're from Chile aren't you? Since the nightlies are uploaded at 03:45 (probably UTC or UTC+1, but I don't know), it'd be today in the late evening for you, I guess. But Justins build is still going to be faster :wink:

**Comment by palmiche** [comment]
@justinclift and @MKleusberg are awesome! 👍 (in no partcular order 😆)

@MKleusberg 
> Well, you're from Chile aren't you?
I'm _in_ Chile but I come from warmer waters, namely Cuba. 😄
Not that it matters because both are in the same zone now. 😉

**Comment by justinclift** [comment]
Just looked at the build progress, seems to be finishing up now.

Give it 5 mins or so for the uploading of the builds to complete. :smile:

**Comment by justinclift** [comment]
k, it's ready to try. :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
Note - I'm signing off for the night now, so if it all goes badly I'm still not going to be around to kick off another manual run.

Instead you'd need to rely on tomorrow's automatic build in ~5.5 hours from now. :wink:

**Comment by MKleusberg** [comment]
@palmiche Thanks :wink: I've actually been to both Cuba and Chile (though Chile only for a couple of days) but didn't even know that they were in the same time zone 😆 

@justinclift Good night! 😄

**Comment by palmiche** [comment]
It's alive! (error: mad scientist emoji not found) 😄 
@justinclift @MKleusberg both this and #1036 are down for the count so I'm closing both. And I didn't have to wait a few more hours. 😆
Again: you guys rock!

@MKleusberg 
Only while both Chile and Cuba are on DST. Chile goes GMT-3 -> GMT-4 and Cuba GMT-5 -> GMT-4 so they meet in the middle. Note that this information is subject to change because Chile changed DST _and/or_ TZ three times in the las two years. 😄

**Comment by MKleusberg** [comment]
Awesome :smile: Thanks for testing this so quickly! And I've learned something about Latin America on the way :wink:

**Comment by palmiche** [comment]
Well, I _am_ one of your users and from all the pies I have my hands on that damned android app is one of the most... anoying, so whatever I do to help you will work towards less hair falling out of my head. 😁
