### ISSUE TITLE
Export CSV not escaping columns or newlines in 3.9.1

### ISSUE THREAD

**Issue by kaisershahid** [sqlitebrowser/sqlitebrowser#1037]
hi, i tried exporting some tables to CSV and i saw that any columns with newlines weren't quoted, nor was the newlines themselves escaped, causing issues with parsing/importing in other contexts.

**Comment by justinclift** [comment]
Interesting.  Do you have an example .csv file with the problem result which we could take a look at? :smile:

**Comment by kaisershahid** [comment]
sure thing! although the examples contain private info that i shouldn't attach here--is there a way i can send you something privately?

**Comment by justinclift** [comment]
Sure, email me directly at justin AT postgresql DOT org. :smile:

**Comment by chrisjlocke** [comment]
Don't forget that exporting (on Windows in v3.9.1) didn't set any options...

![image](https://user-images.githubusercontent.com/7872218/26946013-b5a124ba-4c85-11e7-8d4a-43dfe1184807.png)

Check the export options are set...

**Comment by chrisjlocke** [comment]
I'd also try the nightlies, as v3.9.1 is relatively old now - so many fixes have taken place since that release.

**Comment by justinclift** [comment]
@kaisershahid Did exporting with newlines select in the drop down work? :smile:

**Comment by justinclift** [comment]
Damn, I'm at a loss on how to figure this one out.  For me, the newline options work ok with the data you emailed me... gahh. 😦

**Comment by chrisjlocke** [comment]
@justinclift - How did you enter the multiline text?  On Windows, using the 'Edit Database Cell' doesn't work properly.  Actually, its more the 'import' and 'export' options don't work properly.

When I created multiline fields and exported them, the CSV was without line breaks.

![image](https://user-images.githubusercontent.com/7872218/27585991-4ca9a0f8-5b36-11e7-99a3-b6e483de28c1.png)

![image](https://user-images.githubusercontent.com/7872218/27586008-5f542b42-5b36-11e7-80b5-05f4fa5f3270.png)

**Comment by justinclift** [comment]
Interesting.  I was testing stuff on OSX, and it seemed to work for me.  I'm not sure if I tried multi-line-within-a-field stuff though... I think I may have misunderstood the problem then. Oops. 😇

**Comment by chrisjlocke** [comment]
Clues in the title.... ;)  
If a field contains a carriage return (or newline...) then its not exported at all (as per my screenie above)

**Comment by MKleusberg** [comment]
@chrisjlocke What happens if you open the CSV file in a different editor, e.g. Wordpad (if that still exists on newer Windows version :wink:)? Do the line breaks appear then? I'm asking because Notepad doesn't show ```\n``` line breaks at all and I can imagine that the line breaks in the columns are ```\n```, not ```\r\n``` like the line separator.

If the line break does appear inside the column when viewing it in a different editor (for me it does), then that is a correct CSV file: you'd have the line break (unescaped!) but inside a quoted column. According to the CSV standard (see here, point 2.6: https://tools.ietf.org/html/rfc4180#section-2) that's how you're supposed to do it. And apparently Excel is doing the same thing, at least according to  [this](https://superuser.com/questions/302334/true-difference-between-excel-csv-and-standard-csv) answer.

**Comment by justinclift** [comment]
@kaisershahid I can email the database file you sent me to @chrisjlocke and @MKleusberg for them to double check, if that's ok with you?

**Comment by kaisershahid** [comment]
@justinclift yup that's fine! @MKleusberg what i was seeing is that the columns were not quoted at all (unless it had quote chars inside already)

**Comment by justinclift** [comment]
@kaisershahid Just forwarded your database to @MKleusberg and @chrisjlocke. :smile:

**Comment by MKleusberg** [comment]
Hmm, I'm still not 100% sure about this :wink: I've just made a commit to force-add quotes if there is a newline character inside a field. Prior to this quotes would have only been added when a quote char was selected. But even if none is set, adding quotes might make sense because otherwise the resulting CSV file is pretty much unparsable.

@kaisershahid Does this already help in your case? You can test it by downloading and installing tomorrow's nightly build (see our main page for the link). If it doesn't can you make a screenshot of the CSV settings in the dialog?

**Comment by kaisershahid** [comment]
@MKleusberg that should do it! i'll get the new build and test tomorrow, will keep you posted

**Comment by kaisershahid** [comment]
@MKleusberg @justinclift @chrisjlocke looks like this is working now. thanks a lot for looking into this!

**Comment by justinclift** [comment]
Awesome @kaisershahid. :smile:

I'll close this now, but if it turns out to still need a bit more tweaking to get this issue fully solved you're definitely welcome to re-open it and let us know. :smile:
