### ISSUE TITLE
Toggle button for remote panel on toolbar?

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1079]
Just putting this here for now, so it's not forgotten. :smile:

It'd probably be useful to have a button in the toolbar which toggles the Remote panel open/closed.

I think it'd help people discover our dbhub.io integration easier, and also make it easier to use.  Especially now that there's a button in the panel to upload stuff easily.

We're likely want to make the button only show if the user has the Remote panel enabled in Preferences (which it is by default).  If they disable the panel in Preferences, obviously it's not useful to show them the toolbar button any more. :wink:  i.e. No need to pull a Microsoft here and attempt forcing people to use something if they don't want to :wink:

If no-one has objections, I can probably get it figured out/implemented tomorrow sometime.

**Comment by MKleusberg** [comment]
Hmm, I would probably object that we don't have any toolbar buttons for the other panels either. In general, we only have the bare minimum when it comes to toolbar buttons (somewhere there's an open issue about not having a close database button). So to me it seems strange to have a 'Toggle remote dock' button - not only because it just doesn't seem as important as the other buttons but also because even dbhub users probably won't toggle the dock too often :wink:

I *think* for new installations the remote dock is visible by default, isn't it? My assumption here is that this will be enough to direct users to the dbhub features. What do you think?

**Comment by justinclift** [comment]
Heh Heh Heh

I guess we can leave it without and see how it goes.  Ironically, I was missing not having a "Close database" button just yesterday myself.  Didn't actually think "hmm, I could add that..." at the time though.  Maybe another task, for later, in itself. :wink:
