### ISSUE TITLE
Incorrect syntax highlighting when using the ESCAPE keyword

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#1080]
### Details for the issue

Any text after using the `ESCAPE` keyword with double quotes shows up pink:

![screen shot 2017-08-11 at 17 59 28](https://user-images.githubusercontent.com/5748627/29219221-1dee07a6-7ec0-11e7-9d4a-9de3fd920a51.png)

Replacing that with `ESCAPE '\'` "solves" it.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_ 10.12.5 (16F73) )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.0-beta1
- [ ] 3.9.1
- [ ] Other: 3.9.99 (a nightly from some weeks ago)

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Is this in 3.10.0-beta1 or latest source or ?  :smile:

**Comment by revolter** [comment]
I didn't test it

**Comment by MKleusberg** [comment]
Hi Iulian! Nice to see you here 😄 

I'm currently looking into this issue and I'm pretty sure it's been in every version since 3.0 :wink:

**Comment by MKleusberg** [comment]
Ok, I think I got it 😉 It's actually a bug in Scintilla. It was previously reported [here](https://sourceforge.net/p/scintilla/bugs/725/) but then closed because nobody bothered to fix it. I have now fixed it in our copy of the code but we should really try to get the patch merged upstream because
1) the path is just my attempt to fix this bug without having any further insight into the lexer code and getting it double checked seems like a good idea.
2) this way we don't have to maintain a patch set in our repository.
3) this way users of Linux packages will profit too because many distributions use their Scintilla package instead of ours.

So does anybody of you have a Sourceforge account? Because I don't :wink: If you have one and can spare a minute, this is the patch to propose:
```
diff -r 0e8968428a58 lexers/LexSQL.cxx
--- a/lexers/LexSQL.cxx	Fri Aug 11 10:05:07 2017 +1000
+++ b/lexers/LexSQL.cxx	Fri Aug 11 18:06:15 2017 +0200
@@ -547,7 +547,7 @@
 			}
 			break;
 		case SCE_SQL_STRING:
-			if (sc.ch == '\\') {
+			if (options.sqlBackslashEscapes && sc.ch == '\\') {
 				// Escape sequence
 				sc.Forward();
 			} else if (sc.ch == '\"') {
```

**Comment by justinclift** [comment]
Yeah, I still an ancient SF account.  I'll give it a shot. :smile:

**Comment by MKleusberg** [comment]
Cool, thanks 😄 That spares me creating one :wink:

**Comment by justinclift** [comment]
Done: https://sourceforge.net/p/scintilla/bugs/1968/

Hopefully opening a new ticket for it was ok. :wink:

**Comment by justinclift** [comment]
It turns out the Scintilla project is currently in freeze for their upcoming 4.0 release, so they'll look at the patch after that.

**Comment by MKleusberg** [comment]
Ok cool, that's fine 😄 We can keep the patch in our code base then until they release 4.0.

**Comment by revolter** [comment]
Hi Martin, nice to "see" you (r commits) too.

**Comment by mgrojo** [comment]
This is fixed in our code and the patch for Scintilla is already merged. Can this be closed so it appears no longer as pending?

**Comment by justinclift** [comment]
Definitely.  Good reminder @mgrojo. :smile:
