### ISSUE TITLE
Changes are not saved when closing a database

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#1117]
### Details for the issue

1. Create table.
2. Close Database
3. Say 'Yes' to 'Save changes?'
4. Open database
5. Cry as table has not been saved.  Throw arms in air and scream, "Why me??????"

https://screencast-o-matic.com/watch/cbQnIVIfCD

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ _10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.99 (1 Sep)
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Gaaah!

**Comment by MKleusberg** [comment]
Ha, at least for this bug I have an alibi :wink: Good news it's that it's not in the 3.10.0 release but was introduced shortly after. So no need to worry about this one too much (and no need to mention it in the release notes for 3.10.1 because that would just cause confusion). Anyway, I've just pushed a fix for this 😄 

@chrisjlocke As you seem to be testing the Edit Table dialog a lot at the moment, do you mind playing around with it a little more with tomorrow's nightly build? 😄 I've just made some big changes to our backend code and don't trust them at all :wink:

**Comment by justinclift** [comment]
Oops.  That's definitely possible when I was mucking around with the AppImage stuff yesterday.  Looks like I rewound it too far back.

Sorry all! 🤕

**Comment by MKleusberg** [comment]
No problem at all :wink: Thanks to Git magically storing every commit somewhere it took only a minute or so to restore.

**Comment by justinclift** [comment]
Oh, this was an accidental side effect of #1102.  Doh.

**Comment by chrisjlocke** [comment]
> do you mind playing around with it a little more

Will do.  Anything primarily?  WIll try go through the 'common bits', so to speak .. the obvious things.

**Comment by MKleusberg** [comment]
No nothing in particular. I'm just wondering if it still works for all common use cases 😄 One thing you should try though is the ```Temporary Table``` option (hidden behind the ```Advanced``` button in the Create Table dialog) because that's what I'm currently working on. We've supported temporary tables before but didn't do it properly. For example you can create a table both as a normal table and as a temporary table:
```sql
CREATE TABLE test(a int, b int);
CREATE TEMPORARY TABLE test(x int, y int);
```
This is fine for SQLite because they are in different 'namespaces' and therefore the names don't conflict. The first one can be accessed using the name ```main.test``` (or just ```test```), the second one using the name ```temp.test```. But try that with DB4S 3.10.0! It's going to end in a total mess because we don't use these namespaces at all and aren't able to distinguish the two. That should already have improved in the last nightly build 😄 (Hope that explanation makes sense :wink:)

**Comment by justinclift** [comment]
Ahhh, that sounds nifty. :smile:

**Comment by MKleusberg** [comment]
Can we close this issue? :smile:

**Comment by chrisjlocke** [comment]
Closing as orignal issue fixed.  Thanks @MKleusberg .  💋
