### ISSUE TITLE
Execute SQL tab: UI tweak.  Move "Export to CSV" button to top row

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1122]
### Details for the issue

An UI optimisation has been suggested by a new-to-SQL user here:

&nbsp; &nbsp; https://discuss.zetetic.net/t/save-query-results-as-csv/2343/4

In the issue discussion thread there, they were looking for the `Execute SQL` tab's "Export to CSV" button in the top row, where all of the other buttons are.

It might be decent idea to move it there, so that new users find it easier.  It shouldn't be much/any problem for more experienced users to locate it's new location. :smile:

#### I'm opening this issue because:

- [x] DB4S has another problem

#### I'm using DB4S version:

- [x] 3.10.0

**Comment by chrisjlocke** [comment]
Its not a 'global' button though, but a tab-related button - the button (if moved) would have to know what tab you're on about, and talk to the controls on that tab.  I don't know Qt, but from my VB eyes, it looks like a lot of work....

**Comment by justinclift** [comment]
Oops, I should have been clearer. :smile:

![db4s-1122_from](https://user-images.githubusercontent.com/406299/30223974-de6544da-94c4-11e7-906c-4744c94023b3.png)

![db4s-1122_to](https://user-images.githubusercontent.com/406299/30223978-e2566844-94c4-11e7-8137-c9fb5a943ad0.png)

**Comment by chrisjlocke** [comment]
Yup, got that. But it's still related to the tab its on. Actually (now my brain is plugged in) I guess it's how the other buttons work... I'll shut up! ;)

**Comment by MKleusberg** [comment]
I've tried to move the button to the toolbar :wink: Turns out this isn't as easy as it seems, so I've added this to the 3.11.0 milestone instead of the 3.10.1 one. It should mostly work the same as before with one small difference: if you execute some statement in tab 1, then change to tab 2, and back to tab 1, the button is disabled until you execute the statement again. I hope that's not causing too much of a problem :wink:

**Comment by justinclift** [comment]
Awesome, thanks @MKleusberg.  Hopefully this does turn out better for new users, and doesn't inconvenience our existing ones. :smile:

**Comment by chrisjlocke** [comment]
Just a nod that whenever you open a database or project, TAB 1 is created, regardless of whether one is there already or not.  This is only repeated once (ie, you don't get more than 1 additional tab each time you open a database)

https://screencast-o-matic.com/watch/cbQl2kII93

**Comment by justinclift** [comment]
Yeah, this is on purpose.  It's so people don't lose their existing Execute SQL queries/results when closing a database.  Looking quickly, #1035 seems to be the one. :smile:

**Comment by chrisjlocke** [comment]
Aah, OK.  Excellent!  Well found! 🔎

**Comment by MKleusberg** [comment]
Can we close this issue? :smile:

**Comment by justinclift** [comment]
Testing it out now. :smile:

**Comment by justinclift** [comment]
Yep, this is working decently in testing here.

> if you execute some statement in tab 1, then change to tab 2, and back to tab 1, the button is disabled until you execute the statement again.

Is this something we should fix now (ie leave this open), or ignore until someone ask for it? :smile:

**Comment by MKleusberg** [comment]
I think I would leave it until somebody asks for it :wink: I think we would need to remember the execution status for each tab for this which shouldn't be too hard because it's mostly already saved in the table widget. But it's probably not worth the effort right now and I'll forget to add this anyway until somebody opens an issue for it 😆 So we might as well close this one now.

**Comment by justinclift** [comment]
Cool. :smile:
