### ISSUE TITLE
Filter by "IS NOT" NULL

### ISSUE THREAD

**Issue by renschler** [sqlitebrowser/sqlitebrowser#1124]
### Details for the issue

This is an enhancement request. I want to be able to filter by IS NOT NULL for a column in the DB Browser. I understand the syntax would be "<>NULL". This does not seem to be working. This seems related to https://github.com/sqlitebrowser/sqlitebrowser/issues/588 but for "IS NOT" instead of "IS".

Many Thanks!
Patrick

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:10.12.6 )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.0
- [ ] 3.10.0-beta*
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [no] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

This issue is similar: https://github.com/sqlitebrowser/sqlitebrowser/issues/588
but it only covers the =NULL case, not <>NULL (afaik)

**Comment by justinclift** [comment]
Ahhh yeah.  Makes sense, and should be reasonably easy to implement too. :smile:

**Comment by MKleusberg** [comment]
Oh, I wonder how we (or I) missed that while implementing #588 :wink: But I've just implemented the '<>NULL' syntax and it should be working in the next nightly build. Can you download that tomorrow (from [here](https://nightlies.sqlitebrowser.org/latest/) and give it a try, @renschler? :smile:

**Comment by renschler** [comment]
Sounds good, will do, thanks!!

**Comment by renschler** [comment]
I played with the Sept-11 nightly build. Looks good to me 👍

**Comment by justinclift** [comment]
Excellent.  Thanks for testing and confirming @renschler. :smile:

Well done @MKleusberg. 😁

**Comment by chrisjlocke** [comment]
Just a thought, but <>null isn't valid SQL.  I appreciate these are filters and not SQL, but having two conventions in one product seems a bit odd.  "type values in here, but they're not valid here".  It wouldn't be hard to 'convert' 'is null' into '=NULL'

On a side point, '=NULL' works, but '=null' doesn't - its case sensitive.  Is this by design?
NULLs aren't mentioned in the [Wiki](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Using-the-Filters) at all.  I'll amend that tomorrow.

**Comment by MKleusberg** [comment]
Yeah, the conventions are a bit odd. The idea was to make them as unambiguous as possible, i.e. make sure it's clear what's a special comparison operator and what is not. If we allowed 'is null' as a filter value and treated it like '=NULL' that would mean that it's not possible to filter for an 'is null' string in a text column (except by searching for '=is null' but that's not obvious either and other than 'is null' this is case-sensitive).

So yes, it's all intentional and by design. But you can definitely question the design :wink: Not sure what the best compromise would be. Either way, it's probably a good idea to document this in the Wiki :smile:
