### ISSUE TITLE
Needs UI for adding Unique Contraint for Multiple Columns

### ISSUE THREAD

**Issue by fusionstream** [sqlitebrowser/sqlitebrowser#1139]
On DB4S 3.10.0

There is no provision to add a unique constraint for multiple columns as one (like a multi column primary key), but there is a provision to add the unique constraint to each column.

Issue recreated from https://github.com/sqlitebrowser/sqlitebrowser/issues/1126 for clarity as previous one had multiple issues, and only this one is valid.

**Comment by fusionstream** [comment]
SQLiteStudio has a  button to add a constraint that opens up a dialog:

![image 2](https://user-images.githubusercontent.com/3389188/30409434-86f1c9f4-9937-11e7-9721-1b941369b905.png)

Clicking 'Unique' allows you to create the contraint

![image 3](https://user-images.githubusercontent.com/3389188/30409437-88b0e50e-9937-11e7-8896-9d8235eab64c.png)

**Comment by chrisjlocke** [comment]
UI suggestion for multiple column indexes.

![image](https://user-images.githubusercontent.com/7872218/30329275-bd9189f0-97c9-11e7-838b-0aa237280a86.png)

eg:

![image](https://user-images.githubusercontent.com/7872218/30329321-dc240fbe-97c9-11e7-8de9-0803255e49fc.png)

Not sure why I've pasted two images when one would have done, but hey.
This is from DbMouse, a SQL Server database manager I use.

So this UI part is used for indexes, regardless of whether they're multiple fields or not, so this could be used for constraints, indexes, etc.

**Comment by justinclift** [comment]
> Right now, it blocks development with DB Browser ...

Best workaround for now is to probably craft a SQL statement for running directly in the Execute SQL tab.

Backup your data first though, and maybe experiment on a copy until you're happy with the result to be safe. :smile:

**Comment by MKleusberg** [comment]
We have started adding constraint editing capabilities to the Edit Table dialog. Starting with tomorrow's nightly build it's now possible to add constraint, editing constraints already works since a couple of days. There is still no way to fully edit all parameters of any constraint type but multi-column unique constraints work fine:

![Screenshot_20190810_150741](https://user-images.githubusercontent.com/3153504/62822219-bba6f580-bb80-11e9-8750-266527b72a05.png)

Are you still around to give this a try, @fusionstream? If so, you can download the new version tomorrow from [here](https://nightlies.sqlitebrowser.org/latest/). If not, no worries. We can just close the issue then :smile:

**Comment by justinclift** [comment]
@fusionstream Ping?

**Comment by fusionstream** [comment]
Just saw this. Will give this a try asap (but not like today). Figured I'd post first since your ping was from 29 days ago.

**Comment by fusionstream** [comment]
Works as expected. Thanks very much!

**Comment by justinclift** [comment]
Awesome!  Thanks for testing @fusionstream.  And good work @MKleusberg. :smile:
