### ISSUE TITLE
Edit database in package

### ISSUE THREAD

**Issue by Alkier** [sqlitebrowser/sqlitebrowser#1150]
### Details for the issue

Hi,

I need to access a database within an package-directory on Mac. When trying to open the file i get a file locked error. I can copy the database outside the package and access without problems.

Does the browser not support accessing/editing databases within package-directories?

Best,

Jakob

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x] Mac OS: ( _version:_10.12.6 ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting question.  With the package directory you're trying to look into, you're meaning a .app somewhere inside (say) `/Applications` yeah? (just making sure I'm understanding)

If that's the case what is the primary owner and group for the .app directory set to?  This kind of sounds like a permissions problem, with (for example) the .app directory being owned by (say) root, which disallows things inside it to be changed.

That would kind of match the behaviour you're describing, because DB4S wouldn't be allowed to change a database file it doesn't have permission to.  But when you copy the database file to a new location, the new copy is owned by your users and DB4S can work with that.

This is all a rough guess though.  But worth looking into if you haven't solved the problem yet. :smile:

**Comment by Alkier** [comment]
Hi Justin,

It is actually a database within a "Photos Library" I am accessing. The photos library is a package it contains a sqlite database with reference to all images.

I am the owner of the file. 

I tried again and now it worked. Must have been the photos app that was not completely closed yet.

Best,

Jakob

Den 22. sep. 2017 kl. 22.43 skrev Justin Clift <notifications@github.com>:

Interesting question. With the package directory you're trying to look into, you're meaning a .app somewhere inside (say) /Applications yeah? (just making sure I'm understanding)

If that's the case what is the primary owner and group for the .app directory set to? This kind of sounds like a permissions problem, with (for example) the .app directory being owned by (say) root, which disallows things inside it to be changed.

That would kind of match the behaviour you're describing, because DB4S wouldn't be allowed to change a database file it doesn't have permission to. But when you copy the database file to a new location, the new copy is owned by your users and DB4S can work with that.

This is all a rough guess though. But worth looking into if you haven't solved the problem yet. 😄

**Comment by justinclift** [comment]
No worries.  Glad it's working now. :smile:
