### ISSUE TITLE
CSV import for large file crashes after 31.000 rows

### ISSUE THREAD

**Issue by tueddy** [sqlitebrowser/sqlitebrowser#1154]
### Details for the issue

Hi,

i try to import a very large CSV file into SQLite table. the filesize is > 1 GB.
Fields and separators are recognized fine and import starts. After 31.000 rows the program crashes

I can upload the file for you privatly if want.

SQLiteStudio can import this file after ca. 10 minutes but scrambles the field order.

Best regards
Dirk
#### I'm opening this issue because:

- [x ] DB4S is crashing

#### I'm using DB4S on:

- [ x] Windows: ( _version: 7)

#### I'm using DB4S version:

- [x ] 3.10.1

**Comment by MKleusberg** [comment]
Thanks for reporting this issue, @tueddy! This is actually excellent timing because I've only recently spent some time improving the CSV import stability and speed. You can try the improved code by installing our latest nightly build. Here's the download link: https://nightlies.sqlitebrowser.org/latest/ 😄 Can you check if that fixes your issue?

**Comment by tueddy** [comment]
Hey perfectly cool!!!
Import is fast as lightning, accurate, has progress and finish fine, Thanks!

Best regards
Dirk

**Comment by MKleusberg** [comment]
Awesome :smile:

**Comment by MKleusberg** [comment]
@tueddy If you're still interested in this, you can also try out the most recent nightly build again. We were able to speed up the import even more, especially for large files :smile: If you try, I'd also be interested to know how long it now takes with DB4S :smile:
