### ISSUE TITLE
Multiple SQL tabs titled "SQL 1"

### ISSUE THREAD

**Issue by AGlezB** [sqlitebrowser/sqlitebrowser#1163]
### Details for the issue

Every time a different database is opened a new SQL tab titled "SQL 1" is created as long as the last one has text.

![2017-10-04 11_21_20-db browser for sqlite - d__aglezb_notes_proyectos_sgc_android_sqlite_galaxy_tab_](https://user-images.githubusercontent.com/12277525/31181974-05b93774-a8f9-11e7-81ca-51e82a4ad957.png)

Possible solutions:
1. Not to auto-open new tabs.
2. Keep count so next time opens "SQL 2", "SQL 3", etc.

I'd prefer solution 1 because a secondary effect of auto-opening tabs is that you loose the focus of the tab you where working on. If I want a new tab I just need one click. Closing the new tab and going back to where I was is more complicated, even more so if I have a lot of SQL tabs.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version: 8.1 Pro)
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
I sort of mentioned this in #1122 (didn't realise it was linked to whether it contained text) and apparently its 'by design'.

**Comment by justinclift** [comment]
Oops.  Hadn't realised the number on the tab doesn't increment.  It probably should. :smile:

We can probably also tweak the defaults a bit, or make the automatic creation of tabs a preference setting.  The automatic creation thing was because it was asked for.

Sounds like it gets in way for some people though, so making it a preference setting is probably the right approach.

**Comment by chrisjlocke** [comment]
> Sounds like it gets in way for some people though

If its only creating a new tab because the other tab has text in it, then its probably a good thing.  I believe (looking at the original screenshot) the issue is the multiple 'Tab 1' texts.  
Opening a new database resets the tab counter, which is the only 'bug' I guess.
![image](https://user-images.githubusercontent.com/7872218/31218098-247cd9dc-a9b1-11e7-8c0b-f659021a6dd9.png)

**Comment by palmiche** [comment]
@justinclift A setting please.  :smile:
@chrisjlocke While maybe not a bug, loosing focus after opening another database is certainly not something I'd want as default behavior.
Even when the absolute majority of your users want a feature there will _never_ be a case where 100% of them are satisfied so making it a preference setting is as close as it gets to a _right answer_. Microsoft has a particularly bloody track record in this regard. Just make a list of all _improvements and innovation_ of Win 10 over 8.1 and everything that came in the updates afterwards and you'll notice 90% of them are completely useless to you in the best case scenario. Worst case those _features_ will actively intefere with your work and have you waste time googling -or even worst: binging- for some way to disable or completely uninstall them. And if you hear them talking about it you'll easily believe they invented fire, fireworks _and_ the printing press.  :grinning:

**Comment by sky5walk** [comment]
This bug still exists in latest 3.11.99 nightly v190208.
I have an open project of SQL queries that I run against the currently opened DB.
When I close the DB and open another DB, a new empty SQL 1 tab is appended to my list and given focus. I am forced to relocate my intended SQL tab and delete the new empty one.
I claim BUG, as the user must react to unintended behavior from a simple Open DB operation.

**Comment by justinclift** [comment]
Yeah, that does sound like a bug. :smile:

**Comment by justinclift** [comment]
@sky5walk As a random thought, since you seem to spend a good amount of time doing stuff here in the DB4S repo on GitHub... any interest in being added to the developer team here on GitHub?

Mostly so you'd have access to create/change/etc stuff here in the GitHub issues.  We could certainly do with some extra hands helping out with them. :grin:

**Comment by sky5walk** [comment]
Well, I am not in the repo per se, just reporting issues/requesting features that affect my users.
I would need time(expensive commodity) to setup a Qt system as that is not in my development wheelhouse.

**Comment by chrisjlocke** [comment]
Don't forget you can rename tabs, so you don't have to stick with the default 'SQL 1' name.  You can also move them, so the one you want is the first one, for example.  Doesn't solve your issue, but goes a little way to make it a bit easier...

**Comment by sky5walk** [comment]
Yes, the SQL tab rename/rearrange is a great feature and the main reason I use Projects. 😄

**Comment by mgrojo** [comment]
@sky5walk, this should be solved by d567f3856ffeb2eaa6523583c04b557c0622f804 Could you confirm it using the 3.12 alpha release or a nightly build?

**Comment by sky5walk** [comment]
Yes, this is fixed and tested on nightly v200503.

**Comment by justinclift** [comment]
Awesome. :smile:
