### ISSUE TITLE
New Version Not Recognized?

### ISSUE THREAD

**Issue by russoen** [sqlitebrowser/sqlitebrowser#1180]
### Details for the issue

Every time I try to open DB Browser for SQL lite, I get a message that says "DB Browser for SQLite is already installed. Do you want to uninstall the old version before installing the new one?". I have already installed the new update, but I am then forced to install it again and open it from the installer (if I do not click "Run DB Browser" checkbox in the installer and just try to open by clicking, I am forced to install again),

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ X] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ X] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
It sounds like you're running the installer, rather than running the program.
The installer generally has version numbers in the filename, and the icon (depending on Windows version) has a 'shield' icon overlayed on it.

![image](https://user-images.githubusercontent.com/7872218/31765243-a7b51976-b4bb-11e7-9bef-83b1ec9968e9.png)

If this lives on your desktop, you can delete this file, or move it to your 'Downloads' folder.

Instead, you should have a 'DB Browser for SQLite' icon on your desktop.

This doesn't contain a version, and no shield overlay.

![image](https://user-images.githubusercontent.com/7872218/31765335-f1dbabe6-b4bb-11e7-9bea-c6e85ae0de71.png)

If you don't have this icon, you can easily create it.  I'll assume DB4S is installed in c:\program files\DB Browser for SQLite

So right click the .exe file in this folder.

![image](https://user-images.githubusercontent.com/7872218/31765424-39da030c-b4bc-11e7-85d8-32ae0c1e7c69.png)

and select 'copy'

![image](https://user-images.githubusercontent.com/7872218/31765467-5c676f90-b4bc-11e7-9622-31f283cf911a.png)

Then on your desktop, right click and select 'Paste Shortcut'

![image](https://user-images.githubusercontent.com/7872218/31765516-8bf74668-b4bc-11e7-97f7-0ad071f77eda.png)

No more installing.

**Comment by justinclift** [comment]
@russoen Have you had a chance to look into that? :smile:

**Comment by russoen** [comment]
Hi Justin,
Thank you so much for the response. The problem has been solved through a combination of your solution and making sure that the correct path was in HKEY_CLASSES_ROOT.

Thanks again!

**Comment by justinclift** [comment]
@chrisjlocke May the `.db` extension was being associated with the installer somehow?

**Comment by chrisjlocke** [comment]
Possibly, but not automatically... 
Also, do you open DB4S always through a file? Opening the shortcut on the desktop or start menu would have worked.
But glad it's sorted...
