### ISSUE TITLE
Feature Request: No Transactions + Refresh

### ISSUE THREAD

**Issue by TonyValenti** [sqlitebrowser/sqlitebrowser#1191]
### Details for the issue

I use SQLite as a temporary DB for an app.  Data gets created and deleted very often including recreating the entire database.

SQLiteBrowser seems to start a transaction as soon as you open the database and commit the transaction as soon as you close it.  I'd like to be able to run it in a mode where connections are only established when a query is run and then they're immediated closed.  This would allow me to completely delete and recreate a database and then rerun a query in SQLiteBrowser without having to close the database and reopen it in SqliteBrowser.

Thanks!

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
I would assume from my limited knowledge of the inner guts of DB4S, that this would be quite an overhaul.  Normally, if you edit a table or add a field, DB4S already 'knows' the table layout, etc.  By closing the database when 'not needed' would imply that DB4S would have to 're-read' the database before each operation, otherwise, you might want to edit a table, but that table no longer exists.  It might already do this, but using that as a poor example.  
So just a heads up that this isn't as simple as adding a couple of lines, and might not be implemented immediately.
I''ve come across this annoyance too though - tried to move a database and can't because its open in DB4S.  It does make sense though, and its good in one way - if you're editing a database, its quite an administrative task, so you don't want to go moving databases while that task is ongoing.

**Comment by mgrojo** [comment]
@TonyValenti  have you tried opening the database in read only mode and then refreshing it as needed? In that  If you don't want to edit the database, just viewing it, that would be your solution.

**Comment by justinclift** [comment]
Ahhh, that's a good idea.  @TonyValenti ?

**Comment by karim** [comment]
Closing this due to lack of response.
