### ISSUE TITLE
macos Version 3.10.1 thinks it's 3.70

### ISSUE THREAD

**Issue by DerUser** [sqlitebrowser/sqlitebrowser#1203]
### Details for the issue

When downloading the latest Version 3.10.1, because of a prompt in the app, and installing it, the app keeps complaining that that there is a newer Version.

The newly installed App is referring to itself as being Version 3.70, too.

Is there a problem with the build system?

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [x ] Mac OS: ( _version:_1 2.6 )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x ] Other: 3.7

#### I have also:

**Comment by justinclift** [comment]
Hmmm, yep something doesn't seem correct there.

Would you be ok to take a screenshot of the bit that says it's version 3.7 and paste it here?  That should help us figure out what's wrong. :smile:

**Comment by DerUser** [comment]
![screen shot 2017-10-29 at 16 10 27](https://user-images.githubusercontent.com/3978662/32145127-b44b8aac-bcc3-11e7-8ae3-6ffda484405d.png)

**Comment by justinclift** [comment]
Ahhh.  It looks like the new version isn't taking for some reason.

When you install the new version, are you manually removing the old (3.7.0) version first?

Personally speaking, I've found that sometimes removing an existing program by dragging and dropping it from the Application menu to the trashcan **seems** like it works... but doesn't.  When opening the Application menu again, the application is still there.

I'm kind of thinking that might be what has happened to you.  There are some ways to **force** the old version to be removed, but lets find out if that's what the problem is first. :smile:

**Comment by DerUser** [comment]
So I found the "bug". The Name of the App changed and therefor opening sqlitebroser via spotlight opened the old version.

Thank you for your time

**Comment by justinclift** [comment]
No worries at all, glad it's working now. :smile:
