### ISSUE TITLE
Network latency due to Qt bug when DB Browser is running on macOS

### ISSUE THREAD

**Issue by gee4vee** [sqlitebrowser/sqlitebrowser#1209]
### Details for the issue

I was getting some network latency over WIFI on my local network (erratic ~200 ms ping response times on 802.11ac), causing issues in the Synergy app (symless.com). As suggested, I started quitting apps to figure out which could be causing it and I found that it was due to DB Browser. The CEO said that there is a Qt bug that is causing this and provided a code workaround that they implemented that you can use.

```
// Workaround for QTBUG-40332 "High ping when QNetworkAccessManager is instantiated" 
#if defined (Q_OS_WIN)
    _putenv_s ("QT_BEARER_POLL_TIMEOUT", "-1"); 
#else
    setenv ("QT_BEARER_POLL_TIMEOUT", "-1", 1);
#endif
```

https://symless.com/forums/topic/4287-choppy-mouse-movement-on-mac-connected-to-pc-server/?do=findComment&comment=19150

Hope this helps.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [X] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version:10.13.1 )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Just a thought, but the issue only affects connections on WiFi, but the workaround is 'global' - it'll nobble the setting whether you're on wireless or not. I assume thats not going to be a major problem? (its only checking for connectivity changes)
If it is, rather than setting the value to -1, maybe increasing it to 15 or 30 minutes?  You'll only get a spike every half hour which is better than every 10 seconds.

**Comment by gee4vee** [comment]
Don’t think it should be an issue. I’m told that this is what the Symless folks did to fix it in their Synergy app. But if necessary 30 mins is reasonable.

**Comment by chrisjlocke** [comment]
No, I was just thinking out loud.  If off is good, it gets my vote.  I primarily use DB4S wirelessly at home, but wired at work.  Never really had an issue, but don't use the network that 'closely'... its usually 'good enough'.... ;)

**Comment by MKleusberg** [comment]
Thanks for pointing this out, @gee4vee. I never would have guessed that there is a problem like this :wink: I've just pushed a fix for this. Can you check if it's now working better for you using one of the next nightly builds?

By the way, I don't set the timer to -1 now because that prints an irritating warning to the console whenever you start the application. Instead I'm setting it to INT_MAX which should give you around 596 hours on most systems between each bad ping value :wink:

It definitely doesn't seem like the right approach but likely it's also the only thing we can do... If anybody notices any side effects of this, please point them out.

**Comment by gee4vee** [comment]
Got the nightly just now and the latency is gone. 👍 👊

**Comment by MKleusberg** [comment]
Awesome 😄  Thanks for testing 👍

**Comment by justinclift** [comment]
Interestingly, it seems like the Qt team are looking into a more proper solution finally:
