### ISSUE TITLE
app crash with "Use as Fiter" click

### ISSUE THREAD

**Issue by isrep** [sqlitebrowser/sqlitebrowser#1228]
### Details for the issue

DB Browser for SQLite (DB4S) version 23155a7 crashes on Ubuntu v 16.04.3 LTS
Steps:
1. Open  DB Browser for SQLite
2. make sure you are in Browse Data tab
3. Right click in Browse window
4. Left click on Use as Fiter menu
application crashes

There are several other places application crashes. 
I consider most unfortunate crash while attempting to export data as SQL Inserts.
While clicking on saving the file application crashes and only zero byte export file is created. 
Thank you for looking into it

#### I'm opening this issue because:

- [x] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _Ubuntu v 16.04.3 LTS_ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: latest 23155a7

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
Thanks, @isrep 😄 These are very good catches, especially the one about the SQL export because that one is related to the multi-threaded data loading which I have started to implement some while ago and which is still a bit buggy. So any issue reports related to that are highly welcome :wink:

I believe I have just fixed both crash issues you have mentioned. Can you recompile using the latest commit and check if they are fixed for you? :smile: Also, if you have noticed any other ways to crash the application, you're very welcome to open more issues for them.

**Comment by isrep** [comment]
Thank you @MKleusberg for quick fix.
On my system I can confirm with version 3b511f83c36 both issues fixed.
I shoud express earlier my thanks for your fine program.

Would I encounter any glitches I will not hesitate to report them. Thanks.

**Comment by MKleusberg** [comment]
Cool, thanks for testing, @isrep 😃
