### ISSUE TITLE
Can not change the sql excute result area font

### ISSUE THREAD

**Issue by siqinbilige** [sqlitebrowser/sqlitebrowser#1240]
### Details for the issue
Can not change the sql excute result area font.
Because there is no mongolian (1800-18AF) system font on Mac OS. So I want to change the result erea font to my own font, but not way to do it.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version:10.12.6 )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [X] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by siqinbilige** [comment]
![2017-11-22 11 27 05](https://user-images.githubusercontent.com/13462439/33108242-a29f2ea8-cf7e-11e7-9757-e4ff6542d53c.png)

**Comment by justinclift** [comment]
Ahhh, that's a good point.  Just tried it here, and I couldn't find a way to change the font for the results area either.

It wouldn't make sense to just apply the "SQL Editor" font to the results area either, because then databases that have a different language in the results than being used by the system itself (like in your example) wouldn't display correctly.

We'll probably need to add a new drop down font selector in the **Preferences** → **SQL** tab to choose the results font.  That's probably not too hard to get done. :smile:

**Comment by MKleusberg** [comment]
How very odd, I was sure that the same font settings as for the Browse Data view would apply here too. But apparently not :wink:

I have just fixed that. So with the next nightly build you will be able to change the font in ```View``` -> ```Preferences``` -> ```Data Browser``` -> ```Font```. Can you try if it's working for you, @siqinbilige? 😄

**Comment by justinclift** [comment]
@siqinbilige Ping.  Would you be ok to try our latest nightly build and test if this is working for you now? (and let us know too) :smile:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by justinclift** [comment]
@siqinbilige Reminder ping? :smile:

**Comment by justinclift** [comment]
Closing this due to lack of response.
