### ISSUE TITLE
ATTACH db2; Then SELECT from db2 sets db1 as changed?

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1249]
### Details for the issue
I appreciate SQL support for ATTACH DATABASE, but why does it change my initially loaded database after executing a SQL query of the newly attached database?

### Useful extra information
  Example SQL:
```
  ATTACH 'C:\mydb\db2.db' as db2;  --<< db1 is NOT changed
  SELECT * FROM db2;               --<< db1 is NOW changed?
  DETACH db2;                      --<< db2 is LOCKED? Why?
```
#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( 10 Pro x64 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: latest nightly 171202

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @sky5walk, that sounds like a bug. :smile:

**Comment by sky5walk** [comment]
Is this a tough bug?
If/when fixed, I can deliver complex SQL queries to users' projects instead of standalone app for multi-database queries.

**Comment by justinclift** [comment]
Ahhh, it shouldn't be.  We've just been focusing on fixing other bugs is all.

The `ATTACH` code was written by @MKleusberg not that long ago, so he'll probably be the one to look over this.  My reading of the issue makes it sound like this is just a fairly straightforward thing to fix.  Hopefully I'm not wrong though. :wink:

**Comment by sky5walk** [comment]
Ok, thanks for the heads up. You guys are cranking!

**Comment by justinclift** [comment]
@MKleusberg This is a reminder ping, for when you have some spare time. :smile:

**Comment by MKleusberg** [comment]
Thanks for the reminder :wink:

I have just tried your example SQL using the latest version and this is what I got:
```sql
ATTACH 'C:\mydb\db2.db' as db2;  --<< db1 IS changed
SELECT * FROM db2;               --<< db1 is still changed
DETACH db2;                      --<< db2 is NOT locked
```
When using the menu option to attach the second database, db1 isn't changed. So either way, my results are different than yours, @sky5walk. Don't know why.

That said, I have just pushed a commit which fixes the problem that ATTACH statement set the modified flag. So the issue which I got is fixed by that. Can you give tomorrow's nightly build a try and see if that is working as expected now, @sky5walk? Maybe this commit and some earlier changes already fix your problem.

If not, we need to investigate further 😄

**Comment by sky5walk** [comment]
Thanks, will do.
This is my current behavior with nightly 170103.
```
MENU ATTACH: 'C:\mydb\db2.db' as db2;  --<< db1 is NOT changed.
Execute SQL:
ATTACH 'C:\mydb\db2.db' as db2;  --<< db1 is changed
SELECT * FROM db2.myTable;       --<<
DETACH db2;                      --<< db2 is LOCKED.
```

**Comment by justinclift** [comment]
Hmmm, should that be "180103"? :wink:

**Comment by sky5walk** [comment]
Doh!

**Comment by sky5walk** [comment]
Ok, I tried nightly 180106 and DETACH fails because of lock?
The main db does not flip to changed, but I have intermittent success with DETACH db2?
I tried adding a delay before DETACH but no luck.
```
--DETACH db2;                --< Carrying this statement when final DETACH failed.
--ATTACH 'doc2.db' AS db2;
SELECT * FROM doc AS d1
UNION ALL
SELECT * FROM db2.doc AS d2; --< database db2 is locked: ?
--< START DELAY
WITH RECURSIVE
  cnt(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM cnt WHERE x<1e6)
SELECT x FROM cnt WHERE x=0;
--< END DELAY
DETACH db2;                --< Cannot DETACH
```

**Comment by sky5walk** [comment]
Side Note: Why does this SQL flip loaded db to changed?
```
WITH RECURSIVE
  cnt(x) AS (VALUES(1) UNION ALL SELECT x+1 FROM cnt WHERE x<1e3)
SELECT x FROM cnt WHERE x=0;

```

**Comment by sky5walk** [comment]
And, the SQL log does not show DETACH statements?

**Comment by justinclift** [comment]
@sky5walk Sorry for the delay, we're just a bit snowed under atm. :wink:

**Comment by sky5walk** [comment]
No problem. I am impressed with the development pace and feature set. :)

**Comment by MKleusberg** [comment]
OK, let me summarise the different problems :wink:
- [ ] Can't detach because database is locked
- [ ] RECURSIVE statements set changed flag
- [ ] SQL log doesn't show DETACH statements

The first problem is actually related to another issue we have somewhere. That other issue is about the fact that when you execute a SELECT statement, you will see the Write Changes and Revert Changes buttons be activated for a small amount of time before they are deactivated again. That's because we have to create a savepoint before executing any statement because the statement could write to the database. I will commit a minor change to this shortly which should fix your special case of this problem. Can you check that in tomorrow's nightly build, @sky5walk?

The second problem is sort of related. We have to guess if the database has been changed by a statement and we do this by checking if a statement has returned data. If it hasn't we assume it changed something and vice versa. But your statement doesn't return any data and it doesn't look like a SELECT statement either (by just checking the first word, that is). So our heuristics set the changed flag, just to be sure. In order to fix this we would need to be able to parse WITH statements which is probably quite complicated. So don't expect this to change soon. Sorry about that!

The third problem I can't reproduce, Can you explain what exactly you were doing?

**Comment by sky5walk** [comment]
Yes, I will check tomorrow.
I am confused by your "check if database changed" approach?
Don't most queries return at least 1 row?
"SELECT * FROM db;" should not alter the database unless there are triggers caching queries?
Why not parse the SQL text for "ALTER, CREATE, UPDATE", etc?

I think the 3rd problem with the SQL log is my error?
Let me try tomorrow and see.

**Comment by sky5walk** [comment]
Thanks for the patch. DETACH now works with nightly 180116. :)
I will open another ISSUE for the "database changed" heuristics.

**Comment by justinclift** [comment]
Awesome.  Should we close this issue then? :smile:

**Comment by sky5walk** [comment]
Sure thing. :)
