### ISSUE TITLE
Import CSV with AUTOINCREMENT Key

### ISSUE THREAD

**Issue by Aermec** [sqlitebrowser/sqlitebrowser#1252]
I tryied to import a csv file into a table with a primary auto-increment key with no luck.
Is it possible?
If yes, how?
If not, is it possible to add this feature to the import dialog?

Thanks

**Comment by mgrojo** [comment]
I just tried with a CSV file with empty values for the primary auto-increment key and it has worked (using current development version). Did you tried like that or with the field containing data in the CSV? With data is also working in my version. Could you try again with a nightly build?: https://nightlies.sqlitebrowser.org/latest/

**Comment by Aermec** [comment]
Yes, I tried but it shows an alert -> Inserting row failed: Invalid file format

but if I drop the key column, import in a new table and copy with a sql command, it works so file is fine.

**Comment by justinclift** [comment]
Interesting.  Are we able to get a copy of the database where it fails?  If it's a public database, then maybe chuck it in [dbhub.io](https://dbhub.io).  If it's not, but you're ok to email it, then my email is justin@postgresql.org.  I'll forward it to @mgrojo or @MKleusberg if they're interested in investigating. :smile:

**Comment by justinclift** [comment]
Thanks @Aermec, received the database and forwarded it to @MKleusberg and @mgrojo. :smile:

**Comment by MKleusberg** [comment]
This will be a little tricky to implement and probably require an extra option in the import dialog. I'll have a closer look at our code tomorrow and probably implement it then 😄

**Comment by MKleusberg** [comment]
So, I played around with this a little more and it turns out to be a SQLite weirdness. Executing multiple insert statements with the id field set to NULL works fine and SQLite increments the primary key as expected. Doing the same programmatically using prepared statements results in this error.

We could work around this by constructing insert statements instead but that would slow down the import quite a lot. Having an option for this seems wrong too because it's not really clear what it would be for from a user POV.

So I think the only thing we could do is implementing a way to skip certain columns during import. But that requires a lot of effort for the UI and the import logic. So it's probably not going to happen any time soon.

However, good news is that there is an easy workaround, @Aermec :smile: You can edit the Documents table and turn of the Not Null and the Unique flag of the primary key column, so only Primary Key and Auto Increment are enabled. With these settings the import worked fine for me. If you absolutely need the Not Null and the Unique flags (I think they are pretty much redundant for primary keys with auto increment) you can turn them back on after the import. Does that help you a bit? 😄

**Comment by Aermec** [comment]
@MKleusberg It works! Thanks a lot!

**Comment by MKleusberg** [comment]
Awesome 😄 I'm glad it's working for you now!
