### ISSUE TITLE
Should we add an "integity check" option?

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#1266]
### Details for the issue

SQLite provides a pragma called "integrity_check", which when run tells SQLite to verify the integrity of the entire database (but without checking foreign key constraints).

&nbsp; &nbsp; https://sqlite.org/pragma.html#pragma_integrity_check

Although people can manually run it from the Execute SQL tab (`PRAGMA integrity_check;`)... I'm kind of wondering if we should add a File menu option for it as well.  eg File →Integrity Check

It sounds like the kind of thing which would help newbie users, and more experienced users would just have an easier way to launch it instead of manual typing.

Thoughts? :smile:

#### I'm opening this issue because:

- [x] DB4S has a potential enhancement

#### I'm using DB4S on:

- [x] Linux: ( CentOS 7 x64 )

#### I'm using DB4S version:

- [x] Other: latest git master head

**Comment by justinclift** [comment]
Hmmm, I've just been testing this with some databases I've written random data into the middle of.

SQLite doesn't seem to really catch that much in the way of corrupted databases.  Not sure adding an integrity_check option would be all that useful. 😦

**Comment by MKleusberg** [comment]
Yeah, it's probably not super important because experienced users can execute the pragma via the Execute SQL tab and for inexperienced users the menu option would probably be confusing because (just as you noticed) it's not really checking that much.

But still, if somebody thinks it's a nice addition, we can easily add a menu option :smile:
