### ISSUE TITLE
Abort long-running queries

### ISSUE THREAD

**Issue by Bilge** [sqlitebrowser/sqlitebrowser#1274]
There should be a mechanism to abort queries that run so long they hang the UI thread. Aside, it would probably be a good idea to run the query on a separate thread, but I digress. When a long-running query hangs the program, often due to incorrect query construction, there needs to be a way to abort the operation without killing the process and losing all your work.

**Comment by justinclift** [comment]
Hmmm, I could have sworn we've done some work around this not long ago.

Not sure if it's in the 3.10.1 release though.  Just to check, are you using a recent-ish nightly build, or the 3.10.x release?  If you're using the release build, try a recent nightly. :smile:

**Comment by Bilge** [comment]
Currently on 3.10.1.

**Comment by justinclift** [comment]
Cool.  Try a long running query (in the Execute SQL) window, and see if the UI gives a cancel option.  I'm pretty sure it does now.  (I don't have the bits in front of me to check myself just atm)

**Comment by MKleusberg** [comment]
@Bilge Sorry for the long delay here. Are you still interested in this issue? I'm asking because we are currently preparing some changes which add, besides making some other changes, a cancel button to the Execute SQL area. Because it's changing a lot of our code we want to test this as good as we can. Are you interested in giving it a try? You can find the Windows and OSX build here:

* https://nightlies.sqlitebrowser.org/win32-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher-issue1575v2-win32.msi
* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher-issue1575v2-win64.msi
* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite_issue-1575v1.dmg
* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher_issue-1575v1.dmg

**Comment by Bilge** [comment]
I'm still interested but I'm not very good at writing queries that hang the program deliberately. That usually comes about due to incompetence!

**Comment by MKleusberg** [comment]
No worries :smile: Let's just close this issue because we haven't heard about any problems regarding this for a very long time. If you should stumble upon any remaining problems with this, you can always re-open the issue, @Bilge :smile:
