### ISSUE TITLE
[security] Use https for sqlitebrowser.org

### ISSUE THREAD

**Issue by tdelmas** [sqlitebrowser/sqlitebrowser#1276]
### Details for the issue

sqlitebrowser.org doesn't use https

#### I'm opening this issue because:

Any man-in-the-middle could replace downloads links on sqlitebrowser.org with malicious ones

**Comment by justinclift** [comment]
Yep, agreed.  When I looked into this originally (ages ago), there wasn't a good solution as the website is hosted on GitHub pages.  At least at that time, GitHub's "https" certificate pieces didn't work for us, as they couldn't present a cert for "sqlitebrowser.org".

That may have changed since.  We'll need to look into it.

If the GitHub situation hasn't changed, it probably wouldn't be too hard for us to just set up a VM in Rackspace and host it on that.  The traffic load is only about 200k pages month for a static one page website.  A simple Nginx setup should be fine. :smile:

**Comment by justinclift** [comment]
Taking a quick look now, there doesn't seem to be a solution for our situation with GitHub, as we're not using a `.io` domain name.  We'd need to think about setting up a VM for the main page hosting then instead.

* https://github.com/blog/2186-https-for-github-pages
* https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by glawrence** [comment]
It is also worth reading articles like https://scotthelme.co.uk/our-journey-to-a-https-only-world/ as to do HTTPS properly you need HSTS as well

**Comment by justinclift** [comment]
Thanks @glawrence.  It's been a few months since my headspace was in HTTPS stuff, so it won't hurt to read up a bunch before getting this done. :smile:

**Comment by tdelmas** [comment]
Awesome!

After the (week or two?) switch, I strongly encourage you to activate HSTS, to definitively get rid of the MitM risk.

**Comment by justinclift** [comment]
Hmmm, not sure. :smile:

Apparently HSTS is looked badly upon these days as it makes things fragile, and extremely difficult to recover from if something goes wrong.  That being said, I could be misremembering stuff I've read over time. :smile:

**Comment by tdelmas** [comment]
> HSTS is looked badly upon these days as it makes things fragile, and extremely difficult to recover from if something goes wrong

I think you meant HPKP (public key pinning): https://community.letsencrypt.org/t/hpkp-support-tool/61227/5

The only "risk" with HSTS is if you want to roll-back to http, you have to wait the max-age period. (And if you use the includeSubDomains options, you must ensure that all the subdomains, and not only the first level of subdomains works with https)

Of course, if you **preload** HSTS, then it's a more serious commitment, and it's can't be undone.

Details:
https://www.troyhunt.com/understanding-http-strict-transport/
https://www.tunetheweb.com/blog/dangerous-web-security-features/

**Comment by justinclift** [comment]
Ahhh yeah.  That was my misremembering.  Thanks. :smile:

**Comment by justinclift** [comment]
Discovered something interesting today.  GitHub Pages' HTTPS implementation doesn't support IPv6.

Thought I must have missed something, so emailed GitHub support, and they've confirmed it.

Hopefully GitHub adds support for it in the future.  I'm kind of thinking we should disable the http -> https bounce for now, so that people on IPv6 can at least see *something*.

**Comment by AGlezB** [comment]
![20190726-151015-000969 - DB Browser for SQLite](https://user-images.githubusercontent.com/12277525/61975892-5667d780-afb8-11e9-91f4-cf0216c01b06.png)

**Comment by FranklinYu** [comment]
Why don’t we simply use the assets on GitHub? This way we don’t have to maintain our own download server.

**Comment by justinclift** [comment]
Oops.  I forgot to renew the Lets Encrypt certs.  Fixing now... :smile:

**Comment by justinclift** [comment]
We moved our primary downloads off GitHub **specifically** to reduce dependency on them.

Not going to go back.

**Comment by justinclift** [comment]
Certs updated.  At some point I really need to script that so it's not manual.  Or check if there's a Lets Encrypt plugin for Hover - our current DNS provider - these days.  That would also let this be automated. :smile:
