### ISSUE TITLE
Extension Loading on Linux Needs to Strip `.so` From Filename

### ISSUE THREAD

**Issue by MisterRager** [sqlitebrowser/sqlitebrowser#1290]
### Details for the issue

When I select an extension with the dialog, I get this error message:
```
Error loading extension: /home/mistermister/src/someProject/app/build/intermediates/transforms/mergeJniLibs/debug/0/lib/x86_64/libsqlite-fts5.so.so: cannot open shared object file: No such file or directory
```

I think SQLite adds its own `.so` to the path of the extension, so the app needs to drop the file extension before feeding the path into sqlite's c api.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( Ubuntu Artful )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [x] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @MisterRager.  That should be pretty easy to get fixed. :smile:

**Comment by MKleusberg** [comment]
Hmm, the SQLite docs say they are trying the file name as provided first and only attempt adding an extension if the file wasn't found (see [here](https://sqlite.org/c3ref/load_extension.html)). And I can confirm it's working fine for me (I'm using Linux as well). So it's probably not that easy...

@MisterRager The path you have provided has two '.so' endings. Is that intended? If not, could it be that SQLite has added the second '.so' because it couldn't find the original file name? So that would be my first guess: maybe the file isn't there anymore? Also, you seem to be using an older version of DB4S. I don't remember any changes related to extension loading since 3.9.1 but it's also worth trying a newer version - just to be sure :wink:

**Comment by MisterRager** [comment]
I'm selecting a file from the gui that has only one `.so` in its name:
![screenshot from 2018-01-16 16-02-46](https://user-images.githubusercontent.com/595463/35018508-d23e5e6c-fad6-11e7-8e9b-c58540c9916d.png)
![screenshot from 2018-01-16 16-03-03](https://user-images.githubusercontent.com/595463/35018511-d43a0f04-fad6-11e7-9585-2f603315978f.png)
![screenshot from 2018-01-16 16-04-26](https://user-images.githubusercontent.com/595463/35018538-f6c8727c-fad6-11e7-8902-02ae185e21d8.png)

**Comment by MisterRager** [comment]
![screenshot from 2018-01-16 16-07-48](https://user-images.githubusercontent.com/595463/35018644-71efd99a-fad7-11e7-9320-f4bad7880489.png)

**Comment by mgrojo** [comment]
The extra .so is added by SQLite when it cannot open the file. Could you try to load it with the sqlite3 command line tool?

This is a sample execution. The first time it just says that it cannot open the file *.so.so but when the file is provided without .so, it reports the real problem.
```

sqlite> .load ./libsqlitefunctions.so
Error: ./libsqlitefunctions.so.so: cannot open shared object file: No such file or directory
sqlite> .load ./libsqlitefunctions
Error: ./libsqlitefunctions.so: undefined symbol: sinh
sqlite> 

```

**Comment by MKleusberg** [comment]
Hmm, maybe it's also worth checking if you are allowed to read the file, maybe also to execute it.

**Comment by justinclift** [comment]
@MisterRager Ping? :smile:

**Comment by mgrojo** [comment]
I can reproduce the misleading error if I try to load a shared library that is not actually an extension.  

![imagen](https://user-images.githubusercontent.com/13812910/36275754-fd0080d6-128b-11e8-8e3b-9fd7caa0d9d0.png)

The error in Spanish meaning "cannot open shared object file: No such file or directory", that is, the same error as with sqlite3. This seems a bug in SQLite: all the errors loading shared libraries are masked with the no-such-file error because they are trying a second time adding `.so`.

We could work around it, by striping the .so before passing it to SQLite.

**Comment by justinclift** [comment]
> We could work around it, by striping the .so before passing it to SQLite.

If we do that, won't SQLite still pass us the same error message but just with an now-correct filename?

Hmmm, maybe we should ask on the sqlite-users mailing list if there's a way to get more accurate error codes/info from SQLite about this?  @chrisjlocke is on that mailing list already, so it's probably pretty easy for us to ask. :smile:

**Comment by MisterRager** [comment]
You can use the 3rd parameter to `sqlite3_load_extension` like I did [here](
https://github.com/requery/sqlite-android/pull/53/files) to get a more
verbose error message. My problem is probably wrong abi or something along
those lines. Thanks for the help. I'll see if I can take a look at the
extension loading code here.

**Comment by mgrojo** [comment]
I've stripped the extension and now it returns the correct error message:

![imagen](https://user-images.githubusercontent.com/13812910/36277253-aa0498d6-1290-11e8-8efe-83fd56cef61b.png)

> If we do that, won't SQLite still pass us the same error message but just with an now-correct filename?

It seems that they try with filename as is, it raises an error for whatever reason, then they try adding the extension, that fails again (because library.so.so does not exist) and they return this last error, while the meaningful one is the first one. They should check that the first error was actually no-such-file.

> Hmmm, maybe we should ask on the sqlite-users mailing list if there's a way to get more accurate error codes/info from SQLite about this? @chrisjlocke is on that mailing list already, so it's probably pretty easy for us to ask. 😄

Yes, it's better asking first before adding this workaround in the code. Maybe there are better ways or at least they should be aware of this problem (maybe it's already solved; I'm using SQLCipher Version 3.8.6).

**Comment by MisterRager** [comment]
Actually, it looks like the thing to do would be to just load the right
filename only by seeing which filename us a real file first.

**Comment by mgrojo** [comment]
> You can use the 3rd parameter to `sqlite3_load_extension` like I did [here]( 

That is what are already doing to get the error message:
```c++

    char* error;
    if(sqlite3_load_extension(_db, extensionName.toUtf8(), nullptr, &error) == SQLITE_OK)
    {
        return true;
    } else {
        lastErrorMessage = QString::fromUtf8(error);
        sqlite3_free(error);
        return false;
    }

```

**Comment by MisterRager** [comment]
Yeah - saw that. Also not seeing where the alternative filename is tried.
There's only one call for load:
https://github.com/sqlitebrowser/sqlitebrowser/blob/1110b87d95108f3f01430f7e05aec4c9e7ebc628/src/MainWindow.cpp#L1888

**Comment by mgrojo** [comment]
Yes, there is only one call for load in our code. It's SQLite's sqlite3_load_extension the one trying with an alternate filename as documented here: https://sqlite.org/c3ref/load_extension.html

This is what I've done in my copy for getting the correct error message:

```diff
diff --git a/src/sqlitedb.cpp b/src/sqlitedb.cpp
index 30d6d88..d109604 100644
--- a/src/sqlitedb.cpp
+++ b/src/sqlitedb.cpp
@@ -1566,6 +1566,8 @@ bool DBBrowserDB::setPragma(const QString& pragma, int value, int& originalvalue
 
 bool DBBrowserDB::loadExtension(const QString& filename)
 {
+    QString extensionName = filename;
+    
     if(!isOpen())
         return false;
 
@@ -1576,9 +1578,14 @@ bool DBBrowserDB::loadExtension(const QString& filename)
         return false;
     }
 
+    if (extensionName.endsWith(".so"))
+        extensionName.chop(3);
+    else if (extensionName.endsWith(".dll"))
+        extensionName.chop(4);
+    
     // Try to load extension
     char* error;
-    if(sqlite3_load_extension(_db, filename.toUtf8(), nullptr, &error) == SQLITE_OK)
+    if(sqlite3_load_extension(_db, extensionName.toUtf8(), nullptr, &error) == SQLITE_OK)
     {
         return true;
     } else {

```

**Comment by MKleusberg** [comment]
Closing this because it looks like there isn't much more we can do about this and we haven't heard back anything for a long time. If there's any remaining problem with this, please just re-open this issue any time :smile:
