### ISSUE TITLE
SQLite3 Problem

### ISSUE THREAD

**Issue by AlanPeter1** [sqlitebrowser/sqlitebrowser#1316]
### Details for the issue

 I am getting three entries after clicking a submission button in a PyQt5 Designer window.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x ] DB4S has another problem

#### I'm using DB4S on:

- [x ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x
[problem.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/1714915/problem.zip)

 ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh, it sounds like you're having a problem with SQLite (the library) rather than with this project (a GUI for SQLite).

If that's the case, the best place to seek help is the SQLite users mailing list:

&nbsp; &nbsp; https://sqlite.org/support.html

It's free, and there are lots of knowledgable + helpful people on that mailing list. :smile:

**Comment by justinclift** [comment]
Closing this, as it doesn't seem like an issue with DB4S. :smile:
