### ISSUE TITLE
Can not import more then 20 records in CSV format

### ISSUE THREAD

**Issue by aviarad3** [sqlitebrowser/sqlitebrowser#1337]
Hi 
the export if fine
but when tring to import 60,000 lines in CSV format I get at table of 20 records only.
please help

**Comment by chrisjlocke** [comment]
Which operating system are you using?
Which version of DB4S?  Have you tried the nightly version?
Is the data private?  If you could post links to the CSV files, we could try importing and would be easier to determine where the problem lies.

**Comment by aviarad3** [comment]
attached csv file


[item_screenlist_adapt.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/1789400/item_screenlist_adapt.zip)

**Comment by aviarad3** [comment]
I am trying to add rows to an existing table
the import is working with file with 5-10 lines

**Comment by chrisjlocke** [comment]
> I do not know what is DB4S

DB4S is DB Browser for SQLite ... ie, the program you're using.  Its just the 'shorthand' version of its name (as its a mouthful!)

The CSV file you supplied contains only 3 lines.

![image](https://user-images.githubusercontent.com/7872218/37098986-2eb01796-2217-11e8-912a-da2fde200194.png)

Can you supply the file with 60,000 lines?  A .zip file would be preferable.

**Comment by aviarad3** [comment]
DB4S  the latest one (dowloaded it today) Ver 3.10.99 (Mar 7 2018)
Qt 5.7.1
SQL Ver 3.22.0 nightly

**Comment by aviarad3** [comment]
[sqlscreenlists_adapt.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/1789561/sqlscreenlists_adapt.zip)

**Comment by aviarad3** [comment]
DB4S the latest one (dowloaded it today) Ver 3.10.99 (Mar 7 2018) 
 64 bit ver

**Comment by chrisjlocke** [comment]
I've just imported it here with no issues.  29,763 rows.  This tallies with the CSV.

![image](https://user-images.githubusercontent.com/7872218/37099681-e20eaad6-2218-11e8-8ffb-c67aa4cbd7da.png)

![image](https://user-images.githubusercontent.com/7872218/37099730-fec7061e-2218-11e8-8868-435f2000783a.png)

(one row difference due to the header)

My import settings were set to this:

![image](https://user-images.githubusercontent.com/7872218/37099776-23fbec38-2219-11e8-99df-93e1ebfa6209.png)

Can you confirm your settings?

**Comment by chrisjlocke** [comment]
For the avoidance of doubt, I created a new database (no tables), clicked 'Cancel' on the 'Create Table' dialog, clicked 'File' and 'Import' then 'Table from CSV'.

**Comment by aviarad3** [comment]
I am trying to add info to an existing DB
I do not want to make any steps that i do not need for not compromising the DB health
Me knolege is minimal

**Comment by aviarad3** [comment]
Can you confirm your settings? Yes

**Comment by chrisjlocke** [comment]
OK, can you email me your database?  
![image](https://user-images.githubusercontent.com/7872218/37102746-68ebd7d4-2220-11e8-9552-3061e3ce8a4c.png)

What I was explaining, was importing the CSV has no issues - it seems to work perfectly.  I'm not sure why you are only getting 20 rows, but it seems OK here.
Can you confirm, when you complete the import and view the table, if you click the 'Refresh' button (or press F5) you all the records are displayed?

> Can you confirm your settings? Yes

Sorry, I meant can you post a screenshot of the import settings you're using.  If they are identical to the ones I posted, then obviously thats fine.

**Comment by aviarad3** [comment]
identical

**Comment by chrisjlocke** [comment]
Excellent, thanks.

**Comment by MKleusberg** [comment]
This might be a silly question but just to make sure we are talking about the same thing here: do you mean you only get 20 rows imported in your table, as in there are only 20 rows visible in the Browse Data tab; or are you only seeing 20 rows in the Import CSV file dialog (the one with all the settings for the import)? Because the latter is only a preview and is meant to display only 20 rows for performance reasons. But the rest of the file is imported as well when clicking the OK button.

**Comment by chrisjlocke** [comment]
I'm guessing (note that its only a guess!) but the import is being completed.

> press on import and i get the progress bar message that the import successful and nothing is added to the table.

**Comment by MKleusberg** [comment]
Ah, didn't see that. But 20 rows just sounds suspiciously like the preview size :smile:

**Comment by aviarad3** [comment]
Hi
I ended up with adding 60000 rows and using copy and paste 
Thanks for the help

**Comment by chrisjlocke** [comment]
OK, I'll close this, but if the import fails again, please reopen it.
