### ISSUE TITLE
[exe] Nightly builds version info missing?

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1346]
### Details for the issue
I rely on the nightly builds for bug fixes and features.
For my solutions, I scan user installs of required exe's/dll's/etc. to verify they have minimum versions.
Unfortunately, the nightly DB4S exe has no such info. So, I have to fall back to a file size + date mod combo which is non-standard.
Please modify the nightly build process to populate the Product Version and File Version string fields.
Ex. 3.10.99.xxx, xxx=day of year. 3.10.99.70 if created today.
### Useful extra information
The nightly build exe does have an internal version when selecting Help-About.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ 10 Pro )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: ___3.10.99

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Good point @sky5walk.  You're not the first person to mention the info fields could do with filling out, but I'm just not sure how to make it happen.

If it helps, this is the Windows batch file we use to create the Windows nightlies:

&nbsp; &nbsp; https://gist.github.com/justinclift/11cc926f214e882c8162f97c53929c07

If you have some idea of what needs changing in it, that'd go a long way to getting it done. :smile:

**Comment by sky5walk** [comment]
Yeah, I only know the Windows way with resource files. You have to include an updated resource file in your build.
There are codes to modify the resource block after creation, but that creates a new SHA or MD5 signature, so I would avoid that approach.
The interwebs are full of resource.rc examples.

**Comment by mgrojo** [comment]
Using qmake it seems we could take this approach: https://stackoverflow.com/a/11971210/1092849

I tried to test it, although I'm in Linux, but I cannot make qmake to use qt5 version and consequently I cannot get it to compile.

**Comment by justinclift** [comment]
Interesting.  Setting environment variables should be pretty easy. :smile:

Good find @mgrojo. :smile:

**Comment by karim** [comment]
@sky5walk Sorry for the delay to get this done.

There is a PR about adding the *day of the year* to the nightly build. However, in our discussion and as pointed out by @chrisjlocke it is not practical.

The problem seems to be around, what is going to happen on January 1? A one day earlier build will be `v3.10.99.365` and the next (and more recent build) will be `3.10.99.1`, and this will not work in your case.

Adding a *build number* based on *something* is useful like @justinclift said earlier. But it seems not as easy to implement.

There are some proposed solutions here. Like getting the number of days since *some other date*, say January 1, 2000, and that would be 6714. Or maybe use the current year. This will guarantee we will not have the problem mentioned above and will keep the number of digits to a minimum. You still need to do your own calculations to get the date of the build though.

We can also add the year to the number of days in that year in the format `YYDDD`. So first day in this year will be 18001 and last day will be 18365. This will make finding the date of the build easier than the one above but with longer digits.

Just for the sake of completeness, we can use `YYMMDD`, so today's  build will be 180519. This is the easiest one to get the date of the build from but also the longest. Maybe we can split that number on two? Like 3.10.18.0519 or 3.10.180.519.

Everyone please tell us what do you think. Your feedback is welcome. :smiley:

**Comment by justinclift** [comment]
My preference would be YYMMDD, if 6 digits is acceptable. :smile:

**Comment by sky5walk** [comment]
Yes, I prefer 3.10.YYMMDD.
Why not use the same [semantic version approach](https://semver.org/) as [SQLite](https://www.sqlite.org/versionnumbers.html)?

**Comment by karim** [comment]
It will not be a problem if it is a string. However, [VERSIONINFO](https://msdn.microsoft.com/en-us/library/windows/desktop/aa381058(v=vs.85).aspx) resource in Windows keeps the file/product version as **both** a number **and** a string.

The string part can be anything like `"1.0 Beta 1 Update 2"`, so it will not be a problem to make it `"3.10.99.20180518"`.

But for the number part, a version like `a.b.c.d` where each one is a 16-bit will not be able to store the date in the last part as YYMMDD. The last part (`d` in this example) cannot be greater than 65535.

**Comment by karim** [comment]
@sky5walk I believe semantic versioning applies more to libraries than applications. A library need to tell its user (an application) if it still support a certain API or not by its version. For an application, that doesn't usually mean anything.

This is not what we are debating however. We want to include a build version, a number that will change daily, and a date seems to be the best option. We just don't know how to represent that date in the best possible way.

**Comment by karim** [comment]
We could do *Major.Minor.YEAR.MMDD*, so stable be will 3.10.1 and nightly will be 3.10.18.0519 or 3.10.2018.0519. We will replace *99* in nightly with the year.

**Comment by sky5walk** [comment]
While I disagree on treating lib vs exe versioning differently, I go back to my original post.
I must programatically query all dll's and exe's for specific supported versions.
"3.10.99.xxx" is problematic.
"3.10.18.0519" is fine.

**Comment by chrisjlocke** [comment]
> 3.10.2018.0519. We will replace 99 in nightly with the year.

You've got the same problem.  A nightly on 31 Dec will be 3.10.99.1231.  The next day this will be 3.10.99.0101.  

> and will keep the number of digits to a minimum.

Sorry - my bad terminology.  What I meant was, we only have four values to work with - major, minor, build, revision.

Its annoying the version is limited to 16bit.

In Linux world, an odd version is unstable, with even versions stable, so we could have 3.10.2018.0210 which shows 3.10 was released in Feb, then if we have to release '3.10.1' in March, this would be 3.12.2018.0305 (the nightly would be 3.11.2018.0306, etc.)

**Comment by karim** [comment]
@sky5walk 

> I must programatically query all dll's and exe's for specific supported versions.

Would you mind telling us which version of the .exe do you want to get? As I mentioned in my earlier post, Windows keep the version number as a number (4x 16-bit values) and a string. If the string you are after we can do the whole *"Major.Minor.Patch.YYYYMMDD"*.

**Comment by karim** [comment]
> A nightly on 31 Dec will be 3.10.99.1231. The next day this will be 3.10.99.0101.

I meant something like.. 3.10.18.1231 then next day 3.10.19.0101. The last 2 parts will be used as the date, since only 1 part is not enough to squeeze the whole date in it.

**Comment by chrisjlocke** [comment]
Yes, sorry - I initially read your comment wrong.

**Comment by sky5walk** [comment]
I query the Product Version and File Version using windows api GetFileVersionInfo().
If that fails, I read the resource block directly and parse the version fields within struct VS_VERSIONINFO.

**Comment by karim** [comment]
Ah ok. You are also checking the string part. So I guess adding the build version as a string will not be a problem.

**Comment by karim** [comment]
I will try to make a list of what we thought about so far, and I will edit it to make a complete list.

|  #   |           Format           |     Example      |                 Notes                 |
| :--: | :------------------------: | :--------------: | :-----------------------------------: |
|  1   |   Major.Minor.Patch.DDD    |   3.10.99.139    |     DDD is the day of *any* year!     |
|  2   |  Major.Minor.Patch.YYMMDD  |  3.10.99.180519  |          Not a 16-bit value           |
|  3   | Major.Minor.Patch.YYYYMMDD | 3.10.99.20180519 |             Same as above             |
|  4   |  Major.Minor.Patch.YYDDD   |  3.10.99.18139   | DDD is the day of the current year YY |
|  5   |    Major.Minor.YY.MMDD     |   3.10.18.0519   |  Two parts for the date not just one  |
|  6   |   Major.Minor.YYYY.MMDD    |  3.10.2018.0519  |             Same as above             |

**Note:** These are for the *fixed* 16-bit parts of the file version information. For the string part we can use anything.

**Comment by justinclift** [comment]
Well, I like the format of 3, but for a string value.  For the 16 bit numeric version, then 7 sounds like it'll work and be most stable.

**Comment by karim** [comment]
I updated the PR and changed the build version *string* to be like 3 (YYYYMMDD). Should we remove the other date between parentheses too, since both provide the same information now?

![version1](https://user-images.githubusercontent.com/8761081/40274777-ef785784-5bdf-11e8-8f26-9ae7f67f8a7a.jpg)

**FileVersion** string now shows the build date (marked green). I didn't change the fixed 16-bit numeric version (marked red) though. This can be done later or not at all.

![version2](https://user-images.githubusercontent.com/8761081/40274788-1f3933a8-5be0-11e8-8592-6edf89f31083.jpg)

**Comment by sky5walk** [comment]
Cool, do you mind assigning the Product Version also?
That is my primary sort item. I rarely see these not being identical.
Thanks!

**Comment by karim** [comment]
> do you mind assigning the Product Version also?

Sure, the PR is still open and I can add it, but I don't know if I should though. :smiley:

I will wait to see what the other team members are feeling about it and if it's okay to change that too. Also, if I should remove the other date from About dialog.

> I rarely see these not being identical.

You are right. However, some might argue that the *product version* hasn't changed (only the file) and therefore doesn't need a new version.

**Comment by chrisjlocke** [comment]
> some might argue that the product version hasn't changed (only the file) and therefore doesn't need a new version.

The new file is based on a new build, and thusly a new product version ... ;)

**Comment by justinclift** [comment]
Looking at the ResEdit screenshot:

* **General Information** → **File Version** can probably be left as-is.  Some people might already be using it programmatically, so we might as well leave that alone.
* **General Information** → **Product Version** seems like it should be changed.  @sky5walk uses that.  @sky5walk What's your preference for this field? :smile:
* **File Information** → **FileVersion** (with the new string) looks good to me.

Looking at the About dialog.  I kind of like the long form date in brackets more than the YYYYMMDD patch version on that line.  Could we keep the visual display for the About dialog like it has been so far? :smile:

**Comment by MKleusberg** [comment]
I think we can make the file and the product version the same value. Especially for the nightlies 1) it makes sort of sense because there is no real product there and 2) it doesn't really matter anyway :wink:

I would leave the full date in the About dialog, too. One reason is, as @justinclift pointed out, that it's easier to read and maybe more transparent for some users. The other reason is that the new file version approach is only implemented for cmake (which is fine because a long time ago we decided to make the qmake build as simple as possible in order to avoid maintaining two full build scripts), so the file version and the build date are only redundant if you compile with cmake, but not with qmake.

**Comment by karim** [comment]
@chrisjlocke 
> The new file is based on a new build, and thusly a new product version ... ;)

True. :smiley: 

@justinclift 
> General Information → Product Version seems like it should be changed.

Everything under **General Information** is in the *fixed* part of the file information. Both file and product versions are 4x 16-bit fields, hence the comma between each part. We can either leave them as they are now or pick one from the table above (4 to 7).

This might be confusing though, because...

![product](https://user-images.githubusercontent.com/8761081/40278421-0ba3640c-5c31-11e8-858b-905cce776238.jpg)

Windows shows the file version from the fixed part (marked red) but the product version from the string part (marked green).

That was probably the main reason I didn't change product version string, and I changed the file version string (not shown in the screenshot above) only.

@MKleusberg 
> 2) it doesn't really matter anyway

I think that is the best argument. It really doesn't matter. :smiley:

> I would leave the full date in the About dialog, too.

Okay. I should also remove the YYYYMMDD from the About dialog too.

**Comment by justinclift** [comment]
Ahhh.  In that case I'll defer to your judgement.  I don't use/care Windows often enough to really want to have to grok the fine details. 😉

**Comment by karim** [comment]
Okay, I reverted the changes for About dialog.

![about](https://user-images.githubusercontent.com/8761081/40279000-9fcf9f92-5c3b-11e8-98ae-fc21546f091f.jpg)

Now **FileVersion** and **ProductVersion** are the same.

![resedit](https://user-images.githubusercontent.com/8761081/40279007-b16a788a-5c3b-11e8-8b7e-64b81eed1363.jpg)

**Comment by MKleusberg** [comment]
Looks good :+1:

**Comment by revolter** [comment]
Couldn't we use the number of commits as the build number? It's 100% unique and "automatically" changes for new releases:

```sh
git rev-list --count HEAD
```

From https://stackoverflow.com/a/4061706/865175.

**Comment by chrisjlocke** [comment]
> Couldn't we use the number of commits as the build number?

Some of the libraries on the build box are automatically updated, so if SQLite gets updated to a new version, the .exe will get changed, despite their being no commits.  This could mean v3.10.1.87 (87 commits in) and 3.10.1.87 built the next day could be radically different (different libraries and SQL versions) but the same version number.

Not saying you're wrong, but just highlighting a possible 'gotcha'.

**Comment by justinclift** [comment]
Good concept @revolter.  @chrisjlocke thought about the libraries present on the build box though do sound like they'd potentially create weird edge cases for us though. :smile:

@sky5walk Would you be ok to take a look at last night's nightly build, and see if the version info now included is workable for you?

**Comment by sky5walk** [comment]
Works great. :)
To summarize, I do not mind which method is used to update the Product/File Versions, as long as they are identical.
Thanks for closing this out.

**Comment by justinclift** [comment]
Awesome.  Well done guys. :smile:
