### ISSUE TITLE
How can I reset the toolbar? (Mac)

### ISSUE THREAD

**Issue by darrengoulden-pex** [sqlitebrowser/sqlitebrowser#1366]
I've somehow moved the toolbar off screen and I'm unable to pull it back using the traditional methods!  How can I reset this?

I've tried reinstalling and running the following `find ~/Library/Preferences -name '*sqlitebrowser*' -delete`

<img width="348" alt="screenshot at apr 17 17-50-07" src="https://user-images.githubusercontent.com/35221979/38884563-e7a49bb2-4267-11e8-9e65-fe0d71f923c9.png">

**Comment by justinclift** [comment]
In theory, if you double click on it... it **should** snap back to it's original spot.

I'm not in front of an OSX desktop atm though, so that's from memory.  It might need the double click to be on some specific part of the toolbar too.  I don't remember clearly, off hand.

Hopefully that's enough to point you in the right direction. :smile:

**Comment by darrengoulden-pex** [comment]
Double clicking on it doesn't seem to do anything :(

**Comment by justinclift** [comment]
Damn.  Hopefully someone else with OSX is around to help, as I probably won't be near an OSX box until sometime tomorrow. :frowning_face:

**Comment by darrengoulden-pex** [comment]
Are the toolbar/window settings saved elsewhere on the filesystem?

**Comment by justinclift** [comment]
Good thinking. :smile:

I'm on an OSX desktop today, so able to investigate things a bit better. :smile:

The preferences file on my El Capitan desktop is in:

```
~/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist
```

Just tested things by opening up DB4S, removing all of the toolbars (similar to you), closing DB4S... and then deleting the above preferences file.

That worked the **first** time.  When starting DB4S again, the toolbars were all back in their default positions.  So that's good.

Weirdly, after moving the toolbars around again and existing DB4S, nuking that preferences file isn't resetting things to their default.  I'm not sure what that's from, but it kind of seems like OSX is caching things in some layer. 😦 

Er... does that help at all?

Oh, as a data point. With my desktop here when I drag the toolbar handles back over the main DB4S window (then hover them for a bit) it does let them snap back into place.  So it does sound like something acting a bit weird on your system rather than a bug for everyone.  Well, that's what it looks like so far. :wink:

**Comment by darrengoulden-pex** [comment]
I removed `~/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist` again and this didn't fix it, so I did this https://support.apple.com/en-us/ht204063 and now my toolbar has reset, happy days

<img width="571" alt="screenshot at apr 18 17-06-33" src="https://user-images.githubusercontent.com/35221979/38944104-ec12fcca-432a-11e8-9a1a-4cb8090b389f.png">

**Comment by justinclift** [comment]
Wow.  Having to reset the NVRAM sounds like overkill.  But glad it worked. :smile:
