### ISSUE TITLE
CRASHING OF DB4S 3.10.1 FOR 64 BIT WINDOWS 10

### ISSUE THREAD

**Issue by Nityat24** [sqlitebrowser/sqlitebrowser#1383]
Hi, I just installed DB4S version 3.10.1 for windows 10. It keeps crashing when i open or create a new database. I have tried the nightly version as well as the older version but it shows the same. please resolve this issue.

**Comment by chrisjlocke** [comment]
Is it as soon as you click the 'Open' or 'New' buttons, or literally as soon as DB4S opens?
There are two known points where it crashes - one of them has a fix, and the other doesn't!

If its the latter, then ideally, you'd be great to help us pinpoint the error.  Unfortunately, there aren't many members on the team around to actually put code into the project, so if the error is identified, it may not get immediately rectified... but its a step in the right direction...

**Comment by sky5walk** [comment]
Need more specifics?
I am running DB4S nightly v180502 on Windows 10 Pro without crashes.
Yes, there are hangs with long running queries to nowhere, but bounded queries and the like are working.

**Comment by justinclift** [comment]
From rough memory, as best we can tell it's due to the Windows system in question loading wrong dll's.  eg loading some 32-bit ones instead of the expected 64-bit versions, or perhaps loading different versions than what we used when compiling.

Pretty sure @chrisjlocke wrote up a bunch of instructions on how to investigate it deeper.  I have no idea which issue (or wiki page?) that's in though.

Looking at the wiki quickly, there is a page on grabbing Windows debug info when crashes happen:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Debugging-a-crash-on-Windows

So, that might be useful. :smile:

@Nityat24 If you've been trying the 64-bit version of DB4S, uninstall it and try using the 32-bit version instead.  That sometimes works for this crashing situation. :smile:

**Comment by sky5walk** [comment]
I tried all buttons with x64 nightly DB4S on Windows 10 Pro.
No crashes.
That's why I asked for specifics to reproduce.

**Comment by justinclift** [comment]
Closing this due to lack of response.

@Nityat24 If you still need help with this, you're welcome to reopen this issue. :smile:
