### ISSUE TITLE
Wrong SQL-file when exporting from a database

### ISSUE THREAD

**Issue by valbv** [sqlitebrowser/sqlitebrowser#1385]
Details for the issue
--------------------

#### What did you do?

1) Create dataBase.
2) Copy SQL-script and perform it [testSqlScript.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/1991230/testSqlScript.txt).
3) Save dataBase.
4) Export->dataBase to SQL-file (the selected options are not important). For example, named _1.sql_
5) Close curent dataBase.
6) Create new dataBase.
7) Import->dataBase from SQL-file _1.sql_. or copy content _1.sql_ to SQL-field and perform

#### What did you expect to see?
Error, because wrong order of creation and inserts
![2](https://user-images.githubusercontent.com/14193135/39869083-64d2cbd8-5486-11e8-88db-88f6d710dfe5.png)

#### What did you see instead?
Same database as in "Step 3"

Useful extra information
-------------------------

#### What operating system are you using?
- [x] Windows: ( version: 10 )

#### What is your DB4S version?
- [x] 3.10.1

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
Yes, because the first CREATE statement requires a reference to Scenarios to create the foreign key relationship.  This would be quite hard for DB4S to deduce and produce the SQL script in the right order.  Its done it alphabetically, rather than schematically.

The workaround is to move the "CREATE TABLE IF NOT EXISTS `Scenario` ..." to the first 'block' (if that makes sense) so that table is created first.

This actually occurs again with 'event' and 'param' - so the final SQL should ideally be:

    CREATE TABLE IF NOT EXISTS `Param` (
	`id`	integer PRIMARY KEY AUTOINCREMENT,
	`name`	text NOT NULL UNIQUE,
	`valueType`	text NOT NULL
    );
    INSERT INTO `Param` VALUES (1,'GPU_MODEL','text'),
     (2,'MEMORY_PHYSICAL_GB','numeric'),
     (3,'MEMORY_VIRTUAL_GB','numeric'),
     (4,'CUDA_AVAILABLE','text'),
     (5,'CUDA_ENABLED','text');
 
    CREATE TABLE IF NOT EXISTS `Scenario` (
	`id`	integer PRIMARY KEY AUTOINCREMENT,
	`name`	text NOT NULL UNIQUE
    );
    INSERT INTO `Scenario` VALUES (1,'Scenario1'),
     (2,'Scenario2');

     CREATE TABLE IF NOT EXISTS `Event` (
	`id`	integer PRIMARY KEY AUTOINCREMENT,
	`name`	text NOT NULL UNIQUE
    );

    INSERT INTO `Event` VALUES (1,'APP_EVERY_START'),
     (2,'APP_FAILED'),
     (3,'ACTIVATE_PRODUCT');
 
    CREATE TABLE IF NOT EXISTS `LinkScenarioEvent` (
	`scenarioId`	integer,
	`eventId`	integer,
	FOREIGN KEY(`eventId`) REFERENCES `Event`(`id`) on delete cascade,
	PRIMARY KEY(`scenarioId`,`eventId`),
	FOREIGN KEY(`scenarioId`) REFERENCES `Scenario`(`id`) on delete cascade
    );

    INSERT INTO `LinkScenarioEvent` VALUES (1,1),
     (1,2),
     (2,3);




    CREATE TABLE IF NOT EXISTS `LinkEventParam` (
	`eventId`	integer,
	`paramId`	integer,
	PRIMARY KEY(`eventId`,`paramId`),
	FOREIGN KEY(`paramId`) REFERENCES `Param`(`id`) on delete cascade,
	FOREIGN KEY(`eventId`) REFERENCES `Event`(`id`) on delete cascade
    );
    INSERT INTO `LinkEventParam` VALUES (1,1),
     (1,2),
     (1,3),
     (1,4),
     (1,5),
     (2,1),
     (2,2),
     (2,3),
     (3,1);


But yes, an interesting 'gotcha' - when the SQL commands rely on an existing table to exist, that table needs creating first!
I don't know if SQLite can be told to 'ignore errors' to make the ordering unimportant...
But the easiest workaround is to manually tweak the SQL...

**Comment by MKleusberg** [comment]
Sorting the SQL statements would be extremely difficult or maybe even impossible because there might be circular references etc. So that's not a realistic option.

Ignoring the errors is possible. There are two ways to do this: disable foreign keys or deferring foreign keys.

Disabling foreign keys doesn't work for us because it requires us to commit all changes before **and** after the import. Both is undesirable because it would mean the user's database is overwritten but SQLite just doesn't allow disabling foreign keys or re-enabling them inside a transaction.

Deferring foreign keys means we can keep foreign keys enabled; it's also possible to set the defer flag inside a transaction. So that's good. However, it's only possible to unset the defer flag by committing the transaction. This in turn means we're left with two options: write all changes automatically after each import which as noted before is undesirable, or just let the defer foreign keys flag stay enabled which is undesirable as well because it effectively disables foreign keys until clicking the Write button which is unexpected.

So in short, I don't think we can do much here :frowning: The only case in which we are able to guarantee that an exported file can be imported as-is is when importing it via the menu item when no database is opened because then we can just write changes to the file as we wish.

That said, with tomorrow's nightly build the sorting of the exported file looks like this:
```
- Table 1 schema
- Table 2 schema
- Table 3 schema
- Table 1 data
- Table 2 data
- Table 3 data
```
Instead of this:
```
- Table 1 schema
- Table 1 data
- Table 2 schema
- Table 2 data
- Table 3 schema
- Table 3 data
```
This at least allows you to import the file the way you have tried it after setting the defer flag manually. Here's how:
- Wait till tomorrow :wink;
- Download and install the nightly 
- Export the database again
- Open a database file
- Go to the Execute SQL tab and run this statement ```PRAGMA defer_foreign_keys=on;```
- Now import the file

**Comment by mgrojo** [comment]
@valbv After a change by @MKleusberg (406734a2c9e21407009b5d78008a95ae040176fc) you don't even have to execute the PRAGMA defer_foreign_keys it is done automatically. I you download a current nightly you can follow your original steps without any error. Can you confirm it so we can close this issue?

**Comment by valbv** [comment]
Yes, all right. You can close this issue.

**Comment by mgrojo** [comment]
Great! Thanks for reporting.
