### ISSUE TITLE
Cant modify table if trigger/FK exists

### ISSUE THREAD

**Issue by mglatz** [sqlitebrowser/sqlitebrowser#1398]
Table that has triggers cannot be modified (add/remove/move columns) if there is a trigger on it (possibly just under special circumstances). I have seen these errors on tables that have insert and update triggers and have not really tested alternations.

I think this could be fixed by removing all table triggers and disabling foreign keys pragma before table modification and then recreating those triggers and enabling FK (if enabled before)

I am not sure what version I am on, I believe it is one of nightly builds after lastest final version, but not the latest nightly. Version is specified below.

screenshot of error:

![image](https://user-images.githubusercontent.com/406299/40720333-4a7edf46-640e-11e8-8b17-2dbe890b4cb4.png)

Details for the issue
--------------------

#### What did you do?
modify table columns on a table that has insert and update trigger

#### What did you expect to see?
success

#### What did you see instead?
error

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: 3.10.99

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks @mglatz. :smile:

Would you be ok to include the error message text, or maybe screenshot it or similar?

That's just in case the error you're getting is somehow different from what we get when this is investigated. :smile:

For the nightly version info, it should be in the **Help** → **About**.  That'll generally say something like "Version 3.10.99" and give a build date.  The build date bit will help us know how far back the nightly is from. :smile:

**Comment by mglatz** [comment]
Hi, I added screenshot to original post. My version is 3.10.99 as mentioned in description but info page shows no build date or any other relavant information

**Comment by mglatz** [comment]
after some more testing it seems that only FK causes the issue, Now I've been able to add and move columns with triggers in place. I'd swear it did not worked for me before, but can't reproduce it currently. FK=On however throws the mentioned error

**Comment by justinclift** [comment]
> Hi, I added screenshot to original post.

Thanks.  I just moved it into the OP itself to make things a bit tidier.  With the build date not being present... yeah.  We added it to the nightlies a while back.  Not having it there just means it was before it was added.  No worries. :smile:

With the testing you're doing, I *think* other people have mentioned trigger problems before.  Just went looking through the issues and only found this #1145.  Which is weird, as I could have sworn there was more indepth stuff in there.  Either way, this does need looking at. :smile:

**Comment by mgrojo** [comment]
@mglatz Do you still have the DB schema? Just this table and any other table having references to it would be enough. I'm trying to analyse if the PR #1496 would also solve this issue.

**Comment by mgrojo** [comment]
Thanks, @mglatz. Don't worry about the names, it's the relations what really matters, not the semantic. Just for discarding, could you execute these pragmas in your database for checking if the current data is already fulfilling the foreign key constraints?:

```sql
pragma foreign_key_check; -- Should return nothing
pragma integrity_check; -- Should return 'ok'

```

**Comment by mglatz** [comment]
integrity is OK. FK check returns 58 rows, (I don't have  FKs pragma enabled in my app)

**Comment by mgrojo** [comment]
Then I guess that's the problem and we can't do any better. The table that you try to modify has foreign-key problems and given that we work with the Foreign Key pragma enabled, we are affected by those checks in our modification. The workaround is to fix the foreign key problems or, as you've already noted, disable FK also in DB4S (you can do that in the Preferences, so it is saved if you want that; or in Edit Pragmas if you only want a change for the session).

Nevertheless, could you check with tomorrow's nightly build, since we have improved the modification of tables with foreign keys for #1481? Maybe the message changes and you won't be able still to change the table, but you could give it a try.

**Comment by mglatz** [comment]
hence, I think a solution wold be to disable FK's before running alter table scripts and then reenabling them if they were on

**Comment by mglatz** [comment]
but you are right, If I delete all from Table I want to modify the error no longer occurs

**Comment by mgrojo** [comment]
> hence, I think a solution would be to disable FK's before running alter table scripts and then reenabling them if they were on

Do you say to do that manually as a user or that the application should do that? After the last change we are doing that, but we run a foreign_key_check before committing the table modification. Consequently if the original data has foreign key problems, we will disregard the change. The application needs that the data has referential integrity if the foreign key mode is enabled. Otherwise, leave it disabled and there won't be any problem.

Can this issue be closed or is there something that the application is still doing incorrectly (after the solution for #1481)?

**Comment by mglatz** [comment]
I think the app should do it automatically. I believe it could be done even with fk problems as I can't think of a scenario, where alter table could make previous FK issues even worse. But I'm not database expert so I leave that up to you. Anyway, thank you very much for your help :)
