### ISSUE TITLE
No Access to SQL-Statement of View

### ISSUE THREAD

**Issue by MarcoTroester** [sqlitebrowser/sqlitebrowser#140]
Hi,

I've been using your SQLite Browser software for about some months and just updated to your new program version. Generally I enjoy your software a lot, but recently I've been a bit disappointed about editing options for views:

Your new program version shows the CREATE VIEW SQL on "Database Structure" tab, but doesn't allow to copy or edit it like in your previous versions. I just wanted to copy the SQL I've recently used for creating a view to my clipboard or something like that.

I would suggest you to implement a context menu option "CREATE TO" (similar to SQL Server) that creates a SQL file with CREATE VIEW SQL. Alternatively you could add options "Copy CREATE VIEW to Clipboard" or "Copy CREATE VIEW to new Query Tab".

Kind regards

Marco Tröster

**Comment by Greg-Roberts** [comment]
I feel a bit like an idiot for not trying Ctrl+C before seeing you post. I think it will do what I need but I'd still like to second the request for a clear way to edit the create statement.

Thanks,

Greg

**Comment by MKleusberg** [comment]
I've just added a new action called 'Copy Create statement' to the right-click menu of the Database Structure tab which copies the CREATE statement to the clipboard. From there it can be put in a file or in a SQL editor tab. I hope this makes it more obvious how to access the CREATE statement.

There is no editor window for creating views and therefore we don't support editing them in a graphical way neither. I can't imagine any way of implementing such a dialog, too, because the create statements of views can be incredibly complex... But maybe (hopefully) making it easier to copy the statement to an SQL editor tab already does the trick :)

**Comment by justinclift** [comment]
Thanks @MKleusberg, that's excellent. :smile:

@MarcoTroester @Greg-Roberts Would either of you have time to try out our latest nightly build, and let us know if the new 'Copy Create Statement' approach is workable from your points of view?

**Comment by MarcoTroester** [comment]
Hello everybody,

I really appreciate your efforts.

I would really like to test your product, but unfortunately I cannot compile the sources myself. I've just installed Qt Creator, but when starting the IDE, it crashes.

Could you please compile your sources for me? (I am using Windows 7 OS)

Thanks in advance.

Marco Tröster

**Comment by justinclift** [comment]
You're in luck. :smile:

We automatically compile a build each night from our latest source code (it's scripted), and make that available for download here:

&nbsp; &nbsp; http://rp.oldsch00l.com/sqlitebrowser/

The .xz file there is the compressed version of the program.  Use [7zip](http://www.7-zip.org) to uncompress it, and you should be right to go. :grinning:

**Comment by MarcoTroester** [comment]
Thumbs up for the one who committed the code. Thank you very much :D

**Comment by justinclift** [comment]
@MarcoTroester It's @MKleusberg's work. :smile:

It sounds like this issue is pretty much resolved now, so I'm going to close it.  If that's not the case, feel free to reopen it. :wink:
