### ISSUE TITLE
Error loading extension: The specified procedure could not be found

### ISSUE THREAD

**Issue by jholovacs** [sqlitebrowser/sqlitebrowser#1441]
Getting the above error when enabling the sqlcipher extension and loading a sqlite db.

Version 3.10.1
Qt Version 5.7.1
SQLCipher Version 3.15.2

Windows 10 x64

**Comment by justinclift** [comment]
Thanks @jholovacs.  Would you be ok to try our latest nightly build?

If so, they're here (automatically created each night):

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

There's a decent chance the other fixes we've done for SQLCipher pieces since that release have already have taken care of it. :smile:

**Comment by jholovacs** [comment]
I just did; same result.

**Comment by justinclift** [comment]
Thanks @jholovacs.  Definitely sounding like a bug of some sort then.

Hmmm, as a shot in the dark, would you be ok to try one of the 32-bit builds?  If that works, where the 64-bit one isn't, that points to the problem being .dll related.

**Comment by jholovacs** [comment]
So if I set the preferences to always load the extension and there's no
database loaded, I receive no error... till I load the database, then I get
that message.  Likewise, if I already have a database loaded, and try to
load the extension, I also get the same message.

**Comment by justinclift** [comment]
Ahhhhh.  Has the extension worked for you before, or is it a new one you're trying? :smile:

**Comment by jholovacs** [comment]
It was the first time I was trying any extension.  I was looking for the
JSON extension and then I read something that made me think the
functionality was in sqlcipher, so I tried loading it, with no luck.

I'll be trying out the 32 bit version in a bit.

**Comment by justinclift** [comment]
No worries. :smile:

The JSON functionality should be in the standard SQLite nightly builds.  You shouldn't (in theory) need to load anything extra in order to make it work.

In case it helps, this is the line where the JSON1 extension gets included by our nightly build process:

https://gist.github.com/justinclift/11cc926f214e882c8162f97c53929c07#file-winbuild-bat-L80

**Comment by jholovacs** [comment]
hmm none of the JSON1 functions were recognized.

**Comment by jholovacs** [comment]
All right, I tried the 32-bit version of the msi package, and still got the
same error.  I'm inclined to think this is somehow Windows related at this
point.

**Comment by jholovacs** [comment]
Hmm, I uninstalled everything and tried to install into my local AppData
file, and still got the same error.

**Comment by justinclift** [comment]
@wmertens Do you still do stuff with the JSON1 extension?  If so, would you have a few minutes to check if it's still working ok for you in our latest nightly builds?  I'm kind of wondering if something in the newest SQLite release has busted something. :fearful:

**Comment by wmertens** [comment]
Works fine for me on OS X - @jholovacs what does `PRAGMA compile_options` return? Mine includes JSON1.

**Comment by justinclift** [comment]
Thanks @wmertens. :smile:

**Comment by jholovacs** [comment]
the json commands seem to work, I used one incorrectly and it barked at me,
so I assumed JSON1 extension was not installed... so I went looking to
install an extension.

The (bug?) I'm reporting has less to do with the JSON component and more
with the cryptic error message.

**Comment by justinclift** [comment]
Yeah, it does sounds cryptic. :smile:

With the cryptic error message, what's the exact (incorrect) SQL line you used, and would you be ok to take a screenshot of the error message? We might be able to figure out some better way to display things from that.

**Comment by jholovacs** [comment]
It wasn't SQL, it was through the application:

![image](https://user-images.githubusercontent.com/1767540/41791711-9436892c-7624-11e8-80b7-fc4c5fb9a60c.png)

**Comment by justinclift** [comment]
Thanks @jholovacs.  Ahhh, gotcha.  Error message straight away when loading the database.

I have a feeling this one might be tough to change, as I **suspect** we're just passing through an error message from SQLite itself.  Saying that because just went looking through our source, and there's no occurrence of the string "The specified procedure could not be found".

Hmmm, maybe there's a different approach we can take.  With the extension (file) you tried to add, is it something you compiled yourself, or was it a download from somewhere?

Sorry for all the questions, I'm just trying to figure out a potential solution for the next person in the same situation. :smile:

**Comment by jholovacs** [comment]
None of the above, it was included with the install of the sqlite browser.

When I was trying to find extensions, I first browsed to the directory the
app was installed in, under the assumption that there may be included
extensions that were available but not loaded.  I'd seen some mention
sqlcipher with JSON1, so when I found that file, I was like, Eureka!

In retrospect, I'd imagine this error message actually means something to
the effect of "We can't recognize the file you told us was an extension
library as an extension library.  Perhaps you are an idiot for trying to
load some random file?"

**Comment by justinclift** [comment]
Thanks @jholovacs.

To me, it's sounding like an unusual enough situation that we're probably ok to just leave the loading code "as is" for now.  If future people hit this too (eg we get more reports of this happening), then we can put more effort into figuring out a workaround. :smile:

**Comment by twe1941** [comment]
I'm trying to load a dll, and I get an error message.
Full name of dll: ValidEmailAddressSyntax.dll
which was created by Visual Studio using only C syntax.

The exact sqlite3 line that resulted in an error:
.load ValidEmailAddressSyntax.dll

The error message:
Error: The specified procedure could not be found.

If I give .load the name of a non-existent file, I get the message:
Error: The specified module could not be found.
So I conclude that the problem is finding the procedure within the dll.

I have absolutely no idea how to debug this problem. What more can I send you that might help?

**Comment by twe1941** [comment]
Here is the complete code that resulted in the above problem:

// dllmain.cpp : Defines the entry point for the DLL application.
#include "pch.h"
// Above two lines added so Visual Studio would build dll with no errors

// Extension to verify that an email address has a valid syntax
#include <c:\SQLITE\sqlite3ext.h> 
SQLITE_EXTENSION_INIT1

#include <regex>
#include <string>
using namespace std;

static const regex valid("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,6}$");
static const regex dots(".*[@.]{2,}.*");

bool ValidEmailAddressSyntax(char* abc)
{
	if (abc == nullptr || abc[0] == 0 || abc[0] == '.')
		return false;	//null pointer or zero-length string or initial dot
	string xyz = abc;
	return regex_match(xyz, valid) && !regex_match(xyz, dots);
}

#ifdef _WIN32
__declspec(dllexport)
#endif

int sqlite3_validemailaddresssyntax_init(
	sqlite3* db,
	char** pzErrMsg,
	const sqlite3_api_routines* pApi
) {
	int rc = SQLITE_OK;
	SQLITE_EXTENSION_INIT2(pApi);
	return rc;
}
// Below lines added so Visual Studio will build dll without error

BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}

**Comment by karim** [comment]
@twe1941 Hello there. :smiley: 

> which was created by Visual Studio using only C syntax.

From the code you posted, this doesn't look like C code. Visual Studio treats .cpp files as C++ files and compile them as such.

Your problem is that this extension you are trying to make is compiled as C++ DLL. There is nothing wrong with that, but the exported function name is [mangled](https://en.wikipedia.org/wiki/Name_mangling).

I compiled your code (after slightly modifying it) and the function name was `?sqlite3_validemailaddresssyntax_init@@YAHPEAUsqlite3@@PEAPEADPEBUsqlite3_api_routines@@@Z`.

DB Browser for SQLite and the SQLite command-line cannot load/find this function because they expect its name to be `sqlite3_validemailaddresssyntax_init`. To do that you need to give this function a [C linkage](https://en.wikipedia.org/wiki/Compatibility_of_C_and_C%2B%2B#Linking_C_and_C++_code).

Simply add this before and after the exported function...

```cpp
// Add this before the function
#ifdef __cplusplus
extern "C" {
#endif

#ifdef _WIN32
__declspec(dllexport)
#endif

int sqlite3_validemailaddresssyntax_init(
    sqlite3* db,
    char** pzErrMsg,
    const sqlite3_api_routines* pApi
) {
    int rc = SQLITE_OK;
    SQLITE_EXTENSION_INIT2(pApi);
    return rc;
}

// Add this after it
#ifdef __cplusplus
}
#endif
```

This will tell the C++ compiler to not mangle the function name.

Another way to get a non-mangled function name is to write your extension in C. Change the source file extension to `.c` and Visual Studio will compile it as C. Don't forget to remove/replace the C++ parts, like `using namespace std`, etc.

**Comment by twe1941** [comment]
Karim,
Your suggested code changes worked: sqlite3 can now find the procedure. Thank you!
(The lesson I learned is that just because it looked like a C calling procedure, it wasn't a C calling procedure; I didn't know about mangling.)

So progress has been made. The next problem is that:
sqlite> select ValidEmailAddressSyntax("a@b.cd");
results in:
Error: No such function: ValidEmailAddressSyntax

Again, I have no clue.

**Comment by justinclift** [comment]
Anything useful in these ones?

* https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/extensions/extension-formats.c
* https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/extensions/extension-functions.c

**Comment by twe1941** [comment]
Justin,
Yes, thank you. The second one is particularly useful in that it has several simple instances of passing a string. And they all look familiar (from doing this in C a quarter of a century ago). So my current problem is somewhere else.

**Comment by karim** [comment]
`.load ValidEmailAddressSyntax.dll` will now be able to find the function name inside the DLL, load it, and then call `sqlite3_validemailaddresssyntax_init` function from it to initialize the extension. But since there is nothing inside this function, the extension does nothing.

You *init* function should call other functions (e.g. `sqlite3_create_function()`) to register the new features that your extension adds.

For example, you can do something like this.. `sqlite3_create_function(db, "ValidateEmail", ...);` from inside `sqlite3_validemailaddresssyntax_init` to create `ValidateEmail` function than you can call with `SELECT ValidateEmail("a@b.cd");`

That's why `select ValidEmailAddressSyntax("a@b.cd");` didn't work, because you didn't register a function called `ValidEmailAddressSyntax`.

This link https://www.sqlite.org/loadext.html#programming_loadable_extensions should give you some pointers.

Also this small extension https://www.sqlite.org/src/file/ext/misc/compress.c will show you how to register functions. You can find more here https://www.sqlite.org/src/file/ext/misc/ too.

Good luck. :smiley: :+1:

**Comment by twe1941** [comment]
Karim,
Thank you again. Your last email gave me all the clues I needed. My function now works. Hooray!
The best example code (for me) was regex.c because it had the clearest examples of string arguments and how to access and use them.

This turned out to be considerably more complicated than I expected, which resulted in my not reading all the on-line documentation. It is all explained on-line, but I just didn't realize what all I needed to pay close attention to. So I owe some apologies for not being sufficiently diligent in not exploring the available documentation.

**Comment by karim** [comment]
I'm glad it's working for you now. :smiley: 

If you don't mind me asking, what are you trying to achieve here? Do you want to write/learn about SQLite extensions or you simply want *regexp* support with your database but couldn't find so you thought about writing an extension to do that?

If all you care about is having *regexp* support, then you should know that SQLite already has a [`REGEXP`](https://www.sqlite.org/lang_expr.html#regexp) operator that you can use in your queries.

It was requested in issue #215 and `regexp()` function was added (https://github.com/sqlitebrowser/sqlitebrowser/commit/6d1a874f8077b859bee2dd9d4031f242cfa1e807) to DB Browser for SQLite as a built-in function, so you don't need to write your own. You can check the [wiki](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Regular-Expressions) and see how it works.

I'm not good with *regexp* but you can do something like this..

```sql
-- Get
SELECT * FROM table_name WHERE column_name REGEXP 'your regexp here';

-- Set
UPDATE table_name SET column_name = 'test' WHERE column_name REGEXP 'your regexp here';
```

**Comment by karim** [comment]
Oh, and also.. to validate emails before entering them into the database, you can add a `CHECK` constraint.

```sql
CREATE TABLE users
(
    id INTEGER,
    email TEXT,
    CHECK(email REGEXP 'your regexp here')
)
```

This is **not** tested but should work. :smiley:

**Comment by twe1941** [comment]
This was not a learning exercise. I'm re-implementing an email-list server application that previously used MS Access. We need to move the app off its present host and into the cloud. I'm told that Access won't be available (although I don't quite understand why), thus the re-do. The app reads 49 CSV files from our HQ, has some complex criteria for generating 25 email distribution lists, and then writes those lists out into files from where they are FTPd (or equivalent) to the list server. 

I had written ValidEmailAddressSyntax in Visual Basic when we were using Access. Then in C# connected to Access when it appeared that was a way to go. Doing both of those was easy, and I guess I got into a thinking rut when I started investigating SQLite. I now know that SQLite has regex available, (I examined its C code to create my extension), and that would likely have been an easier. (As a learning exercise, I will try it.)

>> ...  to validate emails before entering them into the database ...
And that is exactly what I'm doing. Your checking suggestion is good.

The results of using SQLite are really great . This version has half the db size and the execution time is 1/10 of the Access version. And SQLite is much easier to use than Access, even on my first project.

Karim, I want to thank you again for your tutorial on how to make C++ code have a C external calling interface. That part was NOT in the SQLite documentation.

twe

**Comment by chrisjlocke** [comment]
> I'm re-implementing an email-list server application that previously used MS Access

What are you writing your app in?  c#?  c?  I'm a vb .net developer (don't kick me) and found the system.data.sqlite.dll very useful.  I've written my own classes and found sqlite a pleasure to use.

**Comment by twe1941** [comment]
I wrote the extension in C++ (initially copied from C#), but I didn't know what I was doing when I started.

**Comment by karim** [comment]
> We need to move the app off its present host and into the cloud.

Since you mentioned *the cloud* and using *SQLite* together in the same comment, I should let you know that we have another project (https://dbhub.io/) that you might find useful. :smiley: :+1: :tada: 

> I had written ValidEmailAddressSyntax in Visual Basic when we were using Access. Then in C# connected to Access when it appeared that was a way to go.

If you are in control of the app that is writing to the SQLite database, then I think you should move the email validation to the app itself, without using regex. Using a class/library maybe. Depends on your programming language of choice, some will have built-in classes for validating email addresses. 

Regex is not prefect when dealing with email addresses. It will work 90% of the times, but it will block a valid email or allow an invalid email from time to time.

https://emailregex.com/ will show you the regex needed to validate emails *most* of the time, for different programming languages. Some of these regex are just painful to watch. :smile: 

Also regex does not account for internationalized domains or the new TLDs. You might want to check this list here... https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains.

> And that is exactly what I'm doing. Your checking suggestion is good.

Even if you are validating emails in the app itself, you should also use SQLite regex too. In case the database was modified by a different app, or someone wanted to insert/modify the data manually.

**Comment by twe1941** [comment]
Karim,

You are right. Doing a perfect job of verifying email syntax is hard, so I've simplified somewhat. My RE rejects anything with double quotes, and I have no idea what it will do with characters outside of ASCII. It does accept top-level domains up to 6 characters, like ".museum".  I think I'll wait until somebody complains about not getting some email distribution before I do anything more. Or perhaps when I get really bored on some rainy evening.   :-)

There is only one writer and one reader, which makes things a lot simpler.

As a item of black humor, I just checked to see if National HQ accepted invalid email addresses. The code there accepted "a..b@@c.de".

**Comment by justinclift** [comment]
> We need to move the app off its present host and into the cloud.  I'm told that Access won't be available ...

Kind of sounds like it's being moved to a non-Windows OS.  But that's just guessing wildly. :smile:

**Comment by karim** [comment]
> Doing a perfect job of verifying email syntax is hard, so I've simplified somewhat.

Yes, using regex with a `CHECK` constraint and/or a loadable extension should be enough for now.

I would have taken the same approach also. Start simple and use regex, then make it better later if and when you find it more appropriate.

> As an item of black humor, I just checked to see if National HQ accepted invalid email addresses. The code there accepted "a..b@@c.de". :-(

This `-.._..-@oO...Oo` is also a valid address according to the regex in the code above. :smiley:

**Comment by twe1941** [comment]
My understanding is email addresses have a dot rule. They should never contain:
^. or .. or .@ or @. or .$
That's hard to implement if there is only one RE. So I used two REs, the second
one to reject dot rule violations. That was slow, so I did it instead in 8 lines of
code, which is really fast.

Now ValidEmailAddressSyntax rejects -.._..-@oO...Oo but still accepts -._.-@oO.Oo
That's not a clear improvement and not clearly worthwhile, but it was easy.

I think this topic has morphed from how to implement SQLite3 extensions to how
to find invalid email addesses.

**Comment by karim** [comment]
> So I used two REs, the second one to reject dot rule violations.

You are right. This second rule I didn't notice, sorry. :smiley: 

> This topic has morphed from how to implement SQLite3 extensions to how
> to find invalid email addresses. Let's call it quits or start another topic.

Yeah. :smile: 

Everything seems to be working now, so let's stop right here, but feel free to start another issue if you encounter any problems. Good luck and have a nice day.

**Comment by krazado** [comment]
Hello everyone,

I am trying to build ICU extension for SQLite, regarding the building everything is fine, I am generating icu.dll with visual studio and then trying to load it with "DB browser for SQLite" and I am getting exception: "Error loading extension: The specified module could not be found."

I am using icu.c  file provided by SQLite: https://www.sqlite.org/src/dir?ci=tip&name=ext/icu
I don't have any modification in that file, I just included needed libraries and built it, I attached demo project, so you can have a look on it.

Exception during loading:
![image](https://user-images.githubusercontent.com/13288912/133602065-752a48b8-670b-4c32-a556-3405e166fb98.png)
DB browser for SQLite version:
![image](https://user-images.githubusercontent.com/13288912/133602150-bf3e36f2-fa8f-4df7-94ad-5ce6734b2f8c.png)
OS: Windows 10, x64

Sample project(Created in visual studio 2019)
[icu_ext.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/7177279/icu_ext.zip)

Thank you in advance!
