### ISSUE TITLE
Remember window's position and size

### ISSUE THREAD

**Issue by epistemex** [sqlitebrowser/sqlitebrowser#1446]
Describe the new feature
--------------------------
Remember window positions and sizes (ie. incl. child windows like create/modify table/index etc.)

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.

Nope

#### Does this feature exist in another product or project? Please provide a link.

Loading examples....

![loading](https://user-images.githubusercontent.com/26116778/41806515-2f0ea258-7685-11e8-982e-5e58c93ad98d.gif)

#### Do you have a screenshot? Please add screenshots to help explain your idea.

![image](https://user-images.githubusercontent.com/26116778/41806508-17a56e80-7685-11e8-989c-5abb739c100d.png)

Oh btw: A dark theme would be nice too.

**Comment by justinclift** [comment]
The window positioning bit seems similar to #633.  Which version of DB4S are you using, and on what platform? :smile:

Oh, there's good news for the dark theme already.  It was added by @mgrojo [back in February](https://github.com/sqlitebrowser/sqlitebrowser/issues/1324#issuecomment-368331884), should should be in all of our nightly builds since then.  Just grab the latest one if you want, which will have it too:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by epistemex** [comment]
I'm on win 8.1 - oo, let me also check out the theme :) Not sure if it's the same. Let me check if the behavior is the same as in that issue

**Comment by m4heshd** [comment]
I'm on 3.10.1 and window position, size works fine for me.

**Comment by epistemex** [comment]
@justinclift The main window works fine, but a child window such as say, "Modify table" reverts back to center and initial size very time it opens. I have no problems with double-clicking cells.
