### ISSUE TITLE
project sqbpro files do not populate SQL

### ISSUE THREAD

**Issue by mglatz** [sqlitebrowser/sqlitebrowser#1458]
when I save a project and then open it, the saved sql tabs in "execute SQL" do not show up

Details for the issue
--------------------

#### What did you do?

opened database, wrote some sql, saved project; closed database, verified that sqbpro has the sql, opened sqbpro file.

#### What did you expect to see?
sql tab with command I saved in "execute SQL"

#### What did you see instead?
empty sql tab

Useful extra information
-------------------------
tried default tab name and renamed tab name, nothing works

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [x] Other: 3.10.99 (Jul 4 2018)

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
Yes, I had already noticed that. It should't happen, but haven't had time to look into it. Probably it's related to the project format change, but it could be also previous, like #1222.

**Comment by justinclift** [comment]
No worries. :smile:

**Comment by mgrojo** [comment]
@mglatz The problem should be solved in yesterday's nightly build. There was a problem since the format change that I implemented for issue #1306. It was affecting both the saving and loading of the SQL data. That means that the files saved by the nightlies from that version until yesterday's cannot be used to restore the SQL data unless manually edited. For that, the `<sql_tab>` node must be moved outside of the `<tab_browse>` node (they must be at the same level).

But the current nightly should be able to save correctly the SQL data, and restore it using the old format (pre issue #1306, 3.10) and the new format (post this issue, future 3.11 format). The intermediate format is considered deprecated and not recognized for SQL restoring.

Might you install the nightly and test that is is working for you as stated?

**Comment by justinclift** [comment]
Oops, sorry.  The nightly build hasn't run for the last two days.  Completely my fault as I was doing something on the nightly build server and didn't leave it running afterwards.

I'll launch the build scripts again in a minute.  The nightly build for "last night" should be ready about an hour afterwards.

**Comment by justinclift** [comment]
Just checked, and the nightly build for "last night" is online. :smile:

**Comment by mglatz** [comment]
it works. 
Would you consider adding support for older sqbpro files? I use quite bunch of them and I'm lazy to write conversion script :)

**Comment by mgrojo** [comment]
Do you mean with <tab_sql> inside <tab_browse> like in your example? Sorry to say this, but that format was an accident and it was only produced by unstable versions. I wouldn't like to add that support and left that accident forever. 

But no worries, at least if you have access to a Unix command line :). This sed command will fix a problematic file:

`sed 's%<tab_sql>%</tab_browse><tab_sql>%g; s%</tab_sql></tab_browse>%</tab_sql>%g' accident.sqbpro > fixed.sqbpro`

**Comment by mglatz** [comment]
my bad. I thought that none of the sqbpro files saved in earlier (stable) versions will no longer work but they do. All resolved then :) 
Thanks

**Comment by justinclift** [comment]
Awesome. :smile:
