### ISSUE TITLE
Always 'Segmentation fault' when  select  'Edit display format' for column of *view*.

### ISSUE THREAD

**Issue by n-arakawa** [sqlitebrowser/sqlitebrowser#1466]
### Details for the issue

Always 'Segmentation fault' when  select  'Edit display format' for column of *view*.
It is ok to 'Edit display format' for column of *tables*.

### Useful extra information

sample db
---- 
create table T1 (id integer primary key,  c1  integer);
create table T2 (id integer primary key,  T1_id, c2 integer,  FOREIGN KEY( T1_id ) REFERENCES T1( id ));
create view v1 as select T1.id, T1.c1, T2.c2 from T1 join T2 on T2.T1_id = T1.id;
insert into T1 (id,  c1) values (0, 1);
insert into T2 (id,  T1_id, c2) values (0, 0 , 2);
-----

1) select 'Browse data' tab
2) select 'v1' in 'Table:' pull-down menu
3) right-click 'id' / select 'Edit display format'
 

#### I'm opening this issue because:

- [ X ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ X ] Linux: ( Fedora 28/Ubuntu 18.04 )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ X ] 3.10.1 ( dnf install / apt install)
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

I cannot  complie latest version both on Fedora 28 and Ubuntu 18.04

**Comment by mgrojo** [comment]
Thanks for reporting. This is working for me in the nightly version. Could you confirm it is also working for you? For Ubuntu, I think you can easily install a nightly as described in https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds-1 Otherwise, it shouldn't be too difficult to compile from the master branch of the git repository following these instructions: https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md

Please, confirm it is working, so we can close this issue.

**Comment by n-arakawa** [comment]
Thanks,

Now it's OK with following commit   on Fedora 28 .

```
commit 5a339ea9d066aae1f5138d5e0abcef583fc7fee4
Author: Martin Kleusberg <mkleusberg@gmail.com>
Date:   Thu Jul 12 20:44:02 2018 +0200

    Fix cmake build on Windows
    
    See issue #1471.
```

**Comment by justinclift** [comment]
Awesome.  Thanks for confirming @n-arakawa. :smile:
