### ISSUE TITLE
Wrong symbol for single quotewhen saving to sql file 

### ISSUE THREAD

**Issue by Bluezy** [sqlitebrowser/sqlitebrowser#1502]
### Details for the issue

the SQL file  obtained via the "Save database to an SQL file" uses ` (U+0060, accent grave) instead of ' (U+0020) apostrophe 

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh.  Would you be ok to try with the latest nightly build (tomorrow's one, in a few hours)?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

We've been doing stuff with the SQL file export recently, and I **think** we've been changing quotes too. :smile:

**Comment by MKleusberg** [comment]
Yep, we have changed quotes throughout the entire program, including the SQL export. So the nightly is worth a try :smile: But I guess you mean double quotes instead of the apostrophe? Because apostrophes are for strings only, not for identifiers, and we've been using them since ever for strings :wink:

Just mentioning one exception to the changes in the nightly build: if the original table definition uses e.g. grave quotes and you configured the application to use double quotes (the new default), it'll export double quotes unless the table or index definition cannot be fully parsed. So if our parser notices something it doesn't fully understand we leave the statement as-is to avoid any loss of information. For triggers and views that's always the case by the way. So these statements would always be exported using grave quotes if that's how they were defined in the first place.

**Comment by chrisjlocke** [comment]
@Bluezy : *cough*

**Comment by chrisjlocke** [comment]
Just exported a database to SQL using the nightly (6 Sep) and while CREATE TABLE and INSERT statements use the user-defined option, CREATE VIEW doesn't.

![image](https://user-images.githubusercontent.com/7872218/45157358-dcc8ce80-b1d8-11e8-8798-832075bf5cae.png)

Also (I'm on Windows) there was no option to set carriage return options, so all the SQL has got squished into one line - note the 'tn3.orderBy=3left join contactsData'.....(etc).  It is valid SQL though (it all imported fine)

**Comment by justinclift** [comment]
Good thing you checked @chrisjlocke. :smile:

**Comment by MKleusberg** [comment]
@chrisjlocke You're right - but it's supposed to be like that :wink: The reason for that is that the quotation settings only affect all the SQL statements generated by us. The INSERT statements are obviously always generated by us and the CREATE TABLE statements at least most of the time because we have the habit to parse them and then put them back together whenever we work with them. But if the parser doesn't quite understand the full CREATE TABLE statement it will just not touch it and export it in its original form. The same is true for indices. Views and triggers on the other hand are never parsed (because we have no parser for them :wink:) so we always export them in their original form, that is by which statements they were originally created and how they were saved in the database.

**Comment by chrisjlocke** [comment]
That's pants! ;)  😆 
Fair enough - makes sense!

**Comment by mgrojo** [comment]
@chrisjlocke:
> Also (I'm on Windows) there was no option to set carriage return options, so all the SQL has got squished into one line - note the 'tn3.orderBy=3left join contactsData'.....(etc). It is valid SQL though (it all imported fine) but its just the 'wrong' line terminators for Windows...

That should be solved with my last commit. Could you confirm it?

**Comment by chrisjlocke** [comment]
Can confirm - the file now looks beautiful.  Almost art.  😉 
Thanks! 👍 

I'll close this as its resolved.  @Bluezy can re-open it or comment further if need be.  📓
