### ISSUE TITLE
Valid trigger not created/processed by sqlitebrowser

### ISSUE THREAD

**Issue by isrep** [sqlitebrowser/sqlitebrowser#1508]
### Details for the issue
Hi,

while trying to open new fossil repository (it is a sqlite database) with notification activated 
(info in http://fossil-scm.org/index.html/doc/trunk/www/emaildesign.md)
DB Browser for SQLite version c4109e6a100 complains with error:

Could not open database file.
Reason: malformed database schema (email_trigger1) - near "ON": syntax error

It seems that following trigger  (official source of trigger code: 
http://fossil-scm.org/index.html/artifact?udc=1&ln=129-143&name=dba99958ae7c49ee)

    CREATE TRIGGER email_trigger1
    AFTER INSERT ON event BEGIN
      INSERT INTO pending_alert(eventid)
        SELECT printf('%.1c%d',new.type,new.objid) WHERE true
        ON CONFLICT(eventId) DO NOTHING;
    END;

is not correctly processed by DB Browser.

All previous version of fossil repositories were opening in DB Browser just fine.
Could you please look into it?
Thanks

    --some detail abstracted from fossil repo
    --you cant create email_trigger1 in DB Browser GUI.

    CREATE TABLE event(
      type TEXT,
      mtime DATETIME,
      objid INTEGER PRIMARY KEY,
      tagid INTEGER,
      uid INTEGER REFERENCES user,
      bgcolor TEXT,
      euser TEXT,
      user TEXT,
      ecomment TEXT,
      comment TEXT,
      brief TEXT,
      omtime DATETIME
    );
    CREATE TABLE pending_alert(
      eventid TEXT PRIMARY KEY,
      sentSep BOOLEAN DEFAULT false,
      sentDigest BOOLEAN DEFAULT false,
      sentMod BOOLEAN DEFAULT false
    ) WITHOUT ROWID;

    CREATE TRIGGER email_trigger1
    AFTER INSERT ON event BEGIN
      INSERT INTO pending_alert(eventid)
        SELECT printf('%.1c%d',new.type,new.objid) WHERE true
        ON CONFLICT(eventId) DO NOTHING;
    END;

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro:_ ubuntu )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.10.1
- [ ] 3.10.0
- [ ] 3.9.1
- [X ] Other: c4109e6a100

#### I have also:

- [x] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by MKleusberg** [comment]
We practically don't handle triggers at all in our application because they are complicated to parse :wink: So my guess is that this problem is caused by your version of SQLite. You can check the version in the Help -> About dialog. Looking at the query you have posted, I can see this bit which is an [UPSERT clause](https://sqlite.org/lang_UPSERT.html):
```
ON CONFLICT(eventId) DO NOTHING;
```
Those are only supported since SQLite 3.24.0, so that's also the minimum requirement to open this database.

**Comment by isrep** [comment]
Thanks for the insight. 
At the moment:
About DB Browser for SQLite window shows "SQLite Version 3.22.0". 
Embedded fossil SQLite shell (handling triggers just fine) report SQLite version  3.25.0

    fossil sqlite3 -R ./test-dbbrowser.fossil
    SQLite version 3.25.0 2018-08-16 16:24:24
    
To the best of my knowledge I have just now installed prerelease snapshot of SQLite (https://www.sqlite.org/snapshot/sqlite-snapshot-201807272333.tar.gz)
sqlite3 command on my system list sqlite version 3.25.0

    sqlite3
    SQLite version 3.25.0 2018-07-27 23:33:16
    Enter ".help" for usage hints.
    Connected to a transient in-memory database.
    Use ".open FILENAME" to reopen on a persistent database.
    sqlite> 

I have also installed new SQLite libraries to /usr/local/bin.
After full rebuild  DB Browser for SQLite version b7dbfc84c9  now reports in About version "SQLite Version 3.25.0".

Unfortunately, I still cant execute "CREATE TRIGGER email_trigger1..." statement nor open database with such trigger defined (the same error as already reported).

Am I missing something? What should I try?
Thanks.

**Comment by isrep** [comment]
With latest DB Browser for SQLite version d5a049062 reporting in About "SQLite Version 3.25.0" (libraries updated by https://www.sqlite.org/snapshot/sqlite-snapshot-201807272333.tar.gz to version  3.25.0) I can create/operate databases with triggers like email_trigger1.

I am not sure why it did not work with DB Browser for SQLite version b7dbfc8.

Any insight? Anyway I am glad it works now. Thanks.

**Comment by justinclift** [comment]
Hmmm, that's pretty weird.  The only change since doesn't seem related. :scream:

Is the database that was failing something we could get access to?  I'm kind of thinking that we should check if it fails for us too, and if so then either @MKleusberg or @mgrojo should probably hit the failure with a debugger.

**Comment by isrep** [comment]
My smalest test case
[test-trigger-DB4S.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/2308912/test-trigger-DB4S.zip)

:
1. create and save empty database in DB4S
2. create tables "event""pending_alert" by executing SQL statements, as defined in ticket, save database.
3. attempt to execute create trigger email_trigger1 -  statement fails

4. if you create trigger email_trigger1 in above database by other SQLite engine, then DB4S fails to open such db.

There is test db attached

**Comment by MKleusberg** [comment]
Unfortunately I have no explanation either. I have tried @isrep's test database with SQLite 3.24 (the latest stable version) and it opened just fine. With an older version of SQLite (simulated by just using SQLCipher actually) I got the error message. This is all as expected because of the UPSERT clause I have mentioned earlier.

Also the error message is shown when opening the database, as @isrep pointed out too. The error comes directly from SQLite and happens before we even have a chance to do anything with the database. So it's definitely an SQLite version thing.

The only question is why it didn't work with 3.25 for @isrep earlier. Normally I'd say this is because of some old files in the build directory and that the recompile fixed it but since the About dialog definitely said it's 3.25 we can rule that out. So my only explanation at the moment is that you were using two different versions called 3.25 - that should be possible because 3.25 is in development right now. Maybe you were after all using two different snapshots for some reason and the SQLite developers broke UPSERT clauses by accident in one of them but fixed it in the other. On the other hand you said you were using the same snapshot, so I don't know :wink:

**Comment by isrep** [comment]
Thank you for more details and checks. As of now my hypothesis would be something system depended (I did install only that snapshot) but there are still those 3.22 libraries in /usr/bin. Perhaps reboot cleared which libraries are  truly used.(and BTW d5a0490 fixed for me repeatable crash with browsing views so big thanks for it as well)

To mitigate similar issues with dependency on sqlite libraries installed on the system could you recommend recipe//settings/switches for building linux DB4S executable with SQLite libraries embedded?

Thanks again

**Comment by MKleusberg** [comment]
You're very welcome, @isrep :smile: I agree, it was probably fixed by the reboot. The thing here is that the SQLite version number we show in the About dialog is baked into the application at compile time. So if it somehow loads a dynamic library of another version, the versions won't match.

Do you build with cmake or with qmake, and with gcc or with clang? If you want to embed the SQLite library into the DB4S executable you have to link it statically. I haven't done that before but in theory it should be possible and we should be able to figure this out :smile:
