### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by antonybits** [sqlitebrowser/sqlitebrowser#1521]
I have been using this application for a while, It's really good.
I like it because it can import multiple csv files in one import,
I have many csv files and they have the same table format, the db browser  asks if i want all csv files to be imported in one table, which is very clever. but i should answer this question as many as the files.
it just could ask if user want to do the same for all imports at first. 
program question is:
"There is already a table of that name. Do you want to import the data into it?"
please add a check mark to ask "Do not ask again."

**Comment by justinclift** [comment]
Hi @antonybits, it sounds like you are using one of the older nightly builds, because I **think** we fixed that already.

Just to check - in case I am remembering wrongly :wink: - what is the date in the "About" box for your version of DB4S?

If it's not recent, or doesn't show a date then please try the CSV importing with a new nightly build:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by antonybits** [comment]
I was using official releases not the nightly builds,
will test those versions as well.


 I could provide this information from DB browser -->Help-->About
version 3.10.1
Qt version 5.7.1
SQLCipher Version3.15.2

**Comment by justinclift** [comment]
Awesome @antonybits. :smile:

Are we ok to close this issue?

**Comment by MKleusberg** [comment]
By the way, you should also be pleasantly surprised by how much faster the import is now :wink:

**Comment by justinclift** [comment]
Hmmm, I think we're ok to close this.  @antonybits did mention it's working for them now. :smile:
