### ISSUE TITLE
UTF-16 in data input fields?

### ISSUE THREAD

**Issue by AAverin** [sqlitebrowser/sqlitebrowser#153]
I'm trying to input some rare UTF symbols, like acute accent (U0301), for example. But looks like edits fields in the UI do not support them.
Would be great if I could see them in UI.
Also, any way to input such symbols? Like, if I write \U0301 in the Edit field, will it read as one symbol in db or as 5?

**Comment by mgrojo** [comment]
In my opinion, this is better done with OS utilities. Take a look at: https://en.wikipedia.org/wiki/Unicode_input#In_Microsoft_Windows

**Comment by justinclift** [comment]
Ahhh, this can probably be looked at again.

I'd kind of expect this to work with our recent releases, as they're using Qt 5.x which I'm fairly sure has decent support for things like this in it.  @chrisjlocke Would you be ok to try out 3.10.1 or a nightly, and check if the above Windows input approach (mentioned by @mgrojo) works?

**Comment by chrisjlocke** [comment]
It would be an honour and a pleasure. Will have a look later. :)

**Comment by karim** [comment]
Pressing and holding `Alt` then typing a number in the numeric keypad should work in all Windows programs. For example, use `Alt+0228` to get `ä`.

![char-map](https://user-images.githubusercontent.com/8761081/43931220-c59815c8-9c3d-11e8-8889-a73cd76629b9.jpg)

This works in DB4S..

![db4s](https://user-images.githubusercontent.com/8761081/43931250-e2844616-9c3d-11e8-9aa4-1f1522402a19.jpg)

However, there seem to be a little problem with this. Alt+ 1, 2, 3, and 4 are assigned as keyboard shortcuts to switch between the tabs (Browse Data, Execute SQL).

So if you want to type `Alt+1234` you can't because as soon as you hit 1 after holding Alt key it will switch to the first tab. `Alt+4567` is not possible also since pressing `Alt` followed by 4 will switch you directly to Execute SQL tab.

The only way to use the numeric keypad to type these codes is to make sure your code doesn't include 1, 3, or 4. But why didn't I say 2 also? Well, `Alt + 2` keyboard shortcut will switch to the Browse Data tab, which you are already on if you are editing the fields so the shortcut will not be triggered I guess. :smile:

**Comment by justinclift** [comment]
Heh Heh Heh

Good catch.  Any idea how other Windows programs supporting <kbd>Alt</kbd>+<kbd>some number</kbd> combinations handle it?

**Comment by karim** [comment]
> Any idea how other Windows programs supporting <kbd>Alt</kbd>+<kbd>some number</kbd> combinations handle it?

I have no idea, but I guess the operating system handles that automatically. [This link](https://en.wikipedia.org/wiki/Alt_code) might provide some info.

**Comment by mgrojo** [comment]
> Heh Heh Heh
> 
> Good catch. Any idea how other Windows programs supporting Alt+some number combinations handle it?

One way would be to bind *only* the regular number keys and not keypad numbers, but I took a look to QKeySequence and made some tests without success. Both keys go together.

In Linux, this method works both for Qt input fields and Scintilla:
> Type Ctrl+⇧ Shift+U, then type up to eight hexadecimal digits corresponding to the character to be inserted, and then type ↵ Enter.

I have tested under wine and it also works, but I guess it was some wine feature, and in Windows might not work. Someone can confirm?

**Comment by mgrojo** [comment]
@AAverin, after so many years, we replaced those shortcuts by general Alt+(underlined letter) accelerator. The next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds) will replace the Alt+Number shortcuts with the following:

- Alt+D Database Structure
- Alt+B Browse Data
- Alt+R Edit Pragmas
- Alt+X Execute SQL

If you are still interested, could you confirm that the insertion of special characters is working now on Windows? I've only tested under Linux, where that functionality isn't available.
