### ISSUE TITLE
Save attached DB info in project file

### ISSUE THREAD

**Issue by n-arakawa** [sqlitebrowser/sqlitebrowser#1532]
Describe the new feature
--------------------------

It' tedious to attach DB and assign name over and over!

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by justinclift** [comment]
Good idea @n-arakawa. :smile:

**Comment by MKleusberg** [comment]
I agree, this is especially a good idea since we already save all the other aspects regarding attached databases (like view and table settings) to the project file. It's just the path and name which are missing. So I have just added the required bits :smile: Can you check tomorrow's nightly build and re-save your project file after attaching the database(s), then load it again to see if it's working as expected now, @n-arakawa?

**Comment by mgrojo** [comment]
So easy :smile: I took a look and thought how to do it using our API but didn't find a way. Using the SQLite is straightforward, I see now. :+1:

**Comment by MKleusberg** [comment]
Haha :smile: I was thinking that we should maybe add an equivalent for ```querySingeValueFromDb()``` someday to query multiple rows. That would offer a cleaner and more obvious API for cases like this one.

**Comment by mgrojo** [comment]
Yes, I meant something in our classes for getting the attached database, but you are right too.

**Comment by n-arakawa** [comment]
Fine!
It's OK with commit b6d436db63e4afb983fa8a0fbf20faa3c72ed657.
Thank you all for efforts.

tested on Ubuntu 1804
Version 3.10.99 (Sep 29 2018)
Qt Version 5.9.5
SQLCipher Version 3.4.1 (based on SQLite 3.15.2)

**Comment by justinclift** [comment]
Excellent.  Good work everyone! :smile:
