### ISSUE TITLE
Will not minimize

### ISSUE THREAD

**Issue by jzbailey** [sqlitebrowser/sqlitebrowser#1602]
### Details for the issue

 I am running DB4S 3.10.1    It will not minimize.  It flashes and then restores to open on desktop.
I just upgraded from DB4S 3.9 and it did the same thing.  I like to minimize it to see the python program that I am working on.    Thanks

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x ] Linux: ( _distro:_ debian___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.11.0-alpha*
- [x ] 3.10.1
- [ ] Other: ___

#### I have also:

- [ ] Tried out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh, yesh.  This was a bug we fixed a while ago (in October
2017), but we haven't yet had a new full release since then.
(we're working on that now, but it'll take a while)

If you're able to try any nightly build created since then,
that bug won't be present.  We do have nightly builds for
Ubuntu, though I don't remember ifhey work for Debian too:

   https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds-1

Alternatively, if you're ok to compile DB4S from source code,
that should also fix the problem.

Does that help? :smile:

**Comment by justinclift** [comment]
For reference, the main bug report with the fix details in it seems to 
be:

   https://github.com/sqlitebrowser/sqlitebrowser/issues/934

**Comment by chrisjlocke** [comment]
@jzbailey - How ya getting on?

**Comment by chrisjlocke** [comment]
I'll close this as there hasn't been a response, and this issue has been fixed in a newer release.
@jzbailey - feel free to reopen or comment further if you have further issues regarding this.
