### ISSUE TITLE
key shortcuts in SQL editor don't work in german translation in nightly

### ISSUE THREAD

**Issue by mdro** [sqlitebrowser/sqlitebrowser#1613]
Details for the issue
--------------------

#### What did you do?
Used german translation.
Pressed Ctrl+F/Ctrl+H in the SQL editor

#### What did you expect to see?
The search dialog/replace dialog opens

#### What did you see instead?
Nothing happens

#### Hypothesis
The toolips for the buttons have translated shortcuts ("Strg + F"). In the french and spanish versions the shortcuts are identical to the english versions ("ctrl + F") and it works. Are those strings parsed by Qt to set the shortcut keys?

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ Win 10 1804 )

#### What is your DB4S version?
- [x] Other: Nightly 2018-11-12

#### Did you also
- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by SilvioGrosso** [comment]
I confirm this issue on my computer as well (Windows 10 - 64 bit): nightly build tested (12th november)
The Ctr+F shortcut works with the English language in the Settings (GUIs) but not with the German one.

There are other problems with shortcuts though.
At present,  with the English language on Windows 10 (64 bit) I can not use all shortcuts to activate your sql code (F5, CTR+Enter, CTR+R) in the Execute SQL tab. Even the buttons do not work!

See my today's comment in this closed previous bug report:
https://github.com/sqlitebrowser/sqlitebrowser/issues/1491

**Comment by mgrojo** [comment]
As I discovered through the Spanish translation (636136a775f9480ec49e1cec3cae583aecde2e2e), Qt either accepts the original English key names or expects a official translation for the language. You can know the official translations for keys looking at standard contextual menu options (options provided by Qt and not us, like the contextual menu of the Text mode of the editor cell dock). The official translation for Ctrl is Strg (Steuerung) and this is the one used in the German translations, so this shouldn't be a problem. The tooltips aren't important (in fact they are problematic because they are just text, see #1539) but the shortcuts defined in code are provided for translation because each language could have it's own mnemonics (this is something a bit controversial, because then users cannot easily switch between languages in applications; but Microsoft does it a lot). 

So, the translation is correct, although it is not actually changing the keys, so these kind of translations could be left empty and nothing should actually change:

```xml
    <message>
        <location filename="../ExtendedScintilla.cpp" line="58"/>
        <location filename="../ExtendedScintilla.cpp" line="232"/>
        <source>Ctrl+H</source>
        <translation>Strg+H</translation>
    </message>
    <message>
        <location filename="../ExtendedScintilla.cpp" line="61"/>
        <location filename="../ExtendedScintilla.cpp" line="236"/>
        <source>Ctrl+P</source>
        <translation>Strg+P</translation>
    </message>
```

In fact I don't reproduce your problem under Linux. My guess: this is related to https://github.com/sqlitebrowser/sqlitebrowser/issues/1567#issuecomment-439039333 If the standard buttons are not translated because something is missing in the Windows build, it might also affect how the translation for shortcuts is interpreted and Strg won't work.

**Comment by mdro** [comment]
Yes, it works now.

**Comment by SilvioGrosso** [comment]
Hello  @karim 

Yes. I confirm it works on Windows 10 (64 bit)
Tested the shortcus: CTR+F and CTR+H (German language for the GUIs).
Tested with: DB.Browser.for.SQLite-win64

Strangely enough, for the first time ever, I have been asked to restart my computer (Windows 10).
This has never occurred in the past and, naturally, I don't know whether this has something to do with your change :-) 

I am asking this question because I am used to make my installations portable later on. 
In short, I always copy the folder where Db Browser for Sqlite is installed ("C:\Program Files\DB Browser for SQLite\") and then I paste this same folder into a *different* computer, through a USB stick, where I don't have any Internet connections.  I hope this new installer does not do any harm to my "portable workflow" :-)
With yestarday's nightlies NO restart was needed (only today I have been asked to do so).

Here is the screenshot with the window related to the restart:

<img width="282" alt="reboot" src="https://user-images.githubusercontent.com/33007383/49034812-40004680-f1b3-11e8-817d-5498aaecc2b5.png">

**Comment by karim** [comment]
@SilvioGrosso Thanks for testing this. :smile: 

> Strangely enough, for the first time ever, I have been asked to restart my computer (Windows 10).
> This has never occurred in the past and, naturally, I don't know whether this has something to do with your change :-)

I'm sure it is not because of my changes. :smile: 

All I did was adding some *.qm files. You will now see a new **translations** folder in this new version. This should make the shortcuts work properly when using a localized language.

The reason you were asked to restart your computer could be related to a pending update on some system files. Our MSI installer includes [Visual C++ Redistributable](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) that must be installed as well. During installation, if your computer has them then they are skipped, if not they are installed. Sometimes some of these files need to be replaced and this is not possible without restarting. The installer handle that automatically for us and we have no control over it.

Please note that we recently updated our build system and compiler from Visual Studio 2013 to Visual Studio 2017, which requires newer version of Visual C++ Redistributable. If the older version you had was from [22/11](https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-2018-11-22-win64.msi) or older (Visual Studio 2013) and tried to install any version after this one you might be asked to restart your computer since newer versions ([24/11](https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-2018-11-24-win64.msi) and [newer](https://nightlies.sqlitebrowser.org/latest/)) are built using Visual Studio 2017.

> In short, I always copy the folder where Db Browser for Sqlite is installed ("C:\Program Files\DB Browser for SQLite") and then I paste this same folder into a _different_ computer, through a USB stick, where I don't have any Internet connections.

We noticed that this a common workflow for some users so we updated our wiki with some instructions to [extract the contents of the installer](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Extracting-installer-contents). You don't need to install first, copy, and uninstall anymore to make it portable.

**Comment by justinclift** [comment]
Hmmm, with the portable workflow, it sounds like some people will need an updated version of the Visual C++ Redistributable.  Using extracted contents of the installer probably won't provide that, so not sure what we should do.

I guess we can point people at the MS download page here, which seems like the right kind of thing:

* https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Hopefully that helps somewhat. :smile:

**Comment by karim** [comment]
> Hmmm, with the portable workflow, it sounds like some people will need an updated version of the Visual C++ Redistributable.

If they have it installed already, or a newer/updated version, then they will not need to re-install it. The old installer was always installing it even you have have it already.

> Using extracted contents of the installer probably won't provide that, so not sure what we should do.

All the files from the Visual C++ Redistributable are also extracted, but in a different folder (System64). If you have Visual C++ Redistributable installed then you don't need this folder. If it is not installed then just move the contents from this folder to "DB Browser for SQLite" folder. This is mentioned in the wiki I think.

I believe this is what some apps are doing (like Firefox), installing Visual C++ Redistributable in the app folder instead of the system folder. Microsoft does not recommend this though because now the app has to manage updates for Visual C++ Redistributable.

I think we discussed this before. We could also create a .zip file from the .msi after creating it and upload it with the nightlies, and save some users from doing this manually.

**Comment by justinclift** [comment]
Ahhh yeah, that does sound familiar. :smile:

**Comment by justinclift** [comment]
Good point.  We should continue the .zip file discussion in #1630 instead. :smile:
