### ISSUE TITLE
Unique constraint failed

### ISSUE THREAD

**Issue by dgrl** [sqlitebrowser/sqlitebrowser#1620]
What is your question
-----------------------

Hi

I have 2 sqlite files
1 with extension *.pspc and 1 with *.pcat
The later one is a catalogus and the first 1 is a spec (used in Plant 3D AutoDesk)
one of the features is that you can extract a catalogus from a spec.
After doing this you need to repair 1 of the colums called 'SizeRecordID'
In the spec file there are a few lines 'sharing' the same SizeRecordID
When i copy these 2 and paste them in the catalogus sizerecordid column i get a error saying

Error changing data:
UNIQUE constraint failed: EngineeringsItems.SizeRecordId

Is there a setting that the program can be overruled and still save this?
In the first file there are multiple lines containing same recordid and i need to match that in the later file

Or if this is a feature please try to implement this

Many thanks in advance
Kind regards

**Comment by chrisjlocke** [comment]
In the catalogue database, the engineeringItems.sizeRecordId column must be unique - a number can only appear once in each row.  In the spec file, you can have duplicate sizeRecordId records.
This is called a 'one to many' relationship - many records in one table point to one record in another table.  Think of the catalogue table as an 'index'.  So you can't have (for example) two records having sizeRecordId numbers of 5, as the database won't know which one to use.
So, either delete the old records before pasting the new records, or (better) renumber the old engineeringItems.sizeRecordId fields before pasting the new records (ie, change the old number to an unused number, eg, 555 instead of 5)

Obviously this is just an educated guess, as I'm not familiar with your database layout, but that's what the error is saying - "you can't have duplicate sizeRecordId fields in this table".

So, this is an 'error' (of sorts) with your database/data, not with the application itself.  We'll try and help where we can, but as we don't know the layout of your data, we're blundering around in the dark a bit .... ensure you've backups of any databases before making drastic amendments!

**Comment by chrisjlocke** [comment]
As this wasn't an issue with DB4S and you've solved the issue yourself, I'll close this.  Feel free to reply back or reopen it if you feel its closed in error.

**Comment by dgrl** [comment]
No it is ok 
It is indeed not an issue with DB4S 
Thanks for the fast help 
KUDOS for you
