### ISSUE TITLE
Does db browser for sqlite log to a file

### ISSUE THREAD

**Issue by rychlym** [sqlitebrowser/sqlitebrowser#1629]
Hello!
Does sqllitebrowser log (user or app) to a file on disk? In case yes, please where is the location of the log file (on Windows/ linux)?

**Comment by justinclift** [comment]
Hmmm, there are a few different types of log that might be useful, depending on what you're needing. :smile:

In the application itself there's a "Log" window, which shows the SQL statements that have been run so far in the session.  You can toggle that on/off through the View menu, and there are some options in there for what to display.  Should be fairly easy to figure them out. Hopefully. :wink:

With databases (as a general concept) they often have a "Log file" which is a bit different than the above thing.  A log file for databases records changes that have been made since things were last saved to disk, and is used as a crash recovery/failsafe thing in case something goes wrong.  These types of log files generally aren't human readable.  (full of binary characters)

If you're after this second type - the failsafe thing - for us we generally automatically save it to disk using the same folder and filename as the database you open, but with something like `-journal` on the end of the filename.  It's been a while, so I'm not sure of the exact string added to the end.  It's should be fairly obvious though when you look at your database file and see another one right next to it with a slightly changed name.

Does that help? :smile:

**Comment by rychlym** [comment]
Thanks for quite comprehensive answer even I see I didn't specified the question so precisely. I was more about the first type. My problem was that I executed some copy/paste sql statements from a different text source wich I accidently lost :( . So I was curious whether i could find those session performed sql statements next day?

**Comment by pvm341** [comment]
Why after a crash which I find happens quite often is there not an option to read the journal file to restore to just before crash status?

**Comment by justinclift** [comment]
@pvm341 Would you be ok to make a new issue for this question?

It helps if/when we need to point at the question later, as if there are multiple people asking questions in a single issue it just leads to confusion. :smile:

**Comment by justinclift** [comment]
Also, which version are you using?  In theory it's not supposed to crash (ever).  Obviously that theory isn't holding water though. :wink:

If you're using our most recent release, figuring out why it's crashing too is probably a good thing. :smile:
