### ISSUE TITLE
Error displaying Cyrillic (Russian characters)

### ISSUE THREAD

**Issue by torerobo** [sqlitebrowser/sqlitebrowser#1631]
Hi! Instead of ru, a doodle is displayed
report
When opening any .db. Instead of ru displayed doodles.
![1](https://user-images.githubusercontent.com/35532898/49138020-23712500-f2ff-11e8-86f2-467cc3be1876.png)

**Comment by justinclift** [comment]
Thanks @torerobo.  That does look like a bug.

As a thought, would you be ok to try a more recent version?  The version you are using (3.10.1) is over a year old now, and we've improved a lot of things since then. :smile:

Just yesterday we released our first beta for the next major release (3.11.01, which would be good to try.

Which Operating System are you using?  Is it a Linux distro of some sort? :smile:

**Comment by torerobo** [comment]
I understand your desire for me to test the new version of the software. But the problem with the Cyrillic alphabet has been around for a long time. Do not you know? (Google writes that the problem is to quit, he cannot read the Cyrillic alphabet).

Output added Cyrillic support to new software or not?

If I copy these curved characters in librewrite, then in it they open normally (in py / cyrillic).

**Comment by justinclift** [comment]
Well, it looks like the right hand side of that hex view should be displaying things in unicode, which should **in theory** (as far as I understand) show Cyrillic characters correctly.

But, it obviously isn't. :frowning:

We have done a lot of improvements since the last release (more than a year ago), including improving our support for many languages.

If you're ok with compiling a newer version (maybe our `master` branch?), that would let us check if the bug has been fixed already, or if it's still present in our source code and still needs fixing.

**Comment by justinclift** [comment]
Ouch.  Those PPA's should work.  Let's ask @deepsidhu1313 (the owner of them) to double check things. :smile:

As a thought, the "sudo: unable to resolve host Https: Invalid argument" in your quote above looks weird.  That shouldn't happen either, and can be a sign of a bad cut-n-paste.  Might be worth double checking that bit too. :smile:

**Comment by FriedrichFroebel** [comment]
It seems like there are some dependency problems of the packages needed for building from source. This might be caused by the fact that you are using the beta version of Ubuntu 19.04. The `sqlitebrowser-testing` PPA seems to have a version built 10 days ago for Ubuntu Disco: https://launchpad.net/~linuxgndu/+archive/ubuntu/sqlitebrowser-testing?field.series_filter=disco

**Comment by MKleusberg** [comment]
The hex editor isn't meant to display the correct characters. It does so 'by accident' when where talking about ASCII encoding and/or the ASCII part of some other encodings but it's not going to work for any multi-byte characters. So if a character takes up two bytes, the hex editor will show you both bytes but not the single character they represent - that's just what its job is.

In the text view however, you should see the correct characters. Does that work for you? If not or if you're in doubt about whether it's working correctly there, can you maybe upload a copy of your database or send it to us by mail? It's totally okay, to delete everything from it except for a single problematic field in order to protect your data - you'll need to vacuum your database though to do that (after deleting the data, use the 'Compact Database' menu item).

**Comment by torerobo** [comment]
All .db databases are databases from Android applications (ru).

If I copy the crooks into a notebook-error. If I copy scribbles in librewrite (office), Cyrillic opens correctly (Russian characters are displayed correctly).

I meet on the Internet everywhere that there is a problem with the display of the Cyrillic alphabet in sqlite. Do I understand correctly that the updated software will not help me (in Russia it has no value).

**Comment by MKleusberg** [comment]
It all depends on the encoding. SQLite and DB4S can handle UTF-8 (probably the most common encoding) perfectly fine. If you're using another encoding, the data becomes more intransparent to the software.
Can you provide a test database? We might be able to figure out the encoding and see what we can do about it. I'm sure it can be made to work since we have quite a few users using Cyrillic or even Chinese characters :smile:

**Comment by torerobo** [comment]
is a change of the coding this change of the coding in .db? It turns out all the bases (android) do not fit ...
I can’t send private data there, but I don’t know how to modify it safely.

**Comment by torerobo** [comment]
I tried.
ctrl + c copies and hex (do you need it? or export data that is read in librewrite?)
I noticed that librewrite is stalling on many messages, too: either part decodes, or completely out.

**Comment by mgrojo** [comment]
@torerobo If provinding a reduced DB isn't possible, you can use the Export button in the cell editor to save the content as is (binary file) and as a hex dump. Then you can attach these files to this issue.

**Comment by torerobo** [comment]
I attach the exported data (file 111.zip). Screenshot of opening file 111
[111.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/2632358/111.zip)
![2](https://user-images.githubusercontent.com/35532898/49273701-e9cb2600-f486-11e8-843d-47b20bc237ff.png)

 in libre write 2.png

**Comment by justinclift** [comment]
Oh.  Is there any chance the window pane on the right hand side is in the wrong mode?  eg it should be in text mode, but is instead in hexedit mode?

@MKleusberg mentioned above that hexedit mode displays each individual byte seperately (eg not as unicode).  But switching the display to text mode would fix that.

**Comment by deepsidhu1313** [comment]
My apologies guys, i didn't check my email from last few days. I was about
to look into that issue this weekend, as i am aware that there are some
dependency problems with latest versions of ubuntu. @justinclift can you
please take a look into the (log)[
https://launchpadlibrarian.net/398088850/buildlog_ubuntu-disco-amd64.sqlitebrowser_3.10.100ubuntu1-0~2206~201811181631~ubuntu19.04.1_BUILDING.txt.gz]
to see if there is code compatibility issue. I will also try to fix the
problem within next two days.

**Comment by torerobo** [comment]
> But switching the display to text mode would fix that.
No! variable "blob" panel is correct. Text panel or images do not open data!

**Comment by mgrojo** [comment]
@torerobo 
I can reproduce the same output as you. This is working as we expect from the design point of view. The column "data" contains binary data with some embedded UTF-8 strings. The problem with this is that we don't show it in the text view, because we detect it isn't pure UTF-8 text. Then we switch to the binary mode, and all that we can show there are the individual byte values in hexadecimal (left) and an "ASCII" dump (right). The "ASCII" dump is interpreting the individual bytes as characters in ISO-8859-1 (Latin-1) which is one of the US-ASCII (7 bits) supersets. Only the characters in the basic US-ASCII subset are the same as your original text (basic latin script, no accented characters like 'áüñ') because they are also a subset of UTF-8. In your data, you can see these snippets: ")fk", "1=400", "1=3601", etc. But Cyrillic text in UTF-8 is encoded using two bytes, instead of one, and consequently cannot be interpreted by the binary view "ASCII" panel who just knows about bytes (and uses a particular 8-bit encoding for displaying them as characters; since it is binary data, that interpretation may or may not make sense).

If the data would be pure text in any encoding, we could choose a different encoding using the contextual menu in the column header for setting the appropriate encoding, but since it contains valid UTF-8 parts and other parts invalid as UTF-8, we cannot use any of our approaches. Hope this helps you.

**Comment by torerobo** [comment]
About this, I wrote that all the databases of Android applications "bobl" does not display the Cyrillic alphabet, and displays the Latin alphabet without problems. This is a global digital divide. Unable to connect any plugin to sqlite? to solve this problem?
