### ISSUE TITLE
Installs for DB Browser (NOT SQLCipher)

### ISSUE THREAD

**Issue by mtissington** [sqlitebrowser/sqlitebrowser#1645]
The DB Browser version not using SQLCipher is shipping with sqlcipher.dll and NO sqlite3.dll.
Following this comment https://github.com/sqlitebrowser/sqlitebrowser/issues/1642#issuecomment-444158192 I assume this is a bug.

I notice this has been happening for sometime.

**Comment by chrisjlocke** [comment]
Are you referring to the nightlies or the alpha/beta release?
I've just downloaded the nightly which has extracted fine.

![image](https://user-images.githubusercontent.com/7872218/49576875-1aef9e80-f93e-11e8-83c4-68231e0a89ed.png)

I've downloaded the ZIP which actually has *more* files than the MSI.

If you're extracting the MSI, delete the destination directory first.  If you're installing from the MSI, try another location (just to test and confirm).

If you can detail the steps you're taking rather than me try to guess, then I can try and replicate it here.  From my initial bumbling around, all seems OK.

**Comment by chrisjlocke** [comment]
Aah, you mean the 32 bit download...

![image](https://user-images.githubusercontent.com/7872218/49577531-7cfcd380-f93f-11e8-9ff0-2a805096ed1d.png)

**Comment by mtissington** [comment]
I was just installing the nightly x64 - While sqlite3.dll is present, DB Browser for SQLite.exe seems to be using sqlcipher.dll - but I'll do a clean install and check again.

**Comment by chrisjlocke** [comment]
What brought you to conclude DB4S was using sqlcipher.dll?

**Comment by mtissington** [comment]
I think the msi update process might not be updating newer files correctly. Up until the new version beta I was installing 3.11 (?) and none sqlcipher version and it would give me sqlcipher.dll .. I've done a full uninstall/install just now with the latest build and it seems to be ok now.

(feel free to close the issue)

**Comment by justinclift** [comment]
As a thought, what was that utility we were pointing people at a while back @chrisjlocke?  The one which shows the .dll's in use by a program.  We were using it when trying to figure out if wrong 32-vs-64-bit dll's were being picked up.

That should be able to show what's getting loaded in a definitive way. :smile:

**Comment by justinclift** [comment]
Ahhh, no worries. :smile:

**Comment by mtissington** [comment]
dependency walker is not very realiable any more.
Doesn't sysinternals have something?

**Comment by chrisjlocke** [comment]
You're probably thinking of [procmon](https://docs.microsoft.com/nb-no/sysinternals/downloads/procmon).  Someone is rolling their own, too.  [Dependencies](https://github.com/lucasg/Dependencies).  Microsoft also bundle a small utility with Visual Studio, dumpbin.

**Comment by justinclift** [comment]
> Dependency Walker?

Yep, that's the one.  The screenshots on the website match the mental image I was thinking of.

Sounds like there are more options out there now.  Probably good to remember those for future bug tracking too. :smile:
