### ISSUE TITLE
About 

### ISSUE THREAD

**Issue by silviulaurentiu** [sqlitebrowser/sqlitebrowser#1663]
I downloaded:
![image](https://user-images.githubusercontent.com/14875058/50001117-76580700-ffa4-11e8-8c9c-5fdadfcf1870.png)

Is ok to be version 10 yet?
![image](https://user-images.githubusercontent.com/14875058/50000575-a0a8c500-ffa2-11e8-822a-b54e2ce85919.png)

**Comment by justinclift** [comment]
Yeah, the `10` there is ok. :smile:

The numbering of things prior to a main release has to be a bit weird, because we can't use `3.11.`<anything>.

* If we used (for example) `3.11.0`, that would conflict with the main (upcoming) `3.11.0` release.
* If we use `3.11.`<any-higher-number>, that would then be a problem with the automatic version check we do at application start up.  eg For the release version (3.11.0), it would then be checking against 3.11.<any-higher-number>.

So, we're using `3.10` + "high number" for the last number of the string.

Does that make sense? :smile:

**Comment by justinclift** [comment]
Yeah, the `3.11.99` is only used for our current nightly builds.  The code going into those will end up in our 3.12.x release series. :smile:

**Comment by silviulaurentiu** [comment]
Now it is clear :). Many thanks!

**Comment by justinclift** [comment]
No worries. :smile:
