### ISSUE TITLE
BUG: Foreign key constraint deletes data on update

### ISSUE THREAD

**Issue by philmetzger** [sqlitebrowser/sqlitebrowser#1676]
Details for the issue
--------------------

#### What did you do?
I have 2 tables Accounts and Projects. Projects has a foreign key constraint to accounts and a foreign key clause of "ON DELETE CASCADE".

If i then add a new column to Accounts, all data in Projects in deleted.

#### What did you expect to see?
New column added and data remains.

#### What did you see instead?
Projects had all data dropped.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( 10 )

#### What is your DB4S version?

- [x] 3.10.1

**Comment by chrisjlocke** [comment]
What version of DB Browser for SQLite are you using?
What operating system are you using?
This information was (or should have been) in the template when you raised the issue.

When you add a new column, are you adding it to the end, or somewhere in the middle?
I'm guessing that doesn't actually matter.

Because SQLite only supports minor table modifications, when you modify a table (eg, adding a field) we create a new table with the new layout, copy the data across, drop the old table, and rename the new table to the name of the old table.  Dropping the table is causing your issue.

The workaround in the short-term is to remove the 'ON DELETE' clause before table editing.

**Comment by philmetzger** [comment]
Sorry about that, updated the issue with the correct template.

Thanks for the workaround. will use that now.

**Comment by chrisjlocke** [comment]
v3.10.1 is quite old, so I'd suggest using the latest alpha.
https://github.com/sqlitebrowser/sqlitebrowser/releases

From my hazy memory, this has had some foreign key stuff added.  Looking at the log, it has ```PRAGMA defer_foreign_keys = '1'```, which "When the defer_foreign_keys PRAGMA is on, enforcement of all foreign key constraints is delayed until the outermost transaction is committed."
I'm not sure if that would solve the issue though .... worth testing ....

**Comment by mgrojo** [comment]
This seems the same problem reported in #1481. That should be solved in the v3.11.0 beta.

**Comment by mgrojo** [comment]
@philmetzger Please, confirm, so we safely close this issue.
