### ISSUE TITLE
[Projects]Save Project is broken. Does not remember changes or existing filename?

### ISSUE THREAD

**Issue by sky5walk** [sqlitebrowser/sqlitebrowser#1706]
As the title states, <Save Project> should not prompt me every time I want to save my changes.
Please remember the loaded project filepathname.

Worse, if I make changes to the content of 1 of my SQL tab queries and quit, I lose that change. 🤕 
This may be mentioned in another issue?
#### Does this feature exist in another product or project? Please provide a link.
This is standard practice for File-Open/Save. 
If I want Save-As, then I'll choose that.

**Comment by justinclift** [comment]
This is a new behaviour isn't it?

**Comment by chrisjlocke** [comment]
> Worse, if I make changes to the content of 1 of my SQL tab queries and quit, I lose that change. 🤕
> This may be mentioned in another issue?

#1386
That also states that loading project files doesn't load the SQL tabs, so project files are a bit broken at the moment...

**Comment by mgrojo** [comment]
> #1386
That also states that loading project files doesn't load the SQL tabs, so project files are a bit broken at the moment...

That was once true, but it should be fixed now. But what the issue #1386 originally stated is still true: if you open an SQL file, make modifications and then close the application, it doesn't warn you that you should saved the unsaved work and you can lose your progress.

**Comment by mgrojo** [comment]
The project saving issues and SQL file saving issues is one of the parts that I would like to improve in the future. That would include: 
- SQL doesn't get saved or reminded on project exit #1386
- [Projects]Save Project is broken. Does not remember changes or existing filename? #1706
- CTRL-S does not save sql files #871

This is what I think how it should behave:
- SQL tabs should differentiate between: volatile buffers (created using "Add Tab" button) and SQL files (created using the save button in a tab or the open file button).
- When closing the application, it shall warn when there are modified SQL files. Volatile buffers are ignored.
- Volatile buffers could be saved as currently done in the project files (then the volatile adjective is not appropiate any more, so a better name should be found).
- But SQL files content should not be saved in project files as they are now. All the tabs contents are currently saved in the project, but the SQL files should only be linked, just like an IDE project only includes a reference to a source file and not its content. So project files will contain linked SQL files (filename reference) and saved "volatile" SQL buffers (including name and content).
- SQL files and  "volatile" SQL buffers should be visually differenciable. Maybe through an icon in the tab.
- There should be a way to save all the files composing a project, including: project file, database file and opened SQL files. Main toolbar button with shortcut Ctrl+Shift+S.
- The project file shall be remembered and reused when saving (this issue)
- A new "Save Project As" button should be added to the application menu (might not have a shortcut).

I think these changes would address all the referred issues. I appreciate your opinions and comments about this design, specially when the point that would change the current behaviour (open SQL file -> save project -> data is saved in the project [current] vs. only file reference is saved in the project [future]).

**Comment by sky5walk** [comment]
Yes, that is a thorough undertaking.
My request is to remove the hidden volatility of SQL tab edits.
I very often "Add SQL Tab's" and definitely want their contents saved to my project.
I understand if I quit DB4S without creating a project, I will lose them. But, even that should force a prompt to the user to save as project or lose SQL edits.

**Comment by chrisjlocke** [comment]
> That was once true, but it should be fixed now. 

Apologies.  The issue I looked at didn't reflect that, but after testing, you would appear correct.

**Comment by mgrojo** [comment]
> I understand if I quit DB4S without creating a project, I will lose them. But, even that should force a prompt to the user to save as project or lose SQL edits.

Yes, it's definitely better to ask the user to save any unsaved data. But I'm thinking on implementing a new setting for allowing users used to have those volatile tabs to restore the old behaviour. Tabs associated to a file, should always be asked for saving, so that DB4S acts like a standard editor on that regard.

Can anyone help me with the naming? Specifically, I don't know how to call the "tabs which are opened empty by the user, then edited, but never saved to a file".

Ask me about saving changes to non-file SQL tabs`     ` [x] enabled

Other options: unlinked SQL tabs, freestanding SQL tabs, unattached SQL buffers...

I think I'm going to push my progress, because it is already usable and my comment will be more understandable.

**Comment by justinclift** [comment]
The name "SQL tabs" sounds right for them, but yeah... what to call the ones that aren't yet saved to files?  Maybe "new SQL tabs"?  Something like?

- [ ] Prompt to save new SQL tabs when closing?

We obviously wouldn't prompt for stuff that's already saved, so this would already imply "stuff that's changed, but not yet saved".

**Comment by chrisjlocke** [comment]
You could extend this by moving the 'open project' and 'save project' as the main 'open' and 'save' options, rather than 'open database' as is now.  DB4S works with 'projects' which primarily is one database.  If you 'attach' another database, this is remembered in the project too.  Don't know if it is already (haven't used it ... and thus my point above .... )
Just thinking aloud now .... rambling .... need alcohol ...

**Comment by mgrojo** [comment]
@chrisjlocke I'm not sure if I'm following you about the templates. Maybe if you give it a try to the last nightly build, we can compare the behaviours.  I already see some clear differences, for example, I'm not considering (yet) closing a tab as a pending to be saved change. But on other aspects, it is near to what you are proposing.

Not sure about moving the project actions, but with the remembering of the saved project filename and prompting to save new SQL tabs to a new project file, this feature is much less hidden already, and much more usable, I think.

If we also extend the projects so opened SQL files are saved as references in the project file, instead of embedded SQL in the project file, it will be even more useful, because the user would be able to choose between:
- I want a project to keep (embed) a set of useful SQL scripts, versus,
- I want a project for automating the opening and management of my SQL files (that could be files later included or used by an application, for example, and thus it's better to keep them independent).

For the first option, they create new tabs in the application, edit them and then save the project. For the second one, they open a set of SQL files and then save the project. And both models could coexist in the project, so a visual way to discriminate both types of tab would be useful (see the point about that in my [previous comment](https://github.com/sqlitebrowser/sqlitebrowser/issues/1706#issuecomment-452485027)).

**Comment by mgrojo** [comment]
> I agree with chrisjlocke. I see the project file as a container. I don't see the benefit of SQL tabs as pointers to external files? Why do I want to manage another set of SQL files?

No problem. If you don't open the tabs from files, they'll never point to files. If you open a file but want it to save it in the project, open a new tab and copy paste the data, then close the file. This gives more use possibilities to projects, not less.

**Comment by mgrojo** [comment]
>  Does the next nightly have the "save as" feature working?

Yes, the next nightly will have the "Save Project As" and the "Save All" features. It will only save the project file if the user has already saved a project file. Maybe I change that when the SQL file are no longer embedded in the project.

**Comment by chrisjlocke** [comment]
> Making the project file a sqlite db can cause confusion, since DB4S has only shown my target db. If the gui could show the PROJECT_DB as separate from my main db, then maybe ok.

Just because the project is a database doesn't mean it has to have a .db extension. It can remain the filename.db.sqbpro it is now. Or something else...

**Comment by justinclift** [comment]
Well, if we're going to radically change the project file structure again (eg make it a SQLite database), we're best to do it now + backport it for the v3.11.0 release, where it's also getting changed.

We should ping people who actively do stuff with our project files too, just to make sure it's not going to have a negative impact on them / be hard to work with. :wink:

@IVitalii Do you reckon us changing our project file's to be SQLite databases themselves would be ok?

---

@mgrojo On a side note since we're already looking at updating the project file format, how feasible would it be for the paths inside project file to be relative instead of absolute, as per (#1478)?

**Comment by mgrojo** [comment]
> Well, if we're going to radically change the project file structure again (eg make it a SQLite database), we're best to do it now + backport it for the v3.11.0 release, where it's also getting changed.

Well, I'm personally not going to make that change, at least in the near future. It would be a lot of effort and I don't see the practical benefits. The only one might be that we could give an option for embedding the project inside the user database under user request (#612), but even in that cases it would be easier and equally effective to embed and XML string in a table, rather than changing all the reading and writting code for a new pure SQLite format.

> @mgrojo On a side note since we're already looking at updating the project file format, how feasible would it be for the paths inside project file to be relative instead of absolute, as per (#1478)?

I'd like to make that improvement, but not sure how it should behave. When I have some time, I'll propose some possible designs in the issue and we can discuss them.

**Comment by justinclift** [comment]
Yeah, I personally think XML is still the right choice for the project file format too.  At least for now. :smile:

**Comment by sky5walk** [comment]
I would lean toward JSON as a lighter weight format and can be embedded in SQLite databases with json extension. Since it is now adopted within standard SQL 2016, it will eventually not require an extension.

**Comment by justinclift** [comment]
Thanks @sky5walk, that's interesting info.

**Comment by sky5walk** [comment]
I will close this issue now that the nightly prevents loss of Execute SQL edits.

**Comment by sky5walk** [comment]
Sorry, found a new bug with Nightly v190318.
If I open a project with the database unknown or missing, DB4S prompts me to select a new database.
After opening a new database, DB4S does not save or prompt to save this change to the project upon closing DB4S.

**Comment by justinclift** [comment]
Thanks @sky5walk, somehow this didn't shows up in my Notifications.

@mgrojo What do you reckon?

**Comment by mgrojo** [comment]
There is still a lot of possible changes, which are saved into project files, that are not remembered in order to determine if the project file requires saving. In fact, the only modification that is being taken into account is the SQL tabs contents and the number and names of open tabs.

I'm going to see what can be done.

**Comment by mgrojo** [comment]
After my last commit, it should warn when closing about the particular case mentioned and several others.

In general, only switching tables or tabs does not declare the project file modified, but any other change saved in the project, should. But there is still a non-working case, because it'd require more work: changes to the Plot Dock.

@sky5walk could you confirm with tomorrow's nightly build that is working as expected?

**Comment by sky5walk** [comment]
Yes, v190407 catches an newly opened DB in the project on exit.
However, it does not catch the newly opened DB if the project was loaded with errors?

> File is not a database.
> File format invalid.
> 

I edited the sqbpro file to simulate a missing/invalid DB path entry.
`<?xml version="1.0" encoding="UTF-8"?><sqlb_project><db path="C:/myDB/" readonly="0" ...`

**Comment by mgrojo** [comment]
The case where  the application is asking for a new DB file is when the file does not exist. The typical case would be that the file has been moved to another location, so it make sense to ask for the new locatioin. But the case of an existent file that loads as DB with errors does not ask for a new file. This would only happen in real scenarios if the DB file has been corrupted. Should we ask for a new file in that case? That can be done, but I'm not sure about the usefulness in that case. If the user has a backup, they can simply replace the damaged file to restore the project to working conditions.

**Comment by sky5walk** [comment]
Not really. The error case was artificial in that my sqbpro file had a wrong <db path="C:\wrongpath".
Imagine users(myself included) are editing the sqbpro outside of DB4S.
It is more fluid to compile and/or autogenerate the SQL queries in an external editor, then apply them inside DB4S.

SUMMARY: When a user loads a project and no DB was successfully loaded. Any later actions to load a DB should trigger the dirty flag on the project file. You should not allow DB4S to exit without prompt to save.

**Comment by justinclift** [comment]
> When a user loads a project and no DB was successfully loaded. Any later actions to load a DB should trigger the dirty flag on the project file.

Yeah, that makes sense. :smile:

**Comment by mgrojo** [comment]
What I can do is to keep asking the user for a DB file until one works or the user cancels returning to the initial state (no DB nor project file is open). That's because it doesn't make sense to load a project without a defined and loaded DB file.

**Comment by sky5walk** [comment]
That is a possible fix, but anyone could load a project just to edit the SQL queries and close.
And, SQL queries can use ATTACH DATABASE, bypassing the DB4S gui.
The use of DB4S is complex 👿

**Comment by sky5walk** [comment]
Hopefully this issue can be closed with a few tweaks.
The latest nightly, v191111, informs the user explicitly in the window title as to whether they are in a sqbpro file+[currently loaded db] or an unsaved mode with a loaded db.
Great, now I suggest the following to remove lingering confusion and nuisance behavior.

1. Please stop appending stray SQL 1 tabs after loading a db into the project!!
    And when I delete them, I am not prompted to save the project?
2. When I close the loaded db, I am not prompted to save the project.
3. Allow saving projects without a loaded database.
4. Provide some feedback when user clicks on Save Project button.
    It behaves like a NO OP.

**Comment by mgrojo** [comment]
>     1. Please stop appending stray SQL 1 tabs after loading a db into the project!!
Agreed.
>        And when I delete them, I am not prompted to save the project?
Not sure how this should behave. It is not asked if the tab is not modified. If you close a tab that is linked to an SQL file, it is obvious that it has to prompt whether to save the changes to the linked file, when it has been modified; and not prompt when it is untouched. But if we save the project file when an unmodified tab is just closed, if would be saved in a state which is no longer current.

>     2. When I close the loaded db, I am not prompted to save the project.

Haven't you get used to a particular behaviour even if it didn't make much sense? Previously it prompted to save the project, because (in theory) closing the DB also closed the project (although in fact the project file was remembered). I think the current behaviour makes more sense. It only prompts to save when closing the application or opening another project file, that is, when you can lose the changes.

> 
>     3. Allow saving projects without a loaded database.

Ok, it is the natural way to go once we have allowed open project files without DB files, but it could open a can of worms. Not sure if it should go for 3.12.

> 
>     4. Provide some feedback when user clicks on Save Project button.
>        It behaves like a NO OP.

It's easy to show a temporary status message in the status bar, something like: "Project saved to file 'foo.sqbpro'"

**Comment by sky5walk** [comment]
Cool, as of now, the project behavior is awesome.
1. and 4. are good enough for me.
I am ok with dropping 2. and 3.
I already see when I open an sqbpro where the last connected db has moved or does not exist, I am prompted to search.

**Comment by sky5walk** [comment]
Did these changes make it into a recent nightly?
I'd like to close this issue.

> > ```
> > 1. Please stop appending stray SQL 1 tabs after loading a db into the project!!
> > ```
> 
> Agreed.
> > ```
> > 4. Provide some feedback when user clicks on Save Project button.
> >    It behaves like a NO OP.
> > ```
> 
> It's easy to show a temporary status message in the status bar, something like: "Project saved to file 'foo.sqbpro'"

**Comment by mgrojo** [comment]
I've just committed them, and they will be available in tomorrow's nightly.

**Comment by sky5walk** [comment]
Works great! Ok to close this issue.
