### ISSUE TITLE
sqlite query stopped working

### ISSUE THREAD

**Issue by thomasuser** [sqlitebrowser/sqlitebrowser#1730]
Details for the issue
(fresh release DB Browser for SQLite 3.11.0)

sqlite query stopped working:

SELECT m.name as tableName,
       p.name as columnName
FROM sqlite_master m
left outer join pragma_table_info((m.name)) p
     on m.name <> p.name
order by tableName

----
It  used to work in previous releases ,  it does using sqlite3, but does not using sqlitebrowser any more
What is reason for that?
Is it a bug or something else has changed?
One can expect a query working in sqlite3 to be working in sqlitebrowser as well.

Kind Regards
Thomas

--------------------

#### What did you expect to see?
two columns output

#### What did you see instead?
-- At line 1:
SELECT m.name as tableName,
       p.name as columnName
FROM sqlite_master m
left outer join pragma_table_info((m.name)) p
     on m.name <> p.name
order by tableName
-- Result: no such table: pragma_table_info

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ X] Linux: ( _distro: debian )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x ] 3.11.0
- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Uh oh, hopefully this isn't a bug that got through. :wink:

Just to check, how are you executing the query?  Are you selecting the whole thing in the Execute SQL query window first, or are you (for example) having the cursor in a single line somewhere in the query + telling it to execute the current query?

Asking because we've slightly changed how the Execute SQL window does stuff, so the logic of where it detects the end of a SQL query might still need a bit of work.

Also, does it work properly if you add a semi-colon (';') to the end of the query, then try running it?

**Comment by chrisjlocke** [comment]
This query works for me (copy and pasted from your post) but there is an odd quirk somewhere - I know in a recent (ish) issue, me and another user were getting random failings from executed SQL.
If you close DB4S, reopen and try again, does it work?

![image](https://user-images.githubusercontent.com/7872218/52421033-26507900-2aeb-11e9-8a78-8104d6adb88a.png)

**Comment by justinclift** [comment]
> ... getting random failings from executed SQL.

???

That's a pretty serious problem. :frowning:

**Comment by chrisjlocke** [comment]
#1690.  @mtissington had an SQL error which I couldn't replicate, then after some fiddling, I did.  Then he didn't.  The error was 'similar' - an SQL error that didn't make sense (couldn't open database, when it could a moment ago).  Guess it just needs more debugging - the returned error may not be 100% accurate, or a flag isn't get reset, etc.
I use the Execute SQL tabs a lot, albeit with simple queries (not multiple line ones) and don't encounter these sort of issues... *scratches head*

**Comment by justinclift** [comment]
Ok.  Unreliability is extremely serious. :frowning:

**Comment by chrisjlocke** [comment]
I'll try the above query (which seems to be working for me) to see if I can break it.  The error reported by @thomasuser is '-- Result: no such table: pragma_table_info' which is wacky - that's a standard table that should be part of the database? (not that I know much about it... just an assumption)

**Comment by thomasuser** [comment]
The query is executed as all, adding semicolon does not help.
In fact the I have still version build in November 2018  from git , which handle this query as expected. Since then I tried some builds beta , or git but got the same failure there.

**Comment by mgrojo** [comment]
I can reproduce this issue with 3.11.0 (SQLCipher Version 3.4.1, based on SQLite 3.15.2). It works well in 3.10.1 (SQLite 3.21.0). The anomalous query can be simplified to:

`select * from pragma_table_info('someTableName');`

I guess the difference is the SQLite version used and not ours. I cannot get any documentation about the pragma_table_info table. There is the `[pragma table_info](https://www.sqlite.org/pragma.html#pragma_table_info)` but not pragma_table_info as a table (or function returning a table).

@thomasuser What happens if you try with the 3.11.0 without SQLCipher support?
@chrisjlocke What edition are you using (with or with SQLCipher)?

**Comment by chrisjlocke** [comment]
> What edition are you using (with or with SQLCipher)?

The latest non-SQLCipher 3.11.0 build (so not the nightlies...)

**Comment by MKleusberg** [comment]
The ```pragma_table_info(...)``` syntax is indeed valid. [Here](https://www.sqlite.org/pragma.html#pragfunc) is some information on it. There are two interesting notes there:

> * This feature is experimental and is subject to change. Further documentation will become available if and when the table-valued functions for PRAGMAs feature becomes officially supported.
> * The table-valued functions for PRAGMA feature was added in SQLite version 3.16.0 (2017-01-02). Prior versions of SQLite cannot use this feature. 

I can confirm the latter. On my Linux system I have SQLCipher 3.4.1 which is based on SQLite 3.15.2 and doesn't support the ```pragma_xxx``` syntax. When I'm switching to vanilla SQLite which is version 3.26 the query runs just fine.

**Comment by thomasuser** [comment]
Without SQLCipher support it works fine (Version 3.11.0, SQLite Version 3.26.0)



I apologize I should have noticed that myself.

Thank you 
Is it me who is supposed to close the issue?

**Comment by justinclift** [comment]
Either yourself or us, whichever way.  There's no real hard set rule. :smile:
