### ISSUE TITLE
DB.Browser.for.SQLite-3.11.0-win64.msi reporting "Qt5Network.dll was not found" error

### ISSUE THREAD

**Issue by djhenderson** [sqlitebrowser/sqlitebrowser#1743]
Details for the issue
--------------------

#### What did you do?
downloaded DB.Browser.for.SQLite-3.11.0-win64.msi from link in upgrade notification.
used sha256sum to verify the download.
double-clicked to install the .msi (did not ask for the cypher version)
entered admin password when prompted
double-clicked desktop icon for DB.Browser.for.SQLite
rebooted and repeated

#### What did you expect to see?
The application window

#### What did you see instead?
windows dialog saying Qt5Network.dll was not found.

Useful extra information
-------------------------
I upgraded from DB.Browser.for.SQLite-3.11.0-beta3-win64.msi which I installed on Jan 23. It worked and in fact notified me that the new release was available.

I downloaded DB.Browser.for.SQLite-3.11.0-win64.zip, extracted it and executed DB Browser for SQLite.exe and got the application main window.

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [X] Windows: 10 Home version 1809 with latest updates as of 2019-02-13T03:02 -0700
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [X] 3.11.0
- [ ] 3.11.0-alpha1 or 3.11.0-beta*
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [N] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [N] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
I've just downloaded the MSI and extracted it, and the DLL appears ...

![image](https://user-images.githubusercontent.com/7872218/52726661-8479d200-2fab-11e9-9f30-cd6de881abc5.png)

I presume you installed DB4S in the default location (c:\program files) ?
If you open c:\program files\db browser for SQLite, do you see the qt5network.dll file there?  If so, how big is the file?  1.19 MB?

Out of curiosity, if you download the ZIP version (https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.11.0/DB.Browser.for.SQLite-3.11.0-win64.zip) and extract that to a directory (can be anywhere - desktop, my documents, etc) does 'db browser for SQLite.exe' run then?  'theoretically' that should be a 'standalone' version...

**Comment by chrisjlocke** [comment]
> windows dialog saying Qt5Network.dll was not found.

This can sometimes be a red herring if Windows can't **load** the DLL, rather than can't **find** it.  If the beta worked though, this doesn't make much sense....  *scratches head*

**Comment by karim** [comment]
Can you try right-clicking on the .msi file and select Repair then try to run the application again? Repair option will re-install any missing files.

**Comment by djhenderson** [comment]
I have identified the critical path that leads to this error.

1. Uninstall DB.Browser.for.SQLite if required.
2. Install DB.Browser.for.SQLite-3.11.0-beta3-win64.msi
3. Execute successful.
4. Install DB.Browser.for.SQLite-3.11.0-win64.msi
5. Execute fails with "The code execution cannot proceed because Qt5Network.dll wa not found. 
Reinstalling the program may fix this problem."
 
<s>Attached is a screen cap</s> of the windows explorer showing the entire content of the install directory. Big fail here. Well *&^% I can not attach that screen cap. Perhaps you will be able to recreate it. _It might be due to me using Firefox Nightly._

I will try a repair later. I think the critical factor is that I installed 3.11.0 over 3.11.0-beta3.

When I uninstall 3.11.0-beta3 before installing 3.11.0, I get a successful install.

As this issue relates to a beta or nightly release, please close this issue at your discretion.

Thanks for you assistance.

**Comment by karim** [comment]
> I think the critical factor is that I installed 3.11.0 over 3.11.0-beta3.

That's probably it, yes. 3.11.0 uses Qt v5.11.3 and 3.11.0-beta3 uses Qt v5.12.0. MSI saw that you already have higher Qt DLL files (version 5.12.0) so it didn't install them.

Uninstalling the older version and re-installing should fix this as well as selecting Repair option.

Thanks for taking the time to report this. I will close this issue now. Feel free to comment here if you have anything you would like to add.

**Comment by justinclift** [comment]
We should definitely include this info in the release notes. :smile:

**Comment by justinclift** [comment]
The 3.11.0 release notes have been tweaked to mention that 3.11.0-alpha and betas need manual uninstalling first.  There's a **lot** of release notes though, so not sure how much that will really help. :angel:

**Comment by chrisjlocke** [comment]
I've not played with the MSI installer - don't know how 'powerful' it is.  Wonder if it detects a beta was installed, we could display a specific 'please read this' page, or uninstall it.  I'll read up about WiX.

**Comment by chrisjlocke** [comment]
Looks interesting.  Will tinker and experiment....
https://stackoverflow.com/questions/2174357/detect-installed-software-using-wix

**Comment by justinclift** [comment]
Good thinking. :smile:

**Comment by karim** [comment]
> Wonder if it detects a beta was installed

If by beta you mean the same application (same product code) then it is done automatically.

However, our nightly version uses the patch number .99 at the end, which is always higher than stable version, and since MSI does not allow downgrading by default the installation of nightly over stable is blocked.

I don't know if this is what we wanted or not, I simply went with the default behavior.

The relevant part is here..

https://github.com/sqlitebrowser/sqlitebrowser/blob/13a8a1f282b334bbaff15505b38d07122cef574e/installer/windows/product.wxs#L23-L27

`DowngradeErrorMessage` is the custom message we use when this happens.

If this is not what we want and we want to install nightly over stable, then all we need to do is just add `AllowDowngrades=Yes` to `MajorUpgrade` elements. [When set to yes, any version can be installed over any other version](http://wixtoolset.org/documentation/manual/v3/xsd/wix/majorupgrade.html).

**Comment by justinclift** [comment]
> If this is not what we want and we want to install nightly over stable,

Is that supposed to be "we want to install stable over nightly"? :smile:

Thinking it over, we should probably add that `AllowDowngrades="yes"` piece,  It's reasonably common for people to try nightly builds because they need some bug fix or new feature, but when a stable release (with the fix/feature) becomes available, then people want to switch to it.

**Comment by justinclift** [comment]
Just added that to product.wxs (https://github.com/sqlitebrowser/sqlitebrowser/commit/20edf75a566cb21114f5448b87ca6bcd34c2de59).

**Comment by karim** [comment]
> s that supposed to be "we want to install stable over nightly"? :smile:

Yes, true. Sorry. :smiley: 

> Thinking it over, we should probably add that `AllowDowngrades="yes"` piece,

The idea of disallowing downgrades is to stops users from installing 3.11.0 over 3.11.1 for example. If you already have a higher version installed, there is no need to install older version.

Since we use .99 for nightly this created a new situation. If you are using stable then you can upgrade to stable or nightly, but if you already have nightly then going back to stable (for the same minor version) is seen as a downgrade and is not recommended and therefore blocked.

Upgrading from nightly to stable is still possible if, for example, you are using 3.11 nightly (version 3.11.99) and 3.12 is released, because 3.12.0 is higher than 3.11.99.

**Comment by chrisjlocke** [comment]
The recent issue (for me) is that the nightlies are now broken (can't rename tables) so I've gone back to the stable.  So you'll sometimes have the scenario of a user regularly updating v3.11.99 (frequent nightlies), but then downgrading back to 3.11.1 (last stable version), then maybe back to 3.11.99 (nightly fixed) but then back to 3.11.2 (better stable version).
