### ISSUE TITLE
Compatibility with shadow build

### ISSUE THREAD

**Issue by samir-aguiar** [sqlitebrowser/sqlitebrowser#175]
I know that the preferred method for compiling is cmake, but I tried to compile through Qt Creator with qmake and had problems with the libraries because I was using shadow build.
Besides, of course, disabling shadow build, another solution I found was to use the OUT_PWD variable instead of the PWD variable when declaring the libs path. The code looks like this:

```qmake
LIBPATH_QHEXEDIT=$$OUT_PWD/../libs/qhexedit
LIBPATH_ANTLR=$$OUT_PWD/../libs/antlr-2.7.7
LIBPATH_QCUSTOMPLOT=$$OUT_PWD/../libs/qcustomplot-source
```

This variable is equal to PWD when shadow build is disabled and equals to the build directory when it’s enabled, so it should keep the current behavior but add support for shadow build.

Of course, although it worked on OS 10.9.5 with Qt 5.4, I’m not sure whether this variable is always valid in every version. This would require some checking (if empty, if valid, etc.).

Anyway, what are your thoughts about this change?

**Comment by MKleusberg** [comment]
I can see no reason why this shouldn't work on any system. The OUT_PWD variable is a standard qmake feature since a long time. So it really will work on any system and for any Qt version (any version we support anyways). Just to be sure, I tested it on my system and it didn't break anything.

@samir-aguiar Sorry for the late reply but I'd be happy to include this fix in our code. cmake might be the preferred build system but we still try to support qmake as well as we can, so this is definitely welcome! Do you want to open a pull request for this, so you're the author of this fix? If not I can make the commit, too :)

**Comment by samir-aguiar** [comment]
@MKleusberg if everything is good, I've just opened a pull request :)

**Comment by MKleusberg** [comment]
Thanks again for your effort! :+1: I've just merged your pull request. I suggest leaving this issue open for another week or so, just in case this does cause problems for somebody, though I'm pretty confident that won't happen :)
