### ISSUE TITLE
Can't add new record

### ISSUE THREAD

**Issue by SIRprise** [sqlitebrowser/sqlitebrowser#183]
"Error adding new record: near ")":syntax error". I don't know where to search the problem.
Please make a repair function, fix this or show the position of the illegal record. https://dl.dropboxusercontent.com/u/13673400/test.sqlite

After "compact database" the button "write changes" is disabled.

**Comment by Z4us** [comment]
The problem is probably in your schema SQLite does not recognize the types 'BOOL' nor 'DATETIME


sqlite> select * from spieleliste;
Name                                      Hersteller    Genre             F  installiert       Pl  durchgespiel  Sonstiges /   Bewertung   Erscheinungsdatum
----------------------------------------  ------------  ----------------  -  ----------------  --  ------------  ------------  ----------  -----------------
Command & Conquer - Die ersten 10 Jahre   EA / Westwoo  Strategie         O  1                 PC  kA                                                       
Command & Conquer 3                       EA            Strategie         O  1                 PC  kA                                                       
Portal                                                  Knobel / Action   S  0                 PC  kA                                                       
sqlite> 

"installiert" BOOL DEFAULT (0) 
"Erscheinungsdatum" DATETIME

See https://www.sqlite.org/lang_createtable.html#tablecoldef

**Comment by Z4us** [comment]
and https://www.sqlite.org/datatype3.html#affinity

**Comment by rp-** [comment]
there was some kind of small bug in our parsing grammar, because it wasn't really covered in the sqlite3 documentation.
Should be fixed with next nightly build.

c6f585e9c4ca86faf9667339c9102c3a357fd48f

**Comment by MKleusberg** [comment]
Re "After "compact database" the button "write changes" is disabled.":
This is actually supposed to happen. The reason is that SQLite requires us to commit all changes before compacting the database, so this is what SQLiteBrowser does. There's also a warning at the top of the Compact Database dialog telling you about the fact that all changes are going to be written to disk before the database is compacted.

**Comment by SIRprise** [comment]
@rp:
thank you for fixing!

@MKleusberg:
Writing the changes is ok, but if you open a db-file and compress it you need to change anything in db to save the compressed one.

**Comment by justinclift** [comment]
@SIRprise Reading through this again, this confuses me:

```
Writing the changes is ok, but if you open a db-file and compress it you need to
change anything in db to be able to save the compressed one.
```

Do you mean that changes are NOT being saved when the database is compressed?

I just tested it with our latest code, and it **seems** to be saving things when compressing.  Am I not seeing something important? :smile:

**Comment by SIRprise** [comment]
@justinclift The "compact" function seems to have effect if a record between records was deleted. Description of behaviour of 2 Versions before, step by step what I did:
- remove record(s) between other records (in "Browse Data")
- write changes
- press compact
- write-button is greyed out, but at this time nothing was saved and filesize is still large

In Version 3.5.1 DB is written to file immediately. I would prefer to be asked, but issue is fixed. :)

**Comment by justinclift** [comment]
Cool.  :smile:

**Comment by MKleusberg** [comment]
As far as I know there is no way to not automatically save your database after doing a VACUUM in SQLite. https://sqlite.org/lang_vacuum.html says that a VACUUM writes all the data into a new database and then replaces the old one; to me this sounds like there's no way to do this without having it written to disk. So unfortunately there is no way for us to let you save the changes manually. Not sure why you couldn't see any file size changes earlier, though. Our vacuum code hasn't been changed for quite some however - so maybe it was a problem in the bundled SQLite version or just some random coincidence.
