### ISSUE TITLE
Creating foreign keys

### ISSUE THREAD

**Issue by IoTFier** [sqlitebrowser/sqlitebrowser#1852]
What is your question
-----------------------
Hi @justinclift ,

I am new to Sqilite and to Sqlitebrowser.
While I understand that project "Fix foreign keys and constraints problems" is still in the works -
* What is the best way to add foreign keys to the tables designed within Sqlitebrowser?

Thanks

**Comment by scottfurry** [comment]
@IoTFier - see this picture for reference - https://imgur.com/rOsUH60
My understanding and basic gist is you have to have more than one table created (FK referencing a field in another table). Shown in the picture is the Create Table Dialog for sqlitebrowser. Expand this dialog a little wider so that you can see the other options available for that field. Under the "Foreign Key" header, double click the row you want to be a Foreign Key. Details can be entered here.

The resulting SQL Data Definition Language (SQL DDL) for that table should show the constraint.
E.g.   FOREIGN KEY(field name) REFERENCES other_table(other_field_name)

This should all conform to details given in the SQLite Documentation for Foreign Keys shown [here](https://www.sqlite.org/foreignkeys.html).

**Comment by IoTFier** [comment]
@scottfurry - Thank you for your help. Somehow, that column feature wasn't much obvious/.
I will validate few things before closing this issue. Thank you again.

**Comment by scottfurry** [comment]
@IoTFier - confirm can close?

**Comment by IoTFier** [comment]
Hi @scottfurry , for now, please close this issue.
Thank you.
