### ISSUE TITLE
ESC key to exit

### ISSUE THREAD

**Issue by nullpointer20** [sqlitebrowser/sqlitebrowser#1871]
Describe the new feature
--------------------------
I want to exit fast. If there's no change, I think esc key to exit feature is useful.

**Comment by justinclift** [comment]
Are you meaning esc key to close things like the "Create Table" dialog window?

If so, that should already work. :smile:

**Comment by mgrojo** [comment]
For exiting dialogs, ESC should work in every case, if not, then there is a problem that should be solved.

For exiting the application, you can use Ctrl+Q or the standard shortcut in your OS to close any window (usually Alt+F4 and with some keyboards, a specific Close key).

**Comment by justinclift** [comment]
Yeah.  @nullpointer20 We need more information on what you're wanting. :smile:

**Comment by chrisjlocke** [comment]
I don't think the application should exit by pressing <kbd>ESC</kbd>- its certainly not a Windows standard.  I'm also not aware of any dialog that doesn't respond to <kbd>ESC</kbd>.
Closing due to lack of response.  @nullpointer20 - feel free to continue to comment though to provide more information, and if needed, this can be re-opened.
