### ISSUE TITLE
Unable to edit UnitDef in Battletech db.

### ISSUE THREAD

**Issue by dwharper34** [sqlitebrowser/sqlitebrowser#1882]
Details for the issue
--------------------

#### What did you see instead? error: "DB Browser for SQLite" FOREIGN KEY constraint failed
(INSERT INTO "main","UNITDEF"("UnitDefID", "FriendlyName", "IconID", "UnitTypeID", "TagSetID", "Cost", "RequiredToSpawnCompanyTagSetID", "MinAppearanceDate")
VALUES ('1','','',0,'',0,NULL);)

Useful extra information: I also tried adding a new record to UnitDef - 
VALUES ('mechdef_stalker_STK-3P', 'Stalker', 'ulxTxrIcon_stalker', 1, 'Unit.mechdef_stalker_STK-3P', 14347770, 'Unit.mechdef_stalker_STK-3P.RequiredToSpawnCompanyTags', '');

Nothing I tried would allow me to add a new line to UnitDef. I was able to add to UpgradeDef and WeaponDef without any problems, so it seems to be a problem only with UnitDef.

Any help would be appreciated!

![Stalker SQLite Error UNITdEF 001](https://user-images.githubusercontent.com/25343777/57348367-ab5b2680-710a-11e9-84c4-911e94dde7d0.jpg)
![Stalker SQLite Error UNITdEF 002](https://user-images.githubusercontent.com/25343777/57348370-ae561700-710a-11e9-9e0d-627b72b09e94.jpg)
![Stalker SQLite Error UNITdEF 003](https://user-images.githubusercontent.com/25343777/57348373-b0b87100-710a-11e9-83f4-896ab36f120d.jpg)
![Stalker SQLite Error UNITdEF 004](https://user-images.githubusercontent.com/25343777/57348379-b31acb00-710a-11e9-9553-c00f027ab69b.jpg)
![Stalker SQLite Error UNITdEF 005](https://user-images.githubusercontent.com/25343777/57348384-b6ae5200-710a-11e9-915b-556663552e17.jpg)
![Stalker SQLite Error UNITdEF 006](https://user-images.githubusercontent.com/25343777/57348387-b9a94280-710a-11e9-875e-04ab1d814619.jpg)
![Stalker SQLite Error UNITdEF 007](https://user-images.githubusercontent.com/25343777/57348391-bc0b9c80-710a-11e9-8633-6bdba2e80458.jpg)
![Stalker SQLite Error UNITdEF 008](https://user-images.githubusercontent.com/25343777/57348394-bf068d00-710a-11e9-84c8-0df1c7e04771.jpg)

-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 7 SP 1 (6.1) (winnt/6.1.7601) [x86_64]
> using SQLCipher Version 4.1.0 community (based on SQLite 3.27.2)
> and Qt 5.11.3

**Comment by scottfurry** [comment]
Dumb question but it begs to be asked...
You're not adding a data line w/ duplicate key, right?

I have to ask not being familiar w/ the Battletech.db.

**Comment by justinclift** [comment]
@dwharper34 We'll probably need to see the structure definition for the `UnitDef`table, to figure this out.

If you switch to the "Browse Data" tab, you should be able to select that UnitDef table and see its column definitions, including the constaints on them.  There could a "Unique" constraint on the table, which would muck up duplicating records.

That's not the only possibility, but it sounds like that would cause the problem.  So... more info needed. :grinning:

**Comment by chrisjlocke** [comment]
> and tried to duplicate line 68

Just to add to the previous answers.  A database consists of rows (like a spreadsheet) with ID numbers.  One row in one table, will refer to another row in another table.  Take a smaller example.  A phonebook.  Entry 1, "Jim Clark" has a "country_id" of 1.  "Basil Brush" has a "country_id" of 2.  If we look in the "countries" table, that has two entries.  row 1 is "United Kingdom" and row 2 is "Belgium".  Databases work like this so that data isn't duplicated unnecessarily.  So we can work out Jim lives in the UK, and Basil in Belgium.  What you're trying to do is add another country, by duplicating row 2, so that row 3 says "2 - Germany".  The database is 'locked down' so that you can't have 2 rows with the same ID.  If you did, where would Basil live - Belgium or Germany?  That's a conflict.  Some databases (or even tables in the same database) can have relaxed rules and allow these conflicts.  You could have a user with a country_id of 99.  That doesn't point to anywhere.  Some applications don't like this though - they try and find country_id 99, fail and don't know what to display - an empty string?  Issues can be compounded, as it might have to find other data for "country_id = 99" which then fails too.  So you might not be able to enter a new row and give the ID a value of 0, or NULL, or "fred".

There are ways of doing what you need, but its important to know how the database is linked together.  There are also 'internal rules' you may not be aware of.  Back to our phonebook example, the country_id was sequential - 1,2,3, etc.  However, we could use 56,90 and 1463.  In fact, we could state internally, 'if the country ID is greater than 1000, then do this, that and the other'.  So changing ID values could have a big impact in how the program operates.  

Two more questions.  What operating system are you using?  Do you frequently amend this database, or is it just a one-off?  Sorry - and a third question.  You can't be the first person to want to amend this database, so there might be a third party application to do the amending for you.  DB4S is a great tool to amend databases, but its not a user friendly application for this specific database.

**Comment by chrisjlocke** [comment]
> What operating system are you using?

Answered my own question.  Should have looked at the screenshots.  Looks like Windows...
I only ask, as it would be easy to knock up a Windows application geared more towards this database.  

So what happens if you change all the 'cost' values to '1'.  Does the game get insanely easy, as everything now just costs 1 unit?

**Comment by dwharper34** [comment]
@justinclift I will try to send you the information you asked for. I was on the Browse Data tab, but it sounds like for what you want, I should be on the "Database Structure" tab.

![Stalker SQLite Error UNITdEF 009](https://user-images.githubusercontent.com/25343777/57391273-04f73b80-7173-11e9-88a3-534c2c8ad12c.jpg)

@chrisjlocke I was trying to add as new Mech to the game. By duplicating the "mechdef_stalker_STK-3F" line it would allow me to only have to change the 3F to 3P like "mechdef_stalker_STK-3P". I can't add any lines to the UnitDef section and that is the problem. I was able to add to the WeaponDef and UpgradeDef sections for new weapons and upgrades.  

![Stalker SQLite Error UNITdEF 010](https://user-images.githubusercontent.com/25343777/57393078-34a84280-7177-11e9-8a4c-a466a19660cb.jpg)
![Stalker SQLite Error UNITdEF 011](https://user-images.githubusercontent.com/25343777/57393081-37a33300-7177-11e9-97f4-d927bf88382c.jpg)

**Comment by chrisjlocke** [comment]
How big is the database?  How big is it if you ZIP it?  We have dbhub.io, if you want to put it there.... emailing might be easier ;)

What I assume is happening (I'd need to look at the other tables) is that you're putting 'mechdef_stalker_STK-3P' in the tagSetID, but that doesn't exist in another table somewhere.  Again, its like you're setting Basil to be in country_id 78, but you need to add country_id 78 first...

For the avoidance of doubt, the issue isn't with DB4S, but how the database has been 'locked down' to ensure you don't enter in invalid data.  Sure, the error could be sweeter, but its not DB4S's fault.  The poor thing.  Its only trying to help.  *gives it a cuddle*....

**Comment by justinclift** [comment]
> @justinclift I will try to send you the information you asked for. I was on the Browse Data tab, but it sounds like for what you want, I should be on the "Database Structure" tab.

Thanks yeah.  Brain-o on my part.  Really probably shouldn't ask questions here on GitHub when I'm really sleepy. :innocent:

**Comment by dwharper34** [comment]
@chrisjlocke Here is the database with the changes I have made. I felt that if I could edit WeaponDef and UpgradeDef, that I should also be able to edit UnitDef. I like DB Browser and I'm hoping you can show me what I'm doing wrong!

@justinclift I tried to double click on UnitDef and it just expands it. I have uploaded the database though and maybe you can check that out.

[MetadataDatabase.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/3159751/MetadataDatabase.zip)

**Comment by dwharper34** [comment]
I just tried to add my mech again as seen in the screenshot below:

![Stalker SQLite Error UNITdEF 012](https://user-images.githubusercontent.com/25343777/57420645-51676900-71bd-11e9-904b-3a53c38ab86e.jpg)

**Comment by scottfurry** [comment]
@dwharper34 - Okay... I played a little.

One thing that kept cropping up is that DB4S kept telling me that there was a problem with the foreign keys. I did as recommended and executed Menu->Tools->Foreign Key Check. It runs an sqlite pragma statement on the database. Looks like it compacted or otherwise cleaned up some indexing issues.

As for the query... Use this.
```
INSERT INTO "TagSet" ("TagSetID","TagSetTypeID") VALUES("Unit.mechdef_stalker_STK-3P",5);
INSERT INTO "UNITDEF"("UnitDefID", "FriendlyName", "IconID", "UnitTypeID", "TagSetID", "Cost", "RequiredToSpawnCompanyTagSetID", "MinAppearanceDate")
VALUES ('mechdef_stalker_STK-3P',
		'Stalker',
		'ulxTxrIcon_stalker',
		( SELECT UnitTypeID FROM UnitType WHERE Name = "Mech"),
		"Unit.mechdef_stalker_STK-3P",
		14347770,
		'Unit.mechdef_stalker_STK-3P.RequiredToSpawnCompanyTags',
		'');
```
The complaint about FK constraint with column 4 (UnitTypeID). Not sure how a numeric/interger could get confused but it can be "worked around" by using a select sub--query. This left the FK problem w/ TagSetID. It has to exist in the other table before you use it. As result, the first line inserting the value into the TagSet table.

No errors after this, at least for me.

**Comment by dwharper34** [comment]
@scottfurry I followed your directions and was able to add my mech. I don't know how you realized that TagSet needed a value, but that is what was needed! Thanks for your help! I will test it now.

Thanks everyone!

**Comment by scottfurry** [comment]
@dwharper34 - it was a "one after the other" situation. Resolve Column 4(UntiTypeID) causing grief, work around with a sub-query to put in a correct value, Column 5 issue pops up. Makes sense as there are two foreign key constraints on the UnitDef table (Table defintions -> modify table and expand out dialog to see whole definition). Since it was just a string key, Insert and reference.

So, if this works for you, safe to close?

**Comment by dwharper34** [comment]
I played for several hours without any errors or complications, so I'm hoping that it is working right!

Thanks again for every ones help!
