### ISSUE TITLE
[request] Have drag-and-drop test for invalid DB, switch to import

### ISSUE THREAD

**Issue by alexchandel** [sqlitebrowser/sqlitebrowser#1883]
Describe the new feature
--------------------------
Every valid unencrypted SQLite file begins with the byte string `53 51 4c 69 74 65 20 66 6f 72 6d 61 74 20 33 00`.  When a file is drag-and-dropped onto a window, the DB4S should test whether the file appears to be a SQLite database.  If so, proceed down the "Open Database" handler. But if not, DB4S should treat it as a CSV file and pass it to the "Import Table from CSV File..." handler.

## Avoiding misinterpreting encrypted files

At present, DB4S assumes the CSV file is encrypted and opens a decryption prompt.  A simple way to avoid mistreating an encrypted database is to test whether the first 1024 bytes of the file are UTF-8, [for which blindingly fast algorithms exist, completing in < 1µs](https://lemire.me/blog/2018/05/16/validating-utf-8-strings-using-as-little-as-0-7-cycles-per-byte/).  The odds of the first 1k of RC4 or AES being valid UTF-8 are negligible.  If it's UTF-8, import it as a table; if not, assume it's encrypted (or just ask the user).

Additional info
---------------
#### Does this feature exist in another product or project? Please provide a link.

File detection for drag-and-drop is quite common.

**Comment by mgrojo** [comment]
Thanks for the suggestion, @alexchandel. I've opted for asking the user, since it also gives us the possibility of attaching a DB file by dropping it.

If no DB is open, DB4S tries to open the dropped file as formerly. Otherwise, the user is prompted for the action:
- Open Database or Project
- Attach Database...
- Import CSV file(s)...

The change will be in tomorrow's nightly build. Could you give it a try and report back any glitch?

**Comment by MKleusberg** [comment]
Closing this as the issue should be resolved and we haven't heard anything for a long time. If it turns out there's any problem with this, please just re-open this issue any time, @alexchandel :smile:
