### ISSUE TITLE
Freeze one or more columns

### ISSUE THREAD

**Issue by datvm** [sqlitebrowser/sqlitebrowser#1888]
Describe the new feature
--------------------------
For tables with a lot of columns, we may want to freeze one or more columns (for example, name and age) while scrolling horizontally. This is similar to Excel's Freeze Panes feature.

Additional info
---------------
#### Is your feature request related to an issue? Please include the issue number.
No

#### Does this feature exist in another product or project? Please provide a link.
Excel have a feature called [Freeze Pane](https://support.office.com/en-gb/article/freeze-panes-to-lock-rows-and-columns-dab2ffc9-020d-4026-8121-67dd25f2508f) where you can scroll but keep some rows/columns in place.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
![image](https://user-images.githubusercontent.com/6388546/57536334-253f1a00-736e-11e9-87fb-25daa3ffd6d2.png)

Not sure if this is helpful, but for Windows (WinForm) developers, we can use [`DataGridViewColumn.Frozen`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridviewcolumn.frozen?view=netframework-4.8) property to achieve that.

**Comment by SilvioGrosso** [comment]
Yep. This same feature is available for LibreOffice Calc as well.
Quite useful indeed! :-)

**Comment by justinclift** [comment]
Good idea.  This probably would be really useful. :smile:

**Comment by SilvioGrosso** [comment]
Hello everyone,

On top of freezing columns this feature might be further improved by adding the option to freeze the rows.

E.g. take a look at this topic as regards Excel:
https://edu.gcfglobal.org/en/excel2013/freezing-panes-and-view-options/1/

**Comment by SilvioGrosso** [comment]
With LibreOffice Calc there is quick way (button) in the Menu > View, to freeze both the rows and the columns:
https://www.youtube.com/watch?v=e_X5b6FKSno
It is extremely handy. 
The downside of this single command is that it forces you to freeze *also* the rows while usually I freeze only the columns (I often have more than 20-30 columns in my tables) and not also the rows 😄

With Db Browser the first "row", with the names of the underneath columns, is always freezed by default, as opposed to spreadsheets where the first row is not freezed at all. Consequently, you might want to freeze it later on.

**Comment by MKleusberg** [comment]
I have just added this feature. You can enable it by right clicking a column header and clicking "Freeze Columns". It freezes all columns from the first up to the one you clicked. So if you right click the second column, the first two columns are frozen. To disable it just right click any column and uncheck the "Freeze Columns" action.

This was a pain to implement because it can interact with manual and automatic resizing of columns, hiding of columns, toggling the rowid column, the filters, etc. in intricate ways. So can you maybe give the next nightly build some extra thorough testing, @datvm and @SilvioGrosso? :wink:

**Comment by SilvioGrosso** [comment]
Hi Martin,

Just tested this new feature on Windows 10 (64 bit) through the nightly Zip (DB.Browser.for.SQLite-win64)
No crash whasoever so far on Windows 10 and the "freezing" of columns is kept among different sessions of work. When I close my project and I reopen it I mean 👍 

Just for nitpicking since I don't know how difficult would be to implement...
Is is possible to add a visual indicator about this option?
For instance, with LibreOffice Calc there is a vertical bar, in bold, to see where the fixed column 
begins. Needless to say, it disappears when you "unfreeeze" the column..
At present, it is difficult to "remember" where the fixed columns begin because there is no visual clue in the Browse editor 😉

**Comment by datvm** [comment]
Can confirm it works without problem so far for me. Thanks a lot, very useful 👍

**Comment by MKleusberg** [comment]
Sorry for the delay but tomorrow's nightly build should have an extra border between frozen and regular columns. Are you interested in giving that a new try, @SilvioGrosso? :smile:

**Comment by SilvioGrosso** [comment]
Hello Martin,

Just tested on Windows 10. It works great :-)

**Comment by MKleusberg** [comment]
Awesome! Thanks for testing :smile: I'll close this issue then.
