### ISSUE TITLE
Installing sqllitebrowser on windows breaks QT Development

### ISSUE THREAD

**Issue by da3moon** [sqlitebrowser/sqlitebrowser#1890]
Hello and thanks for the tool!

During the install, sqllitebrowser asks for QT creator and other QT software to be closed. I guess sqllitebrowser replaces the default sqldriver dlls of QT. 
Unfortunatly, this also means that after rebooting, all my projects using sqllite stopped working, showing that the sqllite driver could not be loaded.
I guess keeping the DLLs local could help. 

Any hints on how to quickfix are welcome. But I guess I'll just reinstall QT.
Thanks!

Chris

**Comment by justinclift** [comment]
Oh.  That's definitely not supposed to happen! :scream: 

Which installer did you use, and on which OS? :smile:

**Comment by justinclift** [comment]
> I guess sqllitebrowser replaces the default sqldriver dlls of QT.

With this bit, nope.  We don't use the Qt SQL pieces at all.  Instead we include our own SQLite library (on Windows and MacOS), installed in the same spot as the rest of the application.  We load that into our application and query it directly.

No idea how/why (etc) that's affecting other stuff.  It obviously is somehow though. :frowning:

**Comment by da3moon** [comment]
Took me some time to realise why everything broke :-D

I used the following installer "DB.Browser.for.SQLite-3.11.2-win64.msi" and it broke my 5.12.1 Mingw 64 on windows 10.

I thought it was the DLLs because the installer asked me to close the different apps I was using. (My own developed one, and QT): Why would it do that otherwise?

**Comment by justinclift** [comment]
Good question.  The .msi installers are created using the [Wix Toolset](http://wixtoolset.org).  It sounds like they have some detection thing that pops up automatically.

Personally, I didn't know they did this.  Not sure what it's really checking for.

Was it just the Qt applications it listed, or was it for "all open applications"?

**Comment by justinclift** [comment]
Either way, I'd go with uninstalling the .msi as it's breaking things, and try the .zip version of our application.

Major hope there is that whatever the breakage was done by the .msi, hopefully just deinstaling that does actually work. :confused:

**Comment by da3moon** [comment]
I'll do that  and let you know. Thanks for the rapid answer!!

**Comment by scottfurry** [comment]
Looking at the CMakeLists.txt file now...
This looks weird:
```
	if(sqlcipher)
		find_file(SQLITE3_DLL sqlcipher.dll)
	else(sqlcipher)
		find_file(SQLITE3_DLL sqlite3.dll)
	endif(sqlcipher)
```
`else` clause in CMake can usually be left empty. This appears in the Win/MSVC sections a couple of times. Probably muddying the waters with this.

To address SQLite question. My understanding is that Qt distributes SQLite as apart of its install (See https://doc.qt.io/qt-5/qtsql-attribution-sqlite.html). 

I come from the NSIS side of things. I don't know enough about Wix to say definitively what it does. There are a lot of hard-coded paths( `set("C:/...")` ) in the CMakeLists.txt that look innocuous.  However, these paths appear to assume a directory structure to find software rather than looking for it. The `[project root]/installer/windows/variables.wxi` file contains a similar disconcerting assumed structure:
```
    <?if $(sys.BUILDARCH)="x64"?>
        <?define QtPath="C:\dev\Qt\5.11.3\msvc2017_64" ?>
        <?define SQLitePath="C:\dev\SQLite-Win64" ?>
        <?define SQLCipherPath="C:\git_repos\SQLCipher-Win64" ?>
        <?define OpenSSLPath="C:\dev\OpenSSL-Win64" ?>
        <?define SQLiteExePath="C:\builds\release-sqlite-win64\Release" ?>
        <?define SQLCipherExePath="C:\builds\release-sqlcipher-win64\Release" ?>
    <?elseif $(sys.BUILDARCH)="x86"?>
        <?define QtPath="C:\dev\Qt\5.7\msvc2015" ?>
        <?define SQLitePath="C:\dev\SQLite-Win32" ?>
        <?define SQLCipherPath="C:\git_repos\SQLCipher-Win32" ?>
        <?define OpenSSLPath="C:\dev\OpenSSL-Win32" ?>
        <?define SQLiteExePath="C:\builds\release-sqlite-win32\Release" ?>
        <?define SQLCipherExePath="C:\builds\release-sqlcipher-win32\Release" ?>
    <?endif?>
```
Worrisome if DB4S decides to install into a directory that the user previously created. For example, user's workflow is to put work into "C:\dev" - where DB4S installer also wants to put stuff. Maybe the directory layout could be re-thought-out. Install into "C:\Program Files\DB4S\libs..." and append that to  system path variable. My $0.02.

**Comment by justinclift** [comment]
With the windows installer, we use a version of sqlite.dll to handle the non-encrypted stuff, and we use a version of sqlcipher.dll to handle the encrypted bits.  Seems to work ok for the most part. :wink:

The `C:\dev` path is to match our nightly build VM because that's where the installer gets run to create the packages.  Those are the paths used to find the right pieces to assemble into the package. :grinning:

**Comment by scottfurry** [comment]
@justinclift  - And we learn something about the build process like it where it expects things. TIL...

**Comment by justinclift** [comment]
No worries.  It's one of things that's been a slowing accumulating mass of shell scripting over the years.  Imagine a floating ship with barnacles.  At some point, it's probably more barnacle than ship. :smile:

**Comment by justinclift** [comment]
@da3moon How'd you go with this?  Are we ok to close this? :smile:

**Comment by da3moon** [comment]
Alright, sorry for the delay: The installer only wanted to close my QT apps and QT creator, nothing else.  Uninstalling the msi unfortunatly wasn't enough. Reinstalling QT now :-) Ok to close!!

**Comment by justinclift** [comment]
Cool. :smile:

If you do figure out what the installer changed/broke, that'd be a useful data point so we can figure out if it's something we can change. :smile:
