### ISSUE TITLE
Launch SQLite Error (error creating SSL context)

### ISSUE THREAD

**Issue by jcialdella** [sqlitebrowser/sqlitebrowser#1903]
Details for the issue
--------------------

#### What did you do?
double click on SQLite application

#### What did you expect to see?
main screen

#### What did you see instead?
error when connecting to https://download.sqlitebrowser.org/currentrelease
error creating SSL context ()
![SQLite Error](https://user-images.githubusercontent.com/20974114/58058039-f7579380-7b2c-11e9-82c8-e7094b1ceb2e.PNG)

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.17134) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by justinclift** [comment]
Oh.  We've seen this happen very occasionally (#1595), but haven't yet found a way to track down the cause.

One way to stop that error message is to turn off the automatic check for updates when the application starts.  There's a setting for that in the application Preferences (first page).

After the error shows up, does the application open normally?  eg you can go into Preferences to change the setting?

**Comment by chrisjlocke** [comment]
@jcialdella- Are you on wireless?  Are you running the 32bit or 64bit
version of DB4S?  (You've pasted details from the 'about' screen, but I can
never remember from that which is which!)  I believe this issue doesn't
occur on the 32 bit version ... or if you connect via LAN.

>

**Comment by justinclift** [comment]
Good point, it's worth having a go with the 32-bit version as well.  That sometimes fixes weird problems that show up in the 64-bit one. :smile:

**Comment by chrisjlocke** [comment]
@jcialdella ... *cough*

**Comment by jcialdella** [comment]
Wireless - no. 64bit version.

**Comment by chrisjlocke** [comment]
So two reports that this error is now occurring on wired connections, rather than just wireless.
There is a possibility that a wireless connection is *available*, but not active (ie, if I'm on wireless but then plug in a LAN cable, the LAN takes precedence, but the wireless is still on.)  This could be enough to still fail the 'check' or cause the issue that triggers the error?

We're displaying an error at the moment.  Could we not 'detect' this error, then wrap it up in a nicer message saying, "blah blah we're having issues checking for a newer version blah blah" then automatically turn off the version check.  Ideally, it should note down the date and throw up a message in three or six months saying, "you've not got version check running, but we recommend you visit the website to check for a newer version anyway - wanna go to the website now?" thing...

**Comment by justinclift** [comment]
@chrisjlocke That's a good idea.  Seems like some better handling (and maybe logging diags to a file?) would be useful for this case.

We've tried just about everything else we can think of.  Including weird edge case stuff, some of which also worked for some people. :wink:

**Comment by chrisjlocke** [comment]
It seems very 'machine specific' (we've hundreds of DB4S's out there, but not many reports of this*) but handling it better would be 'nicer'.

*Not all errors are reported, I guess.

**Comment by chrisjlocke** [comment]
(See also #1915)

**Comment by mgrojo** [comment]
Can this be closed? It seems that the similar issues already are.

**Comment by jcialdella** [comment]
Presumably so.


Sent from Yahoo Mail for iPad


On Friday, December 4, 2020, 2:43 PM, Manuel <notifications@github.com> wrote:




Can this be closed? It seems that the similar issues already are.
