### ISSUE TITLE
msvcr120.dll is missing

### ISSUE THREAD

**Issue by asia73** [sqlitebrowser/sqlitebrowser#1912]
Details for the issue
--------------------

#### What did you do?
Launched DB Browser (SQLite)

#### What did you expect to see?
A running program

#### What did you see instead?
A warning alert that msvcr120.dll is missing, but it doesn't affect the program functionality.

Useful extra information
-------------------------
> DB4S v3.11.99 (Jun  2 2019) [built for i386-little_endian-ilp32] on Windows 7 SP 1 (winnt/6.1.7601) [i386]
> using SQLite Version 3.28.0
> and Qt 5.7.1

**Comment by justinclift** [comment]
Hmm, that's definitely not supposed to happen. :wink:

Which release download did you grab?

Asking because we saw it with an older version of the PortableApps installer, but it was re-created a few weeks ago with a fix.

Hmmm... is there any chance the installer you're using is the PortableApps one, but not the new (last few weeks) version?

**Comment by asia73** [comment]
I tried both DB.Browser.for.SQLite-3.11.2-win32.msi and DB.Browser.for.SQLite-win32.msi (Nightly 02.06.2019)

**Comment by justinclift** [comment]
Thanks. :smile:

Am trying to think of what might cause the problem.  It's a bit weird, because this 3.11.2 version (not portable) doesn't need `msvcr120.dll`.  So, it **shouldn't** (in theory) be asking for it.

But it obviously is.  :confused:

Did you have a previous version of it installed?  I'm kind of wondering if there's a left over installation of it or something, that needs fully removing first.  That **could** cause this kind of problem.

**Comment by karim** [comment]
@asia73 `msvcr120.dll` is required if the application was compiled with Visual Studio 2013.

We were using this version then upgraded our build system to use Visual Studio 2015 (for 32-bit builds) in this [commit](https://github.com/sqlitebrowser/sqlitebrowser/commit/064514a9198fb386c150523ab032aa6aeb015127). As Justin pointed out, this file shouldn't be required if you are using the latest version.

Did you install the latest version/nightly over an older version (before the above commit date) maybe?

Can you right-click the `.msi` file and select `Repair` and try running the application again? If that didn't help, can you completely uninstall the application and re-install it again?

Also, can you try the `.zip` version and see if you get the same error?

**Comment by asia73** [comment]
I installed the latest version over DB.Browser.for.SQLite-3.11.0-beta3-win32.msi. Then I uninstalled it and installed again. I just tried repairing the installed version, I tried ZIP version as well. Both of them ask for msvcr120.dll But then again, they seem to work without a hitch.

**Comment by chrisjlocke** [comment]
>  I don't need the newer versions actually

It probably solves issues like this, plus a host of other weird issues.
The latest is usually the greatest.

>  I don't mind if you just forget about me

Every user is a precious jewel.  We love everyone that uses our software.
Give us a call and we'll even come round and do your cleaning, weeding your
garden, or taking your dog for a walk.

**Comment by scottfurry** [comment]
> Every user is a precious jewel. We love everyone that uses our software. Give us a call and we'll even come round and do your cleaning, weeding your garden, or taking your dog for a walk.
Dibs on dog walking. You get garden weeding as my knees and back couldn't take it.

**Comment by justinclift** [comment]
> I will reinstall the Beta for now ...

No worries.  That works too. :wink:

This is definitely a weird bug.  Hopefully other people aren't being affected by it too.

I'll close this issue, as you have a ~solution, and we have a tonne of open bug issues already. :smile:
