### ISSUE TITLE
CondFormat code bug.

### ISSUE THREAD

**Issue by kapilpipaliya** [sqlitebrowser/sqlitebrowser#1921]
https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/CondFormat.cpp#L101
I think this lines should be removed, because if `val` is empty it not means `val = value`.
```
if(val.isEmpty())
       val = value;
```

**Comment by mgrojo** [comment]
Thanks for the review. Are you trying to implement some feature or just having a look?

This code is in fact needed. It allows to filter the table using the default LIKE operator and a value with wildcards in any position wanted by the user, otherwise the wildcard is appended and prepended. Nevertheless, the code readability could be improved by moving this assignment to a new "else" part in 
https://github.com/sqlitebrowser/sqlitebrowser/blob/b0bb376880cb4e827e964a3e615218c151691d45/src/CondFormat.cpp#L100

**Comment by MKleusberg** [comment]
Closing this because it looks like the original question is answered and we haven't heard back anything for a long time. If I'm missing anything, please just re-open this issue any time :smile:
