### ISSUE TITLE
CREATE TABLE causes DB file to explode in size

### ISSUE THREAD

**Issue by tridiak** [sqlitebrowser/sqlitebrowser#1927]
Details for the issue
--------------------

#### What did you do?
CREATE TABLE tableE AS SELECT tableA.*, tableB.someColumn, tableB.someColumn2
FROM tableA, tableB.

Execute.

CREATE TABLE tableF AS SELECT from tableE.*, tableZ.columnA, tableZ.columnB
FROM tableE, tableZ

Execute.

App CPU jumps to near 100%.
DB file grows from 659KB to 25+GB.
DB file sized continued to climb when I killed the app.

#### What did you expect to see?
SQL newb.
Did not expect it to take so long and create a 25+GB file.

#### What did you see instead?

Useful extra information
-------------------------

App seemed to spend most of its CPU cycles in the SQLCipher.
Memory usage hovered around 90MB. Never spiked.
[Sample of DB Browser for SQLite.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/3341147/Sample.of.DB.Browser.for.SQLite.txt)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X ] Mac OS: ( _version:10.14.5 )
- [ ] Other: ___

#### What is your DB4S version?

- [X ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [X] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
That sounds like the kind of thing that happens when the query produces a lot more rows than expected. :wink:

Suspecting that might be the case this time too, but not sure.  How many rows are in each of the source tables? :smile:

**Comment by tridiak** [comment]
All tables I am trying to merge have 2219 rows.
Largest table has 59 columns.
Other two have 3 columns.

Table A : 59 columns.
Table B : 3 columns.
Table C : 3 columns.

Merging Table A with Table B to produce Table Z does not increase database much.	

Merging Table Z with newly created Table C to produce Table Y results in a very large database file that doesn’t seem to stop filling.
I kill the app.

Why would first creation be small and second creation be humongous?

I am a SQL noob and teaching myself.

**Comment by chrisjlocke** [comment]
> FROM tableA, tableB

Others might have to correct me, but You need to specify the connecting
rows, otherwise every row from A is connected (whether successful or not)
to every row of table B.

Examples are good, and I can't see your database scheme, so take mine of
countries.

Names
id | name | countryId
1 | Chris | 1
2 | Mark | 3
3 | Justin | 5

Countries
id | country
1 | The fridge
3 | The cupboard under the stairs
5 | The server room in the attic

To connect Chris to the country, we have to tell SQL to connect countryId
to the id of the countries table.

select *
from names
left join countryId on countries.id

if we just tell SQL to connect table A to table B, we get a mega merge.

Running your first SQL to create tableE, you've not specified how, so SQL
has mega merged every row with A with every row of B.

Imagine tableA has 10 rows, tableB has 10 rows.  You don't end up with 20
rows (A+B) but 100 rows (TableA for row 1 in tableB, tableA for row 2 in
tableB, etc)

Imagine doing that again for tableC.  Exponentialville.

Provide us with a schema, and what you're trying to achieve.

If you can provide dummy data, even better.

You've created tableE - when you browse that, does that actually look
correct?

**Comment by tridiak** [comment]
You were right.
Added in a WHERE clause and the table row count reduced to something smaller instead of 49M rows for TableE.
Noob mistake.
Thanks for the help.

How do I close the issue?

Mark

**Comment by justinclift** [comment]
No worries.  We've all been through the learning process, so you're in good company. :smile:

> How do I close the issue?

In theory (!), there should be a "Close issue" button at the bottom near the "Comment" one.  I'm here though now, so can get it done. :wink:
