### ISSUE TITLE
sqlcipher with static extensions

### ISSUE THREAD

**Issue by mtissington** [sqlitebrowser/sqlitebrowser#1932]
I have build my own version of sqlcipher.dll and statically linked some additional extensions.
To register the extensions I'm making a call to `sqlite3_auto_extension`

When I use the dll in our main project I can use the extension in SELECT statements.

I then replace the sqlcipher that ships with DB Browser with mine and the extensions are not recognized (everything else works).
I know `sqlite3_auto_extension` is still correctly being called when the dll is attached to the DB Browser process.

Are you making a call to `sqlite3_reset_auto_extension` that might be removing my extensions?
Any other reason that my extensions might not be available?

Thanks....

**Comment by mgrojo** [comment]
> Are you making a call to `sqlite3_reset_auto_extension` that might be removing my extensions?

No, we only make these calls in relation to extensions:
<pre>src/sqlitedb.cpp<font color="#00AAAA">:</font>2090<font color="#00AAAA">:</font>    <font color="#FF5555"><b>sqlite3_enable_load_extension</b></font>(_db, 1);
src/sqlitedb.cpp<font color="#00AAAA">:</font>2094<font color="#00AAAA">:</font>    int result = <font color="#FF5555"><b>sqlite3_load_extension</b></font>(_db, filePath.toUtf8(), nullptr, &amp;error);
src/sqlitedb.cpp<font color="#00AAAA">:</font>2099<font color="#00AAAA">:</font>        <font color="#FF5555"><b>sqlite3_enable_load_extension</b></font>(_db, 0);
src/sqlitedb.cpp<font color="#00AAAA">:</font>2117<font color="#00AAAA">:</font>    <font color="#FF5555"><b>sqlite3_enable_load_extension(_db, Settings::getValue(&quot;extensions&quot;, &quot;enable_load_extension</b></font>&quot;).toBool());
</pre>

>  Any other reason that my extensions might not be available?

Not that I could think of.

**Comment by karim** [comment]
Maybe try `Edit > Preferences > Extensions` and check *Allow loading extensions from SQL code*.

We disallowed loading extensions from code in this issue #1551. I'm not sure if it is related but worth a try.

**Comment by mtissington** [comment]
@karim I was hopeful - but it make no difference. I'm really puzzled about this. I use process explorer to confirm our sqlcipher.dll is getting loaded, and the call to `sqlite3_auto_extension` is happening when the dll is attached to the db browser process (also tried in thread attach).

**Comment by mtissington** [comment]
Hmm I think I know what the issue is - in `sqlitedb.cpp` it looks like  `DBBrowserDB::open` is making a call to `sqlite3_shutdown` which as far as I can tell will mess with `sqlite3_auto_extension`.

Why is the call to `sqlite3_shutdown` being called?
Is there a work around for this?

**Comment by karim** [comment]
> Why is the call to `sqlite3_shutdown` being called?

This is the commit https://github.com/sqlitebrowser/sqlitebrowser/commit/282387ced75a501c9d2cb87e4de92c2cb221cc0e that introduced it. Can you try the nightly before this commit date (Feb 21) and see if it is working?

**Comment by mtissington** [comment]
I have found an almost satisfactory work around for this - I can use the `load_extension` function

I have a function in my sqlcipher.dll called `sqlite3_sha256_init`.
After opening a database a do the following `SELECT load_extension('sqlcipher.dll', 'sqlite3_sha256_init')`
This does make the call to `sqlite3_sha256_init` but than hangs and I have to abort the sql.
After which I can make calls like `SELECT sha256('abc')` and get back a valid value.

Is this a bug that db browser is hanging?

**Comment by karim** [comment]
I don't think we ever used or tested `load_extension`. It just came to our attention that it could be a security risk so we disabled its usage by default.

As to why it hangs I have no idea. Maybe because it tries to reload `sqlcipher.dll` again which is already loaded? Can you try using the `sqlite.dll` version of the app and then try to load the extension from `sqlcipher.dll`?

I guess you chose to link the extensions statically so they are always available to you without the need to load them every time? Did you test them and they load/work correctly (as loadable extensions) before you linked them statically?

Also, did you try using a different version, before Feb 21, to see if the call to `sqlite3_shutdown` is the one causing problems?

**Comment by mtissington** [comment]
Sorry if I wasn't clear - I did try a build from Feb 20th and the auto extensions stay loaded - It's `sqlite3_shutdown` causing the problem.

I've also tried your suggestion of using the `sqlite.dll` version of the app and loading the extensions from `sqlcipher.dll` and it still hangs.

I've also tried using `load_extension` with fileio.dll and formats.dll extensions that you supply and again it hangs. However, in both cases when I click the red `x` to stop execution, the extensions appear to have loaded...

Seems to me a couple of bugs exist here.

1) stopping or return from `load_extension`
2) use of `sqlite3_shutdown` when opening a database

**Comment by karim** [comment]
> It's `sqlite3_shutdown` causing the problem.

Then we should ping @MKleusberg to see why we need this, and if we can find a workaround.

> I've also tried using `load_extension` with fileio.dll and formats.dll extensions that you supply and again it hangs.

I don't think we do anything special with this function, other than putting it behind a toggle for security reasons. Did you try also with SQLite command-line tool (sqlite3.exe)?

**Comment by mtissington** [comment]
> I don't think we do anything special with this function, other than putting it behind a toggle for security reasons. Did you try also with SQLite command-line tool (sqlite3.exe)?

But surly `SELECT load_extension()` should not hang?

sqlite3.exe works correctly and I can use `load_extension`

My understanding is that there should not be a need to call either `sqlite3_shutdown` or `sqlite3_config` each time a database is opened. The code is calling both.

**Comment by karim** [comment]
Sorry for the late reply, I was trying few things.

> But surly `SELECT load_extension()` should not hang?

Yes, `math.dll` did not hang for me, using the latest nightly.

![1932](https://user-images.githubusercontent.com/8761081/60621768-df875680-9dde-11e9-8aa2-08dc7e899ca9.png)

However, trying to load `fileio.dll` hangs, which is weird.

There is some inconsistency here, so this is definitely a bug, but I'm really out of ideas. :smiley: 

> My understanding is that there should not be a need to call either `sqlite3_shutdown` or `sqlite3_config` each time a database is opened. The code is calling both.

From this link https://www.sqlite.org/c3ref/config.html it seems like you need to call `sqlite3_shutdown` before calling `sqlite3_config`. While this page says calling `sqlite3_config` is not recommended, it seems like it was used to change SQLite configuration when you open a new database.

Is there a better alternative for this? I really don't know. We will have to wait for Martin to answer that.

**Comment by karim** [comment]
@mtissington The reason for calling `sqlite3_config` is to implement error logging in `View > SQL Log` as described here: https://www.sqlite.org/errlog.html.

Enable it and check the error log when dealing with extensions. It should show an error that might help us.

**Comment by mtissington** [comment]
@karim Here is the output from the log - wondering why the LIMIT?

`SAVEPOINT "RESTOREPOINT";
SELECT COUNT(*) FROM (select load_extension('sqlcipher.dll', 'sqlite3_sha256_init'));
select load_extension('sqlcipher.dll', 'sqlite3_sha256_init') LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";`

It hangs prior to the ROLLBACK - when I need to cancel the script.

My understand of `sqlite3_config` is that it should be called once when the sqlite lib is first loaded, not every time a database is opened - calling `sqliite3_shutdown` and `sqlite3_config` seems like taking a sledge hammer to crack a nut 😉

**Comment by karim** [comment]
> wondering why the LIMIT?

I think it is appended to every query the application executes, in case the query returned millions of rows.

> My understand of `sqlite3_config` is that it should be called once when the sqlite lib is first loaded, not every time a database is opened

Yes, I think so too.

**Comment by MKleusberg** [comment]
> > My understand of `sqlite3_config` is that it should be called once when the sqlite lib is first loaded, not every time a database is opened
> 
> Yes, I think so too.

I completely agree :+1: In the last commit I have changed the code to call ```sqlite3_config``` only once and completely get rid of ```sqlite3_shutdown```. Can you check if it's working again with the next nightly build, @mtissington :smile:

**Comment by mtissington** [comment]
@MKleusberg - thanks - will let you know. But then there is the remaining issue of it hanging too ...

**Comment by mtissington** [comment]
@MKleusberg I can confirm the build from 6th July fixes the issue with `sqlite3_auto_extension` 😄

**Comment by MKleusberg** [comment]
Awesome! :smile: Now for the issue of it hanging when loading your extension...

This turned out to be an interesting corner case. If you're interested, here's what's happening:
Because of the ```SELECT COUNT(*) FROM (SELECT load_extension('...'));``` statement, the extension is already loaded when the actual ```SELECT load_extension('...')``` is executed. Additionally, the count statements says there is one row to be fetched (```load_extension()``` always returns NULL) but the second statement won't return any data because it errors out. It turns out that we never expected the results of the two statements to differ like this and that's why DB4S indefinitely waits for the expected row to come in. That's why you could safely abort the query and the extension was still loaded.

In case you wonder why some extensions would work and other would not: The init function of the fileio extension returns an error when it can't register its functions, the math extension doesn't - it always returns a success. And when there's a success, SQLite returns a NULL value as expected, even for the second call to ```load_extension()```. So you were doing it right and implemented proper error checking unlike some other extensions, @mtissington :smile: 

Anyway, it should be working in the next nightly build :wink:

**Comment by MKleusberg** [comment]
Thank you, @karim, by the way :smile: Your debugging efforts really helped me to get started digging into this :+1:

**Comment by karim** [comment]
> If you're interested, here's what's happening

I always love to hear the story of bugs. Because while they seem to be appearing randomly, or to some people only, in some kind of an evil plan to evade detection, they usually have a simple explanation. :smile:  

> In case you wonder why some extensions would work and other would not: The init function of the fileio extension returns an error when it can't register its functions, the math extension doesn't - it always returns a success.

Yesssss. I couldn't figure this out and it was bothering me for a while. Thank you. :smiley: 

But I think there might be another problem here. Can you get `fileio` extension to load using `sqlite3.exe`? Because I can't.

I can load it in DB4S but not SQLite command line tool. I think we might be building it incorrectly.

![fileio2](https://user-images.githubusercontent.com/8761081/60762263-a14a9b00-a05b-11e9-8c35-c97affc29727.png)

**Comment by mtissington** [comment]
@karim did you try loading it with the `SELECT load_extension` format?

**Comment by justinclift** [comment]
Also, we pull the latest version of the code from the SQLite repositories for each run.

Mentioning just in case you're using an older/newer version of it, as a potential thing to check. :smile:

**Comment by mtissington** [comment]
@MKleusberg - great job - many thanks - I can confirm both issues are now resolved 😄 
However I have not tried fileio.dll

**Comment by karim** [comment]
@mtissington 
> @karim did you try loading it with the `SELECT load_extension` format?

Yes, both give the same result.

You can close this issue now since both bugs were fixed, and I will probably open a new one for fileio.dll when I find where the problem is. :smiley: 

@justinclift 
> Mentioning just in case you're using an older/newer version of it

I'm trying with the one in the latest nightly, so I'm sure it is the most recent.

**Comment by justinclift** [comment]
Cool. :smile:
