### ISSUE TITLE
Browse Data: auto-resizing on filter changes is jarring

### ISSUE THREAD

**Issue by mlawren** [sqlitebrowser/sqlitebrowser#1941]
Details for the issue
--------------------

#### What did you do?

Modify a column filter resulting in a different maximum width/length value.

#### What did you expect to see?

That the column widths remain the same, or at least that they don't change jarringly when the filter does its work.

#### What did you see instead?

Auto-resizing of column widths, with the associated display "flashing" that appears to be the result of no-matches, followed by new-width-matches.... at a guess.

#### What would you like to see?

My preference would be to have auto-sized column widths only when the database/table is first loaded, and then only update column widths when double-clicking column separators (al-la Excel). 

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 8.1 (6.3) (winnt/6.3.9600) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by MKleusberg** [comment]
As far as I understand, the issue you're describing stems from the fact that the columns are resized automatically to fit their contents. Because if they were not resized automatically, there would be no reason the widths should change when changing the filter. Correct? However, on at least my system all columns have the same default width which is never modified automatically which means I can't reproduce your problem. Sometimes these things depend on the platform and the theme, so maybe that could explain the different behaviour. If that's the case here tomorrow's nightly build might work for you. You can find it [here](https://nightlies.sqlitebrowser.org/latest/).

So two questions :smile: 
1) Am I understanding your issue correctly, i.e. the columns are resized automatically according to their contents?
2) Does it work any better with tomorrow's nightly build?

**Comment by mlawren** [comment]
> 1) Am I understanding your issue correctly, i.e. the columns are
> resized automatically according to their contents?

Yes. Even worse, it appears there is some kind of redrawing/flashing
occuring even when the column doesn't need to change size.  See the
following demo:

    https://rekudos.net/~mark/sqlitebrowser-issue-1941.mp4

> 2) Does it work any better with tomorrow's nightly build?

No change :-(

-- 
Mark Lawrence

**Comment by mgrojo** [comment]
This seems to refer to the same problem than  #1763.

**Comment by mgrojo** [comment]
@mlawren I think that I have avoided the flickering. Could you confirm that it works better also in your platform using tomorrow's nightly build?

**Comment by mlawren** [comment]
On Sat Aug 03, 2019 at 04:14:13PM -0700, Manuel wrote:
> ... using tomorrow's nightly build?

The builds at [1] still have a date of 2019-07-29 so I can't do so yet.

[1] https://nightlies.sqlitebrowser.org/latest/

-- 
Mark Lawrence

**Comment by mgrojo** [comment]
Something is happening with the nightlies, but we will have to wait for @justinclift to know.

I see that there are win64 builds from today:
```
DB.Browser.for.SQLite-win64.msi                    09-Aug-2019 08:01            16277504
DB.Browser.for.SQLite-win64.zip                    09-Aug-2019 08:01            18609655
```
Can you use that?

**Comment by mlawren** [comment]
The 09-Aug-2019 nightly build now displays ideal behaviour - much easier on my eyes :-)

Many thanks for the follow up and fix on this non-critical issue!

**Comment by justinclift** [comment]
Sorry, was doing maintenance on the build boxes a few days ago and broke things.  It's fixed now.

Btw, if that happens again it's probably better to email me directly.  I'm **way** behind on checking GitHub notifications (semi-ignoring them due to 400+ items) atm. :wink:
