### ISSUE TITLE
NULL value imported from CSV file become empty string

### ISSUE THREAD

**Issue by harysutanto** [sqlitebrowser/sqlitebrowser#195]
<b>OS : OS X 10.10.2
SQLitebrowser Version : Feb 06, 2015 nightlies</b>

It is as the title suggests, null value is become empty string when I tried to import from CSV file which has a null value (etc,10,,10,). I tried to import using other SQLite app the null value (etc,10,,10,) become <i>NULL</i> instead of empty string. Oh, and the preview when importing a CSV file (after choosing the CSV file) btw, also display an empty string rather than <i>NULL</i> value. I have already checked when I import using SQLitebrowser and open with another app it becomes empty string for the <i>NULL</i> value.

I don't know if this is a feature or not, but maybe you can add an option when trying to import you give a checkbox and textfield for the <i>NULL</i> value, so when the user check the box but leaves the textfield empty the <i>NULL</i> value becomes empty string or the value of the textfield if any. And when the user does not check the box, the textfield is disabled and the null value becomes <i>NULL</i> when imported.

<b><i>Preview screenshot:</i></b>
![screen shot 2015-02-06 at 10 28 08 pm](https://cloud.githubusercontent.com/assets/7357789/6081935/b20460be-ae4f-11e4-88b4-05c33f412b5a.png)

<b><i>After import screenshot:</i></b>
![screen shot 2015-02-06 at 10 28 59 pm](https://cloud.githubusercontent.com/assets/7357789/6081947/cda887e6-ae4f-11e4-9db3-36f99b17febc.png)

<b><i>Browse table data using another app after import from CSV using SQLitebrowser:</i></b>
![screen shot 2015-02-06 at 11 01 18 pm](https://cloud.githubusercontent.com/assets/7357789/6082820/a53ac984-ae56-11e4-9ada-b4ce73b916f6.png)

<b><i>Browse table data using SQLitebrowser after import using other SQL app:</i></b>
![screen shot 2015-02-06 at 10 32 32 pm](https://cloud.githubusercontent.com/assets/7357789/6081982/1cd7f072-ae50-11e4-85fe-948d54321d4d.png)

<b>In case you need the CSV file, here it is:</b>
https://www.dropbox.com/s/e8pad14efeki5e7/ZWATCHACTIVITY.csv?dl=0

**Comment by harysutanto** [comment]
On second try, I think when importing from a CSV data to current table that exist in the sqlite database ignores whatever default value the table has. Maybe this is why, when importing from a CSV the value of the table become empty cell rather than the table default value NULL.

I already tried using other default value other than NULL, and the result is also an empty cell rather than default value.

**Comment by rp-** [comment]
Well I can live with the argument that an empty: ',,' column should NULL and if you want a empty string the CSV data should be ',"",'.
But to get default values for columns is a bit more tricky and maybe not always what a user would expect or want. And usually it shouldn't be such a problem to get default values you want into the csv data. e.g. with libreoffice calc or excel.

**Comment by justinclift** [comment]
Thinking through this a bit, its pretty straightforward (to me atm :wink:), that a field consisting of only two single quotes, should be an empty string.  eg:
* '','other stuf'
* 1,'',13
* 1,2,''

Also, a field with only NULL in it (unquoted) is very likely meant to be a NULL.  eg:
* NULL,1,2
* 1,NULL,2
* 3,4,NULL

Though section 2.6 of [RFC 4180](https://www.rfc-editor.org/rfc/rfc4180.txt) does indicate it could also be considered a value string of "NULL". :frown:

A field without a value though...yeah, that's interesting.  NULL or "default field value" are both possibilities.

At the risk of making things more complicated, we may need another option added to our cvs import dialog. *sigh*

**Comment by harysutanto** [comment]
Yes, actually I also prefer to have an option for what to do with the empy value (',,') than to set the field to default value by default.

Anyway, Thanks for the responses and keep up the good work!

**Comment by justinclift** [comment]
Just tested CSV import with our new 3.8.0 release.  We still need to get that extra option added to the CSV import dialog, for controlling what happens with fields without values.

It should be a very simple bit of coding, if someone has time to get it done.  @MKleusberg maybe? :smile:

**Comment by justinclift** [comment]
@revolter This "adding an extra option to the CSV import dialog" seems like it might be your kind of thing.  Want to take a look at it?

**Comment by revolter** [comment]
@justinclift, If only I would know how to branch based on the setting.

**Comment by justinclift** [comment]
The database interaction bit could be tricky at the moment, yeah. 😦

**Comment by lhunsicker** [comment]
Has there been any progress on this issue?  I have a large number of SQLite databases that I have entered from *.csv files, using your *.csv import method, each with multiple columns with predefined numeric affinity, but peppered with "text" typed null string entries that were intended to be entered as NULL, and that when exported to R are coerced incorrectly to a numeric 0.  I know that I can repair these files with, e.g.:
      UPDATE core2013 set dx15 = NULL where dx15 = '';
But this is really cumbersome where there are hundreds of such columns in multiple tables.  I suspect that I am not alone in not realizing before that missing values in a .csv file numeric field were entered as null strings rather than as NULL or missing values.   It would be a really nice feature for the *.csv import function to check the type affinity of a column, and where the column has numeric affinity, enter null strings as numeric nulls rather than as text empty strings.
It would be acceptable, but I suspect unnecessary, to give the user the choice in an extra option between the current behavior and my suggested behavior.
Thanks for considering the above, and many thanks for your work with SQLite and import of *.csv files.
Larry Hunsicker

**Comment by justinclift** [comment]
@lhunsicker Unfortunately... we haven't put much/any time into this yet.  We will "at some point"... but it hasn't happened yet. ☹️

**Comment by MKleusberg** [comment]
@lhunsicker Hi Larry, yeah we're currently drowning in issues, so nobody put any effort into this. But thanks for reminding us :wink: I've just made an (experimental) change to the CSV import that implements your suggestion on this. If you're importing into an existing table (if you're not we can't really make any assumptions about data types) and the importer hits an empty field in the CSV file it now checks the data type of the field. If it is numeric it will insert ```0``` or ```NULL``` (depending on the ```NOT NULL``` flag of the field). If it isn't numeric it is still going to insert an empty string.
Are you ok to download and test tomorrow's nightly build (see our main page for the link) and report back if it is improving the situation for you? :smile:

**Comment by lhunsicker** [comment]
Yes!!  Absolutely!  I'll look for the new build on Sunday (after it is posted tomorrow evening.). Thanks for your response!  I'm impressed by your responsiveness.

Larry Hunsicker

**Comment by lhunsicker** [comment]
Hi again, Martin:

As I thought about your message below, it occurred to me to suggest that entering a missing value as a 0 into a non-null numeric affinity SQLite column is probably still an error.  I think that it would be better to "offer" the null value to SQLite and let the SQLite program decide what to do.  The default, I think, would be for SQLite to abort the load, just as if I tried to copy a null into a non-null column within SQLite.  If the person entering the data expected the *.csv data to be a non-null number, (s)he should be alerted to the data error in the *.csv file rather than entering an erroneous numeric value into the SQLite table.  I agree that if the column has not been defined to have numeric affinity, you just have to enter what is given to you (a text type null string).

This is for the future.  I'll still test your experimental change below.  Many thanks for your responsiveness.

Incidentally, as I think that I mentioned, I am an R user, and I have just explored the mechanisms for data entry using the RSQLite package.  The dbWriteTable function has a method for directly copying a *.csv column into an SQLite table that imports null values correctly.  If the table structure is not defined, another function is called that looks at the values and "guesses" what the column affinities should be.  It is remarkably accurate.  As I am sure you know, the RSQLite package is realized on Windows as a .dll following compiling in C++, so that it is amazingly fast (took 5 minutes to enter a file with 3,000,000 records of 135 fields each) into SQLite (without any constraint checking).  This package can also enter other flat file text formats (tab separated, arbitrary character separated, column delimited) the same way.  All the code has been made freely available by the author (Hadley Wickham of RStudio), so I suspect that you could use the Windows .dll to do all the same things for direct data entry from flat files into SQLite, without the need to invoke R.  You may want to consider this approach to offering SQLite users that don't use R the same methods that I have found that I can use within R.  This might make developing this facility for SQLite much easier.  You should give it a look.

Again, thanks for being so responsive!  I have come to depend on SQLite for my big files.  It is an excellent program.

Larry Hunsicker

----- Original Message -----

**Comment by justinclift** [comment]
@lhunsicker Interestingly, we have an issue open detecting the data type when importing CSV's here #1003.

Would you be ok to cast your eye over my proposed approach there?  I'm kind of thinking it should be effective and accurate. :smile:

**Comment by lhunsicker** [comment]
Sure.  I'll take a look tomorrow.  It's great that you're looking into this.

Larry Hunsicker

**Comment by lhunsicker** [comment]
Martin:

Another update to the issue of SQL importing data from a *.csv file.  I have just discovered that the SQLite *.csv importer doesn't strip white space between two commas.  This means that a line in a *.csv file like:
567,  890,123\n
gets read as 567,"  890",123
with the middle value read as a text field rather than as an integer field.  Given how sloppily some *.csv files are composed, it might be nice to strip the white space from a *.csv field before deciding whether it is numeric or text.  

I know that I keep coming up with more trouble for you.  But as I said in my last message, the RSQLite and DBI packages for R do all of these things the way that one would hope.  I'll check your new SQLite build a bit later today. 

Thanks for your interest.

Larry Hunsicker




----- Original Message -----

**Comment by lhunsicker** [comment]
Martin:
Now that I have gotten into this, I have to clarify that I am a github newbie.  How do I "download tomorrow's nightly build"?

Larry Hunsicker

**Comment by chrisjlocke** [comment]
If you click this link, you should see a  the latest builds:
https://nightlies.sqlitebrowser.org/latest/

👍

**Comment by lhunsicker** [comment]
Justin:
Your approach above is generally fine.  I have four comments:
1.  Strip leading and trailing white space as you read in single values.  Currently a line holding:
26,   27, 28\n
will be read as:
26|'  27'|28
with types integer, text, integer.
2.  It would be nice to read more than just the first row.  If the first value in a row is NULL or a 0 length text field, then the entire column would be set to NULL or TEXT.
3.   So read, say, the first 10 rows.  Then, if the sample of a given column holds only INTEGER, REAL, NULL, and 0 length TEXT (""), set any 0 length TEXT fields in the column to NULL.  
(If the *.csv file is being read into an existing table and into a NOT NULL field, and you have a NULL value to enter, I think that you should send a NULL to the database anyway and let the table programming figure out what to do.  The default would be to abort the load and issue an error message.  But you shouldn't have to worry about that.)
Then if all the values in the column sample are INTEGER or NULL, the column is INTEGER.  
Else, if all the values in the column sample are INTEGER or REAL or NULL, the column is REAL.
Else the column is TEXT.
4.  You are correct that you'll have to take location into account.  In Europe, "," is what they use to separate the whole from the fractional part, and typically the field separator is ';'.  But they still call the files "*.csv" files.  In fact, there is no reason to limit the field separator to ','.  It would be nice to offer options to specify the field separator and the "whole/fractional" separator, probably with the expected defaults.  (There is already an option for '|' separated fields.)
This won't be perfect, but it will be a lot better than what we have now.  The R packages DBI and RSQLite have another nice feature.  If the *.csv loader notes specific data types that conflict with the column affinity, it issues an appropriate warning after completing the load.  Not really your problem, but it would alert the user that (s)he has some cleanup work to do.
I hope that this is  helpful to you.  It was interesting for me to go through the logic.
Larry Hunsicker

**Comment by lhunsicker** [comment]
Many thanks!  Larry Hunsicker


----- Original Message -----

**Comment by lhunsicker** [comment]
Wow, Martin!

We have been speaking to some extent at cross purposes.  I am an old command line type, and I was talking about my experience with importing *.csv files using the facilities in the SQLite3 bash shell.  I didn't know about the SQLiteBrowser.  But I downloaded and installed your SQLite Browser and used it for some testing.  I like it!  I'll probably start using it now rather than the SQLite3 bash shell.

First of all, the direct answer to your question.  No, even when I import my test.csv file to an existing table with integer or numeric typed columns, empty (,,) fields in the test.csv file are still entered as blank (0 length?) text fields. If I create a table with untyped columns using the SQLite3 bash shell, then use SQLiteBrowser to enter data, all data are entered as text even when they were clearly integers or reals.

But a couple of other comments:
1.  Using your SQLiteBrowser, I can't create a column with no type (or with NULL type).  I suppose that this is a feature rather than a bug.
2.  Your SQLiteBrowser already permits trimming the white space, selecting the field separator, the quote character, and the coding.  GOOD FOR YOU!  But you might want to add a similar option for the decimal separator.  As you know, Europeans use ',' rather than '.'. 

The SQLiteBrowser is already way beyond what the SQLite3 bash shell does for us.  But I worry about the folks that didn't know about the SQLiteBrowser and are still using the SQLite3 bash shell.  How can I contact them to pass on my concern about NULL csv values being typed as text empty strings?

Thanks for your work on this issue!

Larry Hunsicker
 

----- Original Message -----

**Comment by justinclift** [comment]
Hmm, with this:

> How can I contact them to pass on my concern about NULL csv values being typed as text empty strings?

It's a bit unclear (to me) who the "them" you're meaning are. :wink:

If you're meaning the developers of the SQLite3 bash shell, then definitely reach out to them on the "sqlite-users" mailing list as a first step.  They're pretty friendly too, so it should be a fairly easy experience.

&nbsp; &nbsp; http://mailinglists.sqlite.org/cgi-bin/mailman/listinfo/sqlite-users

Does that help? :smile:

**Comment by lhunsicker** [comment]
Yes.  Thanks!  Larry Hunsicker

**Comment by lhunsicker** [comment]
I am new to the GitHub arena.  I just tried to create a new issue (twice) using the button above, but it seems that none of the information that I put into the first section of the message box got entered into the actual question -- just the stuff about my os, etc.  I realize that this response is out of place here, but could one of you point me to the instructions on how to submit a question correctly?  I would be very grateful.  Larry Hunsicker

**Comment by chrisjlocke** [comment]
Its not very clear, but when you create a new issue, you are meant to type after the right pointing arrow.

![image](https://user-images.githubusercontent.com/7872218/27989733-4fa02f02-6437-11e7-8912-81d3895022e6.png)

The arrows are actually HTML markers to put comments, and anything put between these markers are ignored.  Unfortunately, your comment was between these markers.  I amended your last query, so it should show up now.  👍 

Hope that helps.  🚁

**Comment by lhunsicker** [comment]
Very clear.  I think that I have it now.  Many thanks for helping a "newbie"!

Larry Hunsicker


----- Original Message -----

**Comment by PeterSmyth12** [comment]
Using the 20th December 2017 release (Windows x64)
Importing a table into an already defined schema still does not treat a missing value as NULL but as an empty string ''. 
Even if the field has been defined as REAL and defined as NOT NULL it gets the empty string.

Is there any chance that this is going to get fixed soon?

**Comment by MKleusberg** [comment]
Closing this because the issue should be solved and we haven't heard back from the reporters for a while. If you feel like I closed this issue too early, feel free to re-open it - I'd be happy to hear any more ideas or opinions about this :smile:
