### ISSUE TITLE
Foreign Key drop down list doesn't show existing table, if new table 'name' starts with existing table name.

### ISSUE THREAD

**Issue by 4silvertooth** [sqlitebrowser/sqlitebrowser#1991]
Details for the issue
--------------------

#### What did you do?
1. Created a table named bill, with Primary Key 'ID', and some fields.
2. Try to create a table with name bill_rows whose field 'bill_id' REFERENCES `bill`(`ID`). 

#### What did you expect to see?
I expected to see 'bill' table in drop down list of the 'Foreign Key' tab, in the create/modify table window.

#### What did you see instead?
I saw the `bill` table is missing in the the 'Foreign Key' dropdown list, instead saw the name of the new table I was creating. 
This happens only if the new table's name we are trying to create starts with an existing table name, 'bill_rows' in this case also billRows or billTmp.
 If I create a table name `tmp` with the same fields I want in `bill_rows` and try to modify it's name to `bill_rows` the FOREIGN KEY(`bill_id`) REFERENCES `bill`(`ID`) also changes to FOREIGN KEY(`bill_id`) REFERENCES `bill_rows`(`ID`) or whatever the new table name we are trying if it starts with the name from a existing table.

Useful extra information
-------------------------
> DB4S v3.11.99 (Sep  5 2019) [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.17134) [x86_64]
> using SQLite Version 3.28.0
> and Qt 5.11.3

**Comment by MKleusberg** [comment]
Thanks, @4silvertooth! I'd never have found this issue without your detailed description :+1: I believe this issue is fixed now. Are you ok to give tomorrow's nightly build a try and see if it's working? :smile: 

Here's what happened if you're interested: In the Edit Table dialog you can change the name of the current table. When it changes the list of tables available for foreign keys is updated to replace the old by the new table name. Now as you type ```bill_rows``` at some point your table is named ```bill```. If you type further, the ```bill``` entry is removed by the ```bill_``` entry and so on. And that's why the actual ```bill``` table was removed while typing in ```bill_rows```.
