### ISSUE TITLE
Register sqbpro in the freedesktop/xdg mime-type database

### ISSUE THREAD

**Issue by j77h** [sqlitebrowser/sqlitebrowser#2024]
Using KDE Plasma, .sqbpro files are not opened by sqlitebrowser (nor by anything else).
Searching the web did not find any mention of sqbpro related to xdg or freedesktop.

It seems that if you add sqbpro to the freedesktop mime-type database, the Linux desktops will eventually pick it up.

This page: https://userbase.kde.org/System_Settings/File_Associations/en
says "The KDE software guesses filetypes using the shared-mime-info database, which is shared with many other software projects. To request a new file type to be added to the database, please, follow the instructions here", and points to 
http://cgit.freedesktop.org/xdg/shared-mime-info/plain/HACKING

This might be easier to follow:
https://freedesktop.org/wiki/Specifications/AddingMIMETutor/

More information :
https://freedesktop.org/wiki/Software/shared-mime-info/
https://freedesktop.org/wiki/Specifications/shared-mime-info-spec/

**Comment by justinclift** [comment]
Sounds like a good idea. :smile:

**Comment by MKleusberg** [comment]
I have just committed my attempt to build a MIME file. I guess it is something which distributors should start including in their DB4S packages. I'll try to remember adding a note on this in the release notes.

Adding the file to the freedesktop mime database doesn't seem like an option. See [here](https://cgit.freedesktop.org/xdg/shared-mime-info/tree/HACKING):
> Mime-types/file formats proprietary to one application should only
> be added to a private .xml file and be bundled with the application
> itself

**Comment by mgrojo** [comment]
I guess we should update our [.dekstop entry](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/distri/sqlitebrowser.desktop) to add `application/vnd.db4s-project+xml`. But what should be done with `application/sqlitebrowser;application/x-sqlitebrowser`? Are they actually needed or should be deleted since they aren't actually registered in the Shared MIME-info Database?

Should we also add application/vnd.sqlite3 and application/geopackage+sqlite3 according to
 https://www.iana.org/assignments/media-types/media-types.xhtml ?

I guess so: https://stackoverflow.com/questions/31301552/android-what-is-the-mime-type-to-use-if-i-want-to-see-pick-a-sqlite-database-fr/55071463#55071463

**Comment by mgrojo** [comment]
I've made the additions but not the possible deletions in order not to break anything.

**Comment by mgrojo** [comment]
This seems to be addressed as far as possible and v3.12 is released including our MIME file and new desktop entry file. Is there something we should do to improve the situation?  Has some distribution included the association using our files?
