### ISSUE TITLE
Change Close Database shortcut to something else and use Ctrl+W to close a tab in SQL editor

### ISSUE THREAD

**Issue by T1mL3arn** [sqlitebrowser/sqlitebrowser#2025]
Many programs use `Ctrl+W` to close tabs (e.g Firefox, Chrome). IMHO DB4S should use the same logic and close a tab in SQL editor instead of database.

**Comment by SilvioGrosso** [comment]
Hello @T1mL3arn 

> Many programs use Ctrl+W to close tabs (e.g Firefox, Chrome).

Yep. You are right. Many softwares including Gimp, Krita and others also follow this "convention".
In short, generally speaking, CTR+W closes the current tab; CTR+Q: closes the entire application
With Db Browser, CTR+Q shuts down the entire program, which is usually the "standard" way with softwares (since it easy to recall "Q" as Quit, like it occurs in the Linux Shell).

However, in Notepad++:
- CTR+Q: closes the current tab;
- CTR+SHIFT+Q: closes all tabs currently opened; 
- ALT+F4: exits from the application. 
Therefore, there is not a standard way to opt for... 😄

As an user myself, I don't know why Db Browser for SQLite has adopted this kind of shortcuts 😄

**Comment by justinclift** [comment]
It's probably historical, as we started out only supporting a single tab.

That being said, it's not hard to change, and the failure mode for people getting it wrong if we change it isn't terrible. eg it would close the current tab instead of the current database.

**Comment by mgrojo** [comment]
But Ctrl+W is also a standard shortcut for  "close document" (or "window") and I'd say that is the original meaning. In a lot of applications a document is opened inside a tab and consequently the shortcut covers both meanings.

https://defkey.com/what-means/ctrl-w

Our problem is that we have three kinds of "documents": database file, project file and SQL files (or independent buffers). The first two can be asimilated, because the project includes the DB and in fact Ctrl+W closes both. But SQL tabs are a different thing and I'm not sure if they should be given more relevance than the DB.

I'm not saying that we cannot change the current assignment, but I think the shortcut was assigned consciously. If you prefer Ctrl+W for closing an SQL tab, then at least we have to find a new shortcut for closing the DB, since there are people  that might miss the ability to close the DB file with a keyboard shortcut. Another shortcut meaning "close document or tab" is Ctrl+F4, maybe we could use this one for one thing and Ctrl+W for the other. What do you think?

https://defkey.com/what-means/ctrl-f4

**Comment by T1mL3arn** [comment]
@justinclift 
> it would close the current tab instead of the current database.

I was caught on this, thinking `Ctrl+W` will close SQL editor and lost all changes I made in db. So here this issue. Yep, that's my bad, I should read prompt window more carefully :sweat_smile: . 

@mgrojo 
> What do you think?

`Ctrl+W` is more easy to press, so I suggest to use this combo to close a tab in sql editor (since juggling sql scripts looks like a more frequent task), and `Ctrl+F4` to close database.

**Comment by mgrojo** [comment]
The proposed change will be available in the [tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/). Could you confirm, @T1mL3arn ?

**Comment by T1mL3arn** [comment]
@mgrojo 

Tested. `Ctrl+F4` closes db, `Ctrl+W` closes tabs, and now it is more convenient to work with sql queries, thanks!

A little issue - can't close first `SQL 1` tab with `Ctrl+W` even if there are more sql tabs.
To reproduce:
1. Create few sql tabs in _Execute SQL_
2. Go to the first `SQL 1` tab
3. Try to close it with `Ctrl+W`
4. Nothing happened

**Comment by mgrojo** [comment]
Thanks for testing. The little issue was a silly mistake. It will be fixed in the next nightly build.

I've also implemented that you can close the last open tab. I think it was implemented in that way in order not to leave an empty tab widget, but I've thought that it is better to close the old tab and open a new clean one and don't imagine a case where this new behaviour could be a problem. Could you give it a try and report any unexpected behaviour?

**Comment by T1mL3arn** [comment]
@mgrojo 

Found focusing problem.

1. Open a couple of tabs (SQL 1 and SQL 2)
2. Go to _the last one_ (SQL 2)
3. Close it (with hotkey or just `x` button)
4. Focus sets to `Execute SQL` tab instead of `SQL 1`

On the contrary, if at first close `SQL 1` tab, then focus sets on `SQL 2` tab.

**Comment by mgrojo** [comment]
@T1mL3arn in the next nightly build, the focus will always be set to the new current editor tab.

**Comment by T1mL3arn** [comment]
Tested fixes for focus, all works.
