### ISSUE TITLE
Browse data: Cell aligning inconsistent

### ISSUE THREAD

**Issue by mbraeutigam** [sqlitebrowser/sqlitebrowser#2032]
Details for the issue
--------------------
Displayed text alignment in cells in "Browse data"-tab seems to follow the guessed type of the cell, not of the column in CREATE TABLE statement. This leads into a weird display of data which is hard to visually compare on the fly when viewing bigger tables with lots of data.

#### What did you do?
```SQL
CREATE TABLE TEST (QUELLE TEXT,BESCHREIB TEXT,FLAG TEXT);
INSERT INTO "main"."TEST" ("QUELLE", "BESCHREIB", "FLAG") VALUES ('97', 'Vera+', '');
INSERT INTO "main"."TEST" ("QUELLE", "BESCHREIB", "FLAG") VALUES ('AT', 'ATKIS', '');
```

View data in "Browse data tab"

#### What did you expect to see?
![image](https://user-images.githubusercontent.com/4228180/67839088-16eae300-faf3-11e9-8f6a-ad94f5ab3cbb.png)

as in v3.11.2

#### What did you see instead?
![image](https://user-images.githubusercontent.com/4228180/67839028-ec008f00-faf2-11e9-9009-9acd2abde600.png)

Useful extra information
-------------------------

#### What operating system are you using?

- [x] Windows: ( _version:_ Win10 64bit )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [x] Other: 64bit Windows nightly of 2019-10-30

#### Did you also

- [x] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh, interesting bug.  One part of the cause is that SQLite can display any kind of data in a field, not just what the `create table` statement says.  But the intersection of that and displaying different data types differently... could be better.

Out of curiosity, do any of the column formatting options (right click the column header) help?

**Comment by mbraeutigam** [comment]
Nope, they don't help.

I tried a C-like convert to char & string (not sure if it's right, my C++ knowledge is lacking pretty much)

```C++
printf('%s', "QUELLE")
```
![image](https://user-images.githubusercontent.com/4228180/67842966-6fbe7980-fafb-11e9-8a8f-e394ffdc8fdc.png)

```C++
printf('%c', "QUELLE")
```
![image](https://user-images.githubusercontent.com/4228180/67843154-bc09b980-fafb-11e9-88ef-c3d83fec72c7.png)

But those case-conversion routines don't work neither:
```SQL
lower("QUELLE")
upper("QUELLE")
```
![image](https://user-images.githubusercontent.com/4228180/67843732-d8f2bc80-fafc-11e9-8f29-037712b27348.png)

**Comment by justinclift** [comment]
Interesting.  Sounds like we'll need to add some kind of "override automatic formatting" or "override automatic alignment" thing. :smile:

**Comment by mbraeutigam** [comment]
indeed, and it should inherit the alignment of the type from table definitions by default 😄

**Comment by mgrojo** [comment]
As part of #1976 (c27002c3010f7e820911feed492d5154ace602c9) numbers (independently of the internal data type) are right aligned. This default alignment can be overridden using the text alignment buttons in the new formatting toolbar: use this button ![imagen](https://user-images.githubusercontent.com/13812910/67889955-17659700-fb50-11e9-9e41-2f8b914a436d.png) to show or hide the toolbar  and this one ![imagen](https://user-images.githubusercontent.com/13812910/67889915-03ba3080-fb50-11e9-9612-1778e73e25f8.png)  for aligning the column to the left (select the entire column first using Ctrl+Space).

The issue is legitimate as an enhancement, though, since it makes sense to apply the left alignment not to all values that display as number, but only to values of a numeric data type.

**Comment by SilvioGrosso** [comment]
Hello everyone,

> Ahhh, interesting bug. One part of the cause is that SQLite can display any kind of data in a field, not just what the create table statement says

Yep this is what always confuses new SQLite users at first...
At work we always work with PostgreSQL because of this SQLite feature...
From my experience, SQLite is much more similar to Spreadsheets (Calc, Excel etc) where, even though you state the exact type (text, number, date) of your column, in the long run, quite often, everything gets messed up end you end up with different types of data (text, number) in your spreadsheet column...

Dbeaver 6.2.3 behaves exactly as @mbraeutigam  proposed.
It even goes an extra mile in that in every column is present an extra blue label which clarifies further the type of data (ABC for text - date; 123 for numbers). In all truth, I often find this extra blue label a bit confusing  to look at in that it makes the label too cluttered in my view...

![text_number png](https://user-images.githubusercontent.com/33007383/67898988-aaf39380-fb61-11e9-83d0-a59c30ddaa06.jpg)

**Comment by mbraeutigam** [comment]
@SilvioGrosso I thought about that behaviour/treatment of data in SQLite, too, because it is written in its specs. But what confuses me more, is that if you have a closer look to my SQL INSERT statement, I clearly inserted those values in field QUELLE as TEXT and they are interpreted as numeric.

Have a look at the following two cases:
```SQL
INSERT INTO "main"."TEST" ("QUELLE", "BESCHREIB", "FLAG") VALUES ('01', 'ZeroOneAsText', '');
INSERT INTO "main"."TEST" ("QUELLE", "BESCHREIB", "FLAG") VALUES (01, 'ZeroOneAsNumber', '');
```
![image](https://user-images.githubusercontent.com/4228180/67900983-eabc7a00-fb65-11e9-8e43-8f4205c7f860.png)

ZeroOneAsNumber is treated as expected (leading 0 is cut off, because it is a number and it is aligned like a number).
ZeroOneAsText is not (leading 0 is still there, because it is a text, but is aligned like a number).

**Comment by SilvioGrosso** [comment]
Hello @mbraeutigam,

 > ZeroOneAsText is not (leading 0 is still there, because it is a text, but is aligned like a number).

Yes. I do undertand you point. 
Your first SQL code was already quite self-explanatory :-)
I didn't make myself clear enough in my previous post as far as your post is concerned.
At present, you can align yourself the text with the new buttons in the toolbar. Needless to say it may be a quite time-consuming task.

I have checked the stable version of Db Browser for Sqlite 3.11.2 and this "bug" was already present. Therefore it is not a regression due to some recent refactoring...

Here is how the alignment is done with the stable version with the INSERT code:

![OLD](https://user-images.githubusercontent.com/33007383/67902641-f1e58700-fb69-11e9-96a7-be084f7ea0b9.jpg)

Here is how the 2 rows just  inserted are displayed in the Browse data (stable version as before):

![OLD2](https://user-images.githubusercontent.com/33007383/67902784-4983f280-fb6a-11e9-9510-cf8b81ff2527.jpg)

**Comment by SilvioGrosso** [comment]
Just tried once again with DBeaver.
This time I have added the other 2 rows in the table.
Even DBeaver does not align correctly the fourth row....
This is why SQLite is so prone to confuse people since it allows you to add in the same field differenty types (text, number etc). 

A colleague of mine even asked me once why I work with SQLite since it such an "inferior" database compared to PostgreSQL :-) :-)

![DBEAVER](https://user-images.githubusercontent.com/33007383/67904430-a386b700-fb6e-11e9-9222-d2c7f20857f7.jpg)

**Comment by mbraeutigam** [comment]
Yeah, we had some hot discussions about these different types in cells regardless of the column definitions at work, too 🤣 
But I found a solution the prevent that behaviour by addding type checks constaints into the create table statements. It is a bit hacky, but it worked fro me.

**Comment by mgrojo** [comment]
It's easy to change the behaviour so the text alignment follows the type affinity of the column, but not the actual data type of the cell. I'm going to commit that change, since I agree that it is better than the current behaviour: you get a hint of the type affinity of the column and the entire column has the same default alignment.

**Comment by mgrojo** [comment]
@mbraeutigam @SilvioGrosso It's already committed and will be included in the next (available) nightly build (but we have a problem again with the Windows builds).

**Comment by mbraeutigam** [comment]
@mgrojo Great to hear! I will let you know when I am done with testing.

**Comment by mbraeutigam** [comment]
@mgrojo I tested it:

![image](https://user-images.githubusercontent.com/4228180/69327305-9e88c500-0c4d-11ea-959f-e84bf693af53.png)

![image](https://user-images.githubusercontent.com/4228180/69327583-0b9c5a80-0c4e-11ea-8519-a14bf03b50ac.png)

It is looking good, so I am closing this issue.
Thanks heaps for the fix!
