### ISSUE TITLE
Why does non greedy regexp fail?

### ISSUE THREAD

**Issue by stenci** [sqlitebrowser/sqlitebrowser#2040]
Below two queries. The second group on the former query is greedy, on the latter is not.

Why does the former work and the latter doesn't?

    SELECT * FROM "table" WHERE "field" REGEXP '(Color|Material)=(\w.*)($|,)';
    SELECT * FROM "table" WHERE "field" REGEXP '(Color|Material)=(\w.*?)($|,)';

I asked [this question](https://stackoverflow.com/questions/58756884/why-does-non-greedy-regexp-fail-in-sqlite?noredirect=1#comment103803937_58756884) in Stack Overflow, I got no answers, but a comment says "The regex library used behind the scenes is broken".

Is the regex library used by DB4S really broken?

**Comment by MKleusberg** [comment]
Very good question! Thank you for letting us know about this problem :smile: The answer by C Perkins on Stackoverflow contains a very good analysis of the situation. We implement the regular expression operator using the older QRegExp class from Qt which doesn't have complete support for greediness quantifiers. Furthermore because Qt has changed the behaviour of QRegExp between some versions, we disable parts of this already partial implementation for consistent results across all versions of Qt.

I have now replaced the code to use the newer QRegularExpression class which should have full support for greediness quantifiers. There's really no reason for us to not use this newer and better implementation. Are you ok to give the new version a try and see if it's completely fixing your problem? In theory, you can download it [here](https://nightlies.sqlitebrowser.org/latest/) tomorrow. But it seems like the nightly builds are not running at the moment, so it might take a few extra days :smile:

**Comment by stenci** [comment]
I just tried (even if you said tomorrow) the same query on the last nightly update and it works, on the 3.11.2 and it doesn't. 

Thank you!

**Comment by MKleusberg** [comment]
Thanks for testing! :smile:
