### ISSUE TITLE
Windows version always checking for new version

### ISSUE THREAD

**Issue by pleaseloveme** [sqlitebrowser/sqlitebrowser#208]
The registry key HKCU/Software/sqlitebrowser/sqlitebrowser/checkversion/disable doesn't seem to have any effect for every release I've been using in the last year -- the program always checks and always throws an annoying popup if something new is available. Clicking "Don't show again" does seem to change the registry value, so I guess that works. Just kind of annoying.

Also, it'd be nice if you used a flat file (.sqlitebrowser perhaps?) or INI file in the AppData folder for user selected preferences to make installations more portable. I don't mind the last window size and version number being in the registry, but I'd prefer to be able to backup chosen preferences without exporting registry keys.

**Comment by justinclift** [comment]
Hmmm, that does sound like a bug which needs fixing.

And yeah, using the registry may not the most portable approach.  Using a .ini file or similar is probably a suitable alternative. :smile:

**Comment by MKleusberg** [comment]
I've just added a new option to the settings dialog which lets you disable the update check altogether. If you don't want to wait for the next version to have this included, you can wait for the next nightly build (see download links in the README.md file). Either way, all you need to do is removing the tick from the Automatic updates enabled check box in the settings dialog.

As for the registry/INI discussion: This is a bit more complicated than it might seem because loading and writing settings is entirely done by Qt which stores it in a different locations depending on your platform (http://doc.qt.io/qt-5/qsettings.html#platform-specific-notes). Now, it is possible to implement this by ourselves but honestly I don't see a huge benefit. On the other hand this means more work than it looks like at first because we'd have to implement reading and writing of multiple data types, tons of error checking for the reading part, etc. I'm not sure what you want to do with your INI file but if it's just for backups a small batch script exporting the registry keys (maybe of all installed applications) might be a solution. If it's for copying settings between systems, the Portable Apps version of DB4S might be something for you.

**Comment by pleaseloveme** [comment]
Great response; thanks for the update.

The INI thing was just me nitpicking after realizing that the checkversion flag was in the registry. It's always helpful if user preferences are easy to migrate to another system; registry keys/hierarchy are usually not published by developers. Sqlitebrowser is very light on user preferences, but it's a burden with some Windows programs. I didn't realize that Qt libs are handling configuration persistence, so I understand now that it's not worth the hassle. Thanks for looking into it. 

Keep up the good work!

**Comment by rp-** [comment]
@MKleusberg switching to ini file might not be that complicated. We can specify on every platform if you want to store settings in native style(registry on win) or with an ini file. The problem is just, that we would need a proper upgrade mechanism for windows users, so they don't lose their settings. And I'm not sure if this is worth the work.

**Comment by justinclift** [comment]
@MKleusberg What's the right way for us to verify this is working correctly, before our next release?

I'm thinking maybe building a release from latest source, but modify the source to have an older version number in it, so it should notice the update.  And then see if the on/off toggle works.

Sound about right?

**Comment by MKleusberg** [comment]
@justinclift Yes, that's one possible approach. Maybe it's a bit easier to leave the version number as it is but change the link in [MainWindow.cpp, line 182](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/MainWindow.cpp#L182) to point to a copy of the file in some other place. Then you could change the currentrelease file and test this option as well as the notifications in general (like the patch variable thing from 2c25b7ecb52944db225516a9b41c9f6c1860e749) without recompiling all the time.
But in the end it probably makes no difference which way you choose. Shouldn't take too much time either way :)

**Comment by justinclift** [comment]
The version checking code, and the Preference toggle to disable it, definitely works in the 3.6.0 release.  Tried it earlier. :smile:
