### ISSUE TITLE
Calculated Columns

### ISSUE THREAD

**Issue by cooperld** [sqlitebrowser/sqlitebrowser#2132]
Details for the issue
--------------------

#### What did you do? Created table with  calculated columns using command line.
No issues using table from Command line
Previously tried from SQL window in DBBrowser. Reported Syntax errors.  Then reverted to Command line

#### What did you expect to see?

Table in DBBrowser
#### What did you see instead?
Malformed data . Wont open

Useful extra information
-------------------------
> DB4S v3.11.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18362) [x86_64]
> using SQLite Version 3.27.2
> and Qt 5.11.3

**Comment by mgrojo** [comment]
Do you mean [generated columns](https://sqlite.org/gencol.html)? Version 3.11.2 did not support them at all. In current version @MKleusberg is starting to develop the support for them and with a [nightly build](https://nightlies.sqlitebrowser.org/latest/) and will the future 3.12 release you will be able to open the database. Could you confirm in the current issue for this (#2107) whether it is working for you?

I will close this issue now because it would be redundant, and we are overflooded with issues. Please, subscribe to #2107 for further news.

**Comment by cooperld** [comment]
Thanks for the response. I look forward to the upgrade.
Btw none of the other free browsers support it yet. Tried them all.
Len

**Comment by MKleusberg** [comment]
It's probably only going to happen after the next release (which we are currently working on) but I plan to implement the details of generated columns rather soon-ish :smile:

**Comment by cooperld** [comment]
Thanks for the update
