### ISSUE TITLE
unbundle libs/*

### ISSUE THREAD

**Issue by blshkv** [sqlitebrowser/sqlitebrowser#2134]
There are few bundled libraries getting linked statically from the /libs/ directory.
That causes various incompatibility problems, please see https://bugs.gentoo.org/678206 for example.
Please unbundle them, switch to share libraries and support unmodified versions.

If any changes need to be done to these libraries, they should be pushed to the upstream.

Thanks..

**Comment by scottfurry** [comment]
This was already addressed in some manner with changes to build process some time ago. I believe this is in the master branch and pending in the latest release which is coming soon.

With these options, the libraries must be installed on the system (CMake will find)
dev-libs/qcustomplot (latest upstream is 2.0.1)
x11-libs/qscintilla (latest  upstream is 2.11.3)
app-editors/qhexedit2 (latest upstream is 0.8.6)

If not found, CMake will fall back to building the bundled versions.
See the CMakeLists.txt file @ ~ line 18.
Options include:
FORCE_INTERNAL_QSCINTILLA [OFF(default) | ON]
FORCE_INTERNAL_QCUSTOMPLOT [OFF | ON(defalut)]
FORCE_INTERNAL_QHEXEDIT [OFF | ON(default)]

You would alter the gentoo ebuild `src_prepare` as:
```
mycmakeargs=(
-DFORCE_INTERNAL_QSCINTILLA=OFF
-DFORCE_INTERNAL_QCUSTOMPLOT=OFF
-DFORCE_INTERNAL_QHEXEDIT=OFF
...
```

**Comment by justinclift** [comment]
Yeah, this bundling is important mostly for (non-Linux) systems (eg Windows) that don't have them as part of the system.

But, as @scottfurry mentions above, they can be ignored for systems that do have them. :smile:

**Comment by scottfurry** [comment]
@blshkv - for your education and future reference....
WHO THE HECK ARE YOU TO DICTATE TO A PROJECT HOW THEY DO THINGS?!?!?!?!?!?!?!
NEVER, and I give not one iota who the sender is, NEVER dictate to a project how to do things. You want something changed? Great. Step up and attached a pull request putting code where your mouth is. Otherwise, you will be told to "go away" in extremely harsh and most impolite language.

We ARE NOT apart of Gentoo and there's more to this project than one linux distribution's needs.

**Comment by justinclift** [comment]
@scottfurry Err... relax? :smile:

It was just a request (even saying "Please...").  No need to go over the top about it. :wink:
