### ISSUE TITLE
SQLite Browser fails to open a DB inside a wsl2 installation

### ISSUE THREAD

**Issue by Because789** [sqlitebrowser/sqlitebrowser#2142]
Details for the issue
--------------------

#### What did you do?

I tried to open a SQLite database inside of a Windows Subsystem for Linux 2 installation (Ubuntu) and nothing happened. I copied the database to my desktop and the db opened fine. 

That means, it did NOT work with this path:
    \\wsl$\Ubuntu\home\iamgroot\dev\dev.db
But it did work with this path:
    C:\Users\iamgroot\Desktop\dev.db

I guess that behaviour is to be expected, since I try to open a file from a linux file system in a Windows software, and this issue therefore should be labeled feature request. But looking at the seemless integration of vscode and wsl2, it feels more like a bug...

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x ] Windows: ( _version:_ 2004 (Build 19564.1005) with WSL 2 activated (Ubuntu)) 

#### What is your DB4S version?

- [ x] 3.11.2 (64bit for Windows)

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by mgrojo** [comment]
"Virtual" filesystems usually give problems when opening an SQLite file inside them. See for example #2084. Isn't there any error message when you try to open the DB file?

**Comment by tomlagier** [comment]
I'm having this same issue with WSL1, no error message given. Are there logs somewhere I can take a look at?

**Comment by mgrojo** [comment]
Open it from a "Command Prompt" window; maybe it prints some error. When using a [nightly build](https://nightlies.sqlitebrowser.org/latest/), there is also an error log in the "SQL Log" dock. You have to select it from the combo box.

Besides, have you checked whether you can write to the db file and the containing directory? Try opening it in read-only mode, and maybe the problem is skipped.

**Comment by karim** [comment]
@Because789 Please check #2209 for more information.

> I guess that behaviour is to be expected, since I try to open a file from a linux file system in a Windows software, and this issue therefore should be labeled feature request.

Unfortunately, there is nothing we can do here. WSL is not meant to run GUI apps. If you really want that, you can install an X Server on Windows.

 > But looking at the seemless integration of vscode and wsl2, it feels more like a bug...

VS Code is doing that using an extension (https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl). If you checked the first image in this link https://code.visualstudio.com/docs/remote/wsl you will see how it works.

Basically, you run VS Code on Windows and you just send/receive commands to WSL (Linux environment) in the background, for tools that are running on WSL.

I'm not sure how we can change Database Browser for SQLite to support WSL. If you want to open the app on Windows while the database is on Linux then I wouldn't recommended it with SQLite (the library).

SQLite does not work well on networked/virtualized/emulated file systems due to file locking issues that are unique to each file system. When more than one file system is involved, SQLite fails to operate correctly.

A different approach is to sync/copy the database file itself so you can have access to it on Windows and WSL, while opening it using the GUI on Windows only.

**Comment by justinclift** [comment]
@karim At some future point, we could potentially do something similar to the DbAndroid plugin for SQLite Studio: https://github.com/pawelsalawa/sqlitestudio/wiki/DbAndroid

eg have a plugin that runs on the "remote" system (inside WSL in this case), and pipeline requests between DB4S and that plugin to "do stuff" in WSL.

Can't see it being something we'd do in the near future though, unless someone decides it'd be an interesting project to pick up sooner rather than later.

**Comment by karim** [comment]
That's a good idea, and not hard to do. I will label this as enhancement for now.

**Comment by mattwojo** [comment]
Following. :)

**Comment by jramiresbrito** [comment]
Following too :)

**Comment by ActiveChooN** [comment]
Following too

**Comment by GeoffMaciolek** [comment]
Question - if the problem (or part of the problem?) is filesystem locking not being supported (on the `\\wsl$\...` share) - but, opening "readonly" - shouldn't we be able to skip file locking when opening readonly?

**Comment by noyidoit** [comment]
Still no solution ?...

**Comment by noyidoit** [comment]
It seems still no solution

**Comment by Bilalharoon** [comment]
also following

**Comment by jesuscmdev** [comment]
Siguiendo, 
Al intentar abrir un archivo database.sqlite de mi subsistema linux sqlite browser se queda en blanco 
Gracias!

**Comment by DerAlSem** [comment]
It's still there (and following)

**Comment by vbrozik** [comment]
Could you please fix the SQLite Browser to show an error message when opening a database on a `\\wsl$\` file system fails?

DB Browser for SQLite Version 3.12.2 still fails silently.

**Comment by GusSand** [comment]
October 2022, Still fails silently on WSL2 Ubuntu. Windows 10

**Comment by noviceGuru** [comment]
November 2022, same problem

**Comment by justinclift** [comment]
Do other GUI applications works inside WSL?  Aside from Visual Studio Code that is, which has it's own extension based workaround to support it (as mentioned [above](https://github.com/sqlitebrowser/sqlitebrowser/issues/2142#issuecomment-618919630)).

**Comment by xewl** [comment]
What I do as a workaround; I've set up & installed VcXsrv and run sqlitebrowser (and some other AppImages) from within WSL2.

**Comment by justinclift** [comment]
Ahhhh, interesting.  That's the "set up an X server" approach @karim mentioned.  Does it work decently well?

**Comment by rickh57** [comment]
WSLg works for this. That avoids the need to configure VcXsrv, and WSLg is now available for Windows 10 and Windows 11. (I've tried this from one of my Win11 systems -- I haven't confirmed that it works on my Win10 systems, but I've launched other Linux GUI apps there and expect it to work).

**Comment by justinclift** [comment]
Awesome!  That [WSLg](https://github.com/microsoft/wslg) thing looks useful for people. :smile:

@GusSand @noviceGuru @DerAlSem @Bilalharoon @guluguru @ActiveChooN @mattwojo @tomlagier This seems like it might be the right solution, at least for now. :smile:

**Comment by rickh57** [comment]
I'm using the version of sqlitebrowser that I install using apt.

**Comment by noviceGuru** [comment]
@justinclift Actually this was my problem: 
I used to think using SQLite browser in Windows, if I browsed to the correct directory to pick up my DB file (which is in my WSL), the browser would work, but I was wrong. The only way is to run it from WSL itself, and having Xserver , run the app graphically.
So you'll have to install Xserver on your Windows, get it running and test it, then use apt to install SQLite browser and then run it.
This link worked for me to get my Xserver running (which was a headache):
https://aalonso.dev/blog/how-to-use-gui-apps-in-wsl2-forwarding-x-server-cdj

**Comment by rickh57** [comment]
With the latest WSLg, you don't have to install an Xserver yourself; it's built into WSL itself.

**Comment by xewl** [comment]
> and expect it to work).

Wasn't aware of WSLg myself either, cheers for the heads up!

**Comment by rickh57** [comment]
I installed and ran sqlitebrowser in WSLg on my Win10 systems and it worked fine there, too.

**Comment by justinclift** [comment]
Awesome! :smile:

**Comment by jlw4049** [comment]
WSLg works great. Thanks for the tips!

**Comment by Because789** [comment]
Since we have a good solution with WSLg, I'm gonna close this issue.

**Comment by vbrozik** [comment]
@Because789 using WSLg is a workaround. It is probably not suitable for everyone and the original bug is still there. I do not understand why this is considered to be a reason for closing the issue?

**Comment by chrisjlocke** [comment]
> but that SQLite Browser does not show any error message

Don't shoot the messenger.
If DB4S cannot see a file to open, it cannot open it.  It cannot cast spells and summon the file to appear if the OS doesn't show it.
WSL is a 'feature' and it doesn't guarantee 100% that everything is going to work 100% with everything else.

**Comment by parastooam** [comment]
That is great, thank you @kelle

**Comment by peuris** [comment]
> I found this thread useful and just want to add some more details.
> 
> * The error we got was a "Database is locked" message. So, at least there's an error message now!
> * In order to install SQLite Browser in WSL, follow the install instructions for Ubuntu on the [Downloads page](https://sqlitebrowser.org/dl/). Currently, these are the commands to run from a WSL Terminal:
> 
> ```
> sudo add-apt-repository -y ppa:linuxgndu/sqlitebrowser
> sudo apt-get update
> sudo apt-get install sqlitebrowser
> ```
> 
> * It then shows up as an app in the Start menu.

Awesome @kelle - been looking for this solution for a while! - coffee on me :)

**Comment by KraXen72** [comment]
Hello,
i would like to ask for this issue to be re-opened. Running sqlitebrowser through wslg is not great, and it'd be better to add support to the windows-side sqlitebrowser to open wsl files. 
If they cannot be opened over the local network, instead of throwing an error, it should copy them to the windows equivalent of /tmp, and if any changes are done and it's saved, overwrite the file in wsl destination (optional, i mostly use it for read-only).

**Comment by chrisjlocke** [comment]
As mentioned above, why are you opening the database in WIndows, and not from wsl itself?

**Comment by KraXen72** [comment]
> As mentioned above, why are you opening the database in WIndows, and not from wsl itself?
  
I use windows explorer to explore files, even in wsl. i wanted to check the database files' contents. i double-clicked, and since i have db browser for sqlite installed on windows, it attempted to open it. 
I could either:
- I could install exclusively through wsl, in which case, opening windows-side db files unnecessary goes through WSL and WSLg
- I could install both versions, but then there might be confusion about default apps for opening `.slqlite` and `.db` files, and it's not great to have both versions of the app installed

Additionally, WSLg often doesn't provide enough information, themes or libraries to linux GUI applications to look even remotely good. I haven't tested this with sqlitebrowser in particular, but I remember that opening Vorta, a modern QT app through wslg which on my other linux install looks in line with the rest of qt apps, looked straight out of 1998. in WSLg, It's laggier, the crusor is different, and resizing is choppy. In general WSLg is impressive technically but I don't think it should be the primary way to use any application on windows.

**Comment by chrisjlocke** [comment]
But if it solves your problem, its worth a go, oui?

**Comment by JannetGen** [comment]
One thing I’d try is opening a copy of the database instead of the original, especially if another process might still be using it. Also worth checking the DB Browser and SQLite versions, since some older builds can behave differently with newer database features.
