### ISSUE TITLE
How to build for x32 bit architecture

### ISSUE THREAD

**Issue by JacksiroKe** [sqlitebrowser/sqlitebrowser#2157]
How can I setup Configuration and Platform combination of Debug|Win32?
-----------------------
I have no problem building for x64 bit since your tutorial for windows is pretty straight forward on that. I recently tried for x32 and got the following error
`C:\dev\sqlitebrowser>cmake -G "Visual Studio 16 2019" -A x86 -Wno-dev
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17763.
CMake Error at CMakeLists.txt:1 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 06-Mar-20 13:55:40.
    Project "C:\dev\sqlitebrowser\CMakeFiles\3.16.2\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(379,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|Win32. [C:\dev\sqlitebrowser\CMakeFiles\3.16.2\VCTargetsPath.vcxproj]
    Done Building Project "C:\dev\sqlitebrowser\CMakeFiles\3.16.2\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\dev\sqlitebrowser\CMakeFiles\3.16.2\VCTargetsPath.vcxproj" (default target) (1) ->
    (PrepareForBuild target) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(379,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|Win32. [C:\dev\sqlitebrowser\CMakeFiles\3.16.2\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:31.77

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/dev/sqlitebrowser/CMakeFiles/CMakeOutput.log".`

I have:

1. Windows 10 x64
2. Visual Studio 2019 Community
3. Qt 5.9.9

**Comment by justinclift** [comment]
As a general thought, the script we run each night for building 32-bit on Windows would probably be useful:

https://github.com/sqlitebrowser/sqlitebrowser/blob/master/installer/windows/nightly_build_scripts/win32build.bat

Note that it sets up a bunch of paths to point to various directories on the local system (eg temporary build directory, etc).  There are also paths in the CMakeLists.txt file that need to be correct for your system as well.  eg the location of the 32-bit Qt install, as you can't use the 64-bit one for both 32 and 64-bit.

The `cmake` you used looks slightly different to [ours](https://github.com/sqlitebrowser/sqlitebrowser/blob/b0bca100c0be0629f794b906d0292d94fd3efdf8/installer/windows/nightly_build_scripts/win32build.bat#L88), but that might be because you're using a newer version of MS Visual Studio.

Hopefully that helps.

**Comment by karim** [comment]
I think you need to start the "x86 Native Tools Command Prompt for VS 2019" and run commands from this window, as it will set up the build environment for the 32-bit build.

**Comment by JacksiroKe** [comment]
That doesn't work at all because yourself you are "thinking" about it. Actually as @justinclift suggested the nightly build scripts sorted me

**Comment by justinclift** [comment]
From memory the "x86 Native Tools Command Prompt" (and similar for the x64 one...) just run a standard command shell, but with a addition of running a batch file that sets a few environment variables to point at things.  eg probably PATH and similar

We run the exact same batch file to set the environment variables in our nightly script, so it can be run from the stock standard cmd.exe.  Keeps things simple. :smile:

That being said, it was created several release of Visual Studio ago, so MS may have updated things to use some other approach since.

**Comment by justinclift** [comment]
> the nightly build scripts sorted me

@JacksiroKe Sounds like success?  Are we ok to close this issue? :smile:

**Comment by karim** [comment]
> That doesn't work at all because yourself you are "thinking" about it.

I'm not sure what do you mean by this. "x86 Native Tools Command Prompt" is required to build the 32-bit version.

Our tutorial ([in the wiki](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Setting-up-a-Win64-development-environment-for-DB4S)) is aimed at building the 64-bit version, so the [cmake step](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Win64-setup-%E2%80%94-Step-11-%E2%80%94-Generate-MSVC-solution-file) starts the "x64 Native Tools" instead. Your build is failing at this step so I assumed it is a platform/target mismatch.

> Actually as @justinclift suggested the nightly build scripts sorted me

Yes, since the build script starts/calls the correct platform native tool automatically for you, before running `cmake`.

-----

To be honest, I believe building on Windows could be improved by switching it from using `cmake` to `nmake` which comes already with Visual Studio. Or, bundle Visual Studio solution/project files in the repo. Either one will remove the dependency on `cmake` and will make building on Windows a little bit better.

**Comment by scottfurry** [comment]
> To be honest, I believe building on Windows could be improved by switching it from using `cmake` to `nmake` which comes already with Visual Studio. Or, bundle Visual Studio solution/project files in the repo. Either one will remove the dependency on `cmake` and will make building on Windows a little bit better.

No. CMake can be made to be 'platform' aware and adjust.

As for "bundling solution files", that IMHO, is a non-starter. One look at the mass pollution of solutions files in other project repo's shows an incredible ugly mess. Maintaining a solution file for each and every relevant Video Studio version produced is time consuming and a waste for non-Windows users.

There is more to the world that what M$ produces.

**Comment by justinclift** [comment]
Yeah, let's just keep with the CMake approach, for now at least. :smile:

**Comment by justinclift** [comment]
Going to close this issue, as it seems the original reported problem is solved.  That being said, I'm not trying to stop conversation / flame war :wink: / about MSVC solution files vs other stuff. :grin:
