### ISSUE TITLE
Unable to open DB Browser for SQLite after installing 

### ISSUE THREAD

**Issue by ajilly** [sqlitebrowser/sqlitebrowser#2167]
What is your question
-----------------------
Hi, am unable to open the application after installation. Currently, using Mac OS X 10.9.5 (yes, pretty old version); had difficulty updating the version over the years and this is the last updated version. 

Had tried to install (latest release (3.11.2) for macOS) twice but to no avail; received similar errors (attached here). Believe it could be due to the version of my Mac. Was wondering if the team do have the older version for me to download? 

Thank you. 

![sqlite browser _error ](https://user-images.githubusercontent.com/55618826/77380338-c9c72080-6db5-11ea-89e7-566e92d726ab.jpg)

**Comment by justinclift** [comment]
Ahhh.  Yeah, that's very likely due to the older version of OSX you're using.

There are a couple of potential things to try out, to figure out the best direction to take.

It also depends on what you're trying to do. :smile:

If you don't mind using an older version of our application, then try these out and see if one of them works:

* https://nightlies.sqlitebrowser.org/osx/2017-09/DB%20Browser%20for%20SQLite_20170905.dmg
* https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.10.1/DB.Browser.for.SQLite-3.10.1.dmg
* https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.9.1/DB.Browser.for.SQLite-3.9.1v2.dmg
* https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.8.0/sqlitebrowser-3.8.0v5.dmg
* https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.7.0/sqlitebrowser-3.7.0.dmg

Be aware that the much older versions of the application **might** not work with the latest and greatest database files (!).  Thus the "depending on what you want to do" thing above. :wink:

There's still another approach that **might** work, which is to compile the application yourself.  That will need XCode already installed on your Mac, which might be a pain if you don't have it already.

Does any of the above help? :smile:

**Comment by ajilly** [comment]
Hi Justin, 
Thank you for your swift response.   :)
I tried to download via this link , https://github.com/sqlitebrowser/sqlitebrowser/releases/download/v3.10.1/DB.Browser.for.SQLite-3.10.1.dmg and I could open the application. Am going to give it a try in a while. Will update if its all good to go or if I still need aid. 
Thank you. Cheers

**Comment by justinclift** [comment]
You're welcome.  Sounds like a plan. :smile:

**Comment by justinclift** [comment]
@ajilly How did this go? :smile:

**Comment by ajilly** [comment]
hi Justin! 
i got carried away after i started using the application. it went well. i did my assignments and submitted them smoothly. thank you for your help earlier and follow up here. was super helpful! 

stay safe 
cheers

**Comment by justinclift** [comment]
Awesome! :smile:

**Comment by Uniful** [comment]
Hello there, years after, in 2024, i am still using mac os 10.12 so thank you for your help, problem post, and link to the older version of DB browser.

**Comment by JannetGen** [comment]
I’d start by testing with a copy of the database and making sure no other process has the file open. If the issue still shows up, checking the SQLite/DB Browser versions and trying the same operation on a small test database could help isolate whether it’s the file or the tool causing it.
