### ISSUE TITLE
The program can't start because MSVCR120.dll is missing from your computer

### ISSUE THREAD

**Issue by akeel1983** [sqlitebrowser/sqlitebrowser#2182]
Details for the issue
--------------------

#### What did you see instead?

Useful extra information
-------------------------
> DB4S v3.11.2 [built for i386-little_endian-ilp32] on Windows 8.1 (winnt/6.3.9600) [i386]
> using SQLite Version 3.27.2
> and Qt 5.7.1

**Comment by justinclift** [comment]
Ahhh yeah.  We've seen this before, as it turns out one of the components used somewhere needs it.

We're getting things ready for our next release, so we'll probably make sure it's fixed in that. :smile:

In the meantime, the Microsoft MSVC (2013 ?) redistributable from here should fix the problem:

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by justinclift** [comment]
@akeel1983 I think this is fixed now, in today's nightly build onwards:

* https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.msi

Are you ok to try that, and let us know?

**Comment by justinclift** [comment]
Closing this due to lack of response.
