### ISSUE TITLE
Error whenever I try to insert values to a table

### ISSUE THREAD

**Issue by mandudeman** [sqlitebrowser/sqlitebrowser#2212]
Details for the issue
--------------------
I get this error whenever I try to insert values to a table. This is the error: Error while saving the database file. This means that not all changes to the database were saved. You need to resolve the following error first.  FOREIGN KEY constraint failed (RELEASE "RESTOREPOINT";) I am using SQLite version 3.11.2 on Windows 10.

#### What did you do?
I inserted values to the table. I then tried to write the changes. After clicking the write changes button, I got this error.

#### What did you expect to see?
I expect the values to be added and saved into the table as new records.

#### What did you see instead?
The values were not accepted as new records and I got the error.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ _10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.0-(alpha or betas)
- [x] 3.11.2
- [ ] 3.11.1
- [ ] 3.10.1
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by chrisjlocke** [comment]
There are 'rules' on the table, preventing you adding a new record.  For example, table A holds data which references table B.  Eg, a "country" value.  Rather than stating the country as "United States", you simply use number 3, and another table holds "United States" in record #3.
However, you're trying to create a record referencing #4, but that record doesn't exist.  There is no record #4.

Just ensure the data you're trying to insert is valid.
Insert the referencing data first.

**Comment by mandudeman** [comment]
Thank you very much for the feedback. I will try to figure out where the problem lies base from your idea. It is my first time to post an issue here. It is my mistake. Please accept my humble apology for it. Rest assured that I will be more cautious and compliant with my future posts. Thank you very much again.

**Comment by chrisjlocke** [comment]
> Rest assured that I will be more cautious and compliant with my future posts.

Its not a problem - just didn't know if you were aware or not.

If the data you're using isn't sensitive, feel free to provide some screenshots, and we can assist with more knowledge of whats going on.
Also, rather than just report an error when doing X, explain why you're doing this - sometimes, you're getting an error because you should be doing Y instead - there is no need to do X.  
Good luck with your playing with DB4S, and thanks for taking the trouble to raise an issue.  Don't be afraid to yell if you have any further issues.

**Comment by chrisjlocke** [comment]
Closing this as the initial query has been addressed.  Please feel free to comment further if you have continuing problems.

**Comment by mandudeman** [comment]
Thank you very much.
