### ISSUE TITLE
Default Directory After Opening a DB should be last Successful opened Directory

### ISSUE THREAD

**Issue by jmagyari** [sqlitebrowser/sqlitebrowser#224]
After Opening a DB, then Opening an additional DB the Browser should start from the directory where the last Successful Open occurred

**Comment by justinclift** [comment]
Yeah, I tend to agree with this.  Had the same thought the other day, but didn't get around to turning it into a proper issue here.

Thanks for doing so. :smile:

**Comment by justinclift** [comment]
Hmmm... actually no, I've just remembered we've had discussion about this before and it turns out there are several viewpoints on it.  (it's in previous issues here if you want to investigate)

There is a way forward, but I'd need to go and dig through the issues again myself to refresh my memory first... :wink:

**Comment by Z4us** [comment]
Your default directory will be opened by default. Works for me. Another way is to open one of the last five opened databases.

**Comment by MKleusberg** [comment]
This should be fixed in the 3.7.0 release where we've introduced a new option to the Preferences dialog to change this behaviour. This way everybody should be happy :smiley:
![lastlocation](https://cloud.githubusercontent.com/assets/3153504/8273318/9c697f04-1868-11e5-9791-7dce9ff25cfe.png)
If there are no objections I think we can close these issue soon.

**Comment by justinclift** [comment]
Good thinking @MKleusberg. :smile:

@jmagyari Have you had a chance to try out the new behaviours in our recent 3.7.0 release? :smile:

**Comment by MKleusberg** [comment]
Closing this as it's been reported to work in issue #276. If there still should be any problems with this feel free to re-open the issue or open a new one.
