### ISSUE TITLE
Browser just crashes after executing this query

### ISSUE THREAD

**Issue by lallousx86** [sqlitebrowser/sqlitebrowser#228]
Hello,

Start with a new DB and go to SQL tab and execute:

CREATE TABLE customer(
         id INTEGER,
         firstName TEXT,
         middleName TEXT,
         lastName   TEXT,
         address TEXT,
         contactNum TEXT
);

 CREATE TABLE item(
        id INTEGER,
        name TEXT,
        description TEXT
 );

 CREATE TABLE orders(
        id INTEGER,
        customerID INTEGER,
        date TEXT,
        FOREIGN KEY(customerId) REFERENCES customer(id)
 );

 CREATE TABLE item_order(
        id INTEGER,
        orderID INTEGER,
        itemId  INTEGER,
        quantity INTEGER,
        FOREIGN KEY(orderId) REFERENCES orders(Id),
        FOREIGN KEY(itemId) REFERENCES item(Id)
 );

After you execute this, save the db.

Now switch to the "Database structure" tab, and SQLite Browser will simply close!

Now anytime you try to open that DB, the browser crashes!

**Comment by lallousx86** [comment]
I forgot to mention, I am running on Windows.

**Comment by MKleusberg** [comment]
The problem here was that the spelling of the columns used in the foreign key clauses are different from those actually used in the table definition. See here for example 'customerID' vs 'customerId' (note the final letter 'd'):
```sql
CREATE TABLE orders(
  id INTEGER,
  customerID INTEGER,
  date TEXT,
  FOREIGN KEY(customerId) REFERENCES customer(id)
);
```
Of course this should work anyway and a crash is a bit of a overdramatic reaction :smile: I've just pushed a fix for this issue. If you want to try out the latest version with the fix applied you have to use our nightly builds from http://rp.oldsch00l.com/sqlitebrowser/ Luckily, because it's already night here in Europe, the new version should be there in half an hour or so.

**Comment by justinclift** [comment]
@lallousx86 Would you be ok to try out the nightly build, and let us know if it does or doesn't work well for you now? :smile:

**Comment by lallousx86** [comment]
Thanks for the efforts. I will try that Monday when I am back in the office.

**Comment by justinclift** [comment]
@lallousx86 Reminder ping... :smile:

**Comment by lallousx86** [comment]
thanks. it works. much appreciated.

Sent from Yahoo Mail on Android

**Comment by justinclift** [comment]
Awesome.  Thanks for checking and confirming back to us @lallousx86. :smile:
