### ISSUE TITLE
doesn't fit 1200x1600

### ISSUE THREAD

**Issue by 532910** [sqlitebrowser/sqlitebrowser#2284]
The smalles width is 1299px, my monitor is 1200:
![image](https://user-images.githubusercontent.com/14617699/84415008-d459bf00-ac1a-11ea-9ad8-c1cd749db824.png)

sqlitebrowser 3.11.2-1+b1, debian sid

**Comment by justinclift** [comment]
Ouch.  That sounds like one of our window size definitions is too big.

Um... if you're ok with compiling source code, would you be ok to try our latest development code?

There are instructions for building on Ubuntu, and I'm pretty sure people have said the Debian building is identical:

* https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu-linux

Asking because although the 3.11.2 code is our latest official release, we've done a tonne of work on the upcoming one (3.12.0) that's due next week.  If our development code has the same problem, there's a decent change we can adjust the minimum sizing in time for next week's release. :smile:

**Comment by 532910** [comment]
master brunch works fine!

**Comment by justinclift** [comment]
Awesome! :smile:
