### ISSUE TITLE
[Suggestion] Close project

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2289]
While looking at another issue, once you've opened a project file, you're kind of locked into it and its not overly clear that you are.  If you click on 'New Database', you're still in the project.  There doesn't seem a way of closing a project.  If you click on 'Close Database', even that doesn't close the project file.

I thought this was mentioned, but I couldn't see anything by searching for 'close project'.  

Closing DB4S and reopening it seems a bit 'hacky'.

**Comment by scottfurry** [comment]
My ‎€/$ 0.02, this should be folded into UI redesign. Projects _could_ be a side tab showing current open project (with own controls and/or toolbar).

**Comment by mgrojo** [comment]
At some point I changed the behaviour so the "Close Database" would close the project, if one was already in use, returning to the original state when the application is open without any input file. That was my understanding of how it should behave, but then a @sky5walk asked to return to the old behaviour because he was used to that and had convincing arguments to preserve it. See discussion in #2027.

The current way to "close a project" is to save as a different filename and then you can escape from the project file... to be locked in the new one :smile:

Yes, I suppose that if projects have a longer lifecycle than database files, we should have a proper way to close the project and return to the original state, when no files are open.

**Comment by sky5walk** [comment]
Yeah, I would table this for the UI redesign. Yes, projects can apply to more than 1 database, so their open close mechanism must be separate.

**Comment by mgrojo** [comment]
The "Close Project" action will be present under the File menu in the next nightly build. @chrisjlocke any interest in testing it?

**Comment by chrisjlocke** [comment]
> @chrisjlocke any interest in testing it?

No, I'd rather stick forks in my eyes.
Oh, go on then.  😄

**Comment by MKleusberg** [comment]
I'm closing this as it seems to be working fine and it's an old-ish issue :smile:
