### ISSUE TITLE
Sort order reversed when browsing data

### ISSUE THREAD

**Issue by Krisell** [sqlitebrowser/sqlitebrowser#2300]
Details for the issue
--------------------

#### What did you do?
See this image, the "sorting icon" shows that larger values should be on top, but the actual order is reversed.
![image](https://user-images.githubusercontent.com/25909128/85669977-b4b5a280-b6c0-11ea-9137-9c13b1a23f02.png)

#### What did you expect to see?
That the "sorting icon" (the black triangle) shows which direction values grow vs shrink, where larger values correspond to the wider end.

#### What did you see instead?
The opposite.
I have used DB Browser for SQLite for a long time and never noticed this before, so either this was reversed in the latest version, or the triangle was added in the latest version?

A side note (perhaps a separate issue): The icon looks completely different for the two sorting orders.

Useful extra information
-------------------------

#### What operating system are you using?

- [x] macOS: (10.15.5)

#### What is your DB4S version?
- [x] 3.12.0

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Heh Heh Heh.  Whatever the fix for this is, it sounds like it should go into the 3.12.1 point release. :smile:

**Comment by mgrojo** [comment]
The arrow has a different shape because it is now a character, instead of the standard image used by Qt/Platform. I've checked v3.11 and it used the same meaning for the arrow direction. What has changed is that v3.11 sorts descending on the first click and ascending later. The new release sorts ascending in the first click (arrow pointing upwards) and after second click, descending (arrow pointing downwards).

In Thunderbird the meaning of the arrow in the folders is the same as ours. The same for Ubuntu's file manager. Both start to sort in ascending order. LibreOffice Spreadsheet does not show any arrow after sorting.

Consequently, I wouldn't change anything.

I cannot understand why the arrow has that suspicious look :shit: in Windows, sorry :smile:

**Comment by Krisell** [comment]
Thanks @mgrojo for the info. I understand now that this is not standardized, although what you're writing `descending (arrow pointing downwards)` does not correspond with the image I added, so I guess you mean the other way around?

I checked the Finder in macOS and Twitter Bootstrap table sorting and they use wider end up to mean descending order, but I'm ok with either since there is no consensus between different applications.

**Comment by mgrojo** [comment]
> Thanks @mgrojo for the info. I understand now that this is not standardized, although what you're writing, `descending (arrow pointing downwards)`, does not correspond with the image I added, so I guess you mean the other way around?

Yes, sorry, I got mixed up.
