### ISSUE TITLE
Persistent Column Sizes?

### ISSUE THREAD

**Issue by shaun-ba** [sqlitebrowser/sqlitebrowser#2314]
I'm not 100% sure if this is a feature request or a bug, but is so annoying! Every time I open my DB for editing the column sizes reset and I have to resize them all to fit on my screen :)

**Comment by chrisjlocke** [comment]
If you set the columns sizes you want, then click 'File' then 'Save Project', the 'working environment' (SQL tabs, sizes, et al) should all be saved.

![image](https://user-images.githubusercontent.com/7872218/86221899-6a7b6800-bb7d-11ea-9dce-2fcccfe98f84.png)

The associations may not be configured (depends if you've installed DB4S or just extracted it) but double-clicking a .sqbpro file should open the project as well.

![image](https://user-images.githubusercontent.com/7872218/86222035-98f94300-bb7d-11ea-810e-9074c23ec8b1.png)

Rather than open the database, open the project file instead, and all your column sizes should be retained.

Yell back whether this works OK for you.

**Comment by chrisjlocke** [comment]
*cough*

Have you tried this yet @shaun-ba ?

**Comment by shaun-ba** [comment]
Yes works great thanks.

Just as my other issue would be nice to have a more flexible way to show/hide columns when editing tables with lots and lots of columns which mine does.

Looking at how the project works I guess I could have a project for certain types of edits where all the columns are correctly hidden and save them as different filenames

**Comment by chrisjlocke** [comment]
Excellent, thanks for reporting back. 👍
