### ISSUE TITLE
[Suggestion] Use a local database to store settings

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2317]
Describe the new feature
--------------------------
In Windows, we use the registry to store personal settings.  This means the program isn't portable.  I don't know how this works for Linux or Mac.
We could use an SQLite database to store settings, which would mean they're easily transferable between different PCs - especially in a school environment.
I don't know if the database would be stored with the application (meaning one setting for all users) or 'somewhere else' which would go against the 'being a portable application then', but allow 'per-user' settings... 
Just strikes me as odd that a database maintenance application doesn't 'eat its own dog food' and settings are stored by the OS (bit like project files, but that's another argument).  
Anyway.  This comment fuelled this suggestion:

> @justinclift Portable version is something I wanted to create but it requires a bit of changes in the code 
since the application is saving its config in Windows Registry. To get a true portable version the app should save its config in its own directory.

Anyway.  Just a suggestion.  Realise it would be a lot of work, but 'theoretically' its just two functions - one to load a setting and another to save it, then rattle through the code finding where we load/save/get users' settings (once I assume on program load... but there might be more dynamic checks...)

Additional info
---------------
Please answer these questions before submitting your feature request.

#### Is your feature request related to an issue? Please include the issue number.
Yes.  Various.

#### Does this feature exist in another product or project? Please provide a link.
Yes.  Various.

#### Do you have a screenshot? Please add screenshots to help explain your idea.
No.

**Comment by lucydodo** [comment]
I don't know why the discussion about this suggestion doesn't continue.
While implementing my enhancement idea recently came up with, I leave a comment because it is relevant to this issue.

When manage settings through the QSettings class, the setting values are
- Windows : Registry
- Linux : ~/.config
- macOS : ~/Library/Preferences

stored in.

For now, we initialize QSettings like this (`src/Settings.cpp:29,45`)
`QSettings settings(QApplication::organizationName(), QApplication::organizationName());`
but if initialize as follows, it is saved as a file in the db4s execution path.
`QSettings settings(db4sconfig, QSettings::NativeFormat);`

I think we can modify the code to give us the option to build a portable version by modifying the preprocessor directives and CMakeLists. What do you think about this?

I also attach a screenshot with the code applied.
![Screenshot from 2020-08-25 23-46-54](https://user-images.githubusercontent.com/64626662/91189568-8cccd480-e72d-11ea-8eb4-ba47863d1d6d.png)

**Comment by chrisjlocke** [comment]
Don't forget that @justinclift is working on storing SQLite databases in the cloud, so another 'bonus' of this, is that theoretically, the settings database doesn't even have to reside on the PC, but be 'c;loudable' (is that even a word?! 😉 )  I'm sure millions would choke on their cereal if DB4S was that cloudable, but could still be a nice feature ...

**Comment by lucydodo** [comment]
@chrisjlocke Ahh.. I understand what you said. I simply understood that your issue was change the save DB4S settings to a local file instead operating system dependent, but I didn't think about managing it by a cloud-based.

**Comment by chrisjlocke** [comment]
Well, the cloud-based is an 'optional extra' at some point down the line.  I think using an SQLite database for the settings would be a good step to make the application portable and more system independent.  I guess Qt handles the OS-specific settings saving anyway ... but from a support angle, if (for example) a user-setting had to be reset, it would be easy to get the user to reset it - explaining to a user how to rummage around in the registry is quite a feat.

**Comment by lucydodo** [comment]
@chrisjlocke It's a good idea, of course, but I think using SQLite Database to manage program settings is likely to increase the overhead because there are not many or complicated settings value. (It's just my thoughts, I don't mean to disparage you.)

**Comment by mgrojo** [comment]
I'm with @lucydodo on this. If the goal is to make a fully portable version of DB Browser, using the already built-in portability of QSettings is straightforward. But I wouldn't make two different builds, it will be useful for everyone to have a command-line option or an environment variable to switch to the portable mode setting a configuration file. The appropriate QSettings constructor when a configuration file is specified would be:

`QSettings(settingsFilename, QSettings::IniFormat);`

Examples (Linux command line):
`sqlitebrowser --config DB4S.ini`

```
export DB4S_CONFIG_FILE=/home/teacher/DB4S_SQL_course.ini
sqlitebrowser
```
But the native format would be the default, as currently.

In this way, the INI file could be shared between people to use common settings (good for education, for example, @dmalan :wink:), or one could have a set of different settings for personal use, or move your settings to another computer, even on different OS.

What do you think about this? I step forward to implement it, unless you are interested in doing it yourself, @lucydodo.

I don't know if @chrisjlocke will be satisfied :wink: but the author of #1872  should be :smile:

**Comment by chrisjlocke** [comment]
> I don't know if @chrisjlocke will be satisfied

I'm all for an easy solution.  😉 
If an .INI file is a viable solution, then that's fine.  You could argue .INI is old technology and it should be JSON these days, but I'm joking! 😆

**Comment by lucydodo** [comment]
Opinions seem to be narrowed down. Let me try it once :)

**Comment by dmalan** [comment]
Just to chime in with an educational use case in mind, if we were to distribute some standard settings to students for a class, I think we'd ideally want the workflow to be as simple as, e.g.,

1. Download and install DB Browser for SQLite.
1. Download "this settings file."
1. Launch DB Browser for SQLite, select **File > Load Settings**, and navigate your way to that file.

rather than have students have to place the settings file in a particular location, which might be painful to explain cross platform-wise.

No strong feelings on file format, though if it were to be a SQLite file, I do imagine it'd be ideal for the file extension not to be, e.g., `.db`, as some students will invariably open rather than save the file with their browser, or double-click on it once downloaded, in which case they'd open and see the settings rather than load them.

Thanks for considering!

**Comment by mgrojo** [comment]
> You could argue .INI is old technology and it should be JSON these days, but I'm joking! :laughing:

Ok, let's call it toml and then it's ipso facto modern and super-trendy :laughing:

**Comment by scottfurry** [comment]
> > You could argue .INI is old technology and it should be JSON these days, but I'm joking! laughing
> 
> Ok, let's call it toml and then it's ipso facto modern and super-trendy laughing

_Modern_. You use that word. I don't think it means what you think it means.

**Comment by mgrojo** [comment]
> > Ok, let's call it toml and then it's ipso facto modern and super-trendy laughing
> 
> _Modern_. You use that word. I don't think it means what you think it means.

Don't know for you. For me, modern means _moderno_ :wink:

**Comment by lucydodo** [comment]
@dmalan I just updated code to support user-custom configuration file.
It still only works on the command line, but as you said, I'll suggest to load a user configuration file in a GUI environment, and if agree suggest, I'll implement it. Thanks for the great idea! 😄

**Comment by lucydodo** [comment]
Um... I think the below commits are going on so we can close this issue.

- Add the ability to support custom config files : 0644bc094fa874012f47172a4175625aea282e8c
- Allow users to export or import user-settings file in a GUI environment : 27c2f64dcda40f2b020e9119b65ca5e592375479

Of course, if you have additional opinions, forget me! :smile:

**Comment by chrisjlocke** [comment]
Yes, as an SQLite database as an actual settings store isn't worth the coding hassle, considering its handled by the OS, and a config file makes it portable-ish.
