### ISSUE TITLE
Import from SQL-Dump files is broken since v3.11

### ISSUE THREAD

**Issue by HarryDe** [sqlitebrowser/sqlitebrowser#2323]
Details for the issue
--------------------

#### What did you do?
I tried to import data from a SQL-Dump.

#### What did you expect to see?
Approx. 20,000 records imported into a table

#### What did you see instead?
A syntax error near "DELETE FROM `table`". Removing the DELETE statement resulted in a syntax error near "INSERT INTO ..."

The error was already present in v3.11, upgrading to 3.12 did not fix it.
However, after downgrading to 3.10 the import worked, as it did years before. Hence the bug was most likely introduced in 3.11

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 8.1 (6.3) (winnt/6.3.9600) [x86_64]
> using SQLCipher Version 4.4.0 community (based on SQLite 3.31.0)
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Is there any chance you could email me the dump (or zip of it).  If needed, you could sanitize the data... I'd just need the lump where the error occurs.

What 'possibly' is happening, is that there is no 'standard' for creating a SQL dump file.  Depending on what dumped it, it might have different quotes or formatting.  Additionally, the biggest gotcha is inserting records into a table that hasn't been created yet, or due to foreign keys, a record can't be inserted, as the corresponding record hasn't been inserted yet.  Its a little bit messy...

**Comment by HarryDe** [comment]
@chrisjlocke : I just sent you an email

**Comment by chrisjlocke** [comment]
This appears to be because the .sql file being imported is encoded as UTF-8 (BOM).

![image](https://user-images.githubusercontent.com/7872218/86912483-01fc3000-c115-11ea-862d-7994a53efbfc.png)

If converted to UTF-8 (Notepad++ does this in a simple menu-click) then it imports fine.  👍 

![image](https://user-images.githubusercontent.com/7872218/86912669-4be51600-c115-11ea-8abf-ae3372be6759.png)

Maybe DB4S could detect this file format when importing and do a pre-import cough?  Slightly over my head for these sort of conversions and what DB4S can detect.

**Comment by MKleusberg** [comment]
Should be fixed in the next [nightly build](https://nightlies.sqlitebrowser.org/latest/). Can you give that a try, @HarryDe? :smile:

**Comment by HarryDe** [comment]
Ok, I’ll try tomorrow then and let you know

 

 

 

Von: Martin Kleusberg [mailto:notifications@github.com] 
Gesendet: Mittwoch, 8. Juli 2020 15:39
An: sqlitebrowser/sqlitebrowser <sqlitebrowser@noreply.github.com>
Cc: HarryDe <hd@deedac.com>; Mention <mention@noreply.github.com>
Betreff: Re: [sqlitebrowser/sqlitebrowser] Import from SQL-Dump files is broken since v3.11 (#2323)

 

Should be fixed in the next nightly build <https://nightlies.sqlitebrowser.org/latest/> . Can you give that a try, @HarryDe <https://github.com/HarryDe> ? 😄

**Comment by HarryDe** [comment]
Can you make me a 64-msi? The latest 64 nightly build is of 6. July.

**Comment by MKleusberg** [comment]
Oh you're right. @justinclift Can you check if there was any build failure?

**Comment by justinclift** [comment]
Oops.  I nuked the built win .msi's and logs about an hour ago from the build server Win VM, to free up disk space. :frowning:

As a workaround, I've just kicked off the Win64 build process again manually.  **If** that it completes ok then there should be updated Win64 binaries on the nightlies server in about 30-40 mins. :smile:

**Comment by justinclift** [comment]
The Win64 build process just finished without error. :smile:

@HarryDe New .msi's are here:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

**Comment by HarryDe** [comment]
Works now with UTF-8-BOM
Thanks a lot!

**Comment by HarryDe** [comment]
Perfect, you did even include the unique constraint message.

 

Thanks!

Harry

 

 

Von: Justin Clift [mailto:notifications@github.com] 
Gesendet: Donnerstag, 9. Juli 2020 12:48
An: sqlitebrowser/sqlitebrowser <sqlitebrowser@noreply.github.com>
Cc: HarryDe <hd@deedac.com>; Mention <mention@noreply.github.com>
Betreff: Re: [sqlitebrowser/sqlitebrowser] Import from SQL-Dump files is broken since v3.11 (#2323)

 

The Win64 build process just finished without error. 😄

@HarryDe <https://github.com/HarryDe>  New .msi's are here:

    https://nightlies.sqlitebrowser.org/latest/

**Comment by MKleusberg** [comment]
Awesome :smile: Thanks again for reporting this!
