### ISSUE TITLE
Highlighting Specific Column in Results Pane

### ISSUE THREAD

**Issue by gchan1234** [sqlitebrowser/sqlitebrowser#2343]
What is your question
-----------------------
How to select single column to copy in the results pane after running a sql script. In previous versions (Pre 3.12.0) I can just click on the column name and it selects the whole column but now it no longer works

**Comment by chrisjlocke** [comment]
Oops.  A hacky workaround is to select the first cell, hold down shift, use the mouse to scroll the scrollbar to the bottom, then click in the cell - this will select all cells in between.
Or, ensure the result is just one column (via the select statement) then you can select the whole table by clicking in the top left cell.

**Comment by justinclift** [comment]
This sounds like something we'll want to get working again.  Selecting a column (or multiple ones) is pretty basic functionality.

**Comment by mgrojo** [comment]
The changes to column sorting in Browse Data seems to have broken this. I'll take a look from tomorrow, but there is a workaround working in the query results and the Browse Data tab: select a single cell and then press Ctrl+Space.

**Comment by mgrojo** [comment]
@gchan1234 This should work in [tomorrow's nightly build](https://nightlies.sqlitebrowser.org/latest/) Please, try it and close this issue when you can confirm it.

**Comment by chrisjlocke** [comment]
Thanks @mgrojo - now works!  I'll leave this open for a while for @gchan1234 to confirm.
One /minor/ issue, which has probably been there since day 1 though.  If you click the header to select it, right-clicking the header (as the mouse is already there) does nothing.  You have to move the mouse down to the selection to right-click and select 'Copy'.  Yup, I know - boo hoo - you have to move the mouse a whole 16 pixels?!  First-world problems.  But from a users' perspective, it seems 'wrong' ... Oui?  Whadya think?

**Comment by gchan1234** [comment]
Hi all - I can confirm it works now. Amazing work to all! :)
