### ISSUE TITLE
Duplicate shortcut not working

### ISSUE THREAD

**Issue by rik1301** [sqlitebrowser/sqlitebrowser#2363]
3.12.

In the browse data window, if you select a row and right click it gives an option to duplicate or delete the record.  On the duplicate option it shows a shortcut of CTRL+" .  When pressing these together it doesn't duplicate the highlighted row but instead opens another database on my PC desktop.  If I press it again, it reverts back to the original database.  If I delete the secondary database, it brings up a popup "choose a database file".  Clicking the button itself does indeed duplicate the row and add it at the bottom but why is the shortcut not working ?

This is in Windows 8.1 desktop OS.

**Comment by justinclift** [comment]
Interesting.  This almost sounds like something being triggered in the OS itself.

@chrisjlocke Any ideas? :smile:

**Comment by mgrojo** [comment]
@rik1301 Is the `"` character in your keyboard in the <kbd>2</kbd> key? Are you pressing then:  <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>2</kbd> = <kbd>Ctrl</kbd>+<kbd>"</kbd>? Sometimes this confusion happens when the symbol needs the shift key in your keyboard :smile:

With <kbd>Ctrl</kbd>+<kbd>2</kbd> you're opening the second entry in your recent file list. The second time returns to your first database :smile: By the way, I've added a message in the status bar so at least there is a hint when using the shortcut.

**Comment by rik1301** [comment]
Aha!  Success!  Can confirm that CTRL+SHIFT+2 works for a good duplication at the bottom of the grid !  Thanks. :)

**Comment by rik1301** [comment]
You might like to amend the shortcuts wiki page too.

**Comment by mgrojo** [comment]
> You might like to amend the shortcuts wiki page too.

What do you propose to amend? Take into account that the location (and whether you need to press Shift or not) would depend on the user's keyboard layout. In the English keyboard, for example, I think `"` is over `'` not over `2`.

**Comment by justinclift** [comment]
We could probably cut-and-paste the text of your tip.  Something like:

---

**Note** - If you're trying to do \<not sure what to put here>, but instead a new file opens, then you might need to press the <kbd>Shift</kbd> key as well.

For example, <kbd>Ctrl</kbd>+<kbd>"</kbd> is the short cut for duplicating a row.

However some keyboard layouts need the <kbd>Shift</kbd> key pressed in order to trigger a <kbd>"</kbd>.

For those keyboard layouts, you'll instead need to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>2</kbd>.

---

**Comment by rik1301** [comment]
mgrojo - is it a UK keyboard, so the " is indeed on the 2 key.  What type of keyboards are you guys using?  I thought this was the standard location for it on 'English speaking' country keyboards, but maybe not ?  :scratchchin:

**Comment by justinclift** [comment]
For me, using a "standard international US layout" the `"` key is in the middle row, next to the enter key.  Same row as the "asdf", "jkl;".  The symbol above the number 2 on the number row is "@" on most keyboards.  Not on UK layouts though.

As a data point, I lived in the UK for a few years (until Brexit), and the UK keyboard layout is **weird** to me. :wink:

**Comment by justinclift** [comment]
Ahhh, here's a photo:

https://www.logitech.com/en-au/product/k120?crid=27

That's the "standard" US keyboard layout (that I'm used to anyway). :smile:

**Comment by mgrojo** [comment]
I'm used to the US keyboard layout and I took it as the 'English language' standard, but I remember now that at work we have some keyboards for our customers and the British layout is different and a bit weird to me :smile: But the "weirdest" is the German layout, which exchanges the Z and the Y. In Spain we use a layout where the `"` is in the `2`, so I guessed easily what this issue was.

**Comment by mgrojo** [comment]
I've added a note about this and the Ctrl+1 (etc) shortcuts to the wiki.

https://github.com/sqlitebrowser/sqlitebrowser/wiki/_compare/a5f80e57a394b1be2ebfad780e51781511a55076...903819ceffbdbd3351787739f17b7475e7bc026b

**Comment by rik1301** [comment]
OK good job guys.  Before I bugger off back under my rock, is there an 'undo' function for the data grid view?  I see the shortcuts list says CTRL+Z, but says that this is only for the sql editor.  Indeed, CTRL+Z doesn't seem to do anything in the grid view (nor combined with SHIFT).  I am of course aware of the 'revert changes' button, but that is too much undo-ing! :stuck_out_tongue_closed_eyes:

**Comment by mgrojo** [comment]
No, there isn't an undo operation for the database changes, only a revert button. It was discussed in  #858 and apparently discarded, but it might deserve a second analysis. I think it could be done using [savepoints](https://sqlite.org/lang_savepoint.html).

**Comment by chrisjlocke** [comment]
Closing as the original query has been de-queried.
