### ISSUE TITLE
How to use SQLite built-in functions in 'Browse Data' grid?

### ISSUE THREAD

**Issue by gnbl** [sqlitebrowser/sqlitebrowser#2387]
How can [SQLite built-in functions such as `random()`](https://sqlite.org/lang_corefunc.html#random) be used / entered in the _Browse Data_ tab / table or the _Edit Database Cell_ tool window so they are evaluated and not just used as string?

The corresponding query would be 

    insert into <table> (<column>) values(abs(random()))

The _SQL Log_  unfortunately does not show the actual query with parameters to be able to see "how it's done", i.e. entering "random()" into a cell results in 

    INSERT INTO "main"."<table>"("a","b","<column>","c") VALUES (NULL,NULL,NULL,NULL);
    UPDATE "main"."<table>" SET "<column>"=? WHERE "_rowid_"='3'

Is there an escape character or hotkey?

I've tried:

```
random()
(random())
'random()'
`random()`
"random()"
=random()
=(random())
='random()'
=`random()`
="random()"
```

Please also add information about this to the wiki.
Thanks!

**Comment by gnbl** [comment]
`=(random())` seems to be working for the _Default_ in _Modify Table_ aka _Edit table definition_

**Comment by chrisjlocke** [comment]
Have you used the Execute SQL tab successfully?
Are you updating one cell or a bunch of them?  Stick a known value in there (eg, rrr) then use SQL to update it.

update _table_
set _field_=random()
where _field_='rrr'

**Comment by gnbl** [comment]
Thanks, it's not about the SQL - the query I posted works as expected.
It's rather that I expected to be able to enter "random()" or another function inside the data editor and have it evaluated.

**Comment by chrisjlocke** [comment]
Yes, unfortunately, DB4S doesn't know _random()_ is a function, so wraps quotes around it, so no matter what you try, it's not going to work.  Until its fixed, I was suggesting a workaround using SQL.  

A fix could be to put quotes around the value, unless it begins with **=**, which would just put the raw value in (but not the prefix '=', obviously...)

**Comment by justinclift** [comment]
It's an interesting idea though.  We could add some kind of thing to the Edit Database Cell panel to "Execute this code snippet in SQLite, and return the result".

So `random()` would be executed as `SELECT random()`, with the cell value then equalling the returned result.

**Comment by gnbl** [comment]
> A fix could be to put quotes around the value, unless it begins with **=**, which would just put the raw value in (but not the prefix '=', obviously...)

Which works until someone needs an actual '=' in the data.
A button / shortcut could modify the cell's behavior.
It would be nice to have the same behavior of the "Default" field.

**Comment by gnbl** [comment]
> So `random()` would be executed as `SELECT random()`, with the cell value then equalling the returned result. Along the lines of what Chris is suggesting, maybe backticks (eg `` `random()` ``) like Markdown uses for signifying code?

Adding something is not neccessary. The problem is to _not_ quote data as is apparently happening now so SQLite recognizes the function call instead of a string. 
The Default cell seems to accept '=' to tell DB4S not to pass a string. But as with all escape characters, it must be outside of the range of the data type. Hence, an additional property for the cell.
As an alternative, DB4S could test the data for expressions (by executing it) to decide whether to escape.

**Comment by mgrojo** [comment]
> 
> 
> > A fix could be to put quotes around the value, unless it begins with **=**, which would just put the raw value in (but not the prefix '=', obviously...)
> 
> Which works until someone needs an actual '=' in the data.

In that case, you can add the quotes yourself and they will be respected. Yes, everything is a bit hacky.

**Comment by justinclift** [comment]
An alternative approach might be to add a new "Function" option to the `Mode` drop down (in the Edit Database Cell pane).  When that's selected and the "Apply" button is pressed, the cell contents are run as a SELECT function then set to whatever value is returned.

**Comment by gnbl** [comment]
Given these choices, I'd prefer '=' as escape character to prevent input quoting, as with the _Default_ cell.
The cell could get a different background color when the first character is '=', to indicate the modified behavior.

I feel adding options and having to click buttons to evaluate and copy resulting data is not worth the effort (for implementation or use) for a function that is already built-in. On the same lines, the user should be able to control the SQL statements generated by editing the table.
Of course, there might be a use case where evaluating (SQLite) statements / expressions for data input is generally useful, but for me that would be a corner case where I would probably _Execute SQL_ directly, as suggested as workaround by @chrisjlocke .

**Comment by chrisjlocke** [comment]
> for a function that is already built-in. 

Indeed.  The 'default' cell does seem to operate on its own logic .. or at least that different to the database browser grid.  Never really used the 'default' option, so haven't followed how it was used, and how the = was significant ... and the brackets.  '=7' doesn't work, it has to be '=(7)' (as an example)

**Comment by mgrojo** [comment]
> An alternative approach might be to add a new "Function" option to the `Mode` drop down (in the Edit Database Cell pane). When that's selected and the "Apply" button is pressed, the cell contents are run as a SELECT function then set to whatever value is returned.

I agree with Justin, the best option is to have a new mode ("Function" or "Evaluation") in the cell editor. This could provide SQL syntax highlighting and completion boxes.

Some points that come to my mind:
- Nevertheless, an automatic switching to this mode could be implemented when entering = in the editor, in the same way as when entering right-to-left text and the mode is switched to the RTL editor. This could be made dependent on the current automatic-mode switching button. User could enter = in the cell editor as text disabling the automatic switching off. (Not totally sure about this point, because it might be obscure for users not knowing the feature).
- Should the entered function be immediately replaced by the evaluated value in the editor when apply is pressed? Or should it be kept until the user moves to another cell or mode editor. Easy option is to be immediately replace it, but the user might want to make some trials, until they are satisfied with the result.
- For this mode it might be useful to apply the same function to all the selected cells (not only to the current one, which is the last selected).  (Maybe this should apply, then, to all the modes for consistency)
- Should the entered expression be validated before passing it to SQLite? Or the user is wise and knows better?
- Now, this requires some time to implement and will add some more complexity. I wonder how useful would this turn to be. Do you imagine specific use cases where the DEFAULT wouldn't be enough? I only came up with: some row is updated and I want to update a LastUpdate cell to `datetime('now')`. But this would be better done with triggers, wouldn't it? For `random()` I only get cases where the DEFAULT is the way to go.

**Comment by chrisjlocke** [comment]
> the best option is to have a new mode

Seems a lot of work.  If it works (sort of) in the default cell by entering '=', why can't it work the same way in this grid?
At the moment, if you type 'foo' or 'bar', it wraps single quotes around it... so if the cell was prefixed with '=', then that part doesn't need to occur.  That way, you could type =random() and it would put the SQL as 'update table set field=random() where id=_whatever_.  This method seems the less-coding approach, but also more user-intuitive for the user.
Just a thought...
Then the default value for a column code would need to be tweaked, to mirror this, so that you don't need to add the (unnecessary) brackets.

**Comment by mgrojo** [comment]
> This method seems the less-coding approach, but also more user-intuitive for the user.

Why? If the user does not know the feature and is trying to enter =something as text in the cell, they will be frustrated when they don't get what they want. I think something more explicit is needed.

**Comment by chrisjlocke** [comment]
OK, no problem. 😃 👍 
So the default cell code will match this more explicit method too?

**Comment by mgrojo** [comment]
@gnbl, I've included a new mode in the DB Cell Editor called Evaluation, which will allow entering built-in functions into the cell. In this mode, the editor supports syntax highlighting and helping tips for the functions. I haven't changed the Default field though. Could you confirm that it works well in the [next nightly build](https://nightlies.sqlitebrowser.org/latest/) so this feature request can be closed?

**Comment by chrisjlocke** [comment]
I'll close this due to lack of response.
@gnbl  - Feel free to comment back if needed.
