### ISSUE TITLE
Why does DBFS force mac to switch to discrete graphics and heat up the laptop ?

### ISSUE THREAD

**Issue by nkonk** [sqlitebrowser/sqlitebrowser#2403]
What is your question
-----------------------
I noticed my macbook pro running hot and running its fans at full speed for a long time, I assumed that it was the docker containers that i was running, but the temps and fanspeed didnt subside when I turned off all the containers too.

After installing gfxcardstatus i noticed that the dbbrowser for sqlite ended up being the only dependency in forcing the laptop to constantly keep using the discrete graphics card and not allowing it to fallback to the Integrated GPU.
After closing db browser for sqlite the fans spooled down and the temps returned to normal.

<img width="285" alt="Screenshot 2020-09-17 at 8 50 43 PM" src="https://user-images.githubusercontent.com/6452437/93493496-96f78280-f929-11ea-93e2-728ebe4adacc.png">

**Comment by lucydodo** [comment]
This issue was reported a while ago and has been fixed. (#2377 and 1e864d3d8b7117b2163229858d96a38b60824391)
However, this has not yet been applied to the stable version, so you can resolve this by using latest [nightly build](https://nightlies.sqlitebrowser.org/latest/) if necessary.
We also inform you that a new stable version will be ready soon.

Sorry for the inconvenience. :disappointed:

**Comment by nkonk** [comment]
No problem,
I'm sorry for the dup question, I tried searching in the issues 
before asking but for some reason couldn't find this one.
Thank you for your time. Appreciate the quick response.

**Comment by lucydodo** [comment]
No need to sorry. Glad the problem was solved and thanks for confirm. :smile:
