### ISSUE TITLE
'DB Browser for SQLite' v3.12.1 is ready for translation

### ISSUE THREAD

**Issue by mgrojo** [sqlitebrowser/sqlitebrowser#2405]
We are in the process of releasing our next stable version (3.12.1) with many corrections and some additions (in the Remote panel).

This is your opportunity to make DB4S better by translating it to your language or updating the translation for this release (when available).

# Available preview builds

You can install one of these builds to see strings in context:

### Windows
* https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/untagged-d1f4169581056518e9b5

### macOS
* https://nightlies.sqlitebrowser.org/osx-prerelease/DB%20Browser%20for%20SQLite-3.12.1-rc1.dmg

# Instructions

The `*.ts` files are already updated on the [`v.3.12.x`](https://github.com/sqlitebrowser/sqlitebrowser/tree/v3.12.x) branch, and we don't plan to modify the strings unless needed to include some correction.

You can read [brief indications here](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Translations) about how to do it. Team members will assist you in the process, in case you had any doubt.

# Notifications 
I'll ping here all the translators who have helped us in the past, so they get a notification. Please, report back if you want to help again. When there are more than one volunteer, they can share out the work and/or review each other translations. Happy translation!

lang | complete | unfinished texts | translators
-- | -- | -- | --
ar_SA | Yes | | @safaalfulaij
cs | | 633 | @MrMarmelade  
de | Yes |  | @FriedrichFroebel
en_GB | | 991 | @glawrence 
es_ES |  Yes | | @mgrojo. Possible reviewer: @lulol 
fr | Yes | | @mvt91
it | Yes | | @Feyn-Man, @GortiZ6 
ja  | Yes |  | @hrwatahiki 
ko_KR | Yes | | @lucydodo. Possible reviewers: @progh2, @ChangJoo-Park 
pl | | 89 | @bartlomiej-przymus, @wojnilowicz 
pt_BR | Yes | | @bernardosulzbach
ru | | 348 | @schdub, @zvova7890, @VanDerSam 
tr | | 88  | @firateski 
uk_UA | | 713 | @keedhost 
zh | | 133 | @bssthu, @mercury233 
zh_TW | | 1029 | @PeterDaveHello 
other | | | Your name here!

Source string changes after translation started:

* None yet

**Comment by hrwatahiki** [comment]
I sent the pull request (Update the Japanese file to v3.12.1 #2407).

**Comment by lulol** [comment]
Having reviewed the new `diff` for the Spanish version, found very little that needs fixing (In fact some of these I think are just cosmetic old typos I made myself!). Great work!

Not sure if I could comment specific lines in a commit like can be done in a pull request, so if you don't plan to modify the strings for this release I hope that it's ok to put them here as reference to check before the next one.

----
https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L254
> Abrir la base de datos

El resto de opciones tienen artículo determinado o pronombre demostrativo, por consistencia aquí se podría añadir en esta línea, aunque en el interfaz haya otros casos en donde se omita y tenga un estilo más telegráfico donde no interesa que el texto sea demasiado largo.

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L5117-L5118
> Simplificar disposición de la ventana

Supongo que puede inferirse por el contexto que se refiere a la ventana ya que el resto de opciones del diálogo lo especifican explícitamente.  Sólo lo marco aquí por dejar nota, lo tengo que comprobar en la interfaz para asegurarme.

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L7099-L7100
> Use esto para descargar una base de datos remota **y** editarla localmente usando una URL provista por la página web de la base de datos.

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L7202-L7205
> Esto descarga una base de datos desde un servidor remoto para edición local. 
 Por favor, introduzca la URL desde la que clonar. Puede obtener esta URL 
 haciendo clic en el botón «Clonar base de datos en DB4S» de la página web 
 de la base de datos.

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L7226-L7227
> Ha realizado cambios en el clon local de la base de datos. Al obtener esta versión sobreescribiría los cambios locales.
> ¿Está seguro de **querer** proceder?

Se podrían eliminar los Usted en donde parecen sonar redundantes.

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L7134-L7135

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L7139-L7140

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L7144-L7145

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L7149-L7150

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L7159-L7160

¿Queda más claro traducir commit como versión o como revisión?


----
Some translations for hotkeys are missing or untranslated

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L2341-L2342
> Alt+Supr.

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L2346-L2347
> Ctrl+Mayus.+C

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L5122-L5123
> Mayús.+Alt+0

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L8641-L8642
> Ctrl+Espacio

----
Angle quotes "«»" are being used inconsistently.
https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L820
> No existe una tabla con el nombre «%1» en el esquema «%2».

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L868-L870
> Error renombrando la tabla «%1» a «%2».
> Mensaje de la base de datos: 
> %3

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L2963
> Importar el archivo «%1» tardó %2ms. De ellos, %3ms se gastaron en la función fila.

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L4889
> ¿Quiere guardar los cambios hechos a las pestañas SQL en el archivo de proyecto «%1»?

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L4910
> ¿Quiere guardar los cambios hechos al archivo de proyecto «%1»?

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L5010
> Abriendo «%1»...
</translation> 

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L5015
> Hubo un error abriendo «%1»...

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L5387
> Proyecto guardado en el archivo «%1»

----
There are some items tagged as `<translated>` but with an empty string instead of tagged `<untranslated>` Not sure if this could be an issue or the framework just will use the source text as if were tagged `<untranslated>`.

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L2654-L2655

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L3205-L3206

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L5569-L5570

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L5533-L5534

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L5574-L5575

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L7029-L7030

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L7114-L7115

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L7546-L7547

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L8097-L8098

https://github.com/sqlitebrowser/sqlitebrowser/blob/5d85ca1a5388228af0ca092b0f51397743b46563/src/translations/sqlb_es_ES.ts#L8510-L8511

That's all I found.

**Comment by mvt91** [comment]
Hi Manuel,

That's OK for me.


----- Mail d'origine -----
De: Manuel <notifications@github.com>
À: sqlitebrowser/sqlitebrowser <sqlitebrowser@noreply.github.com>
Cc: mvt91 <mvt91@free.fr>, Mention <mention@noreply.github.com>
Envoyé: Thu, 17 Sep 2020 21:33:39 +0200 (CEST)
Objet: [sqlitebrowser/sqlitebrowser] 'DB Browser for SQLite' v3.12.1 is ready for translation (#2405)

We are in the process of releasing our next stable version (3.12.1) with many corrections and some additions (in the Remote panel).

This is your opportunity to make DB4S better by translating it to your language or updating the translation for this release (when available).

# Available preview builds

You can install one of these builds to see strings in context:

### Windows
* https://nightlies.sqlitebrowser.org/win32-prerelease/DB.Browser.for.SQLite-3.12.1-rc1-win32.msi
* https://nightlies.sqlitebrowser.org/win32-prerelease/DB.Browser.for.SQLite-3.12.1-rc1-win32.zip
* https://nightlies.sqlitebrowser.org/win64-prerelease/DB.Browser.for.SQLite-3.12.1-rc1-win64.msi
* https://nightlies.sqlitebrowser.org/win64-prerelease/DB.Browser.for.SQLite-3.12.1-rc1-win64.zip

### macOS
* https://nightlies.sqlitebrowser.org/osx-prerelease/DB%20Browser%20for%20SQLite-3.12.1-rc1.dmg

# Instructions

The *.ts files are already updated on the [`v.3.12.x`](https://github.com/sqlitebrowser/sqlitebrowser/tree/v3.12.x) branch, and we don't plan to modify the strings unless needed to include some correction.

You can read [brief indications here](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Translations) about how to do it. Team members will assist you in the process, in case you had any doubt.

# Notifications 
I'll ping here all the translators who have helped us in the past, so they get a notification. Please, report back if you want to help again. When there are more than one volunteer, they can share out the work and/or review each other translations. Happy translation!

lang | complete | translators
-- | -- | --
ar_SA |  | @safaalfulaij
cs |  | @MrJiggers 
de |  | @FriedrichFroebel
en_GB |  | @glawrence 
es_ES |  Yes | @mgrojo. Possible reviewer: @lulol 
fr |  | @mvt91
it |  | @Feyn-Man, @GortiZ6 
ja  |  | @hrwatahiki 
ko_KR | Yes | @lucydodo. Possible reviewers: @progh2, @ChangJoo-Park 
pl |  | @bartlomiej-przymus, @wojnilowicz 
pt_BR |  | @bernardosulzbach
ru |  | @schdub, @zvova7890, @VanDerSam 
tr |  | @firateski 
uk_UA |  | @keedhost 
zh |  | @bssthu, @mercury233 
zh_TW |  | @PeterDaveHello 
other | | Your name here!

Source string changes after translation started:

* None yet


-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/sqlitebrowser/sqlitebrowser/issues/2405

**Comment by mgrojo** [comment]
For your information and planning, this is the current state of each translation in the `v3.12.x` branch:

- `sqlb_ja.qm`
    Generated 1300 translation(s) (1300 finished and 0 unfinished)
    Ignored 2 untranslated source text(s)
- `sqlb_ar_SA.qm`
    Generated 1216 translation(s) (1189 finished and 27 unfinished)
    Ignored 86 untranslated source text(s)
- `sqlb_cs.qm`
    Generated 669 translation(s) (303 finished and 366 unfinished)
    Ignored 633 untranslated source text(s)
- `sqlb_ru.qm`
    Generated 954 translation(s) (820 finished and 134 unfinished)
    Ignored 348 untranslated source text(s)
- `sqlb_de.qm`
    Generated 1231 translation(s) (1208 finished and 23 unfinished)
    Ignored 71 untranslated source text(s)
- `sqlb_fr.qm`
    Generated 1231 translation(s) (1208 finished and 23 unfinished)
    Ignored 71 untranslated source text(s)
- `sqlb_zh.qm`
    Generated 1169 translation(s) (1146 finished and 23 unfinished)
    Ignored 133 untranslated source text(s)
- `sqlb_zh_TW.qm`
    Generated 273 translation(s) (191 finished and 82 unfinished)
    Ignored 1029 untranslated source text(s)
- `sqlb_pl.qm`
    Generated 1213 translation(s) (1193 finished and 20 unfinished)
    Ignored 89 untranslated source text(s)
- `sqlb_pt_BR.qm`
    Generated 1230 translation(s) (1208 finished and 22 unfinished)
    Ignored 72 untranslated source text(s)
- `sqlb_en_GB.qm`
    Generated 311 translation(s) (301 finished and 10 unfinished)
    Ignored 991 untranslated source text(s)
- `sqlb_es_ES.qm`
    Generated 1302 translation(s) (1302 finished and 0 unfinished)
- `sqlb_ko_KR.qm`
    Generated 1302 translation(s) (1301 finished and 1 unfinished)
- `sqlb_tr.qm`
    Generated 1214 translation(s) (1189 finished and 25 unfinished)
    Ignored 88 untranslated source text(s)
- `sqlb_uk_UA.qm`
    Generated 589 translation(s) (484 finished and 105 unfinished)
    Ignored 713 untranslated source text(s)
- `sqlb_it.qm`
    Generated 1217 translation(s) (1194 finished and 23 unfinished)
    Ignored 85 untranslated source text(s)

**Comment by mgrojo** [comment]
> Having reviewed the new `diff` for the Spanish version, found very little that needs fixing (In fact some of these I think are just cosmetic old typos I made myself!). Great work!
> 
> Not sure if I could comment specific lines in a commit like can be done in a pull request, so if you don't plan to modify the strings for this release I hope that it's ok to put them here as reference to check before the next one.

I agree with most of your comments and have addressed them in a new commit: 454fd4a50b210c9e434bb57b54b2e4e9bf3ddd3b

> > Abrir la base de datos
> 
> El resto de opciones tienen artículo determinado o pronombre demostrativo, por consistencia aquí se podría añadir en esta línea, aunque en el interfaz haya otros casos en donde se omita y tenga un estilo más telegráfico donde no interesa que el texto sea demasiado largo.

Hecho.

> > Simplificar disposición de la ventana
> 
> Supongo que puede inferirse por el contexto que se refiere a la ventana ya que el resto de opciones del diálogo lo especifican explícitamente. Sólo lo marco aquí por dejar nota, lo tengo que comprobar en la interfaz para asegurarme.

Cuelga de una entrada de menú que ya dice "Window Layout" así que, por no hacer entradas demasiado largas, creo que está bien así. He modificado otra al mismo nivel para acortarla por consistencia.

> > Use esto para descargar una base de datos remota **y** editarla localmente usando una URL provista por la página web de la base de datos.

Hecho.

> > Ha realizado cambios en el clon local de la base de datos. Al obtener esta versión sobreescribiría los cambios locales.
> > ¿Está seguro de **querer** proceder?
> 
> Se podrían eliminar los Usted en donde parecen sonar redundantes.

Hecho en algunos casos. Con este pronombre hay una delgada línea entre que parezca redundante y que la frase resulte ambigua por confundirse con la 3ª persona.


> ¿Queda más claro traducir commit como versión o como revisión?

No he hecho este cambio. Tengo dudas, tampoco es que esté 100% satisfecho con "versión", pero al menos tiene la ventaja de que usuarios sin experiencia con sistema de control de versiones entenderán el concepto. En el original se usa "commit", como git, y es cierto que tampoco lo entendería alguien profano, ya que ni siquiera se usa como sustantivo en inglés general, sino únicamente como verbo. Pero puestos a traducir en vez de dejar el original, prefiero versión. Incluso se podría decir que "revision" es un "false friend" ya que en inglés tiene un significado de "modificación" o "corrección" que no tiene en castellano.

> 
> Some translations for hotkeys are missing or untranslated

[Hemos tenido problemas con esto](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Translations#dont-translate-key-names-in-shortcuts) y preferimos no traducirlo.

> There are some items tagged as `<translated>` but with an empty string instead of tagged `<untranslated>` Not sure if this could be an issue or the framework just will use the source text as if were tagged `<untranslated>`.

No problem with that. When the translation is empty and finished, the result is the same as copying the original to the translation.
 
> That's all I found.

Great. Thanks for the review.

**Comment by mvt91** [comment]
Hi Manuel,

Not sure it is the good way to send the file.

Here is the latest file (french translation (file sqlb_fr-3.12.1.x.zip, contains sqlb_fr-3.12.1.x.ts) for the branch 3.12.1.x

Best regards

Michel

----- Mail d'origine -----
De: Manuel <notifications@github.com>
À: sqlitebrowser/sqlitebrowser <sqlitebrowser@noreply.github.com>
Cc: mvt91 <mvt91@free.fr>, Mention <mention@noreply.github.com>
Envoyé: Thu, 17 Sep 2020 21:33:39 +0200 (CEST)
Objet: [sqlitebrowser/sqlitebrowser] 'DB Browser for SQLite' v3.12.1 is ready for translation (#2405)

We are in the process of releasing our next stable version (3.12.1) with many corrections and some additions (in the Remote panel).

This is your opportunity to make DB4S better by translating it to your language or updating the translation for this release (when available).

# Available preview builds

You can install one of these builds to see strings in context:

### Windows
* https://nightlies.sqlitebrowser.org/win32-prerelease/DB.Browser.for.SQLite-3.12.1-rc1-win32.msi
* https://nightlies.sqlitebrowser.org/win32-prerelease/DB.Browser.for.SQLite-3.12.1-rc1-win32.zip
* https://nightlies.sqlitebrowser.org/win64-prerelease/DB.Browser.for.SQLite-3.12.1-rc1-win64.msi
* https://nightlies.sqlitebrowser.org/win64-prerelease/DB.Browser.for.SQLite-3.12.1-rc1-win64.zip

### macOS
* https://nightlies.sqlitebrowser.org/osx-prerelease/DB%20Browser%20for%20SQLite-3.12.1-rc1.dmg

# Instructions

The *.ts files are already updated on the [`v.3.12.x`](https://github.com/sqlitebrowser/sqlitebrowser/tree/v3.12.x) branch, and we don't plan to modify the strings unless needed to include some correction.

You can read [brief indications here](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Translations) about how to do it. Team members will assist you in the process, in case you had any doubt.

# Notifications 
I'll ping here all the translators who have helped us in the past, so they get a notification. Please, report back if you want to help again. When there are more than one volunteer, they can share out the work and/or review each other translations. Happy translation!

lang | complete | translators
-- | -- | --
ar_SA |  | @safaalfulaij
cs |  | @MrJiggers 
de |  | @FriedrichFroebel
en_GB |  | @glawrence 
es_ES |  Yes | @mgrojo. Possible reviewer: @lulol 
fr |  | @mvt91
it |  | @Feyn-Man, @GortiZ6 
ja  |  | @hrwatahiki 
ko_KR | Yes | @lucydodo. Possible reviewers: @progh2, @ChangJoo-Park 
pl |  | @bartlomiej-przymus, @wojnilowicz 
pt_BR |  | @bernardosulzbach
ru |  | @schdub, @zvova7890, @VanDerSam 
tr |  | @firateski 
uk_UA |  | @keedhost 
zh |  | @bssthu, @mercury233 
zh_TW |  | @PeterDaveHello 
other | | Your name here!

Source string changes after translation started:

* None yet


-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/sqlitebrowser/sqlitebrowser/issues/2405

**Comment by mvt91** [comment]
Here is the file :)
[sqlb_fr-3.12.1.x.ts.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/5248377/sqlb_fr-3.12.1.x.ts.zip)

**Comment by lucydodo** [comment]
@mvt91 Thanks for contributing. I just committed your code in the v3.12.x branch. (of course, authored by you)

**Comment by mvt91** [comment]
Thanks.
I don't know how to do that...
May be I'm too old now :)
----- Mail d'origine -----
De: SeongTae Jeong <notifications@github.com>
À: sqlitebrowser/sqlitebrowser <sqlitebrowser@noreply.github.com>
Cc: mvt91 <mvt91@free.fr>, Mention <mention@noreply.github.com>
Envoyé: Sat, 19 Sep 2020 07:09:30 +0200 (CEST)
Objet: Re: [sqlitebrowser/sqlitebrowser] 'DB Browser for SQLite' v3.12.1 is ready for translation (#2405)

@mvt91 Thanks for contributing. I just committed your code in the v3.12.x branch. (of course, authored by you)

**Comment by lucydodo** [comment]
@mvt91 You're welcome. It is for us to be thankful to the contributors. :smile:

**Comment by mgrojo** [comment]
The release candidate 1 for v3.12.1 has just been published. Is anyone working on an update of the remaining translations? German, Italian, Polish, Portuguese and Turkish were mostly up to date and it's a pity if they would be obsolete for this release. Let us know if you start working on it, so we can coordinate the final release.

**Comment by FriedrichFroebel** [comment]
I am planning to update the German translation, but have been on tour recently. I will try to provide the updated file in the next days.

**Comment by mgrojo** [comment]
Glad to know that!

**Comment by bernardosulzbach** [comment]
@mgrojo 2 weeks late, but here I am. The Portuguese update will be provided soon.

Again, consider always including the "how much work is left" (https://github.com/sqlitebrowser/sqlitebrowser/issues/2405#issuecomment-694977673) message with the original ping, it helps us understand how many work there is to do and when best to schedule it.

**Comment by GortiZ6** [comment]
Updated italian translation as well (#2419)

**Comment by mgrojo** [comment]
> sqlb_zh.qm
Generated 1169 translation(s) (1146 finished and 23 unfinished)
Ignored 133 untranslated source text(s)

Last call: @bssthu, @mercury233. Simplified Chinese is the last major language to lack an updated translation for v3.12.x. Should we wait or this time there is no plan to update it?

**Comment by Codifier** [comment]
I'd like to contribute a Dutch (nl) translation, but I have some trouble getting started.

I've forked this repository, cloned my fork to my local machine and set it to start tracking this repository and finally created and checked out a new branch "translation-nl" (as per [this tutorial](https://jarv.is/notes/how-to-pull-request-fork-github/)). All is fine so far.

Then, as per [your instructions](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Translations) on your Wiki page about translations, I've added a new reference to a new `.ts` file in `/src/src.pro`, like so (last line):
```
TRANSLATIONS += \
    translations/sqlb_ar_SA.ts \
    translations/sqlb_cs.ts \
    translations/sqlb_zh.ts \
    translations/sqlb_zh_TW.ts \
    translations/sqlb_de.ts \
    translations/sqlb_es_ES.ts \
    translations/sqlb_fr.ts \
    translations/sqlb_ru.ts \
    translations/sqlb_pl.ts \
    translations/sqlb_pt_BR.ts \
    translations/sqlb_en_GB.ts \
    translations/sqlb_ko_KR.ts \
    translations/sqlb_tr.ts \
    translations/sqlb_uk_UA.ts \
    translations/sqlb_it.ts \
    translations/sqlb_ja.ts \
    translations/sqlb_nl.ts
```
However, when I then build the project (I'm on Ubuntu 18.04), the build finishes successfully, but the file `/src/translations/sqlb_nl.ts` is not being created automatically. I've tried building from within a separate `/build` directory:
```
mkdir build
cd build
cmake -DFORCE_INTERNAL_QSCINTILLA=ON -Dsqlcipher=1 ..
make
```
...as well as simply building from within the root directory:
```
cmake -DFORCE_INTERNAL_QSCINTILLA=ON -Dsqlcipher=1 .
make
```
...but on both occasions the `/src/translations/sqlb_nl.ts` file is not generated.

Should I just manually create the `/src/translations/sqlb_nl.ts` file? If so, which `.ts` file can serve as a template with all translatable phrases? Is it `sqlb_en_GB.ts`, perhaps?

Cheers

**Comment by mercury233** [comment]
I will do the Simplified Chinese translation today

**Comment by mgrojo** [comment]
@Codifier I think our tutorial is missing an invokation of 'lupdate src/
src.pro' for new entries.

@Mercury233 Glad to know!

**Comment by Codifier** [comment]
@mgrojo Okay, that worked, thanks!

**Comment by Codifier** [comment]
@mgrojo I've finished the first iteration of the Dutch translation. I'd like to create a pull request for you, however for everyone's sanity it's probably wise to only provide you with the relevant files for the Dutch translation, which would be:

- `/src/translations/sqlb_nl.ts`
- `/src/translations/flags/nl.png`

However, invoking `lupdate src/src.pro` also simultaneously modified all other `.ts` files in `/src/translations/` in my local repository. Furthermore, to test my translations and flag I also had to make a few adjustments in:

- '/CMakeLists.txt`
- `/src/translations/translations.qrc`
- `/src/translations/flags/flags.qrc`

Still, I think for future iterations pull requests would probably be the most efficient. I've never created a pull request, though. Could you, or anybody else, assist me in how to create a pull request (and perhaps a commit as well, since I haven't committed anything yet) for you, such that only the above mentioned relevant files are included for you?

Or do you perhaps simply prefer that I provide in another manner?

Thanks in advance. Cheers!

**Comment by lucydodo** [comment]
From now, add Dutch translation for v3.12.x branch (Thanks to @Codifier) 😄

**Comment by justinclift** [comment]
It looks like Simplified Chinese was completed a few days ago in #2421 too.  Does this mean we're ok to create the release now? :smile:

**Comment by lucydodo** [comment]
@justinclift Yes we can. 😄 
However, there are currently translated shortcuts in the translation files. So I'm thinking to going to run the script and remove it again(Arabic translation is excluded because the problem mentioned in #2406 PR a while ago may be caused)

If you think you don't need this, forget my comment. 😎

**Comment by justinclift** [comment]
This is for our stable release series, so we're better off to make this correct instead of hurrying.  I probably won't have a chance to build new binaries before Monday anyway. :wink:

**Comment by lucydodo** [comment]
Cool. I will do it this night (KST, about after 4h). 😄

**Comment by bartlomiej-przymus** [comment]
If I want to carry on with polish translation should i use pl-trans branch or create new one?

**Comment by mgrojo** [comment]
You should create a new one or simply work in the `v3.12.x` branch of an updated fork of yours and then make a pull request.

**Comment by mgrojo** [comment]
[v3.12.1](https://sqlitebrowser.org/blog/version-3-12-1-released/) is now released, so I suppose this issue can be closed. Nevertheless, any pull request for a new translation, or an update of an outdated one, will be very welcome and will be included in our next release.

**Comment by JanErikLaerka** [comment]
Am new to this... but have a translation to Swedish.
Where can I dump it?
Can also see that several parts of the applications can't be translated this way... The english text is present anyway even for included languages.

**Comment by chrisjlocke** [comment]
Easiest is to raise a PR (pull request) - this is where you download the file, edit it, then 'commit' it so it's fed back to our project.
When you say the English text is present anyway, do you have an example of where this is?  Theoretically, there shouldn't be many instances of this .... is there?

**Comment by justinclift** [comment]
> The english text is present anyway even for included languages.

Would you be ok to do a screenshot?  That'd help us figure out where something is going wrong. :smile:
