### ISSUE TITLE
Version 3.12.0 Installed but cannot start on Mac OS Catalina 10.5

### ISSUE THREAD

**Issue by egodefroy** [sqlitebrowser/sqlitebrowser#2472]
This popup is displayed when launching DB Brower for sqlite:

Cannot open "DB Browser for SQLite.app" because Apple cannot verify that it is free of malware.

DB Browser for sqlite 3.12.0

**Comment by chrisjlocke** [comment]
This should be resolved soon, but you can get around this easily.  
See this duplicate issue: https://github.com/sqlitebrowser/sqlitebrowser/issues/2346

**Comment by justinclift** [comment]
@egodefroy We've just released version 3.12.1, which is Notarised on macOS, so should launch properly without any warnings:

&nbsp; &nbsp; https://sqlitebrowser.org/dl/#macos

**Comment by egodefroy** [comment]
@justinclift

Thanks, unfortunately I got this crash when trying to open the application when installed:

There is a mistake in the title. My system is macOS 10.15.7 Catalina

````
Process:               DB Browser for SQLite [37420]
Path:                  /Applications/DB Browser for SQLite.app/Contents/MacOS/DB Browser for SQLite
Identifier:            net.sourceforge.sqlitebrowser
Version:               3.12.1 (3.12.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           DB Browser for SQLite [37420]
User ID:               501

Date/Time:             2020-11-09 08:30:31.542 +0100
OS Version:            Mac OS X 10.15.7 (19H15)
Report Version:        12
Bridge OS Version:     4.6 (17P6610)
Anonymous UUID:        B373349A-8F04-0B0E-7F80-5AB792FD57AC

Sleep/Wake UUID:       1A8316E3-4EA0-4AE1-ABDF-9E218784F470

Time Awake Since Boot: 25000 seconds
Time Since Wake:       2200 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/sqlcipherdb4s/lib/libsqlcipher.0.dylib
  Referenced from: /Applications/DB Browser for SQLite.app/Contents/MacOS/DB Browser for SQLite
  Reason: image not found

Binary Images:
       0x10a0be000 -        0x10a644ff3 +net.sourceforge.sqlitebrowser (3.12.1 - 3.12.1) <35D7546A-A0C0-36FB-8A0A-2D08EE230E20> /Applications/DB Browser for SQLite.app/Contents/MacOS/DB Browser for SQLite
       0x10e1b0000 -        0x10e241f47  dyld (750.6) <1D318D60-C9B0-3511-BE9C-82AFD2EF930D> /usr/lib/dyld

Model: MacBookPro15,2, BootROM 1037.147.4.0.0 (iBridge: 17.16.16610.0.0,0), 4 processors, Quad-Core Intel Core i5, 2,3 GHz, 8 GB, SMC 
Graphics: kHW_IntelIrisGraphics655Item, Intel Iris Plus Graphics 655, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 4 GB, LPDDR3, 2133 MHz, Micron, -
Memory Module: BANK 2/ChannelB-DIMM0, 4 GB, LPDDR3, 2133 MHz, Micron, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Feb 28 2020 15:24:56 version 9.30.357.35.32.5.47 FWID 01-9ce4adf3
Bluetooth: Version 7.0.6f7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.4
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.4
````

**Comment by justinclift** [comment]
Thanks, that's really helpful.  The relevant error fragments seem to be:

```
Termination Reason:    DYLD, [0x1] Library missing
```

and:

```
Dyld Error Message:
  Library not loaded: /usr/local/opt/sqlcipherdb4s/lib/libsqlcipher.0.dylib
  Referenced from: /Applications/DB Browser for SQLite.app/Contents/MacOS/DB Browser for SQLite
  Reason: image not found
```

I'll look into this shortly. :smile:

**Comment by justinclift** [comment]
Testing the .dmg just now on the build server, the same thing is showing up.  AAAAAAARRRRGGGGGH.

Could have sworn I tested it at least prior to notarising.  Going to rebuild it afresh, and see what's going on.

At least I know how to do the Notarising thing now, so that should delay things again.  Hopefully. :smile:

**Comment by justinclift** [comment]
Hmmm.  It looks like we specifically need to use the `macdeployqt` tool that's included in Qt 5.15, rather than the one included in Qt 5.12.

That's going to take a few hours, as the build server is running short of space.  I'll need to migrate the Windows VM off it temporarily, add the newer Qt to our macOS VM, and try with that newer `macdeployqt` version.

**Comment by justinclift** [comment]
So far I've tried:

* `macdeployqt` from Qt 5.12.10 <-- seems released today
* `macdeployqt` from Qt 5.14.2

Neither of those have the options we need for notarised Qt executables.  I'm at a loss to remember what/how/when/(etc) I got it working the first time.

That aside, I'm presently installing the Qt 5.15 release now to try that.

Which due to the Qt Company's brain dead control fuckery can **only** now be downloaded via their official "online" installer.

(they purposely don't release offline installers for Qt 5.15 and above, due to their rabid **requirement** to have a name + email for everyone downloading the installer)

Their online installer downloads several GB's at... ~40kB/s via their not-open-to-selection Chinese mirror.  Instead of the several MB/s of the offline installers, which can be downloaded from any suitable mirror (eg US based one).  So this is probably going to take several wasted hours instead of the standard 20 mins.

Thanks Qt Company, you've continued screwing your users over again.  Why don't you add some McAfee or Ask.com style crapware in your installer too?  Surely that's been a board room discussion point already?

/rant

**Comment by justinclift** [comment]
Oh no, I'm wrong.  It's down to about 12 kB/s now. Yay **not**.

(Yes, I'm fed up with the Qt's Company's bullshit :wink:)

**Comment by justinclift** [comment]
At this point, the Qt installer is just going to have to run overnight.  Hopefully it actually finishes successfully.

**Comment by justinclift** [comment]
The Qt 5.15.1 install went fine overnight, so continuing on now... :smile:

**Comment by justinclift** [comment]
Grrrr.  The Qt 5.15.1 version of `macdeployqt` (which includes the needed "hardened runtime things") **only** works for Qt 5.15.1 applications.  So, even with DB4S compiled using Qt 5.12.8, `macdeployqt` pulls in Qt 5.15.1 libraries, completely breaking the application.

On the face of things, it seems like all versions of Qt prior to Qt 5.15.1 are now effectively useless for macOS applications that want to be `Notarised`.

And Qt 5.15 has known breaking bugs + has the Qt Company's idiotic policy of "must use an online installer, and be signed into a Qt account so we can monetize you".

I'm in two minds about this.  But mostly "screw this, we're going to keep using Qt 5.12.x and are not going to Notarise our builds".

On the other hand, we **could** build with Qt 5.15.1, and fix the problems that causes as people report them.

Thoughts?

**Comment by justinclift** [comment]
@egodefroy Would you be ok to try this?

https://nightlies.sqlitebrowser.org/osx-prerelease/DB%20Browser%20for%20SQLite-3.12.1-v2.dmg

It's a new build of version 3.12.1, using the latest Qt release (5.15.1), and is "Notarised" by Apple.  In theory it should work ok... but I'd like some more people to test it before I put it on our main download page. :smile:

**Comment by egodefroy** [comment]
Hi @justinclift 

Great work ! 

I was able to launch the application and read a sqlite file! Either by launching the application and read a file then or directly by clicking on an existing sqlite file

Thanks for your commitment and diligence...

Eric

**Comment by justinclift** [comment]
Thanks heaps Eric. :smile:

Just added that to the release, and am updating the various pages linking to it. :smile:
