### ISSUE TITLE
How do you set a value to null in the data browser?

### ISSUE THREAD

**Issue by JC3** [sqlitebrowser/sqlitebrowser#252]
How do you set a value to null in the data browser, aside from doing it directly with a sql query?

I couldn't find anything in the wiki or browsing around through the application.

Sorry, but I was unable to find a way to contact you besides filing a bug report. 

Thanks.

**Comment by justinclift** [comment]
A bug report is fine. :smile:

I had a similar question not long ago too... and it turns out there's a bug in the current release which makes it hard.

First you'll probably want to grab the latest nightly build (has the bug fixed).

Then, to set a null value you edit the cell in question, then "clear" the field (there's a button).
![01](https://cloud.githubusercontent.com/assets/406299/7099960/2687dc24-dffe-11e4-93f9-140f38a0282c.png)
![02](https://cloud.githubusercontent.com/assets/406299/7099961/2a471500-dffe-11e4-99aa-12a900420861.png)

The result should be a NULL field:
![screen shot 2015-04-11 at 03 51 48](https://cloud.githubusercontent.com/assets/406299/7099963/2f26fce8-dffe-11e4-887a-fb237d8552ca.png)

Let me know if that doesn't work for you? :smile:

**Comment by JC3** [comment]
Thanks. The "clear" button was the first thing I tried, which didn't work. But I tried again after reading your reply and realized there's a bug that if the value is non-null but empty, "clear" doesn't change it to null (it only works if the current value is not empty). That's what got me. I'm going to file an issue report, unless that's the bug you were referring to?

Thanks again,
J

**Comment by justinclift** [comment]
Hmmm, it's similar to that, so it might be the same thing.

Would you be ok to try the latest nightly build and see if it still happens wrongly there?

**Comment by JC3** [comment]
Good news: It works properly in the current nightly build.

**Comment by justinclift** [comment]
Awesome.  Thanks for trying it out to be sure. :grin:
