### ISSUE TITLE
Encription

### ISSUE THREAD

**Issue by Biz7662** [sqlitebrowser/sqlitebrowser#2545]
![Schermata 2021-01-18 alle 16 56 06](https://user-images.githubusercontent.com/73756170/104937500-21222700-59ae-11eb-8ee9-2accd3be8589.png)

When I try to open a file (.csv or .xls for example) directly on DB browser the software asks me a password or something similar, even if the file is not encrypted. Is not a big problem because I can Import it without problem on a Database yet ready, but why this happens ? 

Thank you

Antonio
-----------------------

**Comment by chrisjlocke** [comment]
Hiya.  When you open a CSV or XLS, because it's not a database file, DB4S assumes its encrypted (as all it can see is garbage).
You can only open database files - not CSV or XLS files.

You can import a CSV into a database, but you can't do anything with XLS files.

I'll close this as the issue has been resolved, but please feel free to comment further or reopen the issue.
