### ISSUE TITLE
No 64-bit Windows Nightlies

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2571]
Assuming there has been a build error for the 64-bit version of the nightlies?

![image](https://user-images.githubusercontent.com/7872218/106717558-ccaab880-65f7-11eb-9a72-a692f6bcdcc8.png)

**Comment by justinclift** [comment]
Interesting.  I'll try re-running it, and lets see what happens...

**Comment by justinclift** [comment]
No idea what the problem was.  The re-run went fine, and uploaded successfully.  Good enough. :smile:

**Comment by chrisjlocke** [comment]
Thanks for looking into it.  👍👍

**Comment by chrisjlocke** [comment]
Oops, just noticed they've stopped again.

![image](https://user-images.githubusercontent.com/7872218/108590728-f0daf900-735c-11eb-96e8-2ebde76ffff6.png)

**Comment by justinclift** [comment]
No they haven't. :wink:

Last commit was on the 13th, so they're fine.

The 32-bit ones though were building every day, thus the difference in dates.  That was because I'd commented out the piece which checks if there's a new commit or not (useful when forcing a rebuild), and forgotten to re-enable it.  Fixed that yesterday though, after noticing the difference in dates too, same as you. :grin:

**Comment by chrisjlocke** [comment]
Aah, phew!  False alarm then.  Must admit, I didn't look at the last commit date - just that the dates were different!
Thanks! 👍

**Comment by justinclift** [comment]
Just noticed the windows nightly builds broke again overnight.  I'll look into it tomorrow morning, when I'm back in the same location as the build server. :wink:

**Comment by justinclift** [comment]
Completely forgot about this (!), but when looking now, there are new ones on the nightlies server.  So, problem seems to have fixed itself. :partying_face:
