### ISSUE TITLE
Sqlite File Increasing in Size When Deleting Columns

### ISSUE THREAD

**Issue by cbracketdash** [sqlitebrowser/sqlitebrowser#2596]
I have a 32 GB sqlite file and was trying to delete several columns as I would not need them. When I pressed "ok", the program stopped responding. When I went to check the file in my file manager, I noticed that the file size was increasing rather than decreasing. Is this normal when deleting columns? 

Thank you in advance for your support in this matter

Kind regards

EDIT: After it finished, it became 42 GB. I would assume it would lose 10 GB when deleting a large amount of data...

**Comment by chrisjlocke** [comment]
Technically, you can't delete columns in SQLite.  You add a new column to the end of a table, or rename a column, but that's about it.  To get around that, DB4S creates a new table, copies all the data, then deletes the old table.  This explains the 'stopped responding' (data was being copied) and the increase in file size (old data).  
Even on your hard-drive, if you delete all the files, the files are not removed from the drive - they are just removed from the 'index' and the space can be re-used.  SQLite does the same thing, otherwise the file would have to be re-written constantly, which would be slow.  So if you delete a bunch of records, they are 'removed' but the space they consumed is not reclaimed in the physical file.  There is a 'vacuum' command you can use to rebuild the database, removing all the 'dead space'.  In DB4S, click 'Tools' and 'Compact Database'.

![image](https://user-images.githubusercontent.com/7872218/108814508-d7c78780-75aa-11eb-9d88-1dc33d1fa73f.png)

Hope this helps.  So all was good and after compacting, the filesize should be reduced.

**Comment by little-brother** [comment]
> you can't delete columns in SQLite

[Coming soon](https://www.sqlite.org/src/timeline?c=c844a331e7894985&y=a) ;)

**Comment by chrisjlocke** [comment]
Oooh, exciting.  This won't change the filesize though, so you'd still need to 'vacuum'. 
Thanks for the info though!

**Comment by cbracketdash** [comment]
Thank you all for your prompt responses.

When I compacting the file however, it seems like it is copying the file to my hard drive, which I do not have enough space on. My external hard drive has plenty of space.  Is there a workaround?

**Comment by chrisjlocke** [comment]
From the 'execute sql' tab, you can type `vacuum into '{filename}'`

![image](https://user-images.githubusercontent.com/7872218/108880246-0456c000-75fa-11eb-9024-892dc5c07688.png)

This will create a new database in the other location.
You'd then either delete (if you were brave, but that should be OK) and move the new file back over, OR, move the database to the external storage, open it, and VACUUM it to where it would originally live (if that makes sense....)

Either way, the process is non-destructive as it creates a new file, so you're not touching the old (larger) database.

**Comment by cbracketdash** [comment]
Yes, thank you very much. That reduced the file size to a more manageable 11 GB.

Now, I have only 1 column left in my database. Is there a way in which I can convert the column to raw text using the Sqlite DB Browser?

**Comment by cbracketdash** [comment]
Ok, so after trying to export it as JSON, I left my computer for a while to do its thing. However, when I came back, my computer had completely frozen up. I could not even do anything with the Windows key nor bring up my task manager. I am assuming that I ran low on RAM. I was expecting this not to be an issue given that it was able to do the other tasks with such a big file fairly easily. 

Anyways, so I tried 1 more but this time monitoring the memory usage for sqlite browser and it just kept increasing with no signs of stopping. It started reaching 2 GB of memory and I just ended the task. Is there a way to export a file without taking up so much RAM?

**Comment by little-brother** [comment]
Try to use [SQLite CLI](https://sqlite.org/cli.html).

**Comment by chrisjlocke** [comment]
You're exporting a table as a CSV?  You mention JSON, but from the 'file' menu is 'export as CSV'.  This will squirt out one field (if that's what you're exporting) on a line on its own - one line for each record.

![image](https://user-images.githubusercontent.com/7872218/108966379-03637400-7676-11eb-90c6-d23f158785b7.png)

I think the JSON option is a bit newer, so I presume (haven't looked) it's building the whole JSON string before exporting - with billions and billions of records, that could be large.  That's purely a badly educated guess though - it might not do anything even remotely like that.
But try the CSV option?

**Comment by cbracketdash** [comment]
Yes, thank you; the CSV file option was exactly what I needed.
