### ISSUE TITLE
Should we not auto-close the Execute SQL tab when closing the dB?

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#262]
As mentioned in #206 by @sergbus:

> Another useful thing might be to not close "Execute SQL" tabs when closing connection to the
> database. I often have a need to execute same ad-hoc query against couple databases and lose
> the query when closing one database and opening another. Maybe disabling the "Execute" button
> is enough?

**Comment by MKleusberg** [comment]
I've finally come around to fix this. Since we already have a couple of other issues open (#336, #938, #1035) asking for the same feature, I'll just proactively close this issue :wink: If there is something with the new behaviour that doesn't work for you, @kthbit, you're always welcome to reopen the issue :smile:
