### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by TeLLie** [sqlitebrowser/sqlitebrowser#2621]
Hi
here are the translation for SE, thanks to Jan-Erik

**Comment by justinclift** [comment]
@TeLLie emailed the files to me directly, as they wouldn't attach to the issue: [trans.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/6127348/trans.zip)

As a guess, they probably wouldn't attach because the files were in a 7zip archive.  I've recompressed them to be in a .zip archive instead, and the attaching seems to be ok.

We should transfer these into a PR or similar. :smile:

**Comment by MKleusberg** [comment]
I have just added the translation to the master branch directly :smile: Thanks to @TeLLie  and Jan-Erik!
