### ISSUE TITLE
'Yes to all' does not work properly when importing multiple CSV files

### ISSUE THREAD

**Issue by antonybits** [sqlitebrowser/sqlitebrowser#2633]
I have to Import hundreds of CSV files into separate tables in my database. I use the import CSV dialog. when the program asks if I want to add new data to the existing tables, One may choose "yes" or "yes to all". I would choose yes to all because of numerous CSV files. but the question repeats for the next CSV file being imported to another table.

the "yes to all" option only works fine if the "separate tables" checkbox is not checked and all CSV files are meant to be imported into one table. 

#### What operating system are you using?

- [x] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [x] Other:  nightly build

**Comment by chrisjlocke** [comment]
Whoopsie!  
It may not help, but DB4S now has a command-line input to import CSV files - you could script it to import a large number of CSV files?  Unsure if that'll work well....
Thanks for reporting this though.

**Comment by antonybits** [comment]
> DB4S now has a command-line input to import CSV files 
I'll try the command line method next time, I hope yes to all will be fixed soon. Now I'm using the combination of import CSV dialog and an auto-clicker app to click on yes!! it has been 2 days since the auto-clicker started clicking yes till now 😂

**Comment by antonybits** [comment]
> Whoopsie!
> It may not help, but DB4S now has a command-line input to import CSV files - you could script it to import a large number of CSV files? Unsure if that'll work well....
> Thanks for reporting this though.

I'll try the command line method next time, I hope yes to all will be fixed soon. Now I'm using the combination of import CSV dialog and an auto-clicker app to click on yes!! it has been 2 days since the auto-clicker started clicking yes till now 😂

**Comment by justinclift** [comment]
@mgrojo This "Yes to all" bug sounds like your kind of thing?

**Comment by mgrojo** [comment]
Yes, I'm looking into it. My first thought solution has turned to be equivalent to reverting this commit (425bfa1e75a2720f53a5ffab2d382d6b8aab861a) so I'm looking at #1121 in order to not break anything.

**Comment by mgrojo** [comment]
The current "Yes to All" answer is affecting only to future prompts *for the same table*. Currently, that only makes sense for two cases:
1. The "Separate tables" option is not checked.
2. Otherwise (separate tables), if several files are named equal to a table name, that can only happen if they are located in different directories, or have different extensions (since the base filename is the only way to indicate the table name, as far as I know).

I don't know if 2 is a very interesting case, but in order to not break any use case, I'm thinking in implementing:
* "Yes" means yes for any future prompt for this table.
* "Yes to All" means yes for all future prompts for *any* table.

Does that make sense in every case?

**Comment by mgrojo** [comment]
@antonybits, it's now implemented in the way I described above. It will be available in tomorrow's nightly build. Could you give it a try and report any inconsistency?

**Comment by antonybits** [comment]
@mgrojo, I've just tested the latest nightly build. The "yes to all" worked fine for separate tables, thank you.

**Comment by chrisjlocke** [comment]
Thanks for the initial report, and thanks for confirming.
Thanks to @mgrojo for the quick fix. 👍
