### ISSUE TITLE
'Copy As SQL' copies all cells from header but only selected cells for values

### ISSUE THREAD

**Issue by chrisjlocke** [sqlitebrowser/sqlitebrowser#2638]
Details for the issue
--------------------

#### What did you do?
Highlighted some non-sequential cells in the 'Execute SQL' results grid and selected 'Copy as SQL'

#### What did you expect to see?
Unsure - hadn't used it before

#### What did you see instead?
All the cells from the first selected cell to the last selected cell was used as column identifiers, but only the selected cells were used for values.  This resulted in invalid SQL being generated.

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:_ _10__ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [x] 3.12.99 (21 Mar 2021)
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [ ] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

Here is a screencast.
https://user-images.githubusercontent.com/7872218/111918224-fcb0fc80-8a7b-11eb-9223-2bccac98a9f2.mp4
Skip to 0:43 as that's where the real action starts - prior to this is just me setting up the new table.

Selecting cells 1 and 4 created this SQL:
`INSERT INTO "main"."" ("Field1", "Field2", "Field3", "Field4") VALUES ('1', '4');`

The empty table name is expected - the grid could be made up from a number of different tables used in the select statement.  However, the insert consists of four fields, but only two values.  The values are correct - field1 value (1) and field4 value (4).

**Comment by mgrojo** [comment]
I wasn't aware that the Execute SQL browser allowed non-contiguous selection. In the Data Browser is explicitly disabled, I think precisely because the clipboard copy-paste does not work well with non-contiguous selections, and not only the SQL, the other kinds of copies give also inconsistent results, and it's even more difficult in those cases to figure out how they should work.

Should we try to make sense of it and implement it, or just disallow non-contiguous selections from the Execute SQL browser?

**Comment by justinclift** [comment]
"non-contiguous selection" sounds like the kind of thing someone probably asked for.  So, disabling it **probably** isn't the way to go. :wink:

That being said, it's definitely possible I'm wrong. :grin:

**Comment by chrisjlocke** [comment]
It seems to work OK for the values - so unsure why it's working OK for that part and not others...

**Comment by mgrojo** [comment]
Good news! I've manage to make non-contiguous selections to work in most cases (internal copy-paste being the exception), so I've enabled them also for the Table Browser. When copying non-rectangular selections into a table, the layout is not preserved for the different rectangles, all are punt one below the other, but I think it still pays off to have non-contiguous selections, because you can, for example, deleted several non-contiguous rows with only one action.

**Comment by chrisjlocke** [comment]
Thanks so much for the quick fix.  Can confirm it works in the browse data tab now.
