### ISSUE TITLE
Spatialite RenameTable Issue

### ISSUE THREAD

**Issue by karosc** [sqlitebrowser/sqlitebrowser#2652]
I am trying to use the spatialite extension with db browser on windows and having an issue with a specific function in the extension. Spatialite has a helper function for [renaming atable](https://www.gaia-gis.it/fossil/libspatialite/wiki?name=Drop-RenameTable+and+RenameColumn). I have no problem using that function in the spatialite cli or spatialite-gui applications. But if I use it in db browser I get the following error in the SQL Log:

```
-- EXECUTING ALL IN 'SQL 1'
--
-- At line 1:
select RenameTable('main','Land_Use_2015','Land_Use_2015_proj')
-- Result: RenameTable exception - FOREIGN KEY constraint failed.

``` 

The foreign key contraint likely comes from the geo tables that reference the geometry column in the table. But I don't understand why this issue only comes up in db browser and not the cli or spatialite gui. I have no problem loading the extension and all dependencies are in a directory in my system $PATH.

**Comment by karosc** [comment]
that stops the foreign key constraint error, but the function Still does not work

```sql
PRAGMA foreign_keys = OFF;
select RenameTable('main','Land_Use_2015','Land_Use_2015_proj');
```

```
-- EXECUTING ALL IN 'SQL 1'
--
-- At line 1:
PRAGMA foreign_keys = OFF;
-- Result: 0 rows returned in 6ms
-- At line 1:
PRAGMA foreign_keys = OFF;
-- Result: 0 rows returned in 7ms
-- At line 1:
PRAGMA foreign_keys = OFF;
-- Result: 0 rows returned in 870ms
-- At line 2:
select RenameTable('main','Land_Use_2015','Land_Use_2015_proj');
-- Result: 0 rows returned in 862ms

```

**Comment by karosc** [comment]
> 
> 
> Interesting. Wonder if temporarily disabling the foreign key constraint checking would help? (eg via `PRAGMA` statement)
> 
> https://sqlite.org/pragma.html#pragma_foreign_keys
> 
> It's probably worth trying out, after making a backup of your database. 😄


Also, digging into the libspatialite source code in the statistics.c file, the RenameTable function should automatically turn off foreign_keys. Very weird. 

```c++
/* saving the current FKs mode */
  ret =
sqlite3_get_table (sqlite, "PRAGMA foreign_keys", &results, &rows,
			 &columns, NULL);
  if (ret == SQLITE_OK)
    {
	if (rows < 1)
	    ;
	else
	  {
for (i = 1; i <= rows; i++)
		  fk_on = atoi (results[(i * columns) + 0]);
	  }
	sqlite3_free_table (results);
    }
  if (fk_on)
    {
	/* disabling FKs constraints */
	ret =
	    sqlite3_exec (sqlite, "PRAGMA foreign_keys = 0", NULL, NULL,
			  NULL);
	if (ret != SQLITE_OK)
	  {
if (error_message)
		  *error_message =
	sqlite3_mprintf ("unable to disable FKs constraints");
return 0;
	  }
    }

```

**Comment by i-s-o** [comment]
I've had similar issues with various Spatialite features. I tested them in Windows 10 and Ubuntu 20.10. Ultimately, I came to the conclusion that DB4S can only be used to query Spatialite DBs (rather than write/manipulate them).

Here is the simplest example in sqlite3 CLI:
```
user@ubuntu2010:~$ sqlite3
SQLite version 3.33.0 2020-08-14 13:23:32
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> select load_extension('mod_spatialite');

sqlite> select InitSpatialMetadata();
1
sqlite> create table test (pk_uid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);
sqlite> select AddGeometryColumn('test', 'geometry', 4326, 'LINESTRING', 'XY');
1
sqlite> select CreateSpatialIndex('test', 'geometry');
1
sqlite> insert into test (name, geometry)
   ...> values ('Length', ST_GeomFromText('LineString (-73.926450 40.877614,-74.013544 40.700486)', 4326));
sqlite> select sql from sqlite_master where type = 'table' and name = 'test';
CREATE TABLE test (pk_uid INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, "geometry" LINESTRING)
sqlite> select
   ...>   ST_Distance(ST_PointN(geometry, 1), ST_PointN(geometry, 2)) as distance
   ...>   , ST_Distance(ST_PointN(geometry, 1), ST_PointN(geometry, 2), false) as distance_0
   ...>   , ST_Distance(ST_PointN(geometry, 1), ST_PointN(geometry, 2), true) as distance_1
   ...> from test;
0.197382099542993|21016.3053896703|20998.7396730285
sqlite> .save test.db
sqlite> .exit
```

When the same statements are executed in DB4S it looks like they fail at the AddGeometryColumn() step (it returns 0). However, the real problem is with InitSpatialMetadata(), because non of the support tables are created even when the return code is 1. Separately, if I open `test.db` (created with sqlite3 CLI) and execute `select DropTable(NULL, 'test');` the table is not dropped as expected.

Here is another example, illustrating InitSpatialMetadata() is not working in DB4S (observe DB Schema showing that no tables were added):

![image](https://user-images.githubusercontent.com/1661549/113541142-9fef2f00-95af-11eb-858e-70d6da08df05.png)

Note that the spherical and ellipsoid versions of the ST_Distance fail because librttopo can't locate spatial_ref_sys table (see the SQL Log): this is one of the Spatialite support tables that would have been created by InitSpatialMetadata(). See Sandro's [indirect] [response](https://groups.google.com/g/spatialite-users/c/PX7PQ1_36mQ/m/Z8zaKt02BwAJ) to a [similar issue in QGIS](https://github.com/qgis/QGIS/issues/41890) explaining how librttopo needs to query spatial_ref_sys.

There is no problem when the same SQL statement is run in a properly initiated Spatialite DB (e.g. `test.db` from sqlite3 CLI above):

![image](https://user-images.githubusercontent.com/1661549/113541619-9e723680-95b0-11eb-9797-8fa93251c8d2.png)

**Comment by motendev** [comment]
Oh man, just spent a couple of hours wrestling with the above scenario before looking at issues. Can confirm that DB4S doesn't work with any of the spatialite features that alter schemas and the like. Data manipulation works.

How I came to a minimal example from https://www.gaia-gis.it/fossil/libspatialite/wiki?name=Lodable+Modules+in+5.0:
```
select load_extension('mod_rasterlite2');
select load_extension('mod_spatialite');
select load_extension('mod_virtualpg');
select spatialite_target_cpu();
select spatialite_version();
select rl2_version();
select InitSpatialMetaData()
```
The above works when running sqlite3 in the command line. In DB4S, everything will work except `select InitSpatialMetaData()` will return 0. You can still use

**Comment by chrisjlocke** [comment]
Unfortunately I don't know how DB4S works, but I think its something to do with statements in the 'execute sql' tab are run in a transaction, and as the 'select' statement doesn't 'do' anything, the transaction is aborted.  

```
SAVEPOINT "RESTOREPOINT";
select InitSpatialMetaData() LIMIT 0, 49999;
ROLLBACK TO SAVEPOINT "RESTOREPOINT";
PRAGMA database_list;
SELECT type,name,sql,tbl_name FROM "main".sqlite_master;
RELEASE "RESTOREPOINT";
```

This is from the SQL log running that select statement.

Playing around, there doesn't seem a way of circumventing this transaction, but you can put it in a view.  View the view, and voila - the tables are created.  
It's a bit 'Eh? 😣🤨😐' but there are no transactions when looking at views! ;)

https://user-images.githubusercontent.com/7872218/120922695-8ad37100-c6c2-11eb-93b7-05180cc50b10.mp4

Sorry about the mad clicking at the end - I needed to press F5, but that key is knobbled by the screen-capture software, and I thought flipping tabs would do it, so had to run the view again... but then it worked...

**Comment by motendev** [comment]
Aha, great find!

**Comment by motendev** [comment]
I'm guessing its this part here? 
https://github.com/sqlitebrowser/sqlitebrowser/issues/2652#issuecomment-855383747

In combination with this part:
https://github.com/sqlitebrowser/sqlitebrowser/blob/93a5c2d0ca81fb26c51a9e0ecabacfc7ab872d62/src/RunSql.cpp#L259

**Comment by justinclift** [comment]
@mgrojo @MKleusberg Any idea if there's a better approach?  Maybe our SQL parser should detect `load_extension()`, and not wrap it in a transaction or something?

**Comment by chrisjlocke** [comment]
Its not the 'loadTransaction' but the 'select InitSpatialMetaData' which is causing the error - we assume all selects don't modify data, thus initiate a rollback, etc - although freakily in this case, the select DOES modify the data (well, schema...)

**Comment by mgrojo** [comment]
At least in this case, [sqlite3_total_changes()](https://sqlite.org/c3ref/total_changes.html) is counting the changes made by `select InitSpatialMetaData()` so I think it could be used to detect those rare select statements that return data and at the same time modify the database. I'll try to implement it in this way.

**Comment by mgrojo** [comment]
It isn't straightforward to apply `sqlite3_total_changes()` because after 1f9101ae2a564121ba2843b68c1d7d3f8cff93ad the execution of statements returning rows is executed in a different thread, but the rollback occurs in the original thread. By mistake, I started fixing this in v3.12.x branch and there it was easy without this optimization. Maybe we should detect, and treat differently, statements with the form: `SELECT function()`. There will return data, but probably not a great number of rows. @MKleusberg or anyone, do you have any better idea on how to fix this?

**Comment by justinclift** [comment]
Do we want to look at this again for the upcoming 3.13 release?

**Comment by mgrojo** [comment]
Looking at this code, there might be an easy solution.
https://github.com/sqlitebrowser/sqlitebrowser/blob/93a5c2d0ca81fb26c51a9e0ecabacfc7ab872d62/src/RunSql.cpp#L254-L263

If I'm not missing something, if we assume that we can revert a savepoint, because the executed statement has not modified the DB, we could as well assume that we can release the savepoint, so nothing gets reverted in the case it modified something. The worst case could be if we write something before the user wanted to. What it's not clear to me right now, it's whether there will be another savepoint or transaction preventing that from actually happening.

**Comment by mgrojo** [comment]
Since nobody seems to have a better proposal, I've implemented the change I described above. This makes the use of these functions with side effects usable in DB4S, but there are still, in my opinion less obtrusive, issues:
* Unless there is a previously open savepoint from an earlier change, the side effect of these impure functions (like the schema creation in `InitSpatialMetaData()`) will be immediately written to the database.
* Since DB4S believes there was no modification, the user has to refresh the Data Browser or the Database Structure to see the modifications.

I hope that with this change, DB4S is in better shape for the 3.13 release.

@karosc, @i-s-o, could you try the nightly build, so we can be sure that there aren't more than those issues for this solution and know how usable is now Spatialite with DB4S?

**Comment by karosc** [comment]
@mgrojo, thanks for your hard work! I probably will have some time at the end of this week to look into this. Does that work with your timeline?

**Comment by justinclift** [comment]
@karosc Yeah, that should be workable. :smile:

**Comment by karosc** [comment]
@justinclift, I can confirm the latest nightly build fixes this issue as long as you run `PRAGMA foreign_keys = OFF;` prior to running the `RenameTable` command. If you don't run `PRAGMA foreign_keys = OFF;` DB Browser does not print any errors, the RenameTable query just doesn't return any value at all (it should return a 1 or 0).

Great work! I'm truly amazed this issue is getting closed after so long. 🥳
