### ISSUE TITLE
Check for another field

### ISSUE THREAD

**Issue by PautassoEGiacomina** [sqlitebrowser/sqlitebrowser#2699]
Hi guys!
I recently approached the world of databases, thanks to DB Browser 4 SQLite. I would like to know if there is a way to insert a check that allows me to insert data in a column only if they are not present in another column (the one next to it for example).
I bring you the construct to try to make you understand better what I mean:

```
CREATE TABLE "Test" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Field 1"	INTEGER,
	"Field 2"	INTEGER CHECK("Field 1" = NULL),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
```

Basically I would like the software to allow me to enter data in "Field 2" only if there is no data in "Field 1". I tried the check I gave you, but it doesn't work. Do you have any suggestions? You would solve a big problem for me, I already got 84 tables for my first database, and if I could solve this I would avoid having to create at least 30 more.

**Comment by chrisjlocke** [comment]
Don't think you can do it in a check, but you might be able to use a trigger.  
How strict is this rule?  Is this for automating data input, or human input?  The beauty with SQLite is that many languages can talk to the database, so it should be easy to knock up a Python, C++, Go or .Net program to do any 'heavy grunt' work required.

**Comment by PautassoEGiacomina** [comment]
> Don't think you can do it in a check, but you might be able to use a trigger.
> How strict is this rule? Is this for automating data input, or human input? The beauty with SQLite is that many languages can talk to the database, so it should be easy to knock up a Python, C++, Go or .Net program to do any 'heavy grunt' work required.

I thank you infinitely here too for your answer!
Do you have any links from which I can learn how to use triggers?
For now, every data in my database is entered by hand by me, and I think the situation will remain so for a long time to come.
I would like to ask you a technical question instead: why does the check of a field (therefore not belonging to the whole table) affect the other fields as well?
In the example above, to make me understand, I tried to set it like this:

```
CREATE TABLE "Test" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Field 1"	INTEGER,
	"Field 2"	INTEGER CHECK("Field 1" > 1),
	PRIMARY KEY("ID" AUTOINCREMENT)
);
```
And when I arrive at "Field 1" it does not make me enter a value less than 1, even if that check is placed next to another field: what is this function for?

**Comment by chrisjlocke** [comment]
> In the example above, to make me understand, I tried to set it like this:

If you create that table, then this SQL will work:
`insert into test ("field 1", "field 2") values (2,3);`
while this one won't
`insert into test ("field 1", "field 2") values (0,3);`

So that check is working.  However, you can also put in NULL values. And empty values.  Everything else should fail.
`insert into test ("field 1", "field 2") values (null,null);'

![image](https://user-images.githubusercontent.com/7872218/118362489-9af6a580-b587-11eb-864d-d7b9590498a1.png)

So it won't let me put 1 in that field.

![image](https://user-images.githubusercontent.com/7872218/118362509-b06bcf80-b587-11eb-9434-c9b8a0fb374e.png)

However, you can put 'd'.

![image](https://user-images.githubusercontent.com/7872218/118362529-c11c4580-b587-11eb-94a8-7e3bce6f3278.png)

You'd need to add a check to only allow numeric values if you wanted to be that restrictive.

As for triggers, this should give you some good help.
https://www.sqlitetutorial.net/sqlite-trigger/

**Comment by PautassoEGiacomina** [comment]
> If you create that table, then this SQL will work:
> `insert into test ("field 1", "field 2") values (2,3);`
> while this one won't
> `insert into test ("field 1", "field 2") values (0,3);`
> 
> So that check is working. However, you can also put in NULL values. And empty values. Everything else should fail.
> `insert into test ("field 1", "field 2") values (null,null);'
> 
> ![image](https://user-images.githubusercontent.com/7872218/118362489-9af6a580-b587-11eb-864d-d7b9590498a1.png)
> 
> So it won't let me put 1 in that field.
> 
> ![image](https://user-images.githubusercontent.com/7872218/118362509-b06bcf80-b587-11eb-9434-c9b8a0fb374e.png)
> 
> However, you can put 'd'.
> 
> ![image](https://user-images.githubusercontent.com/7872218/118362529-c11c4580-b587-11eb-94a8-7e3bce6f3278.png)
> 
> You'd need to add a check to only allow numeric values if you wanted to be that restrictive.
> 
> As for triggers, this should give you some good help.
> https://www.sqlitetutorial.net/sqlite-trigger/

So, first of all, thank you for the explanation.
I'm doing some tests with the trigger function following the link you reported to me.
The table I would like to apply my trigger to is the following:
```
CREATE TABLE "Test" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Field 1"	INTEGER,
	"Field 2"	INTEGER,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
```

The draft of the trigger I wrote is the following (I state that I do not know at all what I am doing):
```
CREATE TRIGGER "Trigger test"
	BEFORE INSERT ON "Test"
BEGIN
	WHEN "Field 1" NOT NULL THEN
		"Field 2" = NULL
		RAISE (ABORT, "It is not allowed to insert more than one data in this record.")
	END;
END;
```
The function that I would like to apply with this trigger is that the software prevents me from inserting a data in the same record in both "Field 1" and "Field 2", that is, I would like to be allowed to insert a data only in one of the two fields in every record.
Obviously the trigger I wrote does not work, I would like to ask you if I am not stealing too much time, what am I doing wrong.
Thank you in advance!

**Comment by chrisjlocke** [comment]
First of, don't have spaces in field names - it makes SQL very hard to read - you have to quote everything, so instead of "field 1", use "field1".  This is the same for table names.  Use camelCase where you can - so employeeRates and not "employee rates".

I've never used triggers before, but there are many tutorials.  Some aren't as good as others! 😁
In the end, this worked.
```
CREATE TRIGGER "test_beforeInsert" 
   BEFORE INSERT ON "test"
BEGIN
   SELECT
      CASE
	WHEN new."field 1" is not null and new."field 2" is not null THEN
   	  RAISE (ABORT,'Can''t add data into both fields')
       END;
END;
```

When you're in the 'before insert' test, you have the 'new' keyword prefix to see what the new values will be.  Found that out from here:
https://www.w3resource.com/sqlite/sqlite-triggers.php#MTBI

So here, you're only checking if both fields aren't null - you can enter a value in just field2 (so field1 will be null) or just field1 (and field2 will be null).

Hope this makes sense!

PS: As above, give triggers a meaningful name!  It'll help later!

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/118393379-bff62180-b636-11eb-9034-0801a3343b3a.png)

**Comment by PautassoEGiacomina** [comment]
> First of, don't have spaces in field names - it makes SQL very hard to read - you have to quote everything, so instead of "field 1", use "field1". This is the same for table names. Use camelCase where you can - so employeeRates and not "employee rates".
> 
> I've never used triggers before, but there are many tutorials. Some aren't as good as others! grin
> In the end, this worked.
> 
> ```
> CREATE TRIGGER "test_beforeInsert" 
>    BEFORE INSERT ON "test"
> BEGIN
>    SELECT
>       CASE
> 	WHEN new."field 1" is not null and new."field 2" is not null THEN
>    	  RAISE (ABORT,'Can''t add data into both fields')
>        END;
> END;
> ```
> 
> When you're in the 'before insert' test, you have the 'new' keyword prefix to see what the new values will be. Found that out from here:
> https://www.w3resource.com/sqlite/sqlite-triggers.php#MTBI
> 
> So here, you're only checking if both fields aren't null - you can enter a value in just field2 (so field1 will be null) or just field1 (and field2 will be null).
> 
> Hope this makes sense!
> 
> PS: As above, give triggers a meaningful name! It'll help later!

I had read that it was better to use the camelCase to name fields and tabs, but I thought it was just to avoid having to put apostrophes when writing something in SQL, which does not bother me, but I really think I will follow your advice.
I thank you so much for your trigger, as soon as I can I try it, but it will definitely work, you are very very very kind, really!!

**Comment by chrisjlocke** [comment]
Always happy to help.  Yell back if it does/doesn't work.

**Comment by mgrojo** [comment]
It seems that the question was answered. Feel free to reopen this in case you need more help.
