### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by bhavna786** [sqlitebrowser/sqlitebrowser#2701]
django.db.utils.DatabaseError: database disk image is malformed

**Comment by chrisjlocke** [comment]
I'll close this as there is no information on which we can act.
@bhavna786 - please provide more details.  What were you doing, how were you doing it, and on what operating system were you doing what you were doing you were doing how you doing you doing.  With just a vague error message, it's hard to give any advice.
But at a basic level, the database has become corrupted.  "Disk image is malformed" means the database isn't right.  This might be because you're opening it remotely, or on another file system, or found it on a USB stick stuck in a grapefruit.  
Look forward to more details.

**Comment by FriedrichFroebel** [comment]
@bhavna786 This is an exception from the Django framework, which is usually out of scope here - especially as your issue description lacks important details as already mentioned by @chrisjlocke.
