### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by PautassoEGiacomina** [sqlitebrowser/sqlitebrowser#2702]
I have recently started creating my first database, but I am already in love with DB Browser for SQLite. It's so simple and clean to use that I was able to build a ton of tables in no time without knowing SQL (not that there's anything to be proud of about that). This software is great, even graphically.
I was wondering if by chance there is the possibility that one day with it you can also create forms to facilitate data entry. Is there this opportunity by any chance? Would it be too complex to implement? I have been using LibreOffice Base so far, but it is poor in some feature, and from the point of view of someone who does not understand anything (...me) it seems far behind MS Access. If DB Browser for SQLite allowed you to also create forms without having to necessarily know SQL, there would be no more rivals, not even in the closed source world.

P.S.: What do you use to easily create forms? Is it mandatory to know how to program to do them without MS Access / LO Base?

**Comment by chrisjlocke** [comment]
I'll close this, as this has been asked here: https://github.com/sqlitebrowser/sqlitebrowser/issues/127
It's on the list, but due to the complexities of forms, it's never been completed.  
I tend to use .Net as a 'front end', mainly because so many fields require a lot of logic - you've entered a name, but does it contain a space (to determine firstname, lastname), or is the date of birth in the future, or does it make the person 800 years old?  Is that email address valid?  Does that file exist?  You've checked box A, but also box B, which doesn't make sense, etc, etc.  
Once dbhub.io grows a bit more, it may be something that's put into there - only because HTML forms are dead easy, etc.
