### ISSUE TITLE
What happened to the multiple table browse ability?

### ISSUE THREAD

**Issue by tonypdmtr** [sqlitebrowser/sqlitebrowser#2705]
What is your question
-----------------------

It used to be that I could open multiple tables (in separate tabs).  This helped to copy paste, check view after updating table or similar work.

Is this ability removed or there is now a different way to get to it?

**Comment by chrisjlocke** [comment]
It's in the nightly code, rather than the 'official' release.  Unsure what version you're using, but if you try one of the nightlies (they don't need to be installed - download the ZIP, extract, and you can run the .exe directly) and you should have that feature back again.  It's still 'in development' which is why it's not in the main code yet.  I believe.
