### ISSUE TITLE
Wrong line number reported for failed SQL query

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#2714]
Details for the issue
--------------------

#### What did you do?

1. Opened DB Browser for SQLite version 3.12.99 (May 3 2021)
2. Ran a false query on any database for any table

#### What did you expect to see?

Example query:
```
select * from mytable
where justin = 'mmm'
```
`justin`  isn't a real column, so I expected to see the error message pointing to the second line where `justin` is actually present.

#### What did you see instead?
```
Execution finished with errors.
Result: no such column: justin
At line 1:
select * from mytable
where justin = 'mmm'
```
Notice from above that 'justin' is on line TWO, but the error above reports a problem on line 1.

Useful extra information
-------------------------

A different SQLite gui app, where I've been keeping the developer busy, has some insights for you to review:
https://github.com/little-brother/sqlite-gui/issues/31

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [x] Windows: ( _version:10 )

#### What is your DB4S version?

- [x] Other: 3.12.99 (May 3, 2021)

#### Did you also

- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by jungle-boogie** [comment]
> I don't see how you can 'correct' this to show the correct line number.

Well then maybe just remove the reference to the line number?

**Comment by jungle-boogie** [comment]
```
Execution finished with errors.
Result: no such column: justin
select * from DoWPercent
where justin = 'mmm'
```

**Comment by chrisjlocke** [comment]
Hmm.  It's complicated.  

![image](https://user-images.githubusercontent.com/7872218/119178468-b1a86b00-ba65-11eb-89b1-2eb22f2eba14.png)

It's reporting the wrong line here, but having a line number is helpful, otherwise you wouldn't know what statement failed.  If you correct the 'froom' then it correctly reports an error on line 9.  So it sort of works, so long as the actual statement is on one line.  You can't blanket remove all carriage returns, as then the error would be reported on line 4, which is even more wrong.

**Comment by MKleusberg** [comment]
A bit more background: SQLite doesn't report a line number at all. That's because it can only execute a single statement at once so if that fails it's obvious from SQLite's perspective which statement just failed. We only know the line number because we keep track of the positions of each executed statement.

That said I agree with @chrisjlocke. Imagine pasting a thousand lines of SQL statements in there and trying to execute them. If DB4S told you there's an error on line 300 when it's actually on line 301 is still pretty useful in that context. What we could do however is use another wording. Instead of saying "At line 1: ..." it could say "In statement starting at line 1: ...". But I'm not sure about that. It would be technically correct but a harder to read because it's so much more text.

**Comment by jungle-boogie** [comment]
Thanks for the information and input, fellas.

This just may be a "no change required" kind of issue, and I'm okay with that.

**Comment by MKleusberg** [comment]
To be honest I'm kind of leaning towards that direction at the moment. On the other hand we could tweak this. Besides the option to change the wording to something like "In statement starting at line 1: ..." we could also make it say "At line 1-2: ...". But again, not sure if that's really more helpful than the current message.

**Comment by jungle-boogie** [comment]
I don't suppose the line highlighting could be targeted to a/the specific line, either, right?

It's helpful in Chris' example above, but if you have a 300 line sql query, the whole thing would be highlighted if there's one error, right?

**Comment by mgrojo** [comment]
Yes, it will highlight all the query and will put the reference to the first line of the query.

I wouldn't change it to "In statement starting at line 1: ...", because the more you write, the less the users read :smile: I wouldn't object the change to "At lines 1-2: ...". Another option, with a not so direct implementation, is to add the lines to the margin:

```
Execution finished with errors.
Result: no such column: justin
1  select * from mytable
2  where justin = 'mmm'
```

The format for the SQL Log has to be taken into account also.

**Comment by jungle-boogie** [comment]
What if `justin` in the example below were a link that would take the user to the line where the error occurred and/or maybe highlight it?

```
Execution finished with errors.
Result: no such column: justin
At line 1:
select * from mytable
where justin = 'mmm'
```

**Comment by chrisjlocke** [comment]
I personally think 'at line 6' (in my example) is still valid.  While the error is technically on line 7, the statement itself is on line 6, which is more than enough information to locate the error and correct it.  Having 'error on line 6-7' (or even worse, something wacky like 'line 3-976') is just 'noise' and makes it more confusing than it needs.

**Comment by MKleusberg** [comment]
> What if `justin` in the example below were a link that would take the user to the line where the error occurred and/or maybe highlight it?

The problem here is that we just get the full error message as text from SQLite. So all we could do was look for words in that message which also appear in the executed statement because we can't tell what's a column or table name and what's just a plain English word. Or a word in the error message could appear multiple times in the statement and we wouldn't know what occurrence caused the error.

I guess as long as SQLite doesn't provide us with a way to get more specific error locations there's really nothing we can do here which wouldn't introduce more confusion than it solves.
