### ISSUE TITLE
Commenting doesn't always group everything

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#2716]
Details for the issue
--------------------

#### What did you do?

Not all parts of a query seemed to be grouped together when commenting

![dbbrowsercommentedout](https://user-images.githubusercontent.com/1111743/119239958-9c811a00-bb01-11eb-8757-e054e59156e7.png)

#### What did you expect to see?

Can `justin` be grouped with other parts that are commented out? That way the expand/collapse includes it too.
This also affects sql statements as well, like `where`, `desc`, `asc`, etc

**Comment by chrisjlocke** [comment]
It would be helpful when submitting bugs to give the version of DB4S you're using.
I've tested this in the nightly from May 3rd, and it appears to be working without issue.

![image](https://user-images.githubusercontent.com/7872218/119240706-5b145d00-bb49-11eb-804c-ab8968e227c9.png)

**Comment by jungle-boogie** [comment]
Sorry. My mistake.

I'm using `DB Browser for SQLite Version 3.12.99 (May  3 2021)`

**Comment by chrisjlocke** [comment]
Playing around, it appears the widget only draws the lines when you press [Enter].  So in your example, press [Enter] after 'justin' (well, after 'mmm') then it'll draw the lines properly.  That's why my screenshot shows it working - it has an extra line.  Remove that extra line, and its still there.  Press [Enter] before 'justin' and it'll break the lines...

![image](https://user-images.githubusercontent.com/7872218/119241028-a6c80600-bb4b-11eb-91a1-3bf76a2ddc85.png)

Delete the line, and it'll appear as your screenshot.

![image](https://user-images.githubusercontent.com/7872218/119241045-b9dad600-bb4b-11eb-9af1-afd160057199.png)

Delete the line the other way (I know what I mean.... 😉) and it'll line up right.

![image](https://user-images.githubusercontent.com/7872218/119241078-e0990c80-bb4b-11eb-8dd8-caaa726cc939.png)

Unfortunately, while not fantastic, I believe this is out of our control (no pun intended) as this widget isn't built/designed/maintained by us.

**Comment by jungle-boogie** [comment]
Ah, good find, Chris.

I agree this is probably outside the tool's control! Thanks for tracking this down.
