### ISSUE TITLE
SQL scripts, which can be run under SQLite CLI with no problems, fails under DB Browser for SQLite

### ISSUE THREAD

**Issue by DavidKonicek** [sqlitebrowser/sqlitebrowser#2754]
Details for the issue
--------------------

#### What did you do?
(1) Download https://github.com/jpwhite3/northwind-SQLite3/blob/master/Northwind.Sqlite3.create.sql
(2) Run sqlite3.exe, create a fresh new database (open --new xxxx.sqlite), run this script (.read Northwind.Sqlite3.create.sql) ... no problems
(3) Run DB Browser for SQLite, create another (!!!) fresh new database (File > New database > enter some file name
(4a) File > Import > Database form SQL file > select and run this script
(5a) .... execution errors 
![2021-06-28 11_04_43-DB Browser for SQLite - C__Users_David_Desktop_pokus sqlite](https://user-images.githubusercontent.com/58885341/123610355-cdd7be80-d800-11eb-967f-09890504da1d.png)

ALTERNATIVELY:
(4b) Tab Execute SQL > Paste the content of the script and Execute
(5b) Error
Execution finished with errors.
Result: no such table: main.Territories
At line 317:
INSERT INTO EmployeeTerritories (EmployeeID, TerritoryID)
VALUES(1, '06897');

#### What did you expect to see?
No errors and the script should be whole run (as under CLI).

#### What did you see instead?
Errors - see above steps 5a and 5b

Useful extra information
-------------------------
DB Browser for SQLite Version 3.12.2
Built for x86_64-little_endian-llp64, running on x86_64
Qt Version 5.12.8
SQLCipher Version 4.4.3 community (based on SQLite 3.34.1).
(run on Win7 Prof. EN)

**Comment by chrisjlocke** [comment]
How did you copy / save the file to import it?  I only ask as the 'territories' part is at line 306, and DB4S seems to think it's at line 128 - that's quite a difference.

![image](https://user-images.githubusercontent.com/7872218/123632790-4003cf80-d810-11eb-9a6b-3081604a4418.png)

I downloaded the file and ran it myself with no problems.
https://streamable.com/fgcj8v

That takes about five minutes, rather than clicking 'File', 'Import' and 'Database from SQL' which took about a second, but did report an error.

![image](https://user-images.githubusercontent.com/7872218/123633116-b30d4600-d810-11eb-851c-8c07040f3dfc.png)

**Comment by chrisjlocke** [comment]
> the 'territories' part is at line 306

Oops, my mistake.  That's 'EmployeeTerritories'.  That kinda explains the above error then.
The 'create table' command references 'territories' but that's not actually created until line 5871.

What are the values of the PRAGMAs for your database?  (Ensure 'View' and 'Edit Pragmas' is set, then navigate to the 'Edit Pragmas' tab)

![image](https://user-images.githubusercontent.com/7872218/123633988-c836a480-d811-11eb-9627-037e12c455ac.png)

**Comment by chrisjlocke** [comment]
I'll close this due to the lack of response.
@DavidKonicek - feel free to comment if you're still having issues and this can be reopened.
