### ISSUE TITLE
Move rows inside a table

### ISSUE THREAD

**Issue by trenting** [sqlitebrowser/sqlitebrowser#2768]
Describe the new feature
--------------------------
I'd like the possibilities, in DB Browser for SQLite:
- to change the position of a row inside a table;
- to insert rows not only at the end of the table.

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by chrisjlocke** [comment]
Hi,
A database (or more specifically, a table) is just a bucket of bolts.  You can't put one bolt on top of the other, or when you add a bolt specify where in the bucket it goes - it just goes in the bucket.
However, the 'clever' bit is that technically, you don't care.  Through the miracles of the bucket, when you put your hand in, if you want the smallest nut, it'll just be right at the top.  Equally, if you want the largest nut, it'll be on the top too.  But if you peer into the bucket, you'll either see the largest or the smallest at the top of the bucket.  Just because that's what you can see, doesn't mean that'll be the next nut out.

Think of a database table with two rows.

Name: Alan
Age: 30

Name: Brian
Age: 20

My table has two rows.  Now I can sort that alphabetically - Alan, Brian or by age - Brian, Alan.
So I don't 'insert' a new record - David with an age of 25 - in the 'middle' - as there is no 'middle'.  I'll just slap him on the end.
Alan
Brian
David

Now, if I add another record, 'Charlie', I want him after Brian and before David.  But again, who cares?
Alan
Brian
David
Charlie

If I ask the database for all records in name order, it'll sort them.  I'll grab them from the bucket in that order - regardless of how I 'see' them peering into the bucket.

Does that make any sense whatsoever??!! 😁

**Comment by chrisjlocke** [comment]
Another example.  Airports in Iceland.

![image](https://user-images.githubusercontent.com/7872218/125330495-c2c37900-e33e-11eb-8087-aebfed656f1b.png)

Or I can sort by name.

![image](https://user-images.githubusercontent.com/7872218/125330547-d373ef00-e33e-11eb-85dc-212701590a86.png)

Or by IATA code

![image](https://user-images.githubusercontent.com/7872218/125330582-e1297480-e33e-11eb-8201-9101548b17c5.png)

So the position in the 'database' (or table) has no bearing at all.  I can't insert a record 'at the end' or 'in the middle' as I have no control over that - the database will shove it wherever it fits and will display it in whatever order I ask for it.

**Comment by chrisjlocke** [comment]
I'll close this due to lack of response, and the issue has been answered.
