### ISSUE TITLE
Duckdb support?

### ISSUE THREAD

**Issue by happydentist** [sqlitebrowser/sqlitebrowser#2793]
Can support DuckDB?
https://duckdb.org/docs/why_duckdb

**Comment by justinclift** [comment]
If it's a drop in replacement for SQLite, that can be compiled instead of the SQLite source code, then it'd probably work.

Otherwise, it's pretty unlikely.

**Comment by MKleusberg** [comment]
Unfortunately it doesn't look like it's a drop-in replacement for SQLite. This means we can't add it to DB4S without rewriting the whole thing. It's also worth mentioning that SQLite is so odd in so many ways that DB4S's user interface and features are unlikely to work with other databases in an actually helpful way. One example would be that SQLite doesn't enforce data types which in turn has many consequences for DB4S making it awkward to use for a database which does enforce types like DuckDB does. Because if this I'll go ahead and close this issue. Sorry about that!
