### ISSUE TITLE
Will you accept a one-time donation? :)

### ISSUE THREAD

**Issue by dannypernik** [sqlitebrowser/sqlitebrowser#2808]
So so glad I found SQLite browser. Was so tired of manual sqlite data manipulation. I'd prefer to make a one-time donation instead of subscribing to Patreon. Is there another place you'll accept a one-time donation? Thank you so much for this resource!

**Comment by chrisjlocke** [comment]
Sure, I can provide my bank account details - due to the application form, it only accepts 'thousands' as the unit, and it must be a positive integer with at least two digits.  😉

**Comment by justinclift** [comment]
@dannypernik Some people subscribe to Patreon for a month, then subscribe afterwards.  It's more of a hassle that way though, and if you forget you get billed for the extra months. :frowning:

From our point of view, Patreon is good because it helps us plan out future goals.  For example, we're saving up to replace our night build server (eta Nov/Dec), and we're also able to plan out hosting costs (etc) due to the way Patreon works.

As you mention though, it's not everyone's cup of tea. :smile:

**Comment by dannypernik** [comment]
Feel free to request $10.000 from @Danny-Pernik on Venmo ;)
