### ISSUE TITLE
Edit View Dialog box with large code

### ISSUE THREAD

**Issue by hrieke** [sqlitebrowser/sqlitebrowser#2820]
Details for the issue
--------------------

#### What did you do?
Clicked on Modified View (Right Click menu item)

#### What did you expect to see?
The buttons "OK", "Cancel", "Help".
See attached image no.1.
![Image 1](https://user-images.githubusercontent.com/17413019/131690283-546dc77e-ecf4-4333-980e-e88aa3177e0e.png)

#### What did you see instead?
A very tall modal dialog box with no way to see the three buttons on the bottom of the screen.
See attached image no.2.
![Image 2](https://user-images.githubusercontent.com/17413019/131690285-ee61df66-f293-476d-a222-11b2fdd88ccc.png)

I would think ideally that the text in the dialog box would be in a control that allows you to scroll up/down right/left.

Useful extra information
-------------------------
> DB4S v3.12.0 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.18363) [x86_64]
> using SQLite Version 3.32.2
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
Yes, rather than a custom dialog, it's just thrown out to a standard OS dialog, which doesn't have that level of control.  
Guess it was never envisaged that a view would be that monstrous! ;)

Not a great 'solution' but the keyboard is still working, so by pressing either [Return] or [Esc] would accept or cancel that dialog.  Obviously the proper fix would be to replace that dialog with a custom one, but due to the number of outstanding issues, it may not be a fix implemented in the short-term.
Thanks for reporting it though!

**Comment by mgrojo** [comment]
Thanks to efb9f9c9e0fffcf2f2b8721474ea64158134836e the query length inthe dialog is limited to 1000 characters. I don't know if that it's enough short for getting a reasonably sized dialog, but it will be better than in the last release. @hrieke could you give the nightly build a try and report if it gives better results? Then we could consider this issue fixed, since showing to query in the dialog is only for informing the user.

**Comment by hrieke** [comment]
It appears that the nightly build for Windows is still kaput.

**Comment by justinclift** [comment]
Yeah. https://github.com/sqlitebrowser/sqlitebrowser/issues/2810#issuecomment-903923268 :frowning:

**Comment by mgrojo** [comment]
@hrieke, they're being built again. Could you confirm the issue is solved for you?

**Comment by hrieke** [comment]
Hi, sorry, work has been a little nuts here.
Tried the nightly build, it looks good!
