### ISSUE TITLE
autoincremented timestamps

### ISSUE THREAD

**Issue by melodical-me** [sqlitebrowser/sqlitebrowser#2857]
Describe the new feature
--------------------------
I hope I haven't under-researched this idea, but I have been looking around for quite awhile, and it doesnt seem to have been addressed.  If the idea below has already been addressed, please let me know, so I can figure out how to use it.

So...  I want to use DB Browser a bit differently than what it is normally used for...  I would like to use it to run a simple journal, like a daily diary, except maybe with multiple entries throughout the day...

To do this, I usually just make a basic table (call it "entries"), and then the columns are id, date and entry.  The id is not null, primary key and autoincrement; the entry is simply a text field set to not null...  The date column is the issue here...

The feature I would like to request, if it hasnt already been made,  is a simple autoinsertable timestamp...  

This is because when I make the entries, I just open the database, and then I go to Browse Data -> Insert a new record...  At this point, I am just concerned with making the entry, and I dont really want to worry much about formatting the timestamp...  It would be easier and more accurate to just insert an entry using the "Edit Database Cell" column on the right, and then let the computer automatically make the timestamp when I hit "Apply"...

Right now, I have to use a python tkinter interface I made to do this, but, while that works, it is still an extra step...  

Timestamps really are not hard to make... They do raise formatting issues, but they are usually standard fare in most all computer languages...  so creating an algorithm to accommodate this feature wouldnt seem to be too hard...  

Again, maybe it has already been done, or a solution I have not yet identified does exist; if so please, let me know what it is...

Thank you!

Additional info
---------------
Please answer these questions before submitting your feature request.

**Comment by justinclift** [comment]
Hiya, welcome to the Community. :smile:

Generally the way this kind of thing is done, is to have a field for holding the timestamp, and have a default value on that field to get the current time.  SQLite uses `CURRENT_TIMESTAMP` for this.  eg the `somedate` field in the definition below :

```
CREATE TABLE "stuff" (
	"id"	INTEGER,
	"somedate"	TEXT DEFAULT CURRENT_TIMESTAMP,
	"entry"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
```

Be aware there is a gotcha (potential catch) though.  If you want to add a new field with `CURRENT_TIMESTAMP` to a SQLite table with data in it already, you have to do it in a few steps to avoid an error:

1. Use the "Modify table" dialog in the "Browse data" table to add the column, but _without_ any default value set, then click the OK button to apply the change.
2. Go back into the "Modify table" dialog, and this time change the `default` value for the field to `CURRENT_TIMESTAMP`.  The click the OK button to apply the new change.

With that, the new field will be in place and have the default value automatically setting the time stamp.  Existing entries in the table won't have a value set though, so you can manually give them all the same value at once by going to the "Execute SQL" tab and running:

```
UPDATE stuff SET somedate = CURRENT_TIMESTAMP;
```

Hopefully that helps? :smile:

**Comment by shariharan2002** [comment]
Hey Chris and Justin 
After cleaning my SQLIte Database using DB4S I tried to connect the 18.6gb dataset to PowerBI via ODBC(DSN).But due to large dataset size it failed(the ODBC worked for small datasets)
So then using SQlLite "Export as CSV" feature, I exported the .db to a csv format which came to a size of 16gb.
Then I connected the entire CSV to PowerBi.It took around 2hrs for the entire dataset to get connected(I deleted the 2-3 columns which I couldn't delete yesterday(due to journal growth) via PowerBi delete column feature.Then I saved it.The PBIX file is 1.6 gb...so I think I can't publish it.But I think I can still make models and maybe try to find some way to take screenshots and add it to a PPT or something like that.
The major thing I wanted to convey via this post is that, I was able to import a cleaned dataset with less errors/null values and hence I can confidently say, this cleaning procedure made it easier for PowerBi to connect/load/transform the dataset in reasonable time.

I thank Justin Clift and Chris Locke for their 
1.Expert
2.Prompt
3.Geneorus
4.To-The-Point
Help that you offered.I am sure, if it wasn't for you SQLlite Experts, viewing that dataset on PowerBI would be a distant dream.I still have a long way to go(creating models etc) but I am really really really thankful from the bottom of my heart for all the help you all offered for amateur analysts like me.
I again thank the experts for all the help
I just want to know, that if I do make my submission for my hackathon, do I have your permission to include your names?
If so could just include your full names(just for confirmation) and the method of contact(its completely your discretion to share,I was thinking of putting as "SQLlite,DB4S Experts-GitHub SQLLite Forum")
Also under the method of contribution I am referencing as "Expert help on managing import of large databases to SQLLite and on Data Cleaning Procedure" Will that be good?Should I add something? 

A Trillion Thanks!



Thanks a lot!

Thank you very very very much!!!!!!!!!!!

**Comment by justinclift** [comment]
Heh Heh Heh, that'd be cool.  You could probably refer to us a "DB Browser for SQLite" (DB4S) maintainers, and specifically mention Chris as he put in so much effort to assist.  For myself, I just threw in a couple of comments as seemed appropriate. :smile:

Btw, when you quote SQLite in important stuff, it's probably best to get the capitalisation right: `SQLite` (on capital `L`, one lowercase one.  It's not super important in anyway, but people who recognise the same will notice it right away. :wink:

**Comment by shariharan2002** [comment]
I am really sorry
I thought I was typing into the correct forum 
Let me place it back into the correct section
Thanks a lot

**Comment by justinclift** [comment]
You're welcome. :smile:
