### ISSUE TITLE
column 'type' in structure 

### ISSUE THREAD

**Issue by Z4us** [sqlitebrowser/sqlitebrowser#287]
In the 'structure' as well as the 'DB Schema' (aren't those two not the same ref to the table called 'sqlite_master' and therefore can better carry only one of aforementioned names [my suggestion 'Schema', bc it's called like that in most books and RFC's] ?) window is a column 'type' (may be one of the four on the left - 'table', 'view', 'index', 'trigger' [ eventually 'meta', but in practice I've never seen such a type... ] so to save space and avoid confusion to others and me you may safely remove it. My €0.02

**Comment by Z4us** [comment]
Sorry I forgot the column-name 'Schema'. One may call it by name in sqlite_master  'SQL' (or lower case 'sql')

Another thing: it seems that the version with sqlcipher when created with 512 byte page_size is automatically changed to the default 1024. Is therefore a reason?

**Comment by justinclift** [comment]
I'm not sure about the first bit, but the 512 → 1024 change for SQLCipher sounds like a bug. :wink:

**Comment by MKleusberg** [comment]
Closing this because while there still is the type column, it now shows only the data type of table fields which actually makes sense.

As for the naming inconsistencies, we could open a new issue for them but I think it's probably best to rethink the whole naming scheme for the 3.13.0 release, not just these inconsistencies :smile:
