### ISSUE TITLE
Why does it automatically order table names?

### ISSUE THREAD

**Issue by tmdwns7809** [sqlitebrowser/sqlitebrowser#2909]
What is your question
-----------------------

i just wanna see tables with original order that I put it in first time. 
but it seems like this program shows tables ascending ordered.
i wanna change this so i searched every features in but i couldn't find. is there no way to see tables the way it is?

**Comment by chrisjlocke** [comment]
As far as the database is concerned, the database of where the tables is, is just another table.  It doesn't have an ID value, so there is no 'record' of the order you put them in there.

![image](https://user-images.githubusercontent.com/7872218/143194555-4df931eb-0378-488d-8edd-b22c5d731a94.png)

The '1' and '2' in the scrrenshot is just the row DB4S gives to the row in the table.

Obviously, you can fork DB4S and remove the 'order by' clause yourself, but it still wouldn't display the order put into the table, but an arbitrary 'random' order of how the database has stored it.  Adding other objects could affect this order.

**Comment by Mohsyn** [comment]
> ## What is your question
> i just wanna see tables with original order that I put it in first time. but it seems like this program shows tables ascending ordered. i wanna change this so i searched every features in but i couldn't find. is there no way to see tables the way it is?

To retain your order of records add an additional column like myrowid and sort on that. It would be worth having a column if the sequence is important to you.

**Comment by chrisjlocke** [comment]
While that would work for your own tables in your own applications, this wouldn't work for DB4S - it's not designed to look at an added myRowId column.  The original question was related to how DB4S sees system tables and displays them.

**Comment by MKleusberg** [comment]
There is no way in DB4S to achieve this. You can run ```select name from sqlite_master where type='table'``` in the Execute SQL tab to get the table names but that's probably not what you're looking for. The reason the table names are sorted alphabetically is because that's what usually makes it the easiest to find the table you're looking for, especially when working with databases by other people or programs. In theory we could add an option to toggle between sorted and non-sorted table names but there are so many places in the UI where we should table names etc. and each of them would need to be implemented and maintained in two ways then. So unfortunately this is probably not going to happen any time soon because it would lots of extra future work and potential for bugs while adding little benefit to 99% of the users.
