### ISSUE TITLE
ZIPVFS compatibility

### ISSUE THREAD

**Issue by haephrati** [sqlitebrowser/sqlitebrowser#2949]
We are using https://sqlite.org/zipvfs and have found out that databases created with this extension, can't be opened from **DB Browser**.

**Comment by chrisjlocke** [comment]
zipvfs is an extension to SQLite.  You'd have to load the extension into DB4S so it knows its there.  Not 100% sure that would work though - unsure if all extensions, especially IO ones are compatible.

**Comment by scottfurry** [comment]
From a site [README page](https://www.sqlite.org/zipvfs/doc/trunk/www/readme.wiki):

> The core SQLite library is in the public domain. However, the ZIPVFS extension needed to read and write compressed database files is licensed software. You should only be able to see the ZIPVFS source code if you have a license. If you do not have a valid license you must delete the ZIPVFS source code.

I believe DB4S would need a license in order to access details or make use of C-API.
Also, project would have to be very careful about how it shares licensed data when distributing DB4S. License incompatibility leads me to lean towards belief implementation may not be possible.

**Comment by haephrati** [comment]
@chrisjlocke so sorry :) thanks!
