### ISSUE TITLE
feature request: sql editor font selection

### ISSUE THREAD

**Issue by palmiche** [sqlitebrowser/sqlitebrowser#299]
Since 3.6.0 sql editor font is not monospace. Please support font customization.

**Comment by justinclift** [comment]
Just checked, and you're right.  I hadn't realised our Preferences dialog doesn't allow a choice of font, it only allows size.

This sounds like a worthwhile enhancement. :smile:

**Comment by palmiche** [comment]
Wow! You just broke about any response time record I've ever heard of.

**Comment by justinclift** [comment]
I was looking at GitHub anyway for other stuff. :smile:

**Comment by MKleusberg** [comment]
This is kind of odd because we're still setting the font to Monospace. No idea why this doesn't get accepted on your system... It would be interesting to know which OS you're using and how exactly the font looks like on your system.
But either way, I've added a new option for setting the editor font to the Preferences Dialog. You'll find the new option in tomorrow's nightly build (see front page of the repository). Maybe manually setting the font already does the trick for you. Let us know if this works for you :)
Saludos a Chile! :smiley:

**Comment by justinclift** [comment]
Wow.  Now **that's** a good response time @MKleusberg. :grin:

**Comment by palmiche** [comment]
How do I set the font manually?

OS: Win 8.1 Pro 64 (6.3.9600)

![sql-editor-font-3 5 1](https://cloud.githubusercontent.com/assets/12277525/7500106/25dd52a0-f402-11e4-8b94-84e65a472370.png)

![sql-editor-font-3 6 0](https://cloud.githubusercontent.com/assets/12277525/7500122/3394d27e-f402-11e4-8f23-2c372e5c53ba.png)

**Comment by justinclift** [comment]
Hmmm, you might need to wait until the automatic build tonight?

**Comment by MKleusberg** [comment]
Yes, you'll need to wait for the nightly build. See details here: https://github.com/sqlitebrowser/sqlitebrowser#windows
The build should be there in ~6h. If you use the binary from that link you can click View->Preferences, then click the SQL tab, and edit the 'SQL editor font' option.

![font](https://cloud.githubusercontent.com/assets/3153504/7500605/e9734b94-f42e-11e4-906c-88060b1ace13.png)

**Comment by palmiche** [comment]
Thanks. I'll let you know you nailed it as soon as I can. :smile:

**Comment by palmiche** [comment]
Nailed it. Not that there was any doubt about it. :grin: 
:+1: @justinclift, @MKleusberg

**Comment by justinclift** [comment]
Awesome. :grinning: 

Thanks for checking and letting us know, it really helps. :wink:
