### ISSUE TITLE
[Bug]: It seems .env file to bypass doesn't work if database's name have character '@'

### ISSUE THREAD

**Issue by Sitlos** [sqlitebrowser/sqlitebrowser#3081]
### What did you do?

use .env to open the db when db name have '@'

### What did you expect to see?

don't need password

### What did you see instead?

still need password

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Oops!  Thanks for reporting this.  
Can you confirm what version of DB4S ytou're using.  the .env thing is relatively new, so just making sure you're using a version with it actually in it...
I assume if you rename the database this does indeed work OK?

**Comment by Sitlos** [comment]
I use the latest version 3.12.99 (June 29 2022). And Yes, I make it work by deleting '@' character in the database file name.

**Comment by Sitlos** [comment]
In file sqlitebrowser/src/DotenvFormat.cpp, the program try to parse .env file by the following expression:
QRegularExpression keyValueRegex("^\\s*([\\w|\\.\\-]+)\\s*=\\s*(.*)\\s*$");

I think the root cause may because "\\w" doesn't include '@'.

**Comment by Sitlos** [comment]
I have created a pull request: https://github.com/sqlitebrowser/sqlitebrowser/pull/3083 to fix.

**Comment by scottfurry** [comment]
The regex expression is setup on the assumption that the database name is made up of valid character names in the form of words. The '\w' regex attribute assumes words are made up of characters a-zA-Z (or standard ASCII) groups. The use of symbols in the regex is not done as regex allows characters that are not allowed as part of file names (i.e. '\', '/', ':', et al). 

Complicating this is usage of DB4S in multiple OSs (Win/MacOS/Unix/Linux). Yes, maybe we need to rework the regex to manage allowable file name characters. This makes the pull request incomplete. In my head, we would need to have a regex string for POSIX compliance, which would take care of Unix/Linux/MacOS world, and then a non-POSIX (windows). Ideally, a pull request encompassing the above situation would be of greater value (a singular change vice a series of expanding changes). We would have a single commit addressing the matter rather than untangling a series of commits. Or I'm being hyper-efficient. Could go either way.

That being said, and before we deep dive down a rabbit role of unknown depth, could you explain in some detail why the at sign ('@') is being used in a file name? Is this part of some automated process punting out the database? Is this a convention/standard/practice that needs to be maintained? How critical is this situation? A little more detail is needed here for me.

**Comment by Sitlos** [comment]
> The regex expression is setup on the assumption that the database name is made up of valid character names in the form of words. The '\w' regex attribute assumes words are made up of characters a-zA-Z (or standard ASCII) groups. The use of symbols in the regex is not done as regex allows characters that are not allowed as part of file names (i.e. '', '/', ':', et al).
> 
> Complicating this is usage of DB4S in multiple OSs (Win/MacOS/Unix/Linux). Yes, maybe we need to rework the regex to manage allowable file name characters. This makes the pull request incomplete. In my head, we would need to have a regex string for POSIX compliance, which would take care of Unix/Linux/MacOS world, and then a non-POSIX (windows). Ideally, a pull request encompassing the above situation would be of greater value (a singular change vice a series of expanding changes). We would have a single commit addressing the matter rather than untangling a series of commits. Or I'm being hyper-efficient. Could go either way.
> 
> That being said, and before we deep dive down a rabbit role of unknown depth, could you explain in some detail why the at sign ('@') is being used in a file name? Is this part of some automated process punting out the database? Is this a convention/standard/practice that needs to be maintained? How critical is this situation? A little more detail is needed here for me.

**Comment by mgrojo** [comment]
Fixed by #3083 thanks to @Sitlos. I suppose we can already close this.
