### ISSUE TITLE
[Feature]: Is there a way to change the UI font ?

### ISSUE THREAD

**Issue by suyangzuo** [sqlitebrowser/sqlitebrowser#3123]
### Describe the new feature

The default font is ugly……
I don't know why. Is there a way to change the UI font ?

<img width="1027" alt="PlipImR7Iz" src="https://user-images.githubusercontent.com/50766353/183272659-a822bf5a-9354-420b-963b-283fdc0a1b7f.png">

**Comment by justinclift** [comment]
Yep, there's a whole section (tab) in our Preferences for mucking around with the various fonts we display.  Take a look, I'm sure you'll figure it out pretty easily. :smile:

**Comment by chrisjlocke** [comment]
The Chinese UI font can't be changed due to a bug in Qt.  See here. https://github.com/sqlitebrowser/sqlitebrowser/issues/2744
Hopefully we can set the application font manually to a pre-determined value from a list (depending on the language), or add the option for the user to change the UI font (which I think would be better, personally).
