### ISSUE TITLE
[Feature]: Display column data from different databases

### ISSUE THREAD

**Issue by Ninon77** [sqlitebrowser/sqlitebrowser#3128]
### Describe the new feature

Dear reader,

I have two columns that I want to display next to each other in order to plot the containing data (either in a new table or in a new view).

example:
data 1: column named "4p0" in Database "Mx" table "DATA" - containing 10 values

data 2: column named "4p0" in Database "Mz" table "DATA" - containing 10 values

when I execute this command:

SELECT "4p0" FROM DATA UNION SELECT "4p0" FROM Mz.DATA

I get one large column containing all 20 values now. Which command do I need to excute in order to get two columns in one view/table?

I can save and open an sql-file (via the buttons in "Execute SQL") - is there also a way to see the history which commands I have already entered in the command window?

Best Regards

![image](https://user-images.githubusercontent.com/110451553/183640697-50a7f4d0-4bac-45a3-92fa-2b2d1610ae32.png)

**Comment by chrisjlocke** [comment]
I don't know what OS you're using, but guessing Windows?  I don't know what version of DB Browser for SQLite you're using, but guessing the latest release.
Download the nightly version.
https://nightlies.sqlitebrowser.org/win32/DB.Browser.for.SQLite-2022-07-09-win32.zip

Extract that .zip and find the 'DB Browser for SQLite.exe' program - just double-click it.  You don't need to install it, and it won't affect the currently installed version.

![image](https://user-images.githubusercontent.com/7872218/183645878-6a146c43-ef6d-4179-9e9a-8f772959908d.png)

This version is a 'in development' version, and allows two tables to be viewed at the same time.

![image](https://user-images.githubusercontent.com/7872218/183645987-daaedc68-f249-4c31-ba71-bfa3e04944f0.png)

In the 'Browse Data' tab, right-click in the header and select 'New data browser'.  You can drag this window around, make it float or 'dock' it in various locations, eg, one above the other.

![image](https://user-images.githubusercontent.com/7872218/183646197-a316064b-1458-492b-bf7f-116908970862.png)

Obviously, horizontally is better in this instance.

So that gives you the ability to view two tables at once, which isn't quite what you're after.
If you want one 'amalgamation' of the data, you can join them together using SQL.  You'll have to use the 'Execute SQL' tab though.

select mx.*,mz.*
from mx
left join mz on mx.ROWID=mz.ROWID

Each table has a hidden column called 'rowId' which is the rowId for that record.  You have to join the two tables together on something.
This gives this

![image](https://user-images.githubusercontent.com/7872218/183647831-ed9245b4-b070-4d7d-a74f-2ca2dd9535b6.png)

**Comment by chrisjlocke** [comment]
@Ninon77 - any thoughts?

**Comment by Ninon77** [comment]
Dear Chris,

thank you very much for your answer! I really appreciate it!
I have now been able to create my plot like I wanted 😊

BR,
Ninon

**Comment by Ninon77** [comment]
Dear Chris,

thank you very much for your answer! I really appreciate it!
I have now been able to create my plot like this 😊

BR,
Heike

Von: Chris Locke ***@***.***>
Gesendet: Dienstag, 9. August 2022 14:34
An: sqlitebrowser/sqlitebrowser ***@***.***>
Cc: Heike von Waaden ***@***.***>; Author ***@***.***>
Betreff: Re: [sqlitebrowser/sqlitebrowser] [Feature]: Display column data from different databases (Issue #3128)


I don't know what OS you're using, but guessing Windows? I don't know what version of DB Browser for SQLite you're using, but guessing the latest release.
Download the nightly version.
https://nightlies.sqlitebrowser.org/win32/DB.Browser.for.SQLite-2022-07-09-win32.zip

Extract that .zip and find the 'DB Browser for SQLite.exe' program - just double-click it. You don't need to install it, and it won't affect the currently installed version.

[image]<https://user-images.githubusercontent.com/7872218/183645878-6a146c43-ef6d-4179-9e9a-8f772959908d.png>

This version is a 'in development' version, and allows two tables to be viewed at the same time.

[image]<https://user-images.githubusercontent.com/7872218/183645987-daaedc68-f249-4c31-ba71-bfa3e04944f0.png>

In the 'Browse Data' tab, right-click in the header and select 'New data browser'. You can drag this window around, make it float or 'dock' it in various locations, eg, one above the other.

[image]<https://user-images.githubusercontent.com/7872218/183646197-a316064b-1458-492b-bf7f-116908970862.png>

Obviously, horizontally is better in this instance.

So that gives you the ability to view two tables at once, which isn't quite what you're after.
If you want one 'amalgamation' of the data, you can join them together using SQL. You'll have to use the 'Execute SQL' tab though.

select mx.,mz.
from mx
left join mz on mx.ROWID=mz.ROWID

Each table has a hidden column called 'rowId' which is the rowId for that record. You have to join the two tables together on something.
This gives this

[image]<https://user-images.githubusercontent.com/7872218/183647831-ed9245b4-b070-4d7d-a74f-2ca2dd9535b6.png>
