### ISSUE TITLE
Windows zip file nightly builds broken

### ISSUE THREAD

**Issue by voltagex** [sqlitebrowser/sqlitebrowser#3156]
DB.Browser.for.SQLite-win32.zip and DB.Browser.for.SQLite-win64.zip on https://nightlies.sqlitebrowser.org/latest/ are currently 22 bytes each. At a guess, these last successfully built on 29-Jun-2022

**Comment by chrisjlocke** [comment]
Thanks for reporting.
We're aware (https://github.com/sqlitebrowser/sqlitebrowser/issues/3105) and it's due to something somewhere being broke (or something a bit more technical).  I've tried building the Windows binaries myself, but I'm about as much use as a handbrake on a canoe.  
The Windows builds from 9 Jul are OK (https://nightlies.sqlitebrowser.org/win32/2022-07/DB.Browser.for.SQLite-2022-07-09-win32.zip).  Thankfully there hasn't been squillions of commits since this point, so it's not overly out of date.

I'll close this as the above issue can be used for discussion, but again, thanks for reporting it. 👍
