### ISSUE TITLE
[Bug]: what wrong with the setting

### ISSUE THREAD

**Issue by guanyanfei01** [sqlitebrowser/sqlitebrowser#3200]
### What did you do?

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/28953468/197749846-3899428f-5628-45d7-8dc1-16c0fc79f71c.png">

### What did you expect to see?

how to set the setting

### What did you see instead?

how to set the setting

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
Click 'Edit' and 'Preferences'.  I'm guessing due to the Chinese (maybe?) font, you don't see 'Edit' or 'Preferences', 

![image](https://user-images.githubusercontent.com/7872218/197754199-06076cf2-a753-4cda-8957-5c0df83067c2.png)

but its the second menu option (1), then the last menu option (2)


![image](https://user-images.githubusercontent.com/7872218/197754293-1bc62497-1a00-4d21-914f-d82ad2fafa91.png)

Change the font (1) to another font and try again.  Some fonts work better than others.

**Comment by chrisjlocke** [comment]
Closing as there has been no response. 😢 
Comment with more information, and it can be reopened.
