### ISSUE TITLE
Browser cannot open STRICT tables

### ISSUE THREAD

**Issue by Krazny** [sqlitebrowser/sqlitebrowser#3259]
Details for the issue
--------------------

#### What did you do?
I tried to open a table created with the STRICT keyword.

#### What did you expect to see?
I expected the table to be opened in the browser.

#### What did you see instead?
The browser complained of a malformed schema.

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19045) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by chrisjlocke** [comment]
This is probably due to 3.12.2 being built with sqlite 3.35.5, when strict tables was introduced with 3.37.
If you download the nightly, this is built with a newer version of sqlite.. 3.40

https://nightlies.sqlitebrowser.org/latest/DB.Browser.for.SQLite-win32.zip

If you just extract the .zip, you can run the .exe in it - you don't need to install it, and it won't get upset you've got his younger brother installed.  The two can co-exist.

**Comment by Krazny** [comment]
Thank you! I'll try that next time I actually have some "me time" at home. I failed to notice the versions 🤦

**Comment by chrisjlocke** [comment]
> Krazny closed this as completed 5 hours ago

I'll re-open this until you can confirm the nightly opens the database ... it'll serve as a reminder for us to bug you in case you forget. ;)
Its handy in case someone else encounters the same issue, and they can be confident the solution offered works. :)

**Comment by fabstu** [comment]
For me nightly allows opening the database without errors, thanks!

**Comment by chrisjlocke** [comment]
Thanks for confirming. :)

**Comment by theborakompanioni** [comment]
Did not work for me with the latest nightly from snap (`3.12.2-3813-b7c4b5a4` | 25 March 2023).

```
[user@host]$ cat /etc/os-release 
ID=fedora
VERSION_ID=37
```

```
sudo snap install sqlitebrowser --edge
```

```
[user@host]$ sqlite3 --version
3.40.0 2022-11-16 12:10:08 89c459e766ea7e9165d0beeb124708b955a4950d0f4792f457465d71b158alt1
[user@host]$ sqlitebrowser --version
DB Browser for SQLite Version 3.12.99 (Mar 25 2023)

Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.12.8
SQLCipher Version 4.4.3 community (based on SQLite 3.34.1).
```

Error is:
> Could not open database file.
Reason: malformed database schema (table_name) - near "STRICT": syntax error

Any suggestion is highly appreciated. :pray:

**Comment by justinclift** [comment]
@theborakompanioni Looking at that `--version` output from our application, you're using a version built with SQLCipher version 4.4.3.

Whilst not terribly outdated, that's not the newest release of SQLCipher.  And that particular version of SQLCipher is [based upon SQLite 3.34.1](https://www.zetetic.net/blog/2021/03/02/sqlcipher-443-release/).  So, it's a bit too old to understand `STRICT` tables.

For now, instead of the snap try our "continuous" AppImage build:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

If you don't need encryption, grab the "SQLite" one instead of the "SQLCipher" one there.  Download the one you choose, `chmod +x` it so it can run, then try with that.

In theory (!), it should work. :smile:

**Comment by theborakompanioni** [comment]
> In theory (!), it should work. smile

In practice, it has worked as well. :rocket: 

Thank you for the insanely fast response.

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by nahoj** [comment]
Hi. I cannot open a DB with a STRICT table using the sqlitebrowser latest/edge snap Version 3.13.99, even though it uses "SQLCipher Version 4.5.5 community (based on SQLite 3.42.0)". Is there anything I can do?

The table open fine using the sqlite3 CLI v3.42.0.

**Comment by justinclift** [comment]
> ... I'll just use the one from the PPA.

Yeah, probably the right approach. :smile:
