### ISSUE TITLE
Can't change column or delete.

### ISSUE THREAD

**Issue by AnthonyUccello** [sqlitebrowser/sqlitebrowser#329]
Howdy

When I add a new field, it adds the field. However I cannot change the name after I save it. It keeps the name it was created with (e.g. field24). I have tried restarting, and I cannot delete the row. Only add. When I try to delete the row I get a popup that says "no error".
![err](https://cloud.githubusercontent.com/assets/3809669/7898423/713d864c-06cd-11e5-86b5-1811f6a5fe69.png)

Thoughts or advice?

I tried with 3.5 as well, still won't work. I can provide the database.

**Comment by schdub** [comment]
@AnthonyUccello, hello. Thank you for reporting.
Which OS do you use? Win8?
Please attach or send me (see my email in my profile) database file for testing purposes.

**Comment by schdub** [comment]
@AnthonyUccello, in SQLite you can rename field in existing table with algorithm something like:
http://stackoverflow.com/questions/805363/how-do-i-rename-a-column-in-a-sqlite-database-table

I note separately: need to drop old table.

Because table 'armor' have PK and table 'grrbls' references this table as FK.
If you have data in table 'grrbls' then you can't rename fields in 'armor' table because dropping old table causes foreign key constraint failed.

**Comment by MKleusberg** [comment]
@AnthonyUccello Does the latest nightly build fix this issue for you? It should work by now :smile:

**Comment by revolter** [comment]
@AnthonyUccello, Ping? 😄

**Comment by justinclift** [comment]
@AnthonyUccello Last ping... :smile:

**Comment by AnthonyUccello** [comment]
Oh hey sorry!

I havent used this for over a year. You can close this issue!

**Comment by justinclift** [comment]
No worries.  Thanks @AnthonyUccello. :smile:
