### ISSUE TITLE
CONCAT in DB

### ISSUE THREAD

**Issue by Ertber** [sqlitebrowser/sqlitebrowser#3301]
Details for the issue
--------------------
Execution finished with errors.
Result: no such function: CONCAT
At line 1:
with t1 as (SELECT InvoiceId, TrackId,  SUM(Quantity * UnitPrice) AmountSpent
from InvoiceLine 
GROUP BY TrackId
ORDER BY AmountSpent Desc)
 
SELECT A.Name,CONCAT(c.FirstName+'_'+ c.LastName), c.CustomerId, SUM(t1.AmountSpent)
From t1
Join invoice I on I.invoiceId == t1invoiceID
JOin Customer c on c.CustomerId == I.CustomerId
JOIN  Track T ON T.TrackId==t1.TrackId
JOIN Album Al on Al.AlbumId==T.AlbumId
JOIN Artist A ON A.ArtistId==Al.ArtistId
GROUP By A.Name, c.FirstName
order by SUM(t1.AmountSpent)DESC;

#### What did you see instead?
I'm getting this error 

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-llp64] on Windows 10 (10.0) (winnt/10.0.19045) [x86_64]
> using SQLite Version 3.35.5
> and Qt 5.12.8

**Comment by justinclift** [comment]
Heya, looks like you're trying to use a dialect of SQL that's slightly different than what SQLite supports.  With SQLite, it has a concatenation **operator** instead of a concatenation function.  This might help:

https://www.sqlitetutorial.net/sqlite-string-functions/sqlite-concat/

:smile:

**Comment by chrisjlocke** [comment]
Change the second select to

`
SELECT A.Name,c.FirstName||'_'||c.LastName as cName, c.CustomerId, SUM(t1.AmountSpent)
From t1
Join invoice I on I.invoiceId == t1invoiceID
JOin Customer c on c.CustomerId == I.CustomerId
JOIN Track T ON T.TrackId==t1.TrackId
JOIN Album Al on Al.AlbumId==T.AlbumId
JOIN Artist A ON A.ArtistId==Al.ArtistId
GROUP By A.Name, c.FirstName
order by SUM(t1.AmountSpent)DESC;
`

As Justin says, rather than a function, use the '||' operator.
You have to suffix it with 'as cName' (cName can be anything, of course) otherwise you don't get a usable column name.

**Comment by chrisjlocke** [comment]
Closing due to lack of response.
@Ertber - yell back if you need further assistance and this can be reopened.
