### ISSUE TITLE
Frequesnt Crashing Using "Execute SQL" tab

### ISSUE THREAD

**Issue by Raviu56** [sqlitebrowser/sqlitebrowser#3303]
Details for the issue
--------------------

#### What did you do?
Open a DB with sqlitebrowser with few thousands of enteries, use "Execute SQL"
Type something like
SELECT * FROM mytable WHERE blabla >  5;

Change the sql few times and execute again

#### What did you expect to see?
Normal query result

#### What did you see instead?
It crashes with this error in terminal
Assertion [cpMax <= pdoc->Length()] failed at ../scintilla/src/Editor.cpp 6096

Useful extra information
-------------------------
> DB4S v3.12.2 [built for x86_64-little_endian-lp64] on openSUSE Tumbleweed (linux/6.2.2-1-default) [x86_64]
> using SQLCipher Version 4.5.3 community (based on SQLite 3.39.4)
> and Qt 5.15.7

**Comment by justinclift** [comment]
@Raviu56 Have you had a chance to try that out?

**Comment by hcae0001** [comment]
i had the same problem on ubuntu 22.04 and i reinstalled sqlitebrowser with this command

`sudo snap install sqlitebrowser`

instead of the same command with "apt-get" and now i have the last release installed without that bug.

for some reasons, the "apt-get" command install an older version that has the bug.

**Comment by justinclift** [comment]
> Seems working fine, but I think you should solve the issue.

Yeah, we have.  That's why the continuous build is working. :smile:
