### ISSUE TITLE
"Only display the icon" is not working after restart

### ISSUE THREAD

**Issue by bartek990** [sqlitebrowser/sqlitebrowser#3312]
Details for the issue
--------------------
When I change Preferences>Toolbar style>Main Window to "Only display the icon" the setting is applying  only until I  close the program. Whenever I run DB Browser it is displaying Main Window in default way (The text appears beside the icon) and I have to change this preference to something else, save and change it back to "Only display the icon" to make it work.

![Zrzut ekranu z 2023-03-31 18-28-23](https://user-images.githubusercontent.com/6698414/229180400-ccbfcac3-d3ec-47dd-b4f1-9768f503bbf3.png)

#### What did you do?
I change Preferences>Toolbar style>Main Window to "Only display the icon".

#### What did you expect to see?
See the interface in desired way after restart.

#### What did you see instead?
Main Window displaying icons and texts as default, but Preferences>Toolbar style>Main Window set as "Only display the icon"

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-lp64] on Ubuntu 22.04.2 LTS (linux/5.19.0-38-generic) [x86_64]
> using SQLite Version 3.33.0
> and Qt 5.15.1

**Comment by chrisjlocke** [comment]
v3.12.1 is quite old now.  I would suggest at least using v3.12.2 or even the nightly.
View the downloads here:
https://sqlitebrowser.org/dl/

The nightlies can be downloaded here:
https://nightlies.sqlitebrowser.org/latest/

If you download the .zip flavours, you can extract and run 'as is' - nothing to install.  You can then easily run 3.12.2 and the nightly side-by-side.

Yell back how you get on.  :)

**Comment by bartek990** [comment]
There is a snap? Apparently I've misspelled 'sqlitebrowser' when I was trying to install it via snap. Thanks a lot :)

**Comment by bartek990** [comment]
So, I ran `sudo apt purge sqlitebrowser` and than `sudo snap install sqlitebrowser` and still I have the same problem.
But some strange things are happening. First of all `sqlitebrowser' runs 3.12.99 version
![Zrzut ekranu z 2023-03-31 21-37-41](https://user-images.githubusercontent.com/6698414/229213485-f10ea2f4-a107-4ace-b483-18332dda26ee.png)
```
$snap info sqlitebrowser
...
channels:
  latest/stable:    3.12.2-3569-6cde3f5  2021-05-24 (3233)  91MB -
  latest/candidate: 3.12.2-3569-6cde3f5  2021-05-24 (3233)  91MB -
  latest/beta:      3.12.2-3809-9426509a 2023-03-18 (3834) 113MB -
  latest/edge:      3.12.2-3813-b7c4b5a4 2023-03-25 (3854) 113MB -
installed:          3.12.2-3569-6cde3f5             (3233)  91MB -
```
and...
```
$ sqlitebrowser --version
Qt: Session management error: Could not open network socket
DB Browser for SQLite Version 3.12.99 (May 24 2021)

Built for x86_64-little_endian-lp64, running on x86_64
Qt Version 5.5.1
SQLCipher Version 4.4.3 community (based on SQLite 3.34.1).
```
I don't like the "Qt: Session management error: Could not open network socket" part and I don't know if this is a good place to report this?

**Comment by scottfurry** [comment]
Session management error is a problem with some files/settings in user profile and QT. A quick google brought up this [this Stackoverflow](https://stackoverflow.com/questions/986964/qt-session-management-error) post. @bartek990, with Ubuntu desktop, try the Gnome desktop suggestion, `export` variable, first. If that doesn't work, try the KDE suggestion and look for recommended files/folders to remove from user profile.

**Comment by bartek990** [comment]
`export` method resolved the problem with qt. Thanks.
I've reinstalled sqlitebrowser with `ppa:linuxgndu/sqlitebrowser` according to [README](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/README.md) on [sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser) repo and version of program changed to 3.12.1, but problem with displaying interface remains the same.

**Comment by chrisjlocke** [comment]
3.12.99 means its a nightly, and the date is obviously from May 2021.  Thats old too.
The network socket error sounds like an issue we had with Qt, but from my fuzzy brain, I thought that was primarily Windows and Wi-Fi.  It may not be relevant.
Could you build from the lastest source?

**Comment by bartek990** [comment]
Ok, I've build sqlitebrowser according to instructions in [BUILDING.md](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu--debian-linux) and...
```
$ sqlitebrowser --version
Przeglądarka BD dla SQLite w wersji 3.12.99 (Mar 31 2023)

Zbudowane dla x86_64-little_endian-lp64, uruchomione na x86_64
Wersja Qt 5.15.2
Wersja SQLCipher 3.4.1 (oparta na SQLite 3.15.2).
```
Still the same problem with interface - property is applied until I close the program. Other settings seems to work fine (like language or application style).

**Comment by scottfurry** [comment]
I just tried this for myself locally on a Gentoo X86_64 and with SQLCipher. Setting main window to only show icons and clicking `Ok`, the GUI immediately snapped to desired setting. Note that I'm using Qt 5.15.8.

Can someone verify that QT is not the problem here (build latest with 5.12.3 - 5.12.5?).

**Comment by bartek990** [comment]
In my case it is also working when I'm changing this setting for the firs time. Check if GUI stays this way after closing and opening program again.

**Comment by scottfurry** [comment]
@bartek990 - Yup. You're right. It isn't *persistent*. That's a problem.
This feels like a setting being written/read but not applied to the GUI properly on start up.

**Comment by justinclift** [comment]
Interesting.  Just tried it here too, and can confirm the same thing.

Heh Heh Heh.  That's pretty ironic. :wink:

**Comment by justinclift** [comment]
@scottfurry You're looking into this, yeah?

I would, except I'm really trying hard to get some final DBHub.io stuff finished over the next 2 weeks.

**Comment by scottfurry** [comment]
@justinclift, @chrisjlocke - I was looking through the code last night to trace the *what* and *where* of settings. Unfortunately, I found what I feared - a can of worms.

My first impression was that on opening the DB4S app, the barest of settings are placed in the default settings file on app closing. It is only the action of actually opening preferences and saving is the settings file fully populated. This is a problem.

Next up was the action of application opening and settings handling. There does not appear to be a clear mechanism of applying settings before the main window is presented.

Settings are only broadly applied when preferences dialog is opened and dismissed with the clicking of the `save` button.

Overall, this bug is endemic of a larger problem - prudent settings handling. A fix would not be simple.

I'm fighting my tendency to *make it right* versus *make it work*. Any fix I could envision may dramatically alter how the application functions. I may take another swing at this, but I would caution folks to not expect an immediate resolution.

**Comment by chrisjlocke** [comment]
> Any fix I could envision may dramatically alter how the application functions

Thats the beauty of the nightlies.  We can join around the virtual water cooler and swop humourous stories of how your code corrupted our OS.... ;)

I don't know how Db4S does it or how C++ works, but in our work applications, we simply create a configuration class which loads all the settings, so that when the program needs a setting, it looks in this class.  The configuration dialog calls the 'save' function of the class which saves the new values.

The time-consuming process here would be creating a class then for each setting, add a setting to the class then search/replace the code for the original value to then put in the class value .. eurgh.
But hey, the benefits are many.... ;)

If this would be an approach you'd take, I'd be more than happy to help and assist.  
If you've another approach, again, I'd be happy to assist if it means drudging through code.

**Comment by bartek990** [comment]
I'm just watching, because I could with code in Ruby or Python - definitely not with C++, but I have suggestion...

Maybe you should "go hybrid" for a while and for now just code @chrisjlocke solution just for this bug as a start of new approach? Then over time you will transfer all settings to this new class and remove old code.

**Comment by scottfurry** [comment]
> I don't know how Db4S does it or how C++ works, but in our work applications, we simply create a configuration class which loads all the settings, so that when the program needs a setting, it looks in this class.

This is done in the Settings.cpp/.h files. Preferences/settings appear to be loaded when the class is constructed/loaded. You will see frequent utilization of `Settings::xxx` namespace calls to get/set values (keys being in strings). Looks like Qt manages this aspect okay.

Main concern is going through each of the classes ensuring there is some kind of *apply* function for settings (similar in nature to `settingsReload` function that *sort of* exists in some UI classes).

Let me *break* this down to smaller, more manageable chucks. I can then sketch out what needs to go where and when.

**Comment by justinclift** [comment]
Tried out my DB4S install again, and the behaviour isn't as bad as I first thought this morning.

For example, if we change font settings those seem to be saved correctly, and loaded upon subsequent settings.

These text+icons setting though act weird.  In testing now, some of the settings (eg not for the main toolbar) seem to stick between session ok.  But the main toolbar one *sometimes* works, and *sometimes* doesn't.

**Comment by justinclift** [comment]
Closing this issue, as @scottfurry is working on it in here instead: https://github.com/sqlitebrowser/sqlitebrowser/discussions/3317 :smile:
