### ISSUE TITLE
IF CLAUSE

### ISSUE THREAD

**Issue by rafael114** [sqlitebrowser/sqlitebrowser#3323]
it could be convenient for the sqlite db to be able to do some validations

**Comment by justinclift** [comment]
What's the problem you're seeing?

**Comment by rafael114** [comment]
it would be awesome to be able of do validations like in SQL server or
MySQL with an IF clause, the particular case i'm in right now it this case,
i need to do a validation like
if 1 = 1
begin
execute an update query

end
else
begin
execute an insert query
end

i've tried in many ways but couldn't reach something similar, if it's there
a way to do it right now could be know it, if it is not, would be cool to
take the suggestion to a future update

thanks for your time, very appreciated

R.

**Comment by justinclift** [comment]
Thinking about that specific example though, raises a different possibility.

The example is effectively "Do an insert, or if [condition] then do an update instead".

That behaviour is commonly used to detect when inserting a new row fails, due to an existing row being present.  eg if there's a unique key on (say) the price for an item, and the item is already in the database, then just update the price instead of trying to re-add the item

SQLite can already do this using what's called an `UPSERT`.  That's really just a name for an `INSERT` statement that has an `ON CONFLICT` clause:

https://www.sqlite.org/lang_upsert.html

It's been in another popular database (PostgreSQL) for a while, and SQLite added it in 2018.

The examples further down that page are pretty good at explaining it. :smile:

**Comment by chrisjlocke** [comment]
Closing as there have been no responses for a while.
In summary, while sqlite itself can't handle stored procedures, a plethora of programming languages which happily talk to sqlite could do what you need.
