### ISSUE TITLE
Does not expand to full screen. Workspace not available.

### ISSUE THREAD

**Issue by Rades1986** [sqlitebrowser/sqlitebrowser#3336]
Details for the issue
--------------------

#### What did you do?
Tried to expand the db browser window to full screen.

#### What did you expect to see?
I expected that the program window would expand to full screen, or it would be possible to reduce the height of the window so that the lower part of the working window was accessible.

#### What did you see instead?
The window does not maximize on a screen with a resolution of 1366x768. Everything works fine on a 1920x1080 screen.
The lower part of the working window of the program is not visible. The height of the window does not change.

Useful extra information
-------------------------
> DB4S v3.12.1 [built for x86_64-little_endian-lp64] on Ubuntu 22.04.2 LTS (linux/5.19.0-41-generic) [x86_64]
> using SQLite Version 3.33.0
> and Qt 5.15.1
![15-43-17](https://user-images.githubusercontent.com/101670940/235669538-ed4c6c03-4adf-4a71-8750-e71de6e67fff.png)
![15-42-37](https://user-images.githubusercontent.com/101670940/235669560-cd24ae15-10a7-4f0e-b26f-72e90bde474a.png)

**Comment by chrisjlocke** [comment]
I believe this is due to the right hand panels - they have a minimum size, or extend beyond the 'real' screen.

![image](https://user-images.githubusercontent.com/7872218/235700064-eff82b1d-701f-4e1f-89ab-3eae11025a01.png)

As a test, close the panels by clicking the [x]'s, as marked by (1) and (2).  I believe it is the 'Remote' tab (or the equivalent for you) which is the culprit.

**Comment by Rades1986** [comment]
Thanks for your help! I disabled "remote server" and the error is gone.

**Comment by Rades1986** [comment]
Thanks for your help! I disabled "remote server" and the error is gone.
