### ISSUE TITLE
High DPI scaling is off

### ISSUE THREAD

**Issue by akrantz** [sqlitebrowser/sqlitebrowser#340]
I'm using a Surface Pro 2 connected to an external 1920x1080 display. 

Some text looks really small since it isn't being scaled properly.

![pic](https://cloud.githubusercontent.com/assets/741153/7991572/f51c7796-0aad-11e5-85e7-f88b353b4e76.png)

**Comment by justinclift** [comment]
Ahhh interesting.  I don't have a HiDPI display to test it on, but one of the other guys might (unsure).

**Comment by akrantz** [comment]
You can always use the Windows Simulator to test this across various window sizes and resolutions.

**Comment by justinclift** [comment]
Interesting idea.  Hadn't heard of the Windows Simulator, but doing some DuckDuckGo-ing shows it might do the trick. :smile:

**Comment by MKleusberg** [comment]
The next Qt version will have improved High DPI support across different platform: http://blog.qt.io/blog/2015/12/18/qt-5-6-beta-released/

Maybe that will help, too?

**Comment by Rockvole** [comment]
It is a problem for me too. The save icon is 2mm wide on my screen for reference.
Dell M4800 with 4k screen 3840x2160

Version sqlitebrowser_2.0.0~beta1+ds.1-3_amd64

![sqlite_tiny](https://cloud.githubusercontent.com/assets/4139576/14859690/2e1c588c-0c5a-11e6-8a92-45436e9a5dfd.png)

**Comment by justinclift** [comment]
@Rockvole Ahh, would you be ok to try a recent release?

The version you're using 2.0.0-beta1, is literally about 10 years old.  We've made a few changes since then, including adding some support for High DPI & Retina (on OSX) displays.

If you need to compile things yourself, it's pretty easy.  There are cut-n-paste type of instructions here, if that's useful:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md

Does that help? :smile:

**Comment by Rockvole** [comment]
Thanks @justinclift - the new version looks fine.
Sorry, I thought the version in the Linux Mint 17.3 Cinnamon repo would be recent.

**Comment by justinclift** [comment]
No worries at all.  For the Linux Mint repo version... yeah, I'm not sure why it's so old.  Hopefully someone out there (not me) has time/interest to look into it, and get that fixed. :smile:

**Comment by justinclift** [comment]
Closing this, as it's ancient and the feedback here says it's fixed. :smile:
