### ISSUE TITLE
fonctionnalité

### ISSUE THREAD

**Issue by ulision** [sqlitebrowser/sqlitebrowser#3408]
ce qui serait bien c'est recherche de doublon dans une table ou aide à formuler des requêtes pour débutant comme moi merci pour votre travail

**Comment by FriedrichFroebel** [comment]
According to Google Translate, your request reads:

> what would be good is searching for duplicates in a table or helping to formulate queries for beginners like me thank you for your work

Given this, you are asking for two different features, namely:

* Allow detection of duplicates inside a table from within the GUI
* (Extended) support for query creation.

At least for second request, I usually would recommend to read/work through some hands-on introduction to SQL/SQLite3 queries as this would allow you to learn about queries in a coordinated manner instead of copying/generating snippets without really understanding what they actually do.

**Comment by ulision** [comment]
Merci
