### ISSUE TITLE
[Bug]: Crash when displaying large table

### ISSUE THREAD

**Issue by angiomach** [sqlitebrowser/sqlitebrowser#3415]
### What did you do?

I opened DB Browser, and opened a very large (5GB) .dat file – part of a backup from an email client. I saw the db structure (1 table, 14 fields).  The field I wished to see is of type BLOB. I choose "Browse Data" and the table data began to appear.  But before it was all displayed — there are 88638 records – the program vanished from the screen without warning.

### What did you expect to see?

I hoped to inspect/retrieve the content of the field in question.  I do not want to change anything, only read.

### What did you see instead?

The program crashed.
The machine has only 8GB of RAM — this is the most the hardware supports.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10 Home, version 22H2

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
I'm not sure you'll be able to use a 5GB database file with a machine having only 8GB of ram. :innocent:

That's more because we haven't spent much time optimising our program's memory use, so it tends to use a fair amount of ram as it's doing things.

My first suggestion is to try using our nightly builds instead, just in case you're hitting a bug rather than a ram limitation:

https://nightlies.sqlitebrowser.org/latest/

If that doesn't work, then I'd recommend trying some other GUI style programs for viewing SQLite data.  There might be others that are better optimised for using less memory.

---

If none of those work, um... are you any good at programming?  If you have even some basic programming skill, you could instead try extracting the rows you want using SQL queries on that database.

That *will* very likely work, but it's the kind of thing that will take some time and effort.

**Comment by chrisjlocke** [comment]
Another thing is to use the execute SQL tab and be specific for what you want. Rather than load all records, just view or edit the one you need. Use specific where clauses.
I've a client table with 45,000 rows but I never need to view all of them .. I'm usually looking for specific ones.

**Comment by angiomach** [comment]
Many thanks for those suggestions.

I tried the nightly built, and at the same time I closed as many 
applications as I could to free memory, but it still crashed although it 
got further than before.

Using sqlite3 and a SELECT to view some of the records — or, as also 
suggested, using Execute SQL within DB Browser —  I was able to confirm 
that certain records were present, but of course I still can't see/save 
the contents of the BLOB field without further software (possibly SQL 
Blob Export <https://www.yohz.com/sbe_details.htm>).

However, as this db was in an e-mail backup, I think I should just 
restore my email from that backup (after backing up its present state, 
for restoring after I've done).

------ Original Message ------
From: "Justin Clift" ***@***.***>
To: "sqlitebrowser/sqlitebrowser" ***@***.***>
Cc: "angiomach" ***@***.***>; "Author" 
***@***.***>
Sent: 2023-07-22 19:10:04
Subject: Re: [sqlitebrowser/sqlitebrowser] [Bug]: Crash when displaying 
large table (Issue #3415)

**Comment by chrisjlocke** [comment]
OK, a sort-of-hacky workaround #2 would be to create a new table, and copy/move into there only the records you're after - even if it was a subset of 3000 records, for example.  This would allow you to view just this table, edit as needed, then copy the records back.
Not ideal, but .. well, slightly better.

**Comment by chrisjlocke** [comment]
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/30a92301-c1b0-49cc-8c04-f7cd6f393851)
😄

**Comment by mgrojo** [comment]
There's a chance that the problem was the number of rows and not the available RAM. In that case, #2801 would have solved your problem, @angiomach, just in case you'd like to try the new nightly build.

**Comment by chrisjlocke** [comment]
@angiomach .. could you try the nightly and confirm/deny if its any better?
You just need to download the .zip and extract .. it doesn't need to be installed.

**Comment by angiomach** [comment]
I no longer use the problem data file, but I retrieved it from a backup 
and ran the nightly build on it. No improvement, however.

My installed version had been crashing while displaying the browse data, 
having got most of the way through it.  With most other apps closed, and 
watching with Task Manager, the program displayed "determining row 
count", and its RAM usage grew rapidly to around 2.6GB, where it stopped 
growing.  Then the browsed data began to appear on the screen, the RAM 
stayed as it was, and other resources fell to near zero.  The RAM 
increased further only when I scrolled the browsed data, but without 
scrolling I couldn't tell how much of the data had been processed. 
Scrolling generally caused a program crash, but by nursing it carefully, 
it proved possible to see right to the end of the data.

Under the same conditions, the nightly version doesn't begin to display 
the data, but crashes while still showing "determining row count".  The 
program's RAM grows rapidly but stops at about 1.7GB.  It stays there 
for a short time, then falls rapidly and the program crashes.

------ Original Message ------
From: "Chris Locke" ***@***.***>
To: "sqlitebrowser/sqlitebrowser" ***@***.***>
Cc: "angiomach" ***@***.***>; "Mention" 
***@***.***>
Sent: 2023-10-18 07:27:12
Subject: Re: [sqlitebrowser/sqlitebrowser] [Bug]: Crash when displaying 
large table (Issue #3415)

**Comment by twistios** [comment]
I just had a very similar problem. My Computer has got 24 GB of RAM so I guess it is pleanty for a DB of size "only" 300MB.
In the "Search Data" tab ("Daten durchsuchen") I can view serval tables with few entries but everytime I open the larger ones (~300,000 up to ~1,400,000) it crashes a bit after the window changes (you can see the column names).

I am able to run the command `select * from TABLE_NAME` on any of the tables.
As a test what the problem might be I created a test db with a table with ~1,200,000 entries and this was working. So different from what @mgrojo said the number of rows was not the problem for me. But the test database was only ~30MB. It could be that the important factor is the size of entries (therefor it would only happen with blobs and the like). My original table did contain blobs.

Info: 
- Windows 11 23H2
- DB Browser for SQLite Version 3.12.2
  Erstellt für x86_64-little_endian-llp64, laufend unter x86_64
  Qt Version 5.12.8
  SQLite-Version 3.35.5

The problem seems to be resolved for me in the latest build (February 08 2024).

**Comment by chrisjlocke** [comment]
> The problem seems to be resolved for me in the latest build

Thanks for confirming.
