### ISSUE TITLE
[Improvement] Edit database cell window positions

### ISSUE THREAD

**Issue by meNESS** [sqlitebrowser/sqlitebrowser#342]
Each time I click on a cell, its editing window will be opened on different positions and it makes me move the window to other positions because the save changes button will be placed under the taskbar.

**Comment by justinclift** [comment]
What would you like it to do instead? :smile:

**Comment by Alirezaaa** [comment]
@justinclift You should set certain positions for such windows. Currently If you edit some cells without moving the window, after four or more times you have to move the window to other positions because you cannot click the save changes button! And that's the problem.

**Comment by MKleusberg** [comment]
Personally, I don't experience this problem because on my (Linux) system the dialog is always centered above the main window. I've tried to implement the same behaviour for Windows now but can only assume it's working (because it looks the same as before to me). So with any luck this issue should be fixed for you in the next nightly build :smile: And please let me know if it doesn't work for you.

**Comment by justinclift** [comment]
@meNESS This has finally been fixed. 😁 

@DelphiGit did it for #633 (thanks!), so closing this now. :smile:
