### ISSUE TITLE
Keyboard shortcut to access FILTER.

### ISSUE THREAD

**Issue by yamamov** [sqlitebrowser/sqlitebrowser#3439]
While viewing data, a shortcut key is needed to access the filters for that column.
I can use the keyboard to navigate to any row or the beginning of the table, but I always need to use the mouse to access the filters. I want to be able to browse the data without having to take my hands off the computer.

**Comment by justinclift** [comment]
Sounds sensible to me.  Looking at the wiki page that lists our Keyboard Shortcuts... yeah.  Nothing seems to be listed. Oops.

https://github.com/sqlitebrowser/sqlitebrowser/wiki/Keyboard-shortcuts

@mgrojo What do you reckon?  Is this do-able? :smile:

**Comment by mgrojo** [comment]
Ok, I've implemented it in this way:

* Focus on the corresponding Table Browser and then:
  * <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd> sets focus to the filter line header.
  * <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>F</kbd> sets focus to the global filter line.

@yamamov, it will be available in the next [nightly build](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds).

**Comment by mgrojo** [comment]
@yamamov maybe you expectated it to go to the filter of the current column? No, it goes to the first filter and then you can use tab to navigate to other columns. Going to the current column would require more work, and I don't see a clear benefit for the user.

**Comment by yamamov** [comment]
I see. In my case, I had the first column hidden, so I didn't notice that the focus had moved there.
If I can use the tab key to navigate and get to my destination, I'm good to go. Thank you.

**Comment by justinclift** [comment]
Ahhh.  @mgrojo Maybe it should go to the first non-hidden column?

**Comment by mgrojo** [comment]
OK, the part about the hidden column convinced me to do it in another way, and now it works better; if there is a current column, it brings the focus to that column filter, otherwise to the first non-hidden column.

As an added bonus:
* Pressing Tab in the last filter line, it passes the focus to the table (formerly, it stopped there)
* The "Use in Filter expression" commands in the contextual menu of the cells, put the focus in the filter line. So one can open the contextual menu with the keyboard (provided the keyboard is modern and has the menu key), set one of those predefined filters and then clear or modify the filter with the keyboard too.

There is a focus trap I couldn't solve though; if you press Alt+2, the Data Browser tab is selected, but the focus is trapped somewhere, and you have to click the table to start working with the keyboard.

**Comment by justinclift** [comment]
Sounds like a good "quality of life" improvement for people. :smile:

**Comment by chrisjlocke** [comment]
Closing as completed.
Thanks @mgrojo

**Comment by danielkrajnik** [comment]
Thank you everyone for adding this shortcut, does anyone know if this should be already available in *3.12.2*?

**Comment by mgrojo** [comment]
No, that release is older than this issue. The feature is currently only in the nightly build, and will be in the long awaited 3.13 release, hopefully available in the next weeks.
