### ISSUE TITLE
[Bug]: New record by browser data

### ISSUE THREAD

**Issue by PatriaMinas** [sqlitebrowser/sqlitebrowser#3448]
### What did you do?

In the data navigation tab, there is the insert new record button.
When clicking on this button, the software already understands that the data has been inserted, and records the blank information, before typing the new record.
Even if there is a trigger to record the data in another table, the data is recorded in blank, before typing the new record.

### What did you expect to see?

It was supposed to record the record after pressing the insert button, and not previously.

### What did you see instead?

The registry was written blank before entering the new values.

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Windows

### OS version

Windows 10

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by chrisjlocke** [comment]
DB Browser for SQLite has always added a blank record and used this record for the new record.  Historical reasons .. probably due to how the Qt grid once worked.
Theoretically, you can hold down the 'add record' button to get access to the 'insert values' box.  This will only add a record when you click [OK].

**Comment by PatriaMinas** [comment]
Thank you very much for the information.

**Comment by justinclift** [comment]
@PatriaMinas Are we ok to close this issue? :smile:

**Comment by chrisjlocke** [comment]
Closing as 'resolved'.
