### ISSUE TITLE
Encoding trouble when importing

### ISSUE THREAD

**Issue by michalferko** [sqlitebrowser/sqlitebrowser#345]
I have an existing database with utf-8 strings inside (tested with Eastern-European characters like čšťžýúä any others). Everything works OK, but when I try to import an .sql file (in "Execute SQL" tab, both "Open SQL file" or copy-paste the whole SQL file contents), the characters are replaced with ?.

This works fine with 32-bit version 3.5.1 (clean portable install) on the same database. I'm reverting to the old version for now.

System: Windows 8.1 Pro
Version: 3.6.0 Portable 64-bit

**Comment by justinclift** [comment]
Interesting.  Would you be ok to try our latest nightly build?  There was a bug in our Unicode handling for the Execute SQL tab, which is fixed in that.  I'm kind of thinking that might solve the problem for you too. :smile:

Download locations for our nightly builds are on the front page of our repo, if that helps. :wink:

**Comment by michalferko** [comment]
Hi, the latest nightly build for Windows I found is an older version: 3.4.0

The front page links here: http://rp.oldsch00l.com/sqlitebrowser/

**Comment by rp-** [comment]
I fixed the build process and did a fresh build

**Comment by michalferko** [comment]
OK, everything works fine with the nightly build. Thanks

**Comment by justinclift** [comment]
Awesome. :smile:
