### ISSUE TITLE
Question Mark Showing Mac pc

### ISSUE THREAD

**Issue by gunns337** [sqlitebrowser/sqlitebrowser#347]
select * from table_mst where names=??????  here my query showing question mark.On mac pc

**Comment by justinclift** [comment]
Would you be ok to try our latest nightly build (download locations are on the front page of our repo)?

There was a bug in the 3.6.0 and 3.6.1 to do with Unicode handling, but it's fixed in our latest nightly builds.  I'm guessing that's the bug you're hitting. :wink:

If the latest nightly build still doesn't work though... that's a new bug we should look into. :smile:

**Comment by gunns337** [comment]
Its working ...Thanx #justinclift

**Comment by gunns337** [comment]
Its working but cant match the record

**Comment by justinclift** [comment]
You're welcome. :smile:
