### ISSUE TITLE
[Bug]: SQLiteBrowser with default window layout doesn’t support small screens (Linux, GNOME)

### ISSUE THREAD

**Issue by jd-develop** [sqlitebrowser/sqlitebrowser#3477]
### What did you do?

I opened a fresh install of SQLiteBrowser under Ubuntu 23.04 with default Ubuntu Gnome DE, with a 1366x768 screen resolution.

### What did you expect to see?

I expected that I can interact with the program, i.e. resize it, fullscreen it, …, or simply open databases, create tables…

### What did you see instead?

I couldn’t resize or fullscreen the program, and it was very difficult to open menus, click on buttons, … because it barely works.

I attached a screen recording, where you can see me trying to resize the window without success, and trying to deal with a database.

[Capture vidéo du 2023-09-29 10-47-50.webm](https://github.com/sqlitebrowser/sqlitebrowser/assets/65287945/c266bc19-0dc4-49e6-b854-de741128cf62)

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

Linux

### OS version

Ubuntu 23.04

### Prevention against duplicate issues

- [x] I have searched for similar issues

**Comment by jd-develop** [comment]
It may be linked to #2097

**Comment by jd-develop** [comment]
My temporary solution was to remove the top bar using a GNOME extension. Also, closing all the widgets from the right part of the window fixes the problem.

**Comment by lucydodo** [comment]
Well, I've tested it on Ubuntu 22.04 and it works fine. Did you have any user settings for GNOME?

**Comment by scottfurry** [comment]
@jd-develop - there is a [qt thread](https://forum.qt.io/topic/145923/qt6-on-ubuntu-22-04-strange-widget-behavior/3) discussing presentations problems. An issue found was a problematic residual environment variable. Confirm, please?

I'm not convinced #2097 is related. KDE Plasma <> Gnome. They are just two different creatures entirely. But this situation could be highlighting a Qt5 bug on our part in the newer Gnome/KDE environments being released. There have been some breaking changes with both desktop environments that have forced Qt to make changes to Qt6. These changes may not have been backported to Qt5 (what DB4S uses).

I have to exert some _google-fu_ to dig up a better explanation for the situation.

**Comment by scottfurry** [comment]
[ArchWiki - HiDPI - Qt5](https://wiki.archlinux.org/title/HiDPI#Qt_5)
@chrisjlocke - thoughts?

**Comment by chrisjlocke** [comment]
This has been reported before, and I believe the fix was to remove (or close) the remote dock window.  

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/16536b78-252d-4685-be1d-f985361a470b)

This doesn't show up well in just screenshots, but when its visible, the screen has a minimum height.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/cd1b258d-a2fd-49d9-9f15-7ef525e984e3)

When closed, the screen can be reduced.

> Also, closing all the widgets from the right part of the window fixes the problem.

This would confirm the above, but just to further advise that just the remote tab needs to be closed.

![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/82a33946-0dfc-4726-bd25-cc0c94d0fa6b)

Also, just to reiterate for anyone else who stumbles across this topic, the remote dock can be closed by clicking the [x] in the dock window (1), or by selecting 'View' from the menu (2) and selecting 'Remote' (3).

**Comment by scottfurry** [comment]
@chrisjlocke - The last link I posted to ArchWiki suggested some environmental changes for Qt5-based apps when used in the latest Gnome/KDE environments. Has anyone determined if those suggestions would alleviate the problem we're observing above? Does anyone in the group use the latest Gnome?

Personally, I'm using other environments(XFCE/Mac). I would have to attempt this in a virtualbox environment and may not be exactly applicable.

**Comment by justinclift** [comment]
It's probably also worth trying our very latest linux build too, rather than the 3.12.2 release:

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

Just grab the SQLite or SQLCipher (has encryption) .AppImage build from there.  It'll likely work a bit better. :smile:

**Comment by chrisjlocke** [comment]
Closing as no response.
