### ISSUE TITLE
Please Add Dark Mode

### ISSUE THREAD

**Issue by FahadIbnaTuhin** [sqlitebrowser/sqlitebrowser#3567]
### Describe the new feature

I have problem while working with white mode. It is so annoying for working huge time. Please add Dark Mode

### Does this feature exist in another product or project? Please provide a link

No

### Do you have a screenshot? Please add screenshots to help explain your idea.

No

**Comment by justinclift** [comment]
@FahadIbnaTuhin Which version of our application are you using?

If it's version 3.12.x or any of our development snapshots in the last year and a half, then it should already be an option in the application preferences.  In theory. :smile:

**Comment by justinclift** [comment]
Closing this due to lack of response.

For anyone else looking for Dark Mode, it's already in the 3.12.x release so you're probably just using an older one.

If you need to upgrade your release but can't find how to do that, then grab a nightly release:

https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds

If none of that works, then you're welcome to create a new issue in our repository here so we can look into it. :smile:
