### ISSUE TITLE
3.7.0: Modifying a table / deleting column does not work

### ISSUE THREAD

**Issue by dbreslau** [sqlitebrowser/sqlitebrowser#362]
I tried to delete a column via the "Modify Table" popup. Selecting the column and clicking on "Remove" brought up a popup that said "No error", but the column remained. The SQL log for the app shows:

SAVEPOINT sqlitebrowser_rename_column
CREATE TABLE `sqlitebrowser_rena... <string can not be logged, contains binary data> ...
INSERT INTO sqlitebrowser_rename_column_new_table SELECT `_ID`,`name`,`local_path_template`,`is_localized`,`is_automatic`,`file_set_id` FROM `FileInfo`;
DROP TABLE `FileInfo`;
ROLLBACK TO SAVEPOINT sqlitebrowser_rename_column;

which I interpret to mean that a) the rollback means that the operation failed, despite the "No error" popup, and b) perhaps binary data in the CREATE TABLE statement is not helping, either? (Could this be a side-effect of the new UTF-8 support?)

**Comment by schdub** [comment]
I guess you have data in table FileInfo and other table references (FK) primary key _ID.
In SQLite you can rename/delete field in existing table with algorithm something like:
http://stackoverflow.com/questions/805363/how-do-i-rename-a-column-in-a-sqlite-database-table
I note separately: need to drop old table. Our application works in a similar way when renaming fields.
When application try to delete old table FileInfo it causes foreign constraint failed. 

For example what going wrong:

    -- 1) create two referenced tables
    create table table1 (`_ID` INTEGER PRIMARY KEY, `data` BLOB DEFAULT NULL);
    create table table2 (`TABLE1$ID` INTEGER REFERENCES  table1(`_ID`));
    
    -- 2) and add some data
    insert into table1(`_ID`) values(1);
    -- table2 references table1
    insert into table2(`TABLE1$ID`) values(1);
    
    -- 3) now try to remove field data in table1.
    --    its failed because FK constraint while deleting old table1
    
    -- 4) disable FK constraint (better use 'edit pragmas' and hit Save).
    PRAGMA foreign_keys = "0";
    
    -- 5) now try step 3 again - and its succeeded.
    
    -- 6) dont forget enable FK
    PRAGMA foreign_keys = "1";
    
WARNING: before do same thing on your db, backup first.

About 'string can not be logged, contains binary data' it was bug while logging
user input in multiline queries. But it already fixed recently.

**Comment by dbreslau** [comment]
Yes, I do have tables that reference FileInfo with foreign keys. It would have been nice to get clearer error messages or logs, but... you get what you pay for :-}

**Comment by justinclift** [comment]
@dbreslau Out of curiosity, apart from the "string can not be logged, contains binary data" (that should be fixed in our latest nightly builds), what would clearer messages/logs look like?  It's something we could consider. :smile:

@schdub Should we add some database calls to our Modify Table code, so it disables and re-enables the primary keys for the rename?  I'm guessing it might help in some situations, and we could still Rollback if an error is detected. (?)

**Comment by dbreslau** [comment]
Thanks for asking. I'm making an assumption here (yes, I could try it out, but... :-) that the sqlite API reports an error message if you try to delete a table, or rows in a table, that can't be deleted due to a FK constraint. So if sqlite's error message(s) could be displayed in the popup, instead of it displaying "No error", that would be a big help. If that's not feasible, then even "Unknown Error" would be better. As it was, the "No error" lulled me into thinking that indeed no error had occurred. (Maybe "No error" was displayed not to mean that no error had occurred, but rather that an error *had* occurred but the browser couldn't determine what the error was.)

I realize this is asking quite a bit more, but: It would be great if, when I try to delete a table or column that's referenced by a foreign key, the browser could tell me in advance of execution "You can't do that; it's got foreign keys pointing to it."

**Comment by justinclift** [comment]
Good thinking, both of those ideas make sense.  I'm personally not sure of the feasibility, but others will know more. :wink:

**Comment by schdub** [comment]
@dbreslau absoulutly agree that this error message should be more informative in this case.
@justinclift I have a look what I can do.

**Comment by justinclift** [comment]
@schdub Excellent. :smile:

**Comment by schdub** [comment]
Should be fixed with #363.
Same issue: #329.

Error message will be something like:
![screenshot from 2015-06-20 225657](https://cloud.githubusercontent.com/assets/1304776/8269139/cc38bfc4-17a5-11e5-95cd-f8b098dfbe21.png)

I think we should to create wiki page what should to do in case such error message (my first post in this thread about pragma foreign_key).

**Comment by dbreslau** [comment]
Thank you!

**Comment by justinclift** [comment]
Excellent stuff @schdub. :grin:

@dbreslau Would you have time to grab our latest nightly build, and verify that it's working properly for you?  (95% chance it will, but it's always good to check just in case :wink:)

**Comment by MKleusberg** [comment]
I've just pushed a small commit series which still needs more testing but in theory should improve the application's behaviour in two ways:
* If you try to change a column name of a column which is referenced in a foreign key this is impossible. Instead of just failing we'll now print an error message, explaining the problem.
* If you try to change a column in a table which is referenced in some foreign key, but it's another column that's being referenced, the application used to fail because of the way the renaming process was done. This is fixed now, so editing these columns should be possible now :smiley:

**Comment by justinclift** [comment]
Awesome as well @MKleusberg.  Good team effort here. :grin:

**Comment by MKleusberg** [comment]
@dbreslau Is the latest nightly build working for you? If so, we can close this issue :smile:

**Comment by dbreslau** [comment]
Hi, all,

I'm very sorry for not getting back to you on this. The short story is that
I *think* that it worked, but I no longer have access to the database where
I found the issue.

Thanks,

Dan

**Comment by justinclift** [comment]
No worries.  I'll close this issue for now, but if you find it is still occurring please reopen it and let us know. :smile:
