### ISSUE TITLE
Quick Browse

### ISSUE THREAD

**Issue by ferieninsel001** [sqlitebrowser/sqlitebrowser#3620]
### Describe the new feature

Being able to browse data of a specific table by double clicking on it in the database structure field

### Does this feature exist in another product or project? Please provide a link

no

### Do you have a screenshot? Please add screenshots to help explain your idea.

no

**Comment by chrisjlocke** [comment]
![image](https://github.com/sqlitebrowser/sqlitebrowser/assets/7872218/39cb6e07-8dc9-4838-888f-cd92fbc405d8)

You can right-click the table and select 'Browse table'.

We (generally) prefer actions the user selects, rather than ambiguous actions .. some people might expect double-clicking to modify the table, or delete the table (indeed they do...) and having an option for the user to decide what to do would clutter the option panel (which is already strewn with tabs and options).

Also, double-clicking opens/closes the key which shows the individual field names.  So this would be counter-entuitive in operation .. double-click the key to close it and it browses the data ... just ... no.
