### ISSUE TITLE
[Bug]: External drives cannot be opened on Ubuntu

### ISSUE THREAD

**Issue by mshd** [sqlitebrowser/sqlitebrowser#3626]
### What did you do?

![Screenshot from 2024-05-02 11-41-06](https://github.com/sqlitebrowser/sqlitebrowser/assets/17379661/b10361fa-eef4-4e1f-bbe4-dbcb81166a17)
I have DB files a flash drive and external hard drives but they cannot be opened.
I also get an error when I open the file from the file explorer, it states: Could not open database file.
I'm using Ubuntu 24.04 LTS, I think it previously worked on Ubuntu 22

### What did you expect to see?

I expect the file to pe opened

### What did you see instead?

Error.

### DB4S Version

3.13.0-rc1

### What OS are you seeing the problem on?

Linux

### OS version

Ubuntu Linux 24.04

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Oh, that's weird.  This kind of thing *seems* like a permissions problem.

Just to double check, is the version of our application the .AppImage from this page?

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/v3.13.x-rc1

Asking that because the problem you mention also happens with Snap packages because they do "weird shit" (:wink:) with how they access parts of the system.  If you didn't install from a Snap though, then it won't be that.

**Comment by mshd** [comment]
Hi Justin, opening an external file from the AppImage file works.
Thanks a lot for your help.

**Comment by justinclift** [comment]
Cool, all good.  Glad you got it working. :smile:
