### ISSUE TITLE
[Bug]: Access SQLCipher database on Windows with custom KDF iteration length fails

### ISSUE THREAD

**Issue by developernotes** [sqlitebrowser/sqlitebrowser#3651]
### What did you do?

I am attempting to open an existing SQLCipher database file that uses a custom KDF iteration length. When I specify the correct values within the custom interface on Windows, DB Browser for SQLCipher is unable to open the database. This issue exists in the [Nightly build](https://nightlies.sqlitebrowser.org/latest/) of DB Browser for SQLite on Windows.

### What did you expect to see?

I should be able to specify a custom KDF iteration length and open a database that was previously configured with those values.

### What did you see instead?

After specifying the correct parameters including the password and the custom KDF iteration length, clicking OK on the SQLCipher encryption dialog clears all field values and presents itself again. The database file is not opened as expected. Upon closing that window, the following dialog is presented:

<img width="241" alt="Screenshot 2024-06-04 at 15 39 27" src="https://github.com/sqlitebrowser/sqlitebrowser/assets/3225/986e1d79-f93b-4ad7-866b-4a938e0273aa">

I'm not sure if it's related, but when executing the following SQL command against a database within DB Browser for SQLCipher (on Windows):

```
PRAGMA cipher_version;
```

No value is reported, which typically means that SQLCipher has not been loaded/linked properly and the application is likely linking to a SQLite implementation instead.

### DB4S Version

3.13.99 (nightly)

### What OS are you seeing the problem on?

Windows

### OS version

Windows 11

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by lucydodo** [comment]
Thank you reporting this. I was able to reproduce the issue.
We recently replaced the CI system that builds our apps, and I think that's when the issue occurred.
For now, I've confirmed that the build dated 05/19/24 is working fine, please use that build until the issue is resovled.

- [DB.Browser.for.SQLite-2024-05-19-win32.msi](https://nightlies.sqlitebrowser.org/win32/DB.Browser.for.SQLite-2024-05-19-win32.msi)
- [DB.Browser.for.SQLite-2024-05-19-win32.zip](https://nightlies.sqlitebrowser.org/win32/DB.Browser.for.SQLite-2024-05-19-win32.zip)
- [DB.Browser.for.SQLite-2024-05-19-win64.msi](https://nightlies.sqlitebrowser.org/win64/DB.Browser.for.SQLite-2024-05-19-win64.msi)
- [DB.Browser.for.SQLite-2024-05-19-win64.zip](https://nightlies.sqlitebrowser.org/win64/DB.Browser.for.SQLite-2024-05-19-win64.zip)

**Comment by lucydodo** [comment]
Now that I think about it, this has happend before: #3582 
It looks like this patching was accidentally removed in a CI migration job.
I pushed a commit that addresses the same issue, so it should (in theory) work. Can you tak a look at it? :)

> I'ld like to test it out first, but I'm out and about right now and don't have a Windows laptop available. :(

**Comment by lucydodo** [comment]
I tested it with the daily build that was built about an hour ago and confirmed that it works fine. Want to give it a try?

> Test environment: Microsoft Windows 11 Pro Version 23H2 (OS Build 22631.3593)

**Comment by developernotes** [comment]
Hi @lucydodo,

Thank you for the quick response. I have checked the nightly Windows build and it is working again properly. I will close this ticket. Thank you!
