### ISSUE TITLE
[Feature]: Support duckdb

### ISSUE THREAD

**Issue by thanasisn** [sqlitebrowser/sqlitebrowser#3699]
### Describe the new feature

Add support for duckdb files.

### Does this feature exist in another product or project? Please provide a link

There is no GUI browser for duckdb as far as I know.

**Comment by FriedrichFroebel** [comment]
This has already been requested in the past, but we decided that supporting DuckDB wouldn't be trivial due to being tied to SQLite rather much: #2793.

**Comment by justinclift** [comment]
Poking through the DuckDB website, it mentions they have a foundation for accepting donations and funding development of DuckDB.

Depending on how well funded that Foundation is, they could likely hire some people to adapt the code base of our project or a different OSS project, so that it works with DuckDB.

That'd then be it's own thing, but at least then they'd have an official GUI. :smile:
