### ISSUE TITLE
Increase "Table" dropdown height in the "Browse Data" tab

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#375]
Even with two tables, the dropdown is unnecessary small, it should __not__ have arrows for such small dropdown.

![screen shot 2015-07-01 at 14 39 16](https://cloud.githubusercontent.com/assets/5748627/8453621/00002c1e-1fff-11e5-9bfa-34d78d7860d1.png)

**Comment by justinclift** [comment]
Which OS are you using, and which version of DB4S? :smile:

**Comment by revolter** [comment]
`OS X Yosemite 10.10.3` and `DB4S Version 3.7.0`

**Comment by MKleusberg** [comment]
@justinclift I don't think we have any real influence on this since it is a Qt thing. But I've just seen that we're still using Qt 4.8.7 for the Mac OS build. So I'm wondering if it's much work for you to change the build process to use Qt5 which brings a load of new features and bug fixes. This issue might be fixed this way. Maybe the open file dialog file name selector thing as well.

**Comment by justinclift** [comment]
@MKleusberg Good idea.  I don't have access to the OSX build box for about another 6 weeks or so (needs to be packed up and posted to me), but I can definitely look into this once I get it. :smile:

**Comment by revolter** [comment]
Somehow it's solved, the list is now much bigger and just some tables there's no need for scroll. I'll close this issue and reopen it if the bug reappears.

**Comment by justinclift** [comment]
Cool, sounds like a plan. :smile:
