### ISSUE TITLE
[Feature]: Filter using multiple values

### ISSUE THREAD

**Issue by riazahmedsg** [sqlitebrowser/sqlitebrowser#3751]
### Describe the new feature

I want to be able to filter using multiple values in the input field of a column

### Does this feature exist in another product or project? Please provide a link

This feature is available with many, many apps.
At the moment, I am not able filter a column using multiple values in its input field for a column

### Do you have a screenshot? Please add screenshots to help explain your idea.

<img width="560" alt="image" src="https://github.com/user-attachments/assets/0f9db824-560b-4a71-ac27-1de3c2574294">

<img width="583" alt="image" src="https://github.com/user-attachments/assets/c23d7938-65b5-45ab-9f38-730b5c8736ef">

**Comment by midoragh** [comment]
You may use regex /.../ to create a more complex filter.

**Comment by mgrojo** [comment]
Yes, as @midoragh  the solution is to use [regular expressions in the filter](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Using-the-Filters#regular-expression-filter). In that case, your example is simply:
```
/value1|value2|value3/
```

We cannot use a so simple syntax for the filter, that is, just using commas, because that would break a common case, which is filtering exactly that string value, with the commas.

Given that, I'll close this issue, but feel free to comment further.

**Comment by riazahmedsg** [comment]
Hi,

Thank you for the clarification.
My key concern remaining is the use of ERD for table design and sql queries.

Regards, Riaz
