### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 971fukker** [sqlitebrowser/sqlitebrowser#3752]
### What did you do?

Hi, after download and installing the DB Browser 13.0 for mac, - open a database - save in my computer and- create table - add camps bla bla... and go to save but a message tell me : 

85 / 5.000
Error creating table. Database message:
There is no database open
somebody can help me?

thanks

### What did you expect to see?

a table

### What did you see instead?

Error creando la tabla. Mensaje de la base de datos:
No hay una base de datos abierta

### DB4S Version

3.13.0

### What OS are you seeing the problem on?

MacOS

### OS version

mac intel ventura and monterey, booth fail

### Relevant log output

```shell
Error creating table. Database message:
There is no database open
```

### Prevention against duplicate issues

- [X] I have searched for similar issues

**Comment by justinclift** [comment]
Hmmm, well that's a new one.  Haven't seen this particular error behaviour before. :grin:

As a diagnostic step, would you be ok to try our latest dev build?

https://github.com/sqlitebrowser/sqlitebrowser/releases/tag/continuous

There's a few bug fixes in that which have been made since the 3.13.0 release.  So just on the off chance that it was one of those bugs then it's worth giving the dev build a go before we investigate other potential stuff. :smile:

**Comment by 971fukker** [comment]
Hi, 

thanks for reply. I got it. I was put on wrong place the database. (Apple put the database placement in the close mac place, in usuarios, and it’s forbiden for mac)



sorry

thanks

**Comment by justinclift** [comment]
No worries at all, glad you got it figured out. :smile:

**Comment by 971fukker** [comment]
Thanks, one think more please:

When I'm working with tables, there's no problem, but if I then change, for example, Id_orders to Id_Orders, the program closes instantly, it's done this twice now…

thanks 

miguel
