### ISSUE TITLE
Autocomplete table name on import

### ISSUE THREAD

**Issue by revolter** [sqlitebrowser/sqlitebrowser#376]
It would be a great addition if the `Table name` field would be auto completed by default with the file's name without the extension.

So if I'm trying to import a table from the file named `my_first_table.sql`, the `Table name` field would contain `my_first_table`, obviously, with the possibility to change it.

**Comment by justinclift** [comment]
That makes sense. :smile:

**Comment by MKleusberg** [comment]
Just pushed a commit for this, so it should be in the next nightly build :smiley:

**Comment by justinclift** [comment]
@revolter Would you be ok to try our nightly build, and verify this is working for you now? :smile:

**Comment by revolter** [comment]
@justinclift, sure, but I don't know how

**Comment by justinclift** [comment]
Hmmm, that's a bit vague.  The download locations for our nightly builds are on the front page of our project (this repo).  In theory, for OSX the nightly builds here should work for you:

&nbsp; &nbsp; http://mirror.salasaga.org/sqlitebrowser/nightly/

Note - Someone mentioned not long ago they've stopped working for older OSX (10.6?) versions.  I haven't been able to investigate though (no access to that OSX build box)for probably another 6 weeks or so.  Still, since you're on new OSX, it's worth trying. :smile:

**Comment by revolter** [comment]
It's working great! Thanks.

**Comment by justinclift** [comment]
You're welcome. :smile:

**Comment by revolter** [comment]
@MKleusberg could this be done for export too?

**Comment by justinclift** [comment]
Um... would you be ok to create a new issue for that?  It's better for us tracking-wise. :grin:

**Comment by revolter** [comment]
Oh, sorry!

**Comment by justinclift** [comment]
No worries at all.  Thanks for getting making it happen. :smile:
