### ISSUE TITLE
Empty the recently used files list in the File Menu

### ISSUE THREAD

**Issue by finjulhich** [sqlitebrowser/sqlitebrowser#379]
or Remove files that don't exist anymore, or both.

It would be good to have this extra menu item in the File menu, a bit like Notepad++

**Comment by justinclift** [comment]
Makes sense, and is probably quick/easy to implement. :smile:

**Comment by MKleusberg** [comment]
I've just updated the code to check if a file still exists before adding it to the menu. There is no new menu option for it though, because I think it's not as important to most users to warrant the extra option. It's automatically executed whenever the menu is updated, i.e. upon start-up and when opening a file.

If you don't want to wait for the next release, you can download the nightly build and test the new feature :smile:

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by justinclift** [comment]
@finjulhich Ping...

**Comment by finjulhich** [comment]
hey, i will try later today, thanks

**Comment by justinclift** [comment]
@finjulhich Never heard back from you.  Any chance you can try the latest build (or even a nightly) and let us know if this is properly addressed for you?

**Comment by finjulhich** [comment]
sorry about the delay, confirmed working, thanks.

**Comment by justinclift** [comment]
Thanks @finjulhich. :smile:
