### ISSUE TITLE
[Feature]: Retain views

### ISSUE THREAD

**Issue by RodeyOrg** [sqlitebrowser/sqlitebrowser#3823]
### Describe the new feature

I would like, and see some value in for others, the ability to 'retain view's' settings when saving a project or even generally reopening a previoud db.

Sometimes filtering down a db to the layout you want takes considerable time and having that recalled with a project or db would be a real time-saver IMO.

**Comment by justinclift** [comment]
Hmmm, I would have thought we'd already save this information to our project files.

@RodeyOrg After opening a database file, have you tried the `File` -> `Save Project As...` option?

That should save a bunch of metadata (like opened SQL tabs, etc) to a "project file" for our application.  When you next start the application, if you open the project file instead of the database (`File` -> `Open Project`) then it should automatically open the database file, settings, tabs, etc.

In theory. 😁

**Comment by mgrojo** [comment]
This looks like #3790. @RodeyOrg please, see https://github.com/sqlitebrowser/sqlitebrowser/issues/3790#issuecomment-2557353572
