### ISSUE TITLE
the ability to enter an incorrect column name

### ISSUE THREAD

**Issue by PKEv** [sqlitebrowser/sqlitebrowser#400]
win7 

to repeat:
1. create table
2. correct table
2.1 add to the name of the column special character "`"
![default](https://cloud.githubusercontent.com/assets/6053197/9262130/3dff4e4e-421b-11e5-88c2-2d985f555a5e.png)

**Comment by GeorgijK** [comment]
I would say the bug is that UI is unable to display names with escaped special symbols. There is nothing bad in having special symbols escaped in the names of fields/tables.

**Comment by MKleusberg** [comment]
This should be fixed by the same patches used for dealing with issue #387 . This means I haven't disallowed the usage of backticks in column names but instead tried to fix the program when they are used. So in short, you're still allowed to use them but now the application will actually work fine even when they're used :smiley: At least I hope it does :smile: 
If you want to test this you can download tomorrow's nightly build and have a try.

**Comment by PKEv** [comment]
ok, all work

**Comment by justinclift** [comment]
@PKEv That's a bit unclear to me.  Do you mean you have tested the latest build, and it's all working now?  eg Is this issue fixed now, so we can close it? :smile:

**Comment by PKEv** [comment]
yes, bug fixed

**Comment by justinclift** [comment]
Thanks @PKEv. :smile:
