### ISSUE TITLE
maximum file size? We work with large single table .db. What is the largest file sqllitebrowser  can handle? On a NTSF drive running 64 bit windows

### ISSUE THREAD

**Issue by cczxcz** [sqlitebrowser/sqlitebrowser#406]
Thank you for any assistance that you can provide! Glenn

**Comment by justinclift** [comment]
Assuming you have a bunch of ram in your system, we've had reports of people using recently DB4S (the new name of SQLite Browser) on files of several GB's.

How big are the database file's you're thinking of using?

**Comment by justinclift** [comment]
Guessing you've seen this already, but putting it here just in case it's helpful:

&nbsp; &nbsp; https://sqlite.org/limits.html

**Comment by MKleusberg** [comment]
In theory sqlitebrowser can open and handle all files you can open using the SQLite command line tool or any other application using the sqlite3 library (see Justin's link above for that). There are two things to consider, though:
* For browsing a table we have to issue two SQL statements instead of just one. This is because there doesn't seem to be a better way to tell the total amount of rows in a table, an information we need for the UI. Effectively this means these two statements are executed each time you open up the table browser, use the filters, change the sort order, etc. In the worst case this increases the loading time by quite a bit of time, though this should get better if your table has a primary key/unique index.
```sql
SELECT COUNT(*) FROM table;
SELECT * FROM table;
```

* The other thing is that while we do support loading the rows in chunks (you can set the size in the Preferences dialog), we don't unload them. This means that by simply scrolling down the table view more and more data is loaded into memory. But because no data is paged out again you could run out of memory (there's a slight overhead for the UI stuff, so it takes a little more memory than needed for the actual database content only). Changing the filters on a table purges this cache though, so working on a subset of the data should be a lot faster and more memory efficient.

But in the end, you'll probably have to simply try opening the files. It might take some seconds for something to happen but it'll still be faster than planning this out theoretically :smile: If you do, I'd be interested to hear your experiences.

**Comment by justinclift** [comment]
@gbhiner1 Does that help enough? :smile:

**Comment by justinclift** [comment]
Closing this, as it's not something we can do more with. :smile:
