### ISSUE TITLE
Show ROWID as a column

### ISSUE THREAD

**Issue by chinhodado** [sqlitebrowser/sqlitebrowser#408]
Is it possible to show the ROWID of a record as a column? Currently each table has an unnamed column (the leftmost one) that looks like ROWID but it is not.

**Comment by justinclift** [comment]
Interesting question.  @MKleusberg, can it be done? :smile:

**Comment by MKleusberg** [comment]
I think I need your help here...

It can be done and I've prepared a patch for this more than a week ago but it's still causing some trouble. I'm not sure what's going on there but I've just pushed it anyway. With the next nightly build there will bee an option for showing the rowid column if you right-click on the table header in the Browse Data tab. There you can click the new option to show the column.

That's the theory anyhow. On my system it simply doesn't work. There are two places where I have to decide whether to show the rowid column or hide it: when this new option is clicked and when changing the current table because in the latter case the previously set settings for the new table shall be loaded. Now, I've found a workaround to make it work when I click the new option but with this workaround enabled the latter case doesn't work. With the workaround disabled _only_ the latter case works (though you have to change the table twice before coming back to make this even weirder). This is especially troubling because it's the same code being executed, it's only called from different locations.

So this is where I need your help: I'm building this using Qt 5.4.2 (you can check this in the Help -> About menu). Assuming the Windows nightly build uses a different version I'd be interested to know how both described use-cases work for Windows users. The MacOS X nightlies still use Qt 4 as far as I know, so this would definitely be interesting to know. Maybe you can test this, @justinclift ? Currently the workaround is disabled by the way. If it works on e.g. MacOS with Qt4 I'll assume a Qt bug...

**Comment by justinclift** [comment]
We're still waiting on @quaid for the Mac Mini build server, so we haven't had nightlies for quite some time now. :frowning:

But, I can do a compile test on my OSX desktop later on today. :smile:

**Comment by glawrence** [comment]
@justinclift I think you have Mac nightly builds working now, so thought a polite nudge might be in order

**Comment by chetan** [comment]
@MKleusberg I just tested on OS X 10.11.2 and it worked the first time I tried it but now it's not displaying the column. 

- I enabled it for one table and it displayed the rowid
- Switched to a second table and enabled it, but no rowid was shown
- Switched back to table one and toggled it off/on, and rowid did not return
- restarted sqlitebrowser and now unable to display rowid at all

Not sure what is going on. Would it be possible to just move 'show rowid' to the preferences pane and apply it across all tables? That would make the most sense to me..

**Comment by justinclift** [comment]
@chetan Ouch, that doesn't sound good.  As a thought, you **might** be able to reset it's behaviour my moving or deleting the preferences file for DB4S.  On OSX it should be located somewhere like:

    ~/Library/Preferences/com.sqlitebrowser.sqlitebrowser.plist

No guarantees, but it's worth a shot.  (back that up before deleting it, just in case :grin:)

**Comment by MKleusberg** [comment]
I think the behaviour described by @chetan here is the same problem I was mentioning earlier. I finally got around to debug this properly and I've found my mistake. With the latest patch it's finally working now. So @chetan and @chinhodado can try the next nightly build to see if the new feature is properly working for them now. Let me know if there's still some problem left; and if it's working, too :wink:

**Comment by chinhodado** [comment]
The feature is working great for me, thanks!

**Comment by MKleusberg** [comment]
Cool, thanks for letting us know. I'm glad I could help. :smile:

**Comment by wetbadger** [comment]
How do you enable this feature?

**Comment by chrisjlocke** [comment]
![image](https://user-images.githubusercontent.com/7872218/187549582-e6141d70-10fd-49e1-866c-eced26a3cdf4.png)

In the 'Browse data' tab, right-click the column header (1) and select 'Show rowId column' (2)

![image](https://user-images.githubusercontent.com/7872218/187549726-a57bb0cd-ff99-4c63-b280-17f1133c6b90.png)

Another column will magically appear.
