### ISSUE TITLE
Version 3.7.0: always attempting render BLOB contents makes scrolling very slow

### ISSUE THREAD

**Issue by habbler** [sqlitebrowser/sqlitebrowser#410]
I have to make sure that the blob column is not displayed to make the scrolling speed acceptable.
There needs to be an option to not attempt to render the contents and just display "BLOB" as was previously the case.

**Comment by justinclift** [comment]
Not a bad idea. :smile:

**Comment by MvGulik** [comment]
Is there a change for a, relative soon, nightly version with a workable BLOB display fix.
With (displayed?) blobs the current 3.7.0 SqliteBrowser becomes so unresponsive its just unworkable.

Tried it with nightly 3.7.99. (added the nightly exe (renamed) to the current installed 3.7.0 version, just in case that's not the way to do it.)

OS: Windows, 32bit, XP
(funny, every time I specify XP I now feel I'm saying something political unacceptable.)

**Comment by justinclift** [comment]
Sorry for the extreme delay with this guys. 😦 

This slowness in displaying blobs was only fixed recently (a few weeks ago).  The fix is in our recent "3.9.0 beta1" release (last weekend), and will be in the "3.9.0" proper release, which should be this weekend.

@MvGulik, the nightly build you grabbed um... yesterday has the fix in it too.  Just to double check, if that showing BLOB's decent quick now for you?

**Comment by justinclift** [comment]
Closing this, as it's definitely fixed for everything except large size images.

Large images will likely be addressed in the next release anyway. :smile:
