### ISSUE TITLE
Project file extension not default on save.

### ISSUE THREAD

**Issue by cknystrom** [sqlitebrowser/sqlitebrowser#437]
Tried a project save and then re-open it but doesn't show on the file list because the file extension identified as a SQLite Browser Project is not on the file.  No clue as to what is expected.

**Comment by justinclift** [comment]
Which extension did it save with?

**Comment by MKleusberg** [comment]
@justinclift None, as far as I understood :frowning: 

@cknystrom Which version are you using? Because the file extension ('.sqbpro') should be added automatically since version 3.4.0 which is from October 2014. Here's the commit where (hopefully) I've fixed your problem: 5d20d97e249a42d7dae1061d946c90c9c987d608
If you're using a version >= 3.4.0 we'll have to investigate further I'm afraid.

**Comment by justinclift** [comment]
Closing this due to lack of response.

@cknystrom We've released a new version (3.8.0) just over a week ago.  That shouldn't have this problem.  If for some reason it does, you're welcome to reopen this issue so we can investigate. :smile:
