### ISSUE TITLE
"Write changes" button not working anymore with nightly build

### ISSUE THREAD

**Issue by zwrmueller** [sqlitebrowser/sqlitebrowser#447]
Topic says it all.

Regards
 Ralf

**Comment by justinclift** [comment]
Thanks Ralf, which OS are you on?

**Comment by zwrmueller** [comment]
Hi Justin,

I'm on Windows 7. With the last stable this button was fine. 

I used this button most while attaching databases - and this only could be done by SQlitebrowser one by one - with saving the first attached database before being able to attach the next.

Regards
 Ralf

**Comment by justinclift** [comment]
:frowning: Ugh, I do the OSX builds for this, not the Windows ones.  It's not something I have much capability to investigate properly personally.

@rp- Do you have time to look into this?

**Comment by zwrmueller** [comment]
sorry Justin - betatester, no progger :(

**Comment by justinclift** [comment]
Yeah, I just build OSX binaries and help out here. :smile:

**Comment by MKleusberg** [comment]
Hi Ralf,
I think the last commit fixes your issue. The problem was that the database actually *was* saved but the state inside the application wasn't changed to reflect the saving. Anyway, let us know if tomorrow's nightly build fixes the issue for you :)

**Comment by justinclift** [comment]
@zwrmueller Do you have a few minutes to try out the latest code, to see if this is fixed now for you? :smile:

**Comment by zwrmueller** [comment]
Hello Justin,

sorry for letting you waiting. Seems fine to me :-)

The only thing I wonder about is: the nightly build exe file is roughly tenfold bigger than the one from the original release (32MB to 2,2MB).

Regards
 Ralf

**Comment by tonypdmtr** [comment]
Yes, but it has no dependencies on other files (DLL, etc.)
I wish the actual release did the same.  I like the stand-alone binary version better (like with SQLite3 or FOSSIL)

**Comment by justinclift** [comment]
@zwrmueller Thanks for verifying this, and letting us know. :smile:

@zwrmueller @tonypdmtr The nightly builds are created through cross-compilation from a Linux host, using Windows as the target.  It produces a "static build", where all of the libraries needed by the program get compiled into the end result.  So... much bigger output file.  It's also 32-bit only, so anyone needing to open really large database files (several GB's) can't use it.

Our older releases used to use this same approach too, but we changed it a few releases ago to a dynamic build approach.  This lets us create 64-bit releases for Windows (so people with large databases can use them).

... and it turns out the static 32-bit build approach is useful for some people still.  It might be useful if we figure out a way to create the releases for Windows using both approaches.

**Comment by tonypdmtr** [comment]
+1 for releasing both ways.

**Comment by zwrmueller** [comment]
Thanx for shedding some light on this Topic, Justin. 

Personally I use the portable version, that's my main concern. I put the nightly build into the 64-folder, as with the original release I use the 64-version. With the Information now, that the nightlys are 32bitters, that is the wrong Folder. But it does not matter anyway, because the static nature of the build. Right?

Regards
 Ralf

**Comment by justinclift** [comment]
Hmmmm, good question.  I'm not running it on Windows personally, so I'm not real sure.

I guess... if it's still working, then it can't be too wrong. :grin:
