### ISSUE TITLE
how to connect a in-memory-shared sqlite3 database?

### ISSUE THREAD

**Issue by AnotherGoogleFans** [sqlitebrowser/sqlitebrowser#455]
I create a database in memory and shared it.
But I don't know how to connect it with this tool.

**Comment by MKleusberg** [comment]
I'm not entirely sure on this but to be honest I think that's not possible nor is it possible for us to implement this feature. The reason is that each process has its own virtual memory which is invisible from within other processes. So if you have an in-memory database opened in one thread (which I assume you do when you say you created an in-memory shared-cache database) we can't inspect it from the separate sqlitebrowser process. There are way of interprocess communication, of course, but it doesn't seem like SQLite implements any of them:

https://www.sqlite.org/inmemorydb.html says:
```
Of course, all database connections sharing the in-memory database need to be in the same process.
```

And https://www.sqlite.org/sharedcache.html says:
```
Enabling shared-cache for an in-memory database allows two or more database connections in the same process to have access to the same in-memory database.
```

So it definitely sounds like you have to be in the same process but unfortunately we have no chance to do that :frowning:

**Comment by AnotherGoogleFans** [comment]
Oh, I see. Thank u.
