### ISSUE TITLE
Installer does not recognize zh_TW

### ISSUE THREAD

**Issue by progheal** [sqlitebrowser/sqlitebrowser#466]
I'm running installer in Traditional Chinese (zh_TW) environment, but the installer message is in zh_CN (both encoding and the message itself), which shown as mojibake. (See attached image.)
The problem both appears in 3.7 and 3.8. It only affects installer; the main program correctly detected zh_TW.

OS: Win 7 Enterprise with SP1, 64-bit, Traditional Chinese Version

![mojibake](https://cloud.githubusercontent.com/assets/4156121/12028493/eada9ae8-ae12-11e5-92f7-d6ed303584e8.png)

**Comment by justinclift** [comment]
Thanks for the bug repot @progheal. :smile:

Are you able to provide the correct installer message(s)?  If so, our packager for Windows (@rp-) might be able to get them incorporated into the next release.

Personally, I'm not multi-lingual so that's just my guess for the correct approach to fixing this.  If you have suggestions for a better idea, we're happy to hear them. :smile:

**Comment by progheal** [comment]
I've never working on installers, so I don't know how or what to setup; since this mojibake message is the ordinary zh_CN default message, I think using default message for zh_TW should suffice.

**Comment by rp-** [comment]
well this is a bit out of my scope, as I just use the NSIS installer software and it might be a bug there.
I'll try to update it for the next release.

**Comment by justinclift** [comment]
Wonder if there's an NSIS developer mailing list or something we could ask on?

**Comment by MKleusberg** [comment]
Let's close this issue. To be honest, I don't know whether this is fixed in the current releases but we have changed the installer from NSIS to MSI in the meantime which probably did fix it :smile:
