### ISSUE TITLE
Version 3.8.0 claims DB is invalid

### ISSUE THREAD

**Issue by mdahouse** [sqlitebrowser/sqlitebrowser#524]
I have upgraded from 3.4.0 (win32) to 3.8.0(win64v2) and now DB Browser for SQLite is saying the database I have is invalid.
I have dropped down to 3.7.0(win64) and that opens the database fine.

**Comment by justinclift** [comment]
Hmmm, the only time I've heard of this happening before, was due to the database being damaged.  In the previous instance, the earlier version of DB4S used an older SQLite which doesn't have as good database checking as newer versions.

I wonder if it is the same problem here.

Are you able to open the database with the command line version of SQLite? :smile:

**Comment by mdahouse** [comment]
Hi, sorry for the delay.
I have been able to open the DB on Fedora 21 using a different version of SQLite 3.8.11.1
sqlite> .version
SQLite 3.8.11.1 2015-07-29 20:00:57 cf538e2783e468bbc25e7cb2a9ee64d3e0e80b2f
sqlite>

**Comment by justinclift** [comment]
Interesting.  Are you able to try with SQLite 3.9.2 somehow?

**Comment by MKleusberg** [comment]
Closing this due to lack of response. If you're still having similar problems even with newer versions of DB4S, please re-open this issue any time you like :smile:
