### ISSUE TITLE
Feature Request: Edit Constraints

### ISSUE THREAD

**Issue by tyteen4a03** [sqlitebrowser/sqlitebrowser#538]
I want to add a custom UNIQUE constraint but I don't see how with the current app.

**Comment by MKleusberg** [comment]
Not sure if you're still interested, @tyteen4a03, but we're finally making progress regarding this. It's now possible to add and modify a custom unique constraint in the Edit Table dialog. If you still need this, you can grab tomorrow's nightly build [here](https://nightlies.sqlitebrowser.org/latest/). But since this issue is more than three years old now, you can just let us know if you have moved on to other things. We can just close the issue then :smile:

**Comment by MKleusberg** [comment]
Closing this issue because it's rather old and I'm quite confident that we have implemented the requested feature by now. If you have any issues with the new feature, you're definitely welcome to re-open this issue or open a new one :smile:
