### ISSUE TITLE
Defer "New Record" Insert Statement

### ISSUE THREAD

**Issue by Jeff-G** [sqlitebrowser/sqlitebrowser#553]
When on the "Browse Data" tab, clicking "New Record" immediately inserts a new row containing default values into the database.  This causes the validation logic to run against those defaults, even though it is reasonable for a client to want to edit the values prior to inserting them.  It would be preferable to create a new UI element upon pressing the "New Record" button, but defer the insert statement until:

1) the row is deselected by the client, or
2) enter is pressed when not editing a cell value, or
3) the client attempts to change the table being browsed

Upon any of these user-initiated actions, if validation fails, show a dialog explaining the error and re-select the offending row.  To continue, the user must either click "Delete Record" or fix the offending data.  This enhancement is hinted at from #294, #463, and #514.

**Comment by justinclift** [comment]
Makes sense.  Don't suppose you're any good with C++ and want to try whipping up a fix? 😀

**Comment by innermous** [comment]
I double this and #463 , very irritating bug.
This would be so much easier if QSqlTableModel was used :cry: QEditStrategy::onRowChange could be a cure but...

**Comment by justinclift** [comment]
Yeah, I think the reason it's not, is that DB4S predates using Qt's build in SQL stuff.  Personally, I'm only just learning C++ and Qt now, so am not really sure (yet).  Will know more as I gain some experience with them. :wink:

**Comment by MKleusberg** [comment]
Closing this as it has been solved with the Add Record dialog. If there are still problems like this, feel free to just open new issues :smile: 

As for using ```QSqlTableModel```: If somebody has put some thought into this, please open a new issue too :smile: I'm not sure if it helps much in our case because we have customised our model class so much that I'm not sure we would in effect reimplement it inside ```QSqlTableModel``` anyway. But I'm looking forward to any opinions on this :smile:
