### ISSUE TITLE
Support JPEG BLOBs

### ISSUE THREAD

**Issue by TWiStErRob** [sqlitebrowser/sqlitebrowser#579]
What is required to support JPEG in BLOB typed columns?

I see there's PNG and BMP, both huge files especially if you store stuff in DB (=you have many rows), what's the reason for no JPEG yet?

The JPEG encoder/decoder at http://www.ijg.org/ works nicely, I just integrated it myself in Java JNI few weeks ago.

**Comment by justinclift** [comment]
@MKleusberg Thoughts?

**Comment by MKleusberg** [comment]
We're supporting whatever image formats are supported by Qt. Qt does support JPEG and on my (Linux) system DB4S therefore supports JPEG, too. However, the Qt developers have moved most images formats out of their library and into plugins. So for our Windows release, we'd need to distribute these plugins, too (or at least the JPEG one, that is). I hope this makes sense :grinning: So in effect, this is a distribution issue, not a code issue. Could be that the JPEG plugin is linked into the nightly builds, too; so that might be worth giving a try as well.

**Comment by justinclift** [comment]
Ahhh, that's interesting.

@TWiStErRob Which OS are you using? :smile:

**Comment by TWiStErRob** [comment]
Windows 7 SP1 x64, and I can confirm that the nightly build shows the JPEG BLOB and the latest release doesn't.

Nightly: 3.8.99 QT 4.8.7 SQLite 3.12.0
Latest: 3.8.0 QT 5.5.1 SQLite 3.9.2

**Comment by MKleusberg** [comment]
@justinclift This might also be interesting for your instructions for compiling on Windows. It'd be nice to have an extra directory called 'imageformats' inside the app dir. In this directory you have to copy some or all of the DLLs in ...\Qt Directory\Qt Version\plugins\imageformats.

**Comment by TWiStErRob** [comment]
Looking at the extensions list in the import dialog:
3.8.0:
![image](https://cloud.githubusercontent.com/assets/2906988/14936777/52d67c0a-0ef5-11e6-9d99-29855438aad5.png)
3.8.99:
![image](https://cloud.githubusercontent.com/assets/2906988/14936781/5b7ecb96-0ef5-11e6-9ff4-262620fa890f.png)

**Comment by justinclift** [comment]
@MKleusberg Doesn't sound like it'll be a problem.  I'll just need to understand better what needs to be added, and where. :smile:

Is this something extra we need to add/tick/enable for the Qt installation step (Qt install step in development here):

&nbsp; &nbsp; https://github.com/justinclift/sqlitebrowser/wiki/Win64-setup-—-Step-7-—-Install-Qt

Or is it more of something to do prior/post compiling of DB4S?

&nbsp; &nbsp; https://github.com/justinclift/sqlitebrowser/wiki/Win64-setup-—-Step-13-—-Compile-DB4S-using-MSVC

Note, I'm still going through those docs (right now, working on Step 8), replacing/fixing screenshots, tweaking wording, etc.  So, feel free to point out or ask things as needed.

@TWiStErRob As a thought, if you're interested in compiling DB4S on Windows, it'd be super useful having someone go through those instructions and test them out for Win 7.  I'm writing them up using Win 8.1, so I've been **assuming** they'll work on Win 7 the same.  But it would be good to have someone actually check, to make sure. :wink:

**Comment by justinclift** [comment]
@MKleusberg Hmmm, reading over your comment again... it's more something we need to add to the packaging step isn't it?  If so, we can probably add it into the NSIS package script, so it works "out of the box" for everyone.

**Comment by TWiStErRob** [comment]
Holy-moly I thought [this](https://github.com/justinclift/sqlitebrowser/wiki/Notes-for-compiling-on-Windows) was the full docs for that :) Sorry, but I don't have time right now, and I'm planning to update to Windows 10 soon, so you're probably better off setting up a VM.

**Comment by justinclift** [comment]
Sure, no worries at all. 😉 

(and yeah, it turns out to be a fairly involved process) 😧

**Comment by justinclift** [comment]
Hmmm, if the solution to fixing it is as easy as shown in the answer here, we can probably do this for 3.9.0:

&nbsp; &nbsp; https://stackoverflow.com/questions/6724606/include-the-jpeg-plugin-in-my-application

**Comment by justinclift** [comment]
This will have to be a 3.10.0 thing instead of for this release.  Didn't get time to investigate it properly for 3.9.0.

**Comment by justinclift** [comment]
Looking into this now.  Testing in a Win7 VM at the moment, it's pretty simple to get the plugins working manually:

* After installing DB4S, create an "imageformats" directory inside the DB4S directory
* Extract the "imageformats" .dll files from Qt 5.7.1, and copy them into the above imageformats directory
  * For 32-bit Windows, use https://download.qt.io/archive/qt/5.7/5.7.1/qt-opensource-windows-x86-msvc2013-5.7.1.exe
  * For 64-bit Windows, use https://download.qt.io/archive/qt/5.7/5.7.1/qt-opensource-windows-x86-msvc2013_64-5.7.1.exe

DB4S will automatically load those plugins when it starts, and the matching image types will be available for import/export (depending on the plugin capabilities).  Tried it using both the latest nightly, and the build from 20th October (just a random selection), older ones probably work too.

There are several image format plugins included with the above Qt download.  Several of them should be ok to include as-in in our installers, others we'll probably need to do a bit of work for:

#### Should be ok to include

* GIF - Graphics Interchange Format
* ICNS - Apple Icon Image
* ICO - Windows Icon file
* JPEG - Joint Photographic Experts Group
* SVG - Scalable Vector Graphics
* TGA - Truevision Graphics Adapter
* WBMP - Wireless Bitmap

#### Lets skip these for now

* DDS - Microsoft DirectDraw Surface.  Has known security issues, so not included with Qt 5.8 onwards.  Lets not include this.
* TIFF - Tagged Image File Format.  [Uses a different licence](http://doc.qt.io/qt-5/qtimageformats-attribution-libtiff.html), so lets skip it for now.
* WEBP - Google WebP.  [Uses a different licence](http://doc.qt.io/qt-5/qtimageformats-attribution-libwebp.html), so lets skip it for now.

With the TIFF and WEBP ones, they should be ok to include if we just copy their licences into appropriate spots.  But, that can probably come later instead of right away. :smile:

Further reference info, if that's helpful:

&nbsp; &nbsp; http://doc.qt.io/qt-5/qtimageformats-index.html

**Comment by justinclift** [comment]
In theory :smile:, this should be working for Windows now.  I've updated the nightly build script to include the right pieces, and rebuilt today's (Windows) nightly builds for anyone that wants to test right away:

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org/latest/

All of the nightly builds for Windows include this, so it's not urgent to get done before tomorrow (in case someone's wondering). :smile:

Next step, figure out the OSX equivalent...

**Comment by justinclift** [comment]
Just investigated this for OSX.  It turns out that on OSX we already bundle the required image format plugins, as we're using the Qt provided `macdeployqt` tool.  That automatically includes **all** of the image format plugins.

This is what's included with our 3.10.1 release:
![screen shot 2017-11-07 at 19 05 18](https://user-images.githubusercontent.com/406299/32512495-1175d37c-c3ef-11e7-98c4-415ae0ab4bb2.png)

Note that it's including the DDS, TIFF, and WEBP formats which we're skipping on Windows at the moment.

I guess the question is should we start including the TIFF and WEBP ones now (in Windows)?

**Comment by MKleusberg** [comment]
Hmm, maybe not include them and add them if somebody asks for them? But I guess nobody will really use them, especially inside databases.

Does JPEG work on OS X then? Or are they just bundled but not loaded?

**Comment by TWiStErRob** [comment]
> for anyone that wants to test right away

hint :wink:, hint :wink:; sorry I didn't have any computer time recently

> maybe not include them and add them if somebody asks for them? But I guess nobody will really use them, especially inside databases.

I would probably be using WebP if my [Android target allowed it](https://developer.android.com/guide/topics/media/media-formats.html#image-formats), but my minimum supported level is too low as of now. Note: Did you think anyone would use JPEG?

**Comment by MKleusberg** [comment]
Fair enough :wink: WEBP might be useful for somebody :smile: No idea about the licence thing though.

@justinclift Is it working on OS X? Or do we need to add some extra code, too?

**Comment by justinclift** [comment]
Haven't actually tested the WEBP extension, as I just assumed it would be working (as per JPEG, etc).

We don't need to write any extra code.  Instead, we just need to add text to the About dialog mentioning the two projects (TIFF, WEBP) and a link to them.  I think that'll satisfy their licence requirements.

For OSX I still need to update our build script to delete the DDS extension during the process.  We really don't want to ship things with security holes. :smile:

Hmmm... it might be better to update our OSX Qt build to use Qt 5.9.2 instead.  I don't think there's any strong reason for us to keep with 5.7 on that platform, unlike Windows where we need it for XP compatibility.

This is probably something I'll get done tonight. :smile:

**Comment by justinclift** [comment]
Just updated the OSX build box to Qt 5.9.2, and ran the nightly build script to make sure it works.  That fixes the DDS extensions security problem.

Next steps:

* Add the license info and links for TIFF & WebP to the About dialog
* Update the Windows build to include the TIFF and WebP plugins

**Comment by justinclift** [comment]
Tried adjusting the About dialog to include the TIFF and WebP license info, but it was just way too much text and didn't like the right approach.

Instead of that, we now have a new "[LICENSE-PLUGINS](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/LICENSE-PLUGINS)" text file in the top directory with the plugin license info in it and a brief description of what it's for.  That should satisfy their license requirements and also not be confusing for people. :smile:

**Comment by justinclift** [comment]
Ahhh, just realised that new license info text file will need to be bundled with the OSX and Windows installs too.  I'll look into that tomorrow.

**Comment by MKleusberg** [comment]
Cool, that sounds like progress :smiley:

Glad it's working on OS X. I was afraid we need to add some more code to point the plugin loader to the app dir or something.

**Comment by justinclift** [comment]
Just updated the CMake build file to include the TIFF and WebP formats on Windows.  Tomorrow I'll look into updating that to include the new plugin license file too.  Same will need to be done on OSX.  Shouldn't be too hard for either. :smile:

**Comment by justinclift** [comment]
The OSX builds now include both the LICENSE and LICENSE-PLUGINS text files in the .dmg (rebuilt todays nightlies, just to make 100% sure).

Windows ones next.  That'll be a CMake change... might put it off until tomorrow though. :smile:

**Comment by justinclift** [comment]
Just updated the CMake build file for Windows, so the LICENSE and LICENSE-PLUGINS files are now installed in the DB4S directory (under "licenses") along with the rest of our file set.  They're also removed when uninstalling too (checked, just to be sure).

In theory, I think that's everything that needs to be done for this issue.  If someone has time to check the nightly builds from tomorrow onwards on Win32/64 and verify JPEG is working + the license files are included in the install dir, that would be great. :smile:

@TWiStErRob @chrisjlocke @karim Would any of you have time to check that? :smile:

**Comment by justinclift** [comment]
Closing this as the image support is definitely now working in OSX and Windows, which is "good enough". :smile:
