### ISSUE TITLE
sqlite version in sqlitebrowser

### ISSUE THREAD

**Issue by jungle-boogie** [sqlitebrowser/sqlitebrowser#596]
Hello,

I downloaded windows nightly with date stamp of the 18th of May and noticed it's built with sqlite 3.12.0. The latest available version of sqlite3 is 3.13.0 but that was just released today. ;) The next most recent version is 3.12.2:
http://sqlite.org/changes.html

I believe 3.12.0 had such a serious issue Dr. Hipp removed it from being downloadable.

Can 3.12.2 or 3.13.0 be used in sqlitebrowser?

Thanks!

**Comment by justinclift** [comment]
Ahhh, I guess it means the Windows nightly build box isn't autoupdating its packages.

I'll ping @rp- by email and see if he's ok to fix that.

**Comment by justinclift** [comment]
@jungle-boogie Received an email from @rp- this morning saying the Windows nightly build box should now be auto-updating its packages.

Want to try the build tomorrow and verify things from your end? :smile:

**Comment by jungle-boogie** [comment]
Yes, I'll try this out with the 20th of May's build!

**Comment by jungle-boogie** [comment]
Much better! Now it's a version 3.13.0!

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by jungle-boogie** [comment]
Looks like 3.13.0 is still bundled with sqlitebrowser , but sqlite team has released 3.14.0, 3.14.1, 3.14.2 since then.

In a couple weeks (or less) 3.15.0 will be released.

sqlite releases happen quite often, as you can see here:
http://sqlite.org/chronology.html

13 releases for this year alone.

Prior to a release of sqlitebrowser, perhaps sqlite could be updated to the latest sqlite version. Then after that, follow sqlite's releases once a quarter? once a month? every releases?

I have no idea what would work best with the team, so happy to hear some input.

**Comment by revolter** [comment]
AFAIK, we don't use SQLite anymore, and instead, we package the Windows and the macOS apps with SQLCipher. So they need to merge the new releases into it. But I'm not sure this is correct, @justinclift knows the best about this.

**Comment by jungle-boogie** [comment]
What made the project switch away from sqlite itself and move to SQLCipher? Could that have been added as an extension?

**Comment by justinclift** [comment]
With SQLite vs SQLCipher, it's a "one or the other" thing when the build gets compiled.  It doesn't seem possible to have SQLite be compiled in, and also include SQLCipher on the side.

People generally don't seem to be demanding the newest things from SQLite anyway, so adding encryption as an option for everyone seems like a decent win.

The SQLCipher team will hopefully make a new release soon, and it'll probably be based on something much newer. :smile:

**Comment by revolter** [comment]
So I got it right 😄 And, yeah, I think there would be more upset people (including me) if we drop SQLCipher support than if we don't support latest SQLite feature. That doesn't mean that not having the latest features is a good thing, but as @justinclift said, we can't do both, so we only have to wait for SQLCipher to release new versions.

Does that make sense? If yes, is it ok to close this issue? 😄

**Comment by jungle-boogie** [comment]
Hi @justinclift, @revolter,

It's not always about new features when upgrading, right? Bugs are fixed and many optimizations are made. Just take a look at the changes page:
https://www.sqlite.org/changes.html

You'll notice that there are new "features" but it seems there's a number of optimizations (using that very generically) and bug fixes.

Being dependent on SQLCipher may mean it's a good pairing with sqlitebrowser, but it also means users will miss out on sqlite's improvements.

**Comment by justinclift** [comment]
Yeah.  On the balance of things, encryption by default seems like the right choice. :smile:

**Comment by chrisjlocke** [comment]
Would it be possible (as a feature...) to download sqlite.dll / sqlcipher.dll and plonk that next to the db4s.exe (not that its called that of course...) and it looks at that instead of its compiled version?  Of course, if the .dll is missing, it uses its compiled version.  This would mean the people who want the latest version of sqlite.dll to fix an issue can have that, otherwise they can have the sexy encrypted cipher version...

Guess its a bit like how WinAmp and the like work ... the mp3 DLL was shipped with the .exe, otherwise you could point it to a different version.

**Comment by justinclift** [comment]
Interesting idea.  If someone (eg not me) knows out to implement that in a practical way, then ok, it's possible.

Alternatively, we could provide a build for each:

* Win32 + latest SQLite
* Win32 + latest SQLCipher
* Win64 + latest SQLite
* Win64 + latest SQLCipher
* OSX + latest SQLite
* OSX + latest SQLCipher

So far I've been viewing that idea as "unnecessary complication", rather than something that would benefit people.

Any ideas if there's a better way to do it? (the "provide your own .dll" thing seems too hard at the moment)

**Comment by jungle-boogie** [comment]
Wow, that does seem to complicate the build process. Maybe the only change being to include Win32 + latest SQLite?

**Comment by justinclift** [comment]
The build process would be more icky yeah... I'm also thinking of the download page as well.  6 buttons instead of 3.

We definitely have novice users hitting the website, thus my strong desire to keep that particular side of things simple.

If you really want the newest SQLite included in builds, when I get around to making the new [automated Windows nightlies for Qt5](https://github.com/sqlitebrowser/sqlitebrowser/issues/775), I can make sure that it spits out both SQLite and SQLCipher versions.  The OSX nightlies do that already, so it'd just be copying that approach.

This will only suit the people who know where to look though.  Most likely [here](http://nightlies.sqlitebrowser.org/win64/).

Thoughts?

**Comment by jungle-boogie** [comment]
Right, I don't think there would be an easy way to really explain the differences between 
Win32 + latest SQLite and Win32 + latest SQLCipher to novice users on the download page.

I'm perfectly happy with your proposal and I'm thankful you've kept an open mind to the thoughts (not even going to say concerns) I've brought up.

**Comment by justinclift** [comment]
No worries.  Sounds like we have a solution then. :smile:

**Comment by justinclift** [comment]
@jungle-boogie Would you have the time/interest to try out the new Qt5 based Windows nightly builds?

There are builds with SQLite, and with SQLCipher, for both 32 and 64 bit windows:

* http://nightlies.sqlitebrowser.org/win32/
* http://nightlies.sqlitebrowser.org/win64/

In theory (!) they should be good, but it wouldn't hurt to have someone double check and make sure. :smile:

**Comment by jungle-boogie** [comment]
@justinclift,

Both installed and worked without an issue for my quick testing!

Can @chrisjlocke give them a shot, too?

Thanks for the efforts on building both!

**Comment by justinclift** [comment]
Excellent @jungle-boogie, thank you. :smile:
