### ISSUE TITLE
Browse Data tab shows no fields and no data

### ISSUE THREAD

**Issue by techkey** [sqlitebrowser/sqlitebrowser#60]
The `Browse Data` tab shows the correct number of rows but no fields. If I Execute the same SQL as the `Browse Data` tab does then the fields are visible and populated with data.

I've attached 3 screenshots, one from the `Database Structure` tab, one from the `Browse Data` tab and one from the `Execute SQL` tab.

![database_structure](https://cloud.githubusercontent.com/assets/670271/3634743/683b9216-0f46-11e4-8214-3906ca47c630.png)

![browse_data](https://cloud.githubusercontent.com/assets/670271/3634742/68395e24-0f46-11e4-93cc-760ee5e36e99.png)

![execute_sql](https://cloud.githubusercontent.com/assets/670271/3634741/68379c42-0f46-11e4-8dbc-86a3849e6aea.png)

The database works perfectly with PHP and NaviCat.

```
SQLite Database Browser Version 3.2.0
Windows XP SP3 x86
```

Any info on this will be much appreciated, thank you.

Cornelis.

**Comment by justinclift** [comment]
Interestingly, there is progress on the C++ port for ANTLR 4:

* https://github.com/DanMcLaughlin/antlr4cpp
* https://groups.google.com/forum/#!topic/antlr-discussion/rjVEUxMJBcI

Doesn't sound usable yet, but it's slowing happening.

**Comment by MKleusberg** [comment]
We have finally solved this issue :wink: Starting with tomorrow's nightly build (if they build that is), our parser now finally works with this database. I don't expect you're still really waiting for this, @techkey, which is why I'm closing this issue proactively. But if you are still interested in this, feel free to give the nightly a try ([download link](https://nightlies.sqlitebrowser.org/latest/), build will be ready tomorrow). And if there are any issues with it, please just reopen this issue :smile:
