### ISSUE TITLE
How can I open two database at the same time?

### ISSUE THREAD

**Issue by evherran** [sqlitebrowser/sqlitebrowser#617]
Hello
I am learning SQL, now I am practising with queries that combine data from multiple tables that are related to one another. How I can do it on DB Browser? I

Thank you so much

**Comment by chrisjlocke** [comment]
Clicking 'File' and 'Attach' should attach another database into the mix.  Might just be the databases I was using, but it didn't do much for me...
You can't use it (the attach keyword) in the SQL window, as that uses transactions and you can't use ATTACH in a transaction.

**Comment by evherran** [comment]
Hi Chris
Thank you so much for your quick reply, but i have tried it before and it doesn´t work; I attach the another database but when I do a query the browser doesn´t find that new database.

**Comment by chrisjlocke** [comment]
No, I must admit, I tried it when I saw your query (never used it before in anger) and couldn't get it to work either, and just assumed it was because there was either a schema clash or the planets weren't aligned quite right... (I was using it on Win 10 ... unsure if that matters....)
I was also using the latest nightly, in case that helps... (thats the usual first reply ... ensure you're using the latest version!)

I assume you're getting the 'enter a name for the attached database' dialog window?

Looking at the SQL log, something is attempted...
ATTACH 'D:/Downloads/Applications/SQLite Database Browser/sqlitebrowser.exe- 7 Jun 2016/1.db' AS `test`
SELECT type,name,sql,tbl_name FROM sqlite_master UNION SELECT type,name,sql,tbl_name FROM sqlite_temp_master;
SELECT COUNT(*) FROM (SELECT `_rowid_`,* FROM `test2` ORDER BY `_rowid_` ASC);
SELECT `_rowid_`,* FROM `test2` ORDER BY `_rowid_` ASC LIMIT 0, 50000;

but not much happens... no errors....

**Comment by evherran** [comment]
Yes finally i have had to create a new table inside the other. It was a simple exercise to query multiple tables that have relationships with each other.
Thank for your time and help

**Comment by chrisjlocke** [comment]
What were your steps to do that?

**Comment by evherran** [comment]
I wrote CREATE TABLE artists(id INTEGER PRIMARY KEY, name TEXT); and then I inserted a few registres, for example: INSERT INTO artist (id, name) VALUES (1, Iron Maiden); and it had worked for the exercise which i had to do. Were very simply queries such as SELECT * FROM albums LEFT JOIN artists ON albums.artist_id = artists.id;

**Comment by justinclift** [comment]
Ahhh yeah, that sounds like you are on the correct path.

Using multiple databases is a different thing, a bit more advanced.

Though to be fair, we need to fix the program so that works properly too. :wink:

**Comment by MKleusberg** [comment]
Any update on this? Basically there are two ways to work with multiple databases:
1) Open a second instance of DB4S and open the other database in there.
2) Attach another database (as mentioned above) to the main connection.

The problem with approach 2 is that (at least for now) the attached databases don't show up in the UI. But that's a different issue, I think :smiley:

**Comment by MKleusberg** [comment]
Quick update here: the second approach (attaching other databases) is now improved in the latest nightly builds. The attached databases now show up in the UI and can be edited like the normal database. Are you still interested in this, @evherran? If so, feel free to give it a try. If not, that's no problem either :smile: We can just close the issue then.

**Comment by justinclift** [comment]
@evherran ping?

**Comment by justinclift** [comment]
Closing this due to lack of response.

**Comment by thachnb85** [comment]
https://sqlitestudio.pl/index.rvt?act=download
SQlite Studio allows you to open multiple DBs in multiple windows.
