### ISSUE TITLE
Crash in Browse Data Tab when copying blank values

### ISSUE THREAD

**Issue by AO-StreetArt** [sqlitebrowser/sqlitebrowser#626]
I have seen repeated crashes when the following actions are taken, and this is reproducible with the most recent nightly build.

1. With a DB open, go to the 'Browse Data' tab
2. Select a blank record (note: when I say blank I mean "", not (NULL).  As in an empty string).  These can easily be generated by a CSV import without all fields populated for every row
3. Ctrl+C to copy the cell value
4. Select a cell with a non-null value in it, Ctrl+V to paste
5. The application crashes

I am using Windows 7 Enterprise

**Comment by justinclift** [comment]
Ahhh yeah, that definitely sounds like the kind of thing that could happen.

Thanks for reporting it @AO-StreetArt. :smile:

**Comment by innermous** [comment]
All clipboard code is broken.
Try to copy several rows and insert them somewhere - enjoy your crashes.

**Comment by innermous** [comment]
In  addition, I wanna say, when copying *NULL* field and inserting it in another cell just inserts **NULL** as text.

**Comment by innermous** [comment]
Fixed with [this commit](https://github.com/sqlitebrowser/sqlitebrowser/commit/1ce62d74a47461a45c445d90ba4894575952c257)

**Comment by justinclift** [comment]
@innermous Awesome! 😁 

I've just reopened this because before we close stuff, we always ask the person who created the bug report to confirm it first.  That's because even though **most** of the time things are ok, sometimes fixes turn out to be not-quite-as-complete as we were expecting.  Or the bug reporter finds an unexpected side effect. :wink: So asking the bug reporter to verify things first leads to a better result.

@AO-StreetArt Would you be ok to try the latest nightly build (download locations are on the front page of our project) and let us know if it's working properly for you now? :smile:

**Comment by justinclift** [comment]
@AO-StreetArt Ping?

**Comment by AO-StreetArt** [comment]
Sorry for the delayed response, absolutely ill test it at work tomorrow when I use the browser :)

**Comment by AO-StreetArt** [comment]
I have re-tested the issue with the latest nightly build and the crash is no longer observed.  

I tested copying a blank value into a populated cell, copying a blank value into a blank cell, copying a blank value into a null cell, and copying blank values into cells with different data types.  All tests passed.

Note: It is interesting that the Browse Data tab doesn't perform validations on entries into the cells based on data type.  Was this intentional?

Closing this ticket, thank you for the quick response!

**Comment by justinclift** [comment]
Awesome, thanks heaps for testing it and getting back to us @AO-StreetArt. :smile:

**Comment by justinclift** [comment]
@AO-StreetArt Just noticed your question about no validation of entries based on data type.

Just in case you're still curious about it, yeah, this is intentional. :wink:

SQLite itself considers the flexibility of datatypes to be a feature, and we'd be opening a weird can of worms if we didn't follow with the official position with it. :smile:

&nbsp; &nbsp; https://www.sqlite.org/datatype3.html

Hope that helps. :smile:

**Comment by AO-StreetArt** [comment]
Very good explanation! 
--
Sent from Mail.Ru app for Android Wednesday, 13 July 2016, 11:21AM -04:00 from Justin Clift  notifications@github.com :
