### ISSUE TITLE
Cut the Gordian knot

### ISSUE THREAD

**Issue by vtronko** [sqlitebrowser/sqlitebrowser#628]
Do we really need to write after each edit/insertion/removal? Why can't just user write changes whenever he wants or when database is closed?
App is tied to sql back-end too much, every action yields sql query triggered. Write for every action is redundant and application really suffers from it. Constraint bugs are hard to deal with update-per-action approach. In fact, if you look at other db managers - none of them writes every single change.
Currently, when we are adding new record - it's instantly written without letting user to input some data. It's so unnatural!
It's just my opinion, but maybe you can suggest something better.

**Comment by justinclift** [comment]
What's the better way to do this, do you reckon?

Should we have most stuff be kept "in memory" (without running the SQL) until the person hits the "Write Changes" button?

If that's the case, any idea where we should start?

**Comment by innermous** [comment]
It's just my opinion, but keeping it in model and run SQL only on purpose sounds less error-prone.
@MKleusberg what do you think about it?

**Comment by chrisjlocke** [comment]
I mentioned something similar in #599 - whenever a field is moved/edited, a whole bunch of SQL is executed.  I can't understand why this isn't 'written' when the user clicks OK, which must happen when a table is created, rather than edited.

**Comment by justinclift** [comment]
Yeah.  The current code base is the way it is due to a long legacy.

But, if someone wants to make things better, we'll definitely merge/patch/etc things so everyone benefits.

Definitely no incentive to keep doing things the old/bad way "just because". 😬

**Comment by MKleusberg** [comment]
I'd vote for sort of a middle way here.
The issue mentioned by @chrisjlocke should definitely be addressed. I don't think either that it makes any sense to do that whole operation each time a field is moved. The only reason why we do it that way is because it's been the easiest and least error-prone implementation and I never got around to improve it. What we probably should do instead is comparing the old and the new table schemas and calculate a 'fastest' transtormtion from the one to the other.

There are probably more cases like these where we can reduce the amount of SQL commands issued in some way. But other than these I'd leave it the way it is, that is relying on SQLite for all the operations. Here are some reasons:
* It's a lot easier to implement for us, e.g. enforcing foreign key constraints: currently we can just send a new cell value to SQLite; sure, maybe it fails but we can handle this error. On the other hand, doing the check by ourselves would involve making queries do the referenced table as well as checking if foreign keys are enabled for this database. Because of this I don't think we can gain any performance here. Because of all the special cases like multi-column keys or the like our code would probably also be more complex than it is now. So in short: more code and no better performance here.
* We'd have to implement and maintain all this functionality and given our current manpower this would probably eat up all the time we have and which would be better off spent in fixing existing bugs.
* Also we'd have to keep track with SQLite's development. If the SQLite developers decide to change the behaviour of some feature, we'd have to re-implement it on our side too, to keep in sync with them. Again, they are definitely faster than we are :wink: 

So to not reinvent the wheel I'd leave it the way it is. What we can and should do however is keep working on improving the way we use SQLite: @chrisjlocke 's suggestion is one example, but handling the errors SQLite generates when something fails in a better way, too. Also we should extend our SQL grammar parser to understand more ot the SQL commands by ourselves and not having to rely on SQLite for that.

I hope this makes some sort of sense :smiley:

**Comment by innermous** [comment]
@MKleusberg but how you wanna deal with situation where editing is locked due to instantly failed constraints(in various situations) and user being confused?

**Comment by innermous** [comment]
We should really start working on this issue, since a great amount of constraint bugs have been reported so far.
Let's start from the very beginning. Imagine we have a table, that doesn't fail when you add new row in a table with all those possible weird constraints :smile: It gives you possibility to edit fields of new record.
Then, eventually, you change focus, or press enter, or whatever - and the new record passes. It passes all constraints and is successfully added to sql backend.
But what happens if it's not? Should the new *virtual* (I like to call it this way :smile:) record be purged, or should it throw errors again and again until we input everything correct? What are the ways to undo that virtual row, besides explicit deletion?
All those questions should have answers before we actually start fixes.

**Comment by justinclift** [comment]
Timing wise... I'm kind of thinking we should do it after 3.9.0 is released - which I'm hoping to get done in maybe a week or 1.5 weeks.

Saying that because it sounds like changing the code in this way will give us a better foundation to build on... but at the same time is likely to show up lots of weird edge case bugs that we haven't fixed.  Better to do that for the release after 3.9.0 (4.0.0 maybe?), so we have more time to test, and not 250k people wanting to file new bugs. :wink:

Thoughts?

**Comment by innermous** [comment]
My only thought is this is kinda highest priority issue. It's not cosmetic or some not game breaking glitch. But it really reminds about itself every time. I had some research on it a month ago, now I am back to it again. 
Help is really appreciated,  as I mentioned [here](https://github.com/sqlitebrowser/sqlitebrowser/issues/628#issuecomment-233172979).
But well it can wait till release. I think this one will require some significant changes in the code.

**Comment by justinclift** [comment]
Yep, same thought.  And the "wait one release"... think of it more like "wait just a few weeks". 👼

**Comment by mgrojo** [comment]
I think all the actual issues we had with the current design have been long fixed (see [project](https://github.com/sqlitebrowser/sqlitebrowser/projects/2#card-149524)). As it is working fine, I don't think we should try to change this design. 

Can this be closed, then?

**Comment by justinclift** [comment]
Good idea.  Yeah, lets close this one. :smile:

**Comment by FriedrichFroebel** [comment]
Do we still need the "help wanted" tag in this case when the issue itself has been closed already?

**Comment by justinclift** [comment]
Oops.  Good point, probably not. :smile:
