### ISSUE TITLE
Crashes when selecting a different table while in Browse Data

### ISSUE THREAD

**Issue by eeinfalt** [sqlitebrowser/sqlitebrowser#707]
#### I'm opening this issue because:

- [X] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem: ___

sqlitebrowser crashes when selecting a different table while in Browse Data

### I'm using DB4S on:

- [X] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

### I'm using DB4S version:

- [ ] 3.7.0
- [X] 3.8.0
- [ ] Other: ___

### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by revolter** [comment]
Please try out the nightly version

**Comment by justinclift** [comment]
@eeinfalt Thanks for reporting this.  We're **very close** to releasing a major new version 3.9.0.  There's a pretty good chance this is already fixed in that.

If you're ok to try out the nightly build (download locations are on our front page), it's the same code as our upcoming 3.9.0 release.

Are you ok to give that a go and let us know if the problem still happens?

**Comment by justinclift** [comment]
@eeinfalt ping?

**Comment by justinclift** [comment]
Closing this due to lack of response.
