### ISSUE TITLE
Register Windows file extensions (open from Explorer)

### ISSUE THREAD

**Issue by AdamPS** [sqlitebrowser/sqlitebrowser#745]
### Details for the issue

I had hoped to be able to open files directly from outside of sqlitebrowser - e.g. from Windows Explorer, another file manager, or the command line.  For this to work, it would need sqlitebrowser to register for some file extensions: *.sqlite, and maybe others.

Is this something that you would expect to work?  If not, please can I request it as a feature?

Thanks

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [x] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.0
- [ ] 3.8.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Yep, in theory this should work.

However... it seems like I broke the file extensions again with this release by changing the installation path. 😦 

We have a now-outdated wiki entry for the old location:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/wiki/Windows-File-Associations

The concept mentioned in it is correct, although the paths need updating for this new release.

I'll spin up a Windows VM now, and see if I can figure it out. :smile:

**Comment by justinclift** [comment]
Actually, I think this might be a duplicate report for an existing (much older) report of the same breakage.  But, lets get this fixed for now, and we can figure out the duplicate-or-not later.

**Comment by AdamPS** [comment]
Thanks for a very quick reply, and let me know if you need me to test a Beta

**Comment by justinclift** [comment]
Hmmm, investigating this more, it seems like association with file extensions isn't something we've **yet** done automatically (or given an option for).

But, because almost everyone uses file extensions for this exact purpose :smile:, everyone has been creating the extensions manually (eg using Windows Explorer).

Two bits of thought arise for this:

a) Changing the installation path - which I did for this release - will probably break the existing (manually created) file associations everyone has set up.  Ouch. 😦 

b) We really should offer to set up the file associations, either during installation, and/or through our "Preferences" dialog.  That should solve a) above too. :smile:

@AdamPS I can investigate the this stuff, but it's not going to generate an immediate solution.  In the meantime, you should be able to manually create the association from whichever extensions you want, to DB4S.

If you're not sure how, let me know.  I just took a bunch of screenshot for the process while trying things out, and can put them somewhere useful as an step-by-step sequence. :smile:

**Comment by justinclift** [comment]
Found it, #279 is the older issue about this too.

**Comment by justinclift** [comment]
@AdamPS I'll close this issue now as a duplicate, and we can continue to get a solution in place through the older issue. :smile:
