### ISSUE TITLE
Weirdness in plot with NULL values

### ISSUE THREAD

**Issue by justinclift** [sqlitebrowser/sqlitebrowser#822]
### Details for the issue

Found a bug with our Plot code when trying some things out.  It seems like any column whose first value is NULL gets excluded from the plot list.  For example, the `downloads_this_hour` field isn't shown on the Plot panel:
![screen shot 2016-10-13 at 10 18 04](https://cloud.githubusercontent.com/assets/406299/19343574/9e154906-912e-11e6-9a1f-ecbfe8b635a0.png)
After adjusting the SQL query so the first result isn't NULL, the column shows up:
![screen shot 2016-10-13 at 10 26 52](https://cloud.githubusercontent.com/assets/406299/19343790/9a1dcaa2-912f-11e6-904c-29e9c37b3a6c.png)

#### I'm opening this issue because:

- [x] DB4S has a bug

#### I'm using DB4S on:

- [x] Mac OS: ( _version:_ 10.11.6 )

#### I'm using DB4S version:

- [x] 3.9.1
- [x] Other: git master https://github.com/sqlitebrowser/sqlitebrowser/commit/e76e5b3241af5e79474ae32fda393da921696d96

**Comment by MKleusberg** [comment]
I vaguely remember that there already is an issue which at least mentions this. However I cannot remember coming to a conclusion there. The problem is this: you obviously can't text values or something similar; all our plotting supports is numbers and dates. Now NULL isn't a text value but it's not a number either. We *could* treat it as zero and it would all work as expected but from a data point of view this would be wrong. 0 means there is data and its value is 0, whereas NULL means there is no data and no value. What we could check is if it's possible to plot it in cases like yours anyways and just have a gap in the graph where there is a NULL data point.

**Comment by justinclift** [comment]
For a NULL value, that means there's nothing to plot at that increment.  eg it's an unknown value, so can't be put anywhere

So yeah, a gap in the graph at the NULL data point is probably the right approach. :smile:

**Comment by MKleusberg** [comment]
Should be fixed :smiley: Can you give it a quick test, Justin?

**Comment by MKleusberg** [comment]
Found it! This is a duplicate of issue #513 :smiley:

**Comment by MKleusberg** [comment]
Also see issue #499.

**Comment by justinclift** [comment]
@MKleusberg Sorry for the delay.  Was away from my OSX desktop.

Tested latest master here, this is fixed now. :smile:
![screen shot 2016-10-14 at 00 21 06](https://cloud.githubusercontent.com/assets/406299/19370710/52578b38-91a5-11e6-9583-a51bac1fda7a.png)

Another win for you @MKleusberg. 😁
