### ISSUE TITLE
sqlitebrowser binary is not copied at install

### ISSUE THREAD

**Issue by leventelist** [sqlitebrowser/sqlitebrowser#833]
### Details for the issue

I configured the code using 'qmake USE_QT5=1 ..'. The code compiles fine, but when I 'make install', the built binary doesn't get to /usr/local/bin. If I copy by hand, the application seems to run fine.
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [x ] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [ ] Windows: ( _version:_ ___ )
- [x ] Linux: ( _distro:Debian stable_ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___
#### I'm using DB4S version:
- [ x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Thanks Lev, we'll look into it. :smile:

**Comment by MKleusberg** [comment]
Sorry for the delay, @leventelist! Can you try again using the latest version from master? This should work now:
```
qmake
make
make install
```

**Comment by leventelist** [comment]
Ok, I'll try as I have a chance. Maybe today evening.
Thanks for fixing the bugs anyways.

What about the cmake support? I'll test that too.

Lev

**Comment by leventelist** [comment]
Unfortunately it doesn't compile on my system. I have an up to date Debian Jessie. It seems that my system got too old.

/usr/include/c++/4.9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \

I try tomorrow on a Debian testing with more recent compiler.

Lev

**Comment by justinclift** [comment]
@leventelist As a thought, it's probably a good idea to install Qt 5.7 from the Qt.io download site too.  I've been trying things out with Ubuntu 16.04 today to investigate a a few of the issues reported over time.  It turns out that Qt versions older than Qt 5.7 have some weird problems. 😦

**Comment by leventelist** [comment]
Ok. Just a note. Should the cmake/qmake system take care about dependencies? So it shall detect Qt5.7, and refuse to configure the code if it is older.

**Comment by justinclift** [comment]
Sort of. :smile:

When you install Qt 5.7 (eg in ~/Qt by default), it comes with it's own version of `qmake`. (eg somewhere under ~/Qt/5.7/)

If you run that version of qmake, it's supposed to automatically choose the correct Qt 5.7 versions of bits instead of the older ones.

Hmmm, as a temporary thing which might be helpful, I took a bunch of screenshots earlier today of the Qt install + compile process, but on Ubuntu 16.04. I haven't yet renamed them into sensible things + added good description, but if you follow the sequence by timestamp it be pretty self explanatory:

&nbsp; &nbsp; https://github.com/sqlitebrowser/db4s-screenshots/tree/master/wiki/ubuntu_16.04

With the Qt version... it just needs to be version 5.7 or later.  Thinking about it now, you might as well pick the latest one (5.8), as there's probably useful extra bug fixes in that anyway.  The screenshots are for 5.8 too anyway.  But, up to you. :smile:

**Comment by leventelist** [comment]
I tried on Debian testing, with recent Qt and compiler. qmake doesn't
complained about my obvious missing dependency:

In file included from sqlitedb.cpp:2:0:
sqlite.h:13:25: fatal error: sqlite3.h: No such file or directory
     #include <sqlite3.h>

After installing the required packages, it installed fine. I suggest using
cmake as the code configuration tool.

Levente

**Comment by justinclift** [comment]
Thanks Lev. :smile:

I'm working through some `qmake` stuff at the moment, and yeah our CMake setup turns out to be more complete for Linux.

When CMake is used it puts the icon file, metadata, etc in the right places.  But our Qmake install doesn't.  I'm looking into it now, but it might take a few more days of mucking around with until it's correct. :smile:

I doubt either CMake nor Qmake will detect missing dependencies up from though.  It's normally the kind of thing which a configuration file does (eg ./configure, which we don't have)... or the end user when the compile busts. 😁

**Comment by leventelist** [comment]
One of the major user case of cmake is to detect installed packages. .configure (autotool) did the same thing, but it isn't portable (eg. it is a PITA on Windows). I personally use cmake it to detect SQLite. Here is what I do.

[CMakeLists.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/991259/CMakeLists.txt)

I use the same CMakeLists.txt on Linux and FreeBSD, so this is cross platform. I was lazy, and I just detect presence of libsqlite3, but with a small tweak, you can even detect, and require specific major/minor/patch version too.

I'm sorry if this is not the right place to suggest things.

**Comment by leventelist** [comment]
And I think we can close this issue, since the original problem is solved now. Thanks.

**Comment by justinclift** [comment]
No worries Lev, thanks. :smile:
