### ISSUE TITLE
Browse data loses context between tab switches

### ISSUE THREAD

**Issue by MarrinerDev** [sqlitebrowser/sqlitebrowser#849]
#### I'm opening this issue because:
- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem
#### I'm using DB4S on:
- [X] Windows: ( _version: 10 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___
#### I'm using DB4S version:
- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
#### I have also:
- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Ahhh, interesting.  From memory this was fixed shortly after the 3.9.1 release.

Would you be ok to try out one of the nightly builds?

&nbsp; &nbsp; https://nightlies.sqlitebrowser.org

**Comment by justinclift** [comment]
@MarrinerDev Did you have a chance to try the nightly builds? :smile:

**Comment by aneroid** [comment]
I duped this one in issue #873.

Re-tried and works, with the last nightly build - 2016-11-18, win64, v3.9.99

**Comment by aneroid** [comment]
One thing to add to this bug, which is **also/already fixed in the nightlies**: When we right-click on a Table or View and select 'Browse Data', that didn't take you to that table in the data browser, always the first one by sort order. In the nightly I tested against (2016-11-18), this works correctly: right-click on table/view ➜ Browse data takes you to that one in the data browser.

_Btw, this should probably be added to [3.10.0 - A Rubber Cactus Has Many Uses](https://github.com/sqlitebrowser/sqlitebrowser/milestone/11)._

**Comment by revolter** [comment]
Wow, I didn't even know about the "Browse Table" option! 😲 

Also, I don't think adding duplicates to the milestone would help much. It looks like #748 is the first one, followed by #757, #784, #849 and #873.

**Comment by MarrinerDev** [comment]
Hi Justin,


  yes, sorry for the delay in getting back to you. I can confirm that this bug is fixed in the latest nightly build.


Cheers,

Michael.


________________________________

**Comment by justinclift** [comment]
Awesome, thanks Michael. :smile:
