### ISSUE TITLE
Cannot add a table column with type BOOLEAN

### ISSUE THREAD

**Issue by deandob** [sqlitebrowser/sqlitebrowser#881]
When using the modify table option, adding a field (new column) you can select all SQLite types except BOOLEAN. Even if you edit the TYPE field with text BOOLEAN it remains as the default INTEGER.

**Comment by justinclift** [comment]
Ouch, that's not good.

Which version is that happening with, and on which OS?

**Comment by chrisjlocke** [comment]
> SQLite does not have a separate Boolean storage class. Instead, Boolean values are stored as integers 0 (false) and 1 (true). There is no boolean data type. ... "But as soon as INTEGER values are read off of disk and into memory for processing, they are converted to the most general datatype (8-byte signed integer)."24 Mar 2010

Also, in at least 3.9.1, if I add a field and make the type "widgetFluffyBum', then it accepts that.  In fact, it even accepts Boolean.  I think the issue is that people aren't pressing Enter to save the adjustment.  Here is a screencast:
http://screencast-o-matic.com/watch/cDXTlYQiO3

So I have a field called 's' which I change to 'fluffy'.  If I click OK, it doesn't accept it.  You'd think it would be like Notepad where it would say, "Do you want to save changes to .... ?" rather than just losing the amendments, but hey... maybe the next version .... :wink:
But the second half of the video shows pressing Enter saves the amendment, and all is good.

**Comment by deandob** [comment]
Thanks. Interestingly when I initialize the database I use BOOLEAN as the data type which is accepted by SQLite and also displayed in sqlitebrowser as BOOLEAN - hence this threw me off.
