### ISSUE TITLE
Installer doesn't drop priveleges before running program for first time after install

### ISSUE THREAD

**Issue by Kudalufi** [sqlitebrowser/sqlitebrowser#889]
### Details for the issue
At the end of an install, the installer asks if you would like to run the program.  If you leave that checkbox ticked yes, then the installer doesn't drop its own administrative priveleges before running DB Browser.  DB Browser, thus, gets run with those priveleges.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [X] Windows: ( _version:_ 7 )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [X] Other: 3.9.99 (Nightly: "DB Browser for SQLite-sqlcipher-2016-11-28-win64.exe")

**Comment by justinclift** [comment]
Oops, forgot to respond to this.  It's a valid concern, but I'm thinking the bug isn't really with us directly.

We create the installer (auto-generated) using CMake + NSIS.  This bug **sounds** like its a problem with how with CMake is generating things, or perhaps even how the NSIS backend to CMake is doing stuff.

Any interest in reporting this to the CMake project people, so they can discuss/investigate it?

&nbsp; &nbsp; https://cmake.org/mailman/listinfo/cmake

Asking because if/when it's fixed by whichever of those two is the causing bit, then it'll automatically be fixed for us when we update. :smile:

**Comment by justinclift** [comment]
Closing this due to lack of response. 😦
