### ISSUE TITLE
Range operator for Filter

### ISSUE THREAD

**Issue by karim** [sqlitebrowser/sqlitebrowser#935]
If I have an INTEGER column I can filter the numbers in it using the supported operators from this page https://github.com/sqlitebrowser/sqlitebrowser/wiki/Using-the-Filters.

Is it possible to have a filter for **range** (- or \~)? Something like _min-max_ (or _min~max_) to show only the numbers in this range. For example, If I want to filter a column with numbers between 1 and 5 I can type in filter something like **1-5** (or **1~5**). It is like combining _Equal to or greater_ and _Equal to or less_ together.

Also, maybe we can have an **and** (,) operator? To show only specific numbers we can type something like **1,2,5**.

#### I'm opening this issue because:

- [x] DB4S needs a feature

**Comment by justinclift** [comment]
Sounds like a worthwhile enhancement.  We could probably do something to make it work. :smile:

@MKleusberg Thoughts?

**Comment by MKleusberg** [comment]
We've just merged a PR by @schdub that implements this (using the ```1~5``` notation) :smiley:

@karim Can you test tomorrow's nightly build to see if it's working for you? :smiley:

**Comment by karim** [comment]
@MKleusberg Thanks. Yes I will try it and report back.

**Comment by karim** [comment]
@MKleusberg I tested it and it is working very nice. Thanks!

@schdub Thanks a lot for this! 😄

**Comment by justinclift** [comment]
@chrisjlocke Any interest in updating the Filters page on the wiki with this new operator? :smile:

**Comment by chrisjlocke** [comment]
Just updating the wiki, but ... well, its not working for me....

![image](https://cloud.githubusercontent.com/assets/7872218/22418793/62f771b0-e6d2-11e6-88ab-9e090208a9fe.png)

1~6 shouldn't be including 11 should it? If I change it to 2~6, I get the right result.

**Comment by chrisjlocke** [comment]
Wiki page updated.  👍

**Comment by MKleusberg** [comment]
@chrisjlocke I've stumbled upon that, too :wink: But that's actually because of SQLite's treatment of data types. ```Field3``` is probably of type ```text``` in your database. If you change it to ```integer``` SQLite it'll work as expected. That's just how SQLite works: you can save any kind of data in any column, no matter the column's data format. But as soon as you're querying the table the data format of the columns actually does matter. In this case 11 is between 1 and 6 because 11 is a text, not a number, and only the first character is used for comparison. If the data format of the column is integer, the value is basically casted to an integer before comparison and 11 is definitely not between 1 and 6 :wink:

Going one step further we could think about casting the field to an integer automatically when doing range comparisons but I'd suggest to leave it as it is in order to not hide the logic of SQLite. But we might add an 'attention' box to the Wiki page. What do you reckon?

**Comment by chrisjlocke** [comment]
Good spot - yup, the field type was text.  `*blush mode on*`.  Doh! ;)
Changing it to integer works as required.  (`*flushes head down toilet*`)

**Comment by MKleusberg** [comment]
No worries, it took me some time to figure this out, too :smiley: And it wasn't even the first time this confused me :wink:

**Comment by karim** [comment]
Maybe DB4S should provide a hint when the `~` (range) operator is being used on a column that is not an `INTEGER`. A tooltip, modeless dialog, or changing the background color of the column's filter?

This should work also with `>` (greater than) and `<` (less than) operators, since they are only used with numbers.

**Comment by karim** [comment]
Sorry, I forgot to close this. :smiley:

**Comment by pablonana** [comment]
this doesn't work for float fields, can you fix that?

**Comment by chrisjlocke** [comment]
Can you provide an example of 'doesn't work'?  Seems to work OK for me...

![image](https://user-images.githubusercontent.com/7872218/106801927-3491eb00-665a-11eb-8b4f-a1758f657bfd.png)

This is for values 1.1, 2.2 and 3.3

![image](https://user-images.githubusercontent.com/7872218/106801988-470c2480-665a-11eb-85ec-3b6d3eae2751.png)

**Comment by chrisjlocke** [comment]
Even works with non-integers...

![image](https://user-images.githubusercontent.com/7872218/106802140-702cb500-665a-11eb-8c19-86f8680486c9.png)

![image](https://user-images.githubusercontent.com/7872218/106802163-7884f000-665a-11eb-999d-9299877de359.png)

**Comment by MatthieuGomes** [comment]
Sorry to reopen : doesn't work for datetime for example
