### ISSUE TITLE
Right to left formatting of text is not retained when using 'Edit Cell' dialog

### ISSUE THREAD

**Issue by awi1369** [sqlitebrowser/sqlitebrowser#949]
i want save text in right side! but when i click Apply ,text save in left side!
i can not save it right side!
please see video,how can i  save in right side!?help me please
https://youtu.be/LmHSJrNqi6c

**Comment by justinclift** [comment]
Interesting.  That definitely seems like a bug.

@awi1369 Was that with version 3.9.1?  If so, do you have time to try our latest nightly build?  The behaviour may be different in that. :smile:

* https://nightlies.sqlitebrowser.org/win64/DB%20Browser%20for%20SQLite-2017-01-27-win64.exe

**Comment by justinclift** [comment]
@SafaAlfulaij This might be of interest to you. :smile:

**Comment by awi1369** [comment]
@justinclift   same problem in  nightly build!  i can not save in right side!

**Comment by justinclift** [comment]
Oh well. 😦   Thanks for checking @awi1369, that does help. :smile:

**Comment by SafaAlfulaij** [comment]
The problem is actually that sqlitebrowser doesn't set the direction for that textbox to LTR automaticly. It should do that as all other widgets. I'll check. I think it's because of the text formatting (It's a richtext widget).

And for the bug, it is not. This is the right and correct behaviour. You can't save in "Right side", because you started the text with LTR direction letter.
It doesn't matter really for the database, but visually, it matters a bit.
You can force the text direction to be RTL when viewing the page (seems to be a webpage).

**Comment by justinclift** [comment]
@SafaAlfulaij Thanks. :smile:

And yeah, if you get this figured out we're happy to merge a PR. 😁

**Comment by SafaAlfulaij** [comment]
@awi1369 Can you please write the information of your system locale? I tested it in Windows 10 with both English and Arabic locales, and the text in the edit box was aligned to left (And it's direction is LTR).
Appeared as:
<div dir="ltr">
H5:
</div>
and not (as you have):
<div dir="rtl">
H5:
</div>

**Comment by justinclift** [comment]
@awi1369 @SafaAlfulaij Is this something we still need to investigate or put time into? :smile:

**Comment by justinclift** [comment]
Closing this due to lack of response by @awi1369.

@awi1369 If this is something you're still needing fixed, and can put some time and effort into helping out by answering @SafaAlfulaij's questions then you're welcome to reopen this so we can continue. :smile:
