### ISSUE TITLE
Foreign key editing widget is too small

### ISSUE THREAD

**Issue by prutz1311** [sqlitebrowser/sqlitebrowser#951]
### Details for the issue
When I create or modify table, foreign key field wigdet size is too small:
![image](https://cloud.githubusercontent.com/assets/6525383/22394812/987c78a0-e53b-11e6-9cbb-83761708c1e3.png)

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: ( _distro: Xubuntu 14.04.5 LTS trusty)
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [ ] 3.9.1
- [ ] 3.9.0
- [ ] Other: 2981351

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [x] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
The same thing happens on OSX too.  It was introduced recently with the new foreign key drop down widgets).

We just haven't gotten to figuring out better sizes for those widgets.

If you have the time and interesting to investigate it, we'd welcome a PR. :smile:

**Comment by prutz1311** [comment]
I can only make it look like this:
![image](https://cloud.githubusercontent.com/assets/6525383/22397962/dc074c6e-e58e-11e6-94d1-a21994588d78.png)
No idea though how to align these boxes to the top.

**Comment by innermous** [comment]
@justinclift it was not "introduced", table view was malformed from the beginning, there's nothing wrong with delegate, it inherits cell's geometry.

**Comment by justinclift** [comment]
@innermous Sorry.  That was a misunderstanding on my part then. 😦

**Comment by MKleusberg** [comment]
Because it hasn't been (explicitly) mentioned here before I'll add another observation of mine.

When editing a foreign key it looks like this for me:
![screenshot_20170130_123615](https://cloud.githubusercontent.com/assets/3153504/22421798/55f65438-e6e9-11e6-809e-8e1132aa0122.png)
The height is a little smaller than it could be but that doesn't bother me much. However, if I click on another row to close the foreign key editor and then double click the foreign key again, I get this:
![screenshot_20170130_123731](https://cloud.githubusercontent.com/assets/3153504/22421836/8a99d3b8-e6e9-11e6-8870-e1191b6d489b.png)
As you can see the widgets have become a lot smaller, the contents almost doesn't fit in them anymore.

**Comment by innermous** [comment]
I can't reproduce it :(

**Comment by MKleusberg** [comment]
Just pushed an experimental patch for this. Can you try again with the latest version from master, @prutz1311? No guarantees it's going to get any better with that though :wink:

**Comment by prutz1311** [comment]
Now it fits perfectly on Xubuntu 14.04.5:
![image](https://cloud.githubusercontent.com/assets/6525383/22600777/1acc7664-ea4d-11e6-9fb7-4cb37c0142b2.png)
Not sure however what it looks like on other systems. We probably also need feedback from @innermous .

**Comment by MKleusberg** [comment]
Thanks for testing this so quickly, @prutz1311! :smiley: I guess this should work on all platforms then. For me, the second time I open the foreign key editor it's still a little smaller than the first time, but only very slightly and only sometimes. So that's no big problem for me.
