### ISSUE TITLE
Cant define PRAGMAs from "run sql" tab

### ISSUE THREAD

**Issue by hackingtosh** [sqlitebrowser/sqlitebrowser#966]
### Details for the issue

I cant define pragmas on the run-sql tab. E. g. if I type and execute "pragma auto_vacuum = 1;" and choose the tab "edit pragmas" i cant see my changes.

Its also not working when i modify the options directly on the "edit pragmas" tab, also if i hit the "save" button hundrets of times.

But i found a workaround, if i type and execute this:
end transaction;
pragma auto_vacuum = 1;

and after that I clicked the "compact database" option on the menu strip, then changes were accepted.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [x] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [x] Windows: ( _version:_ _7_Professional_ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___
- [x] also occuring at version 3.8.0

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Sounds like our transaction control bits are/were interfering with setting pragmas.

Would you be ok to try out the latest nightly version?  We've done a fair amount of work on our transaction control pieces since our 3.9.1 release.  There's a decent chance this bug won't be present in the nightlies. :smile:

**Comment by hackingtosh** [comment]
Yes I tried "DB Browser for SQLite-2017-02-22-win64", but the problem is still there. The changes will be accepted only, if I hit the "compact database" option. Cant you recreate my problem by yourself?

**Comment by justinclift** [comment]
It's not something I have time to look at personally today.  My focus for today is on other stuff which is well overdue. :wink:

Hopefully one of the other team members has time to investigate. :smile:

**Comment by hackingtosh** [comment]
Ok thanks, I thought maybe you already noticed this problem ;)

**Comment by justinclift** [comment]
No worries at all. :smile:

**Comment by MKleusberg** [comment]
This seems to be the same issue as in #980. I've just tried to explain the problem in that issue and will just copy & paste it: :smiley:

That happens because we have to execute all SQL commands inside a transaction and the foreign key pragma [or any other pragma for that matter] can't be set inside a transaction. The only reasonable workaround for us that I can think of right now is to somehow detect a ```pragma foreign_keys=x``` [or other pragmas] statement and disable transactions for that. But that's always going to be error-prone...

**Comment by justinclift** [comment]
Maybe if add a checkbox option to the Execute SQL tab "[ ] Run inside transaction", so people can enable/disable the transaction themselves?

**Comment by MKleusberg** [comment]
@hackingtosh I believe this is fixed in the next nightly build. Can you download that (see our main page for the link) and check if it's working for you as expected? :smile:

**Comment by justinclift** [comment]
Closing this, as #980 seems to cover it well enough. :smile:
