### ISSUE TITLE
Upgrade now wants password when one was not entered

### ISSUE THREAD

**Issue by Gilead7** [sqlitebrowser/sqlitebrowser#971]
### Details for the issue

Just upgraded to Win7 from XP. I was working on an SQLite Database for a Unity project using the previous XP compatible sqlite browser. After I install the newest version 3.91 and load my previous database, it asks for a password. I never had a password before, how do I get back into my database?

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [ ] DB4S has a bug
- [ ] DB4S needs a feature
- [x ] DB4S has another problem

#### I'm using DB4S on:

- [x ] Windows: ( _version:_7 ___ )
- [ ] Linux: ( _distro:_ ___ )
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [x ] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [ ] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
That's strange.  DB4S asks for a password when it can't recognise the file as a database, so it assumes it's an encrypted one.

Are you able to open the database ok with the command line version of SQLite?  That should help figure out where the problem lies.

**Comment by chrisjlocke** [comment]
Are you able to email me the database at all, or is it confidential information?

**Comment by Gilead7** [comment]
It's basically for scratch/testing purposes.
I uninstalled and then reinstalled and was able to open it. If there is 
something funky, do let me know. Crazy things can happen when migrating.

**Comment by chrisjlocke** [comment]
Weird.  Glad its now resolved now though.

**Comment by Gilead7** [comment]
Me too

**Comment by Gilead7** [comment]
One more thing, not sure why or how to fix it. When I tried to add to 
the database, it said is was read only. I can't find anything that tells 
me where that setting is.

**Comment by justinclift** [comment]
@Gilead7 On windows, it's probably the file level settings for "Read Only".  You can change that in Windows Explorer by right clicking then choosing properties.

That's the theory anyway. :wink:

**Comment by chrisjlocke** [comment]
Its also dependant on how you access that file.  What I mean by that is, if its a network share, then file permissions are based on that share as well as the physical file permissions.  So you might have physical file permissions, but the share permissions say otherwise.

If you're accessing the file locally, then yes, its file permissions.

If you're accessing the file in c:\program files or c:\program files (x86) then thats a bit more tricky, as Windows doesn't like you opening files there.  You have to have special admin permissions for that (usually right click a program and select 'Run as administrator')
