### ISSUE TITLE
PRAGMA foreign_keys = ON; failed

### ISSUE THREAD

**Issue by qiulang** [sqlitebrowser/sqlitebrowser#980]
### Details for the issue

PRAGMA foreign_keys = ON; 

Query executed successfully: PRAGMA foreign_keys = ON; (took 0ms)

Run PRAGMA foreign_keys; again and still show 0

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [X] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [ ] Windows: ( _version:_ ___ )
- [ ] Linux: ( _distro:_ ___ )
- [X] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using DB4S version:

- [X] 3.9.1
- [ ] 3.9.0
- [ ] Other: ___

#### I have also:

- [ ] Tried out the nightly version: https://github.com/sqlitebrowser/sqlitebrowser#windows
- [X] Searched for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

**Comment by justinclift** [comment]
Interesting.  Does it still happen with our recent nightly builds?  Download locations are listed on our front page, if that helps. :smile:

**Comment by MKleusberg** [comment]
That happens because we have to execute all SQL commands inside a transaction and the foreign key pragma can't be set inside a transaction. The only reasonable workaround for us that I can think of right now is to somehow detect a ```pragma foreign_keys=x``` statement and disable transactions for that. But that's always going to be error-prone...

@qiulang Do you need to be able to do this using SQL? Or can you just use the GUI editor in the Edit Pragma tab instead?

**Comment by MKleusberg** [comment]
This also seems to be related to #966.

**Comment by MKleusberg** [comment]
@qiulang I believe this is fixed in the next nightly build. Can you download that (see our main page for the link) and check if it's working for you as expected? :smile:

**Comment by justinclift** [comment]
Closing this due to lack of response.
