### ISSUE TITLE
Latest release doesn't remove previous version from add remove program menu

### ISSUE THREAD

**Issue by HarelM** [sqlitebrowser/sqlitebrowser#982]
I just installed version 3.9.1.
My file association was targeting the previous version (3.8.x) which made me understand that it wasn't removed as part of the installation of the latest version...

**Comment by chrisjlocke** [comment]
Yes, this was an issue in the 3.8.x installer (and 3.9 I believe) which should be fixed now, as the issue was identified when people starting upgrading to 3.9.1.
It didn't help that the directory location for the installation also changed between versions, otherwise this wouldn't have been an issue... ;)

**Comment by mgrojo** [comment]
Should this be closed then, since it is fixed in current versions?

**Comment by justinclift** [comment]
Ahhh yep.  Thanks @mgrojo. :smile:
