### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by keedhost** [sqlitebrowser/sqlitebrowser#987]
Hello. I made full ikrainian translation for sqlitebrowser.

Please test it and add to main repo/

https://github.com/keedhost/sqlitebrowser-ukrainian

**Comment by justinclift** [comment]
Thanks @keedhost, that's excellent. :smile:

I'll add the sqlb_uk_UA.ts file in the next few days.  Did you base the translation upon our latest development code (eg our "master" branch), or upon something else?

**Comment by keedhost** [comment]
Yes

**Comment by justinclift** [comment]
I'm attempting to get this working in a branch here:

&nbsp; &nbsp; https://github.com/justinclift/sqlitebrowser/tree/ukrainian

It's working fine when compiled on OSX.  I can change to Ukrainian, see messages in that, and change back to English without a problem.

It's not working on Windows though, and I have no idea why. 😦 

On Windows, the option for Ukrainian appears in the list and can be selected, but DB4S is in English after restarting.  Changing to other languages is working fine though, so there's something not quite right with the Ukrainian change.  It's probably something I've forgotten to do, I just need to figure out what.

To solve this I'll probably need to install a full development environment of Qt on Windows, and debug the process.  I don't have time for it today though. :frown:

@chrisjlocke @MKleusberg Just in case, don't suppose you have any ideas what might cause that behaviour? :smile:

**Comment by keedhost** [comment]
Can you make for me any screenshots with ukrainian version on Mac?

**Comment by justinclift** [comment]
Yep, I can definitely do that.  I'll be tomorrow though. :smile:

**Comment by keedhost** [comment]
I don't know why but on FreeBSD 11 same problem like on Windows: after choosing ukrainian and restarting app, locale sets to default. Who knows?

**Comment by justinclift** [comment]
Hmmm, now I'm wondering what happens if we change it from "uk_UA" to just "uk".  Perhaps the Windows and FreeBSD are recognising "uk_UA" for some unknown reason?

**Comment by justinclift** [comment]
I'll setup a Windows development VM again later on today, and see if I can figure out what's going wrong. :smile:

**Comment by justinclift** [comment]
I ***think*** this is everything, except for the CSV import dialog (which I'm having a problem with at the moment). :smile:

- [x] Menus
![screen shot 2017-04-04 at 13 19 03](https://cloud.githubusercontent.com/assets/406299/24660899/b8e94690-1948-11e7-8a82-e5318538883d.png)
![screen shot 2017-04-04 at 13 20 40](https://cloud.githubusercontent.com/assets/406299/24660898/b8e8c724-1948-11e7-9ac0-de51d994b374.png)
![screen shot 2017-04-04 at 13 20 50](https://cloud.githubusercontent.com/assets/406299/24660900/b8ea89d8-1948-11e7-9d48-e77cbaf011b6.png)
![screen shot 2017-04-04 at 13 20 55](https://cloud.githubusercontent.com/assets/406299/24660901/b8ec077c-1948-11e7-9665-cbb3ca009997.png)
![screen shot 2017-04-04 at 13 21 00](https://cloud.githubusercontent.com/assets/406299/24660902/b8eeacac-1948-11e7-8220-76d54dffbb55.png)
![screen shot 2017-04-04 at 13 21 11](https://cloud.githubusercontent.com/assets/406299/24660903/b8ef5396-1948-11e7-94d0-b54db3f38a14.png)
![screen shot 2017-04-04 at 13 21 16](https://cloud.githubusercontent.com/assets/406299/24660904/b90ef138-1948-11e7-9ad5-23a94d03f014.png)
![screen shot 2017-04-04 at 13 21 20](https://cloud.githubusercontent.com/assets/406299/24660905/b911b35a-1948-11e7-8e95-b750ad3eeba4.png)

- [x] AboutDialog.ui
![screen shot 2017-04-04 at 15 01 15](https://cloud.githubusercontent.com/assets/406299/24660985/fd2f3832-1948-11e7-8378-781e62059bea.png)

- [x] CipherDialog.ui
![screen shot 2017-04-04 at 15 36 36](https://cloud.githubusercontent.com/assets/406299/24662281/90e0354c-194c-11e7-98e6-0d94f73527f3.png)
![screen shot 2017-04-04 at 15 36 56](https://cloud.githubusercontent.com/assets/406299/24662282/90f185e0-194c-11e7-8cb4-f6d8a3e1b01b.png)
![screen shot 2017-04-04 at 15 38 06](https://cloud.githubusercontent.com/assets/406299/24662379/c8505494-194c-11e7-83ca-a7c41cee0761.png)
![screen shot 2017-04-04 at 15 38 13](https://cloud.githubusercontent.com/assets/406299/24662380/c856bd2a-194c-11e7-8e49-fd916bc1af9b.png)

- [x] ColumnDisplayFormatDialog.ui
![screen shot 2017-04-04 at 15 39 35](https://cloud.githubusercontent.com/assets/406299/24662428/f34cc9e8-194c-11e7-8039-51525cd78749.png)
![screen shot 2017-04-04 at 15 39 39](https://cloud.githubusercontent.com/assets/406299/24662429/f34def9e-194c-11e7-9408-16b295043633.png)

- [x] CreateIndexDialog.ui
![screen shot 2017-04-04 at 14 39 23](https://cloud.githubusercontent.com/assets/406299/24661297/eb63b820-1949-11e7-97d7-2a3c8333f644.png)

- [x] EditDialog.ui
![screen shot 2017-04-04 at 14 42 20](https://cloud.githubusercontent.com/assets/406299/24661205/aeb0fdac-1949-11e7-9f48-a3e440c11e17.png)
![screen shot 2017-04-04 at 14 42 23](https://cloud.githubusercontent.com/assets/406299/24661213/b525436e-1949-11e7-8782-016ac3dba0e4.png)

- [x] EditTableDialog.ui
![screen shot 2017-04-04 at 14 38 16](https://cloud.githubusercontent.com/assets/406299/24661770/2ef204c4-194b-11e7-8011-ca51e3dc07f6.png)

- [x] ExportDataDialog.ui
![screen shot 2017-04-04 at 13 30 28](https://cloud.githubusercontent.com/assets/406299/24661532/866f28fe-194a-11e7-931e-6a9d02889ec0.png)
![screen shot 2017-04-04 at 13 30 31](https://cloud.githubusercontent.com/assets/406299/24661535/8674ced0-194a-11e7-9261-b689d6ad4c58.png)
![screen shot 2017-04-04 at 13 30 35](https://cloud.githubusercontent.com/assets/406299/24661533/8672bafa-194a-11e7-902d-6680cfc3a9b7.png)
![screen shot 2017-04-04 at 13 30 39](https://cloud.githubusercontent.com/assets/406299/24661534/8673f6cc-194a-11e7-8d59-584159a890d8.png)
![screen shot 2017-04-04 at 13 31 05](https://cloud.githubusercontent.com/assets/406299/24661536/8678f69a-194a-11e7-8fa8-33f70de08431.png)

***Note*** - This next dialog is for exporting to JSON.  There was a bug with the code, so the window title said "CSV" instead of JSON.  Fixed earlier today. :wink: ace89f124d143fb7e594f16b399a35df8059f436
![screen shot 2017-04-04 at 13 31 24](https://cloud.githubusercontent.com/assets/406299/24661587/aa52c5fa-194a-11e7-8bf4-ffde307bf68d.png)

- [x] ExportSqlDialog.ui
![screen shot 2017-04-04 at 13 28 23](https://cloud.githubusercontent.com/assets/406299/24661483/5fdbaba4-194a-11e7-91a6-4c5ada07b044.png)
![screen shot 2017-04-04 at 13 29 19](https://cloud.githubusercontent.com/assets/406299/24661484/5fdda706-194a-11e7-8761-a2b5bbb091e5.png)
![screen shot 2017-04-04 at 13 30 03](https://cloud.githubusercontent.com/assets/406299/24661486/5fe1ed02-194a-11e7-9f63-1062990a6c3f.png)

- [x] MainWindow.ui
![screen shot 2017-04-04 at 13 18 45](https://cloud.githubusercontent.com/assets/406299/24661074/451f9be6-1949-11e7-9609-a196d4b4afef.png)
![screen shot 2017-04-04 at 14 40 08](https://cloud.githubusercontent.com/assets/406299/24661351/0d633fa4-194a-11e7-8271-d7acf6880cb8.png)
![screen shot 2017-04-04 at 14 40 41](https://cloud.githubusercontent.com/assets/406299/24661352/0d7c30f4-194a-11e7-8a79-e9765c24a563.png)
![screen shot 2017-04-04 at 14 41 05](https://cloud.githubusercontent.com/assets/406299/24661349/0d4d771e-194a-11e7-9c9a-7c94e1bedeba.png)
![screen shot 2017-04-04 at 14 41 17](https://cloud.githubusercontent.com/assets/406299/24661348/0d4c4e2a-194a-11e7-961c-e94689eac6b2.png)
![screen shot 2017-04-04 at 14 41 39](https://cloud.githubusercontent.com/assets/406299/24661347/0d4b7cac-194a-11e7-90a1-a0e4676b04a9.png)
![screen shot 2017-04-04 at 14 42 03](https://cloud.githubusercontent.com/assets/406299/24661350/0d5e8a18-194a-11e7-8a1d-c1f1f05dc503.png)

- [x] PreferencesDialog.ui
![screen shot 2017-04-04 at 15 01 30](https://cloud.githubusercontent.com/assets/406299/24661023/20aaf152-1949-11e7-871e-0394eb28686f.png)
![screen shot 2017-04-04 at 15 01 36](https://cloud.githubusercontent.com/assets/406299/24661024/20ad164e-1949-11e7-90a7-075b038237c2.png)
![screen shot 2017-04-04 at 15 01 45](https://cloud.githubusercontent.com/assets/406299/24661026/20c008bc-1949-11e7-8ba8-41109b434a46.png)
![screen shot 2017-04-04 at 15 01 54](https://cloud.githubusercontent.com/assets/406299/24661031/2162d18c-1949-11e7-97a9-a50e7c58794b.png)
![screen shot 2017-04-04 at 15 02 01](https://cloud.githubusercontent.com/assets/406299/24661030/213a9d98-1949-11e7-8e96-5b11f0cc7ab4.png)
![screen shot 2017-04-04 at 15 02 27](https://cloud.githubusercontent.com/assets/406299/24661025/20ae3b50-1949-11e7-85b3-fd55c7960044.png)
![screen shot 2017-04-04 at 15 02 42](https://cloud.githubusercontent.com/assets/406299/24661028/20dd6484-1949-11e7-8143-9ad9a9e0ef17.png)

- [x] VacuumDialog.ui
![screen shot 2017-04-04 at 15 35 06](https://cloud.githubusercontent.com/assets/406299/24662216/6a9aebac-194c-11e7-8a2c-4269b46d1004.png)

- [x] Various other dialogs
![screen shot 2017-04-04 at 13 22 56](https://cloud.githubusercontent.com/assets/406299/24661133/77331572-1949-11e7-9144-45b71a77cfb8.png)
![screen shot 2017-04-04 at 13 23 20](https://cloud.githubusercontent.com/assets/406299/24661157/8c0c380c-1949-11e7-9da5-77e75db238a5.png)
![screen shot 2017-04-04 at 14 48 42](https://cloud.githubusercontent.com/assets/406299/24661183/9ec6d902-1949-11e7-9d15-82fde3e1b094.png)
![screen shot 2017-04-04 at 14 39 06](https://cloud.githubusercontent.com/assets/406299/24661787/3bc24c54-194b-11e7-98ae-4970af7a167f.png)
![screen shot 2017-04-04 at 15 29 21](https://cloud.githubusercontent.com/assets/406299/24662196/5b334ed4-194c-11e7-8e32-51b6066e517d.png)

- [x] ***File*** → ***Import*** -> ***Database from SQL file...***
![screen shot 2017-04-04 at 13 27 56](https://cloud.githubusercontent.com/assets/406299/24662048/f6bd79fc-194b-11e7-9f87-572e7ee4d05b.png)
![screen shot 2017-04-04 at 13 26 43](https://cloud.githubusercontent.com/assets/406299/24662060/fe360820-194b-11e7-8840-8d68d3b01f09.png)
![screen shot 2017-04-04 at 13 28 03](https://cloud.githubusercontent.com/assets/406299/24662076/052738d4-194c-11e7-80f0-6930cb465c7b.png)

**Comment by justinclift** [comment]
@keedhost I don't think I'll get to checking the Windows problem today after all.  It should be tomorrow, or Thursday at the very latest though.

**Comment by justinclift** [comment]
Found the problem.  It was indeed my fault... a typo in the change I made to src/translations/translations.qrc:

https://github.com/justinclift/sqlitebrowser/blob/d5a6bc496dd97004dba6f005d5def7570962812d/src/translations/translations.qrc#L14

The filename extension on that line should be **.qm**, not **.ts**.  Oops.

I'll update my branch with that, and also pull in your updated patch. :smile:

**Comment by justinclift** [comment]
Ok, I *think* this branch has the latest changes, including Genyk's pieces:

https://github.com/justinclift/sqlitebrowser/tree/ukrainian_version2

Can you double check from your side?

If you're happy with it, I'll merge it in. :smile:

**Comment by justinclift** [comment]
Ahhh, I didn't see Genyk's patch-7 & patch-8.  I'll add those now too.

**Comment by justinclift** [comment]
@keedhost @Genyk I've added the patch-7 and patch-8 changes here too:

&nbsp; &nbsp; https://github.com/justinclift/sqlitebrowser/commits/ukrainian_version2

Do you want me to merge it "as is", or should I take updated screenshots again? :smile:

**Comment by justinclift** [comment]
Hmmm, I'm just going to merge it. :smile:

**Comment by justinclift** [comment]
@keedhost @Genyk All of the Ukrainian translation patches are merged into our master branch now.

Do either of you have time to double check it?

I'll also close the Pull Request, as this was done a bit outside of that. :smile:

**Comment by Genyk** [comment]
I can recheck all the translation, but i haven`t used this program before. So i cant understand some function even in English :(

**Comment by justinclift** [comment]
@Genyk If you have the time to play around with it and try things out, then most (80%) of the program is fairly simple.  It's mostly just a display of databases in a spreadsheet format.

You can download a sample database to use with it here:

&nbsp; &nbsp; https://dev1.dbhub.io/justinclift/DB4S%20download%20stats.sqlite
&nbsp; &nbsp; (the green download button on the right side)

Does that help? :smile:

**Comment by Genyk** [comment]
@justinclift I will try to check it all at the weekends.

**Comment by justinclift** [comment]
@Genyk Awesome!

If you have questions, you're welcome to ask here and I should be able to respond without *too much* delay. :smile:

**Comment by justinclift** [comment]
Oops, forgot to close this ages ago.  Doing it now. :smile:
