### ISSUE TITLE
Typo in menu "Help -> SQL Ciper" of german translation

### ISSUE THREAD

**Issue by ecki** [sqlitebrowser/sqlitebrowser#988]
### Details for the issue

On german UI under "Hilfe" there is a "SQL Ciper FAQ" item, which should be "SQL Cipher" I guess. The same "SQLCiper-Version" text also shows up in the about dialog for the version (3.11.0)

### Useful extra information

Portable App, if I switch UI language to english it is fine.

#### I'm opening this issue because:

- [ ] DB4S is crashing
- [Y] DB4S has a bug
- [ ] DB4S needs a feature
- [ ] DB4S has another problem

#### I'm using DB4S on:

- [Y ] Windows: ( _version: 7 )

#### I'm using DB4S version:

- [X ] 3.9.1

**Comment by justinclift** [comment]
Thanks @ecki. :smile:

@FriedrichFroebel @VanDerSam What are you thoughts on this? :smile:

**Comment by ecki** [comment]
Strange enough I dont see the bug in the translation file, the About dialog seems to be translated correctly and the help menu is untranslated. Is there another place for the translations of Windows Portable DB Browser?

**Comment by MKleusberg** [comment]
Ahh, you're probably comparing version 3.9.1 to the translation file from the latest version here on Github (which eventually is going to be 3.10). Iulian has fixed the the typo in the meantime (see commit 1257134dc65547662a81c66bf331dd627ff576f5), so that's why it's correct in the translation file but not yet in the release versions. Can you double check by downloading the latest nightly build? It should be fixed in there :smiley:

**Comment by ecki** [comment]
Yes I an confirm it is fixed in the nightly build.
